"""Router facade export manifest shard.

The shard keeps registry rows grouped by domain while the aggregator preserves
the public OWNER_EXPORTS contract.
"""

from __future__ import annotations

from typing import TypeAlias

ExportSpec: TypeAlias = tuple[str, str]
RegistryKey: TypeAlias = tuple[str, bool, bool]

OWNER_EXPORTS_ROUTE: dict[RegistryKey, tuple[ExportSpec, ...]] = {('flowpilot_router_model_gate_state', True, False): (('_active_model_miss_review_block_flags',
                                                       '_active_model_miss_review_block_flags'),
                                                      ('_require_single_active_model_miss_review_block',
                                                       '_require_single_active_model_miss_review_block'),
                                                      ('_sync_model_gate_alias_flags', '_sync_model_gate_alias_flags')),
 ('flowpilot_router_payload_contracts', True, False): (('_display_surface_receipt_payload_contract',
                                                        '_display_surface_receipt_payload_contract'),
                                                       ('_heartbeat_payload_contract', '_heartbeat_payload_contract'),
                                                       ('_payload_contract', '_payload_contract'),
                                                       ('_pm_decision_payload_contract_for_card',
                                                        '_pm_decision_payload_contract_for_card'),
                                                       ('_pm_model_miss_triage_payload_contract',
                                                        '_pm_model_miss_triage_payload_contract'),
                                                       ('_pm_parent_segment_decision_payload_contract',
                                                        '_pm_parent_segment_decision_payload_contract'),
                                                       ('_pm_resume_decision_payload_contract',
                                                        '_pm_resume_decision_payload_contract'),
                                                       ('_pm_terminal_closure_payload_contract',
                                                        '_pm_terminal_closure_payload_contract'),
                                                       ('_resume_role_rehydration_payload_contract',
                                                        '_resume_role_rehydration_payload_contract'),
                                                       ('_role_decision_payload_contract_for_events',
                                                        '_role_decision_payload_contract_for_events'),
                                                       ('_role_slots_payload_contract', '_role_slots_payload_contract'),
                                                       ('_startup_answers_payload_contract',
                                                        '_startup_answers_payload_contract'),
                                                       ('_terminal_summary_payload_contract',
                                                        '_terminal_summary_payload_contract')),
 ('flowpilot_router_resume', False, True): (('_append_heartbeat_tick', 'append_heartbeat_tick'),),
 ('flowpilot_router_route_artifacts', True, False): (('_clear_active_gate_outcome_block_for_pass',
                                                      '_clear_active_gate_outcome_block_for_pass'),
                                                     ('_freeze_root_acceptance_contract',
                                                      '_freeze_root_acceptance_contract'),
                                                     ('_gate_outcome_path_from_token', '_gate_outcome_path_from_token'),
                                                     ('_route_payload_from_reviewed_draft',
                                                      '_route_payload_from_reviewed_draft'),
                                                     ('_validate_current_node_packet_envelope',
                                                      '_validate_current_node_packet_envelope'),
                                                     ('_validate_current_node_packet_event',
                                                      '_validate_current_node_packet_event'),
                                                     ('_validate_current_node_result_event',
                                                      '_validate_current_node_result_event'),
                                                     ('_validate_current_node_reviewer_pass',
                                                      '_validate_current_node_reviewer_pass'),
                                                     ('_validate_selected_child_skills',
                                                      '_validate_selected_child_skills'),
                                                     ('_write_capabilities_manifest', '_write_capabilities_manifest'),
                                                     ('_write_child_skill_gate_manifest',
                                                      '_write_child_skill_gate_manifest'),
                                                     ('_write_child_skill_selection', '_write_child_skill_selection'),
                                                     ('_write_compatibility_alias_artifact',
                                                      '_write_compatibility_alias_artifact'),
                                                     ('_write_dependency_policy', '_write_dependency_policy'),
                                                     ('_write_evidence_quality_package',
                                                      '_write_evidence_quality_package'),
                                                     ('_write_gate_outcome_block_report',
                                                      '_write_gate_outcome_block_report'),
                                                     ('_write_material_dispatch_repair',
                                                      '_write_material_dispatch_repair'),
                                                     ('_write_node_acceptance_plan', '_write_node_acceptance_plan'),
                                                     ('_write_parent_backward_replay', '_write_parent_backward_replay'),
                                                     ('_write_parent_backward_targets',
                                                      '_write_parent_backward_targets'),
                                                     ('_write_parent_segment_decision',
                                                      '_write_parent_segment_decision'),
                                                     ('_write_pm_model_decision', '_write_pm_model_decision'),
                                                     ('_write_pm_process_route_model_decision',
                                                      '_write_pm_process_route_model_decision'),
                                                     ('_write_pm_product_behavior_model_decision',
                                                      '_write_pm_product_behavior_model_decision'),
                                                     ('_write_pm_research_absorption', '_write_pm_research_absorption'),
                                                     ('_write_pm_resume_decision', '_write_pm_resume_decision'),
                                                     ('_write_pm_review_block_repair', '_write_pm_review_block_repair'),
                                                     ('_write_pm_revised_node_acceptance_plan',
                                                      '_write_pm_revised_node_acceptance_plan'),
                                                     ('_write_product_behavior_model_report',
                                                      '_write_product_behavior_model_report'),
                                                     ('_write_product_function_architecture',
                                                      '_write_product_function_architecture'),
                                                     ('_write_role_block_report', '_write_role_block_report'),
                                                     ('_write_role_gate_report', '_write_role_gate_report'),
                                                     ('_write_root_acceptance_contract',
                                                      '_write_root_acceptance_contract'),
                                                     ('_write_route_activation', '_write_route_activation'),
                                                     ('_write_route_mutation', '_write_route_mutation'),
                                                     ('_write_route_process_issue_report',
                                                      '_write_route_process_issue_report'),
                                                     ('_write_route_process_pass_report',
                                                      '_write_route_process_pass_report'),
                                                     ('_write_route_product_pass_report',
                                                      '_write_route_product_pass_report')),
 ('flowpilot_router_route_completion_support', True, False): (('_active_node_acceptance_plan_path',
                                                               '_active_node_acceptance_plan_path'),
                                                              ('_active_node_completion_ledger_path',
                                                               '_active_node_completion_ledger_path'),
                                                              ('_active_node_completion_write_missing',
                                                               '_active_node_completion_write_missing'),
                                                              ('_active_node_packet_index_path',
                                                               '_active_node_packet_index_path'),
                                                              ('_active_node_root', '_active_node_root'),
                                                              ('_active_node_write_grant_path',
                                                               '_active_node_write_grant_path'),
                                                              ('_inline_child_nodes', '_inline_child_nodes'),
                                                              ('_node_completion_event_advanced_to_next_node',
                                                               '_node_completion_event_advanced_to_next_node'),
                                                              ('_node_identifier', '_node_identifier'),
                                                              ('_raw_route_nodes', '_raw_route_nodes'),
                                                              ('_reset_flags', '_reset_flags'),
                                                              ('_resume_decision_path', '_resume_decision_path'),
                                                              ('_resume_mechanical_replay_completed_without_pm',
                                                               '_resume_mechanical_replay_completed_without_pm'),
                                                              ('_resume_waits_for_pm_decision',
                                                               '_resume_waits_for_pm_decision'),
                                                              ('_task_completion_projection_path',
                                                               '_task_completion_projection_path')),
 ('flowpilot_router_route_frontier', False, True): (('_active_frontier', '_active_frontier'),
                                                    ('_active_node_definition', '_active_node_definition'),
                                                    ('_active_node_definition_from_route',
                                                     '_active_node_definition_from_route'),
                                                    ('_active_node_has_children', '_active_node_has_children'),
                                                    ('_active_route_flow', '_active_route_flow'),
                                                    ('_active_route_path', '_active_route_path'),
                                                    ('_active_route_payload', '_active_route_payload'),
                                                    ('_active_ui_task_catalog', '_active_ui_task_catalog'),
                                                    ('_build_current_status_summary', '_build_current_status_summary'),
                                                    ('_build_progress_summary', '_build_progress_summary'),
                                                    ('_build_route_state_snapshot', '_build_route_state_snapshot'),
                                                    ('_card_delivery_phase', '_card_delivery_phase'),
                                                    ('_card_required_source_paths', '_card_required_source_paths'),
                                                    ('_controller_delivery_fact_for_pending_return',
                                                     '_controller_delivery_fact_for_pending_return'),
                                                    ('_current_display_plan', '_current_display_plan'),
                                                    ('_current_route_draft_path', '_current_route_draft_path'),
                                                    ('_current_status_active_batch_summary',
                                                     '_current_status_active_batch_summary'),
                                                    ('_current_status_summary_path', '_current_status_summary_path'),
                                                    ('_display_plan_path', '_display_plan_path'),
                                                    ('_display_plan_projection', '_display_plan_projection'),
                                                    ('_display_plan_sync_payload', '_display_plan_sync_payload'),
                                                    ('_display_route_nodes', '_display_route_nodes'),
                                                    ('_effective_child_ids', '_effective_child_ids'),
                                                    ('_effective_route_nodes', '_effective_route_nodes'),
                                                    ('_enter_next_child_node', '_enter_next_child_node'),
                                                    ('_event_markers', '_event_markers'),
                                                    ('_filter_events_by_legal_route_actions',
                                                     '_filter_events_by_legal_route_actions'),
                                                    ('_first_incomplete_child_node_id',
                                                     '_first_incomplete_child_node_id'),
                                                    ('_flatten_route_nodes', '_flatten_route_nodes'),
                                                    ('_frontier_completed_node_ids', '_frontier_completed_node_ids'),
                                                    ('_is_leaf_readiness_passed', '_is_leaf_readiness_passed'),
                                                    ('_is_route_root_like_node_id', '_is_route_root_like_node_id'),
                                                    ('_is_route_root_node', '_is_route_root_node'),
                                                    ('_iter_route_nodes', '_iter_route_nodes'),
                                                    ('_latest_event_payload', '_latest_event_payload'),
                                                    ('_latest_pre_route_phase', '_latest_pre_route_phase'),
                                                    ('_legal_next_action_context', '_legal_next_action_context'),
                                                    ('_legal_next_action_ids', '_legal_next_action_ids'),
                                                    ('_legal_route_action_allowed', '_legal_route_action_allowed'),
                                                    ('_live_card_delivery_context', '_live_card_delivery_context'),
                                                    ('_load_route_action_policy_registry',
                                                     '_load_route_action_policy_registry'),
                                                    ('_mark_current_node_packet_records_completed',
                                                     '_mark_current_node_packet_records_completed'),
                                                    ('_mark_display_plan_dirty', '_mark_display_plan_dirty'),
                                                    ('_mark_frontier_node_completed', '_mark_frontier_node_completed'),
                                                    ('_matching_controller_delivery_actions',
                                                     '_matching_controller_delivery_actions'),
                                                    ('_next_effective_node_id', '_next_effective_node_id'),
                                                    ('_next_parent_child_entry_action',
                                                     '_next_parent_child_entry_action'),
                                                    ('_node_child_ids', '_node_child_ids'),
                                                    ('_node_completion_ledger_current',
                                                     '_node_completion_ledger_current'),
                                                    ('_node_completion_ledger_path_for',
                                                     '_node_completion_ledger_path_for'),
                                                    ('_node_kind', '_node_kind'),
                                                    ('_optional_source_path', '_optional_source_path'),
                                                    ('_parent_segment_decision_value',
                                                     '_parent_segment_decision_value'),
                                                    ('_plan_item_status', '_plan_item_status'),
                                                    ('_pm_context_action_extra', '_pm_context_action_extra'),
                                                    ('_pm_prior_path_context_path', '_pm_prior_path_context_path'),
                                                    ('_process_route_model_report_path',
                                                     '_process_route_model_report_path'),
                                                    ('_product_behavior_model_compatibility_report_path',
                                                     '_product_behavior_model_compatibility_report_path'),
                                                    ('_product_behavior_model_report_path',
                                                     '_product_behavior_model_report_path'),
                                                    ('_ready_parent_scope_after_child_completion',
                                                     '_ready_parent_scope_after_child_completion'),
                                                    ('_reconcile_non_current_running_index_entries',
                                                     '_reconcile_non_current_running_index_entries'),
                                                    ('_refresh_route_memory', '_refresh_route_memory'),
                                                    ('_require_legal_route_action', '_require_legal_route_action'),
                                                    ('_require_pm_prior_path_context',
                                                     '_require_pm_prior_path_context'),
                                                    ('_require_process_route_model_report',
                                                     '_require_process_route_model_report'),
                                                    ('_require_product_behavior_model_report',
                                                     '_require_product_behavior_model_report'),
                                                    ('_require_route_process_pass', '_require_route_process_pass'),
                                                    ('_require_route_product_pass', '_require_route_product_pass'),
                                                    ('_reset_route_hard_gate_approvals_for_recheck',
                                                     '_reset_route_hard_gate_approvals_for_recheck'),
                                                    ('_reset_route_review_after_route_draft_repair',
                                                     '_reset_route_review_after_route_draft_repair'),
                                                    ('_route_action_for_card', '_route_action_for_card'),
                                                    ('_route_action_for_event', '_route_action_for_event'),
                                                    ('_route_action_policy_by_id', '_route_action_policy_by_id'),
                                                    ('_route_action_policy_issues', '_route_action_policy_issues'),
                                                    ('_route_action_policy_registry_path',
                                                     '_route_action_policy_registry_path'),
                                                    ('_route_action_policy_rows', '_route_action_policy_rows'),
                                                    ('_route_active_path', '_route_active_path'),
                                                    ('_route_descendant_node_ids', '_route_descendant_node_ids'),
                                                    ('_route_display_depth', '_route_display_depth'),
                                                    ('_route_display_refresh_path', '_route_display_refresh_path'),
                                                    ('_route_hidden_leaf_progress', '_route_hidden_leaf_progress'),
                                                    ('_route_history_index_path', '_route_history_index_path'),
                                                    ('_route_item_status', '_route_item_status'),
                                                    ('_route_memory_ready', '_route_memory_ready'),
                                                    ('_route_memory_root', '_route_memory_root'),
                                                    ('_route_mutation_review_lane', '_route_mutation_review_lane'),
                                                    ('_route_mutation_superseded_nodes',
                                                     '_route_mutation_superseded_nodes'),
                                                    ('_route_node_checklist', '_route_node_checklist'),
                                                    ('_route_node_depth', '_route_node_depth'),
                                                    ('_route_node_history', '_route_node_history'),
                                                    ('_route_node_label', '_route_node_label'),
                                                    ('_route_node_map', '_route_node_map'),
                                                    ('_route_nodes', '_route_nodes'),
                                                    ('_route_process_check_path', '_route_process_check_path'),
                                                    ('_route_product_check_path', '_route_product_check_path'),
                                                    ('_route_progress_completed_ids', '_route_progress_completed_ids'),
                                                    ('_route_progress_parent_map', '_route_progress_parent_map'),
                                                    ('_route_progress_path_nodes', '_route_progress_path_nodes'),
                                                    ('_route_state_snapshot_path', '_route_state_snapshot_path'),
                                                    ('_run_elapsed_seconds', '_run_elapsed_seconds'),
                                                    ('_status_summary_waiting_for', '_status_summary_waiting_for'),
                                                    ('_supersede_active_current_node_packet_for_route_mutation',
                                                     '_supersede_active_current_node_packet_for_route_mutation'),
                                                    ('_sync_derived_run_views', '_sync_derived_run_views'),
                                                    ('_sync_execution_frontier_phase',
                                                     '_sync_execution_frontier_phase'),
                                                    ('_update_display_plan_current_node',
                                                     '_update_display_plan_current_node'),
                                                    ('_validate_route_action_policy_registry',
                                                     '_validate_route_action_policy_registry'),
                                                    ('_validate_route_mutation_phase_boundary',
                                                     '_validate_route_mutation_phase_boundary'),
                                                    ('_waiting_for_pm_display_plan', '_waiting_for_pm_display_plan'),
                                                    ('_write_current_status_summary', '_write_current_status_summary'),
                                                    ('_write_display_plan_from_pm_payload',
                                                     '_write_display_plan_from_pm_payload'),
                                                    ('_write_display_plan_from_route',
                                                     '_write_display_plan_from_route'),
                                                    ('_write_node_completion_ledger', '_write_node_completion_ledger'),
                                                    ('_write_pre_route_phase_display_plan_if_needed',
                                                     '_write_pre_route_phase_display_plan_if_needed'),
                                                    ('_write_route_draft', '_write_route_draft'),
                                                    ('_write_route_state_snapshot', '_write_route_state_snapshot')),
 ('flowpilot_router_runtime_state', False, True): (('_active_packet_ledger_record', '_active_packet_ledger_record'),
                                                   ('_append_role_memory_delta', '_append_role_memory_delta'),
                                                   ('_build_continuation_quarantine_record',
                                                    '_build_continuation_quarantine_record'),
                                                   ('_continuation_binding_path', '_continuation_binding_path'),
                                                   ('_continuation_quarantine_path', '_continuation_quarantine_path'),
                                                   ('_create_empty_execution_frontier',
                                                    '_create_empty_execution_frontier'),
                                                   ('_create_empty_packet_ledger', '_create_empty_packet_ledger'),
                                                   ('_create_empty_role_memory', '_create_empty_role_memory'),
                                                   ('_create_run_id', '_create_run_id'),
                                                   ('_create_startup_bootstrap_state',
                                                    '_create_startup_bootstrap_state'),
                                                   ('_derive_resume_next_recipient_from_packet_ledger',
                                                    '_derive_resume_next_recipient_from_packet_ledger'),
                                                   ('_load_existing_bootstrap_state', '_load_existing_bootstrap_state'),
                                                   ('_packet_ledger_record_by_id', '_packet_ledger_record_by_id'),
                                                   ('_role_memory_event_role', '_role_memory_event_role'),
                                                   ('_scheduled_continuation_requested',
                                                    '_scheduled_continuation_requested'),
                                                   ('_set_pre_route_frontier_phase', '_set_pre_route_frontier_phase'),
                                                   ('_startup_answers_from_run', '_startup_answers_from_run'),
                                                   ('_write_continuation_quarantine', '_write_continuation_quarantine'),
                                                   ('active_run_root', 'active_run_root'),
                                                   ('load_bootstrap_state', 'load_bootstrap_state'),
                                                   ('load_run_state', 'load_run_state'),
                                                   ('load_run_state_from_run_root', 'load_run_state_from_run_root'),
                                                   ('new_bootstrap_state', 'new_bootstrap_state'),
                                                   ('new_run_state', 'new_run_state'),
                                                   ('run_state_path', 'run_state_path'),
                                                   ('save_bootstrap_state', 'save_bootstrap_state'),
                                                   ('save_run_state', 'save_run_state')),
 ('flowpilot_router_self_interrogation', True, False): (('_evidence_path_record', '_evidence_path_record'),
                                                        ('_format_self_interrogation_status_issue',
                                                         '_format_self_interrogation_status_issue'),
                                                        ('_pm_suggestion_ledger_path', '_pm_suggestion_ledger_path'),
                                                        ('_pm_suggestion_ledger_status',
                                                         '_pm_suggestion_ledger_status'),
                                                        ('_read_pm_suggestion_ledger', '_read_pm_suggestion_ledger'),
                                                        ('_require_clean_self_interrogation',
                                                         '_require_clean_self_interrogation'),
                                                        ('_router_owned_check_proof_path',
                                                         '_router_owned_check_proof_path'),
                                                        ('_self_interrogation_entry_path',
                                                         '_self_interrogation_entry_path'),
                                                        ('_self_interrogation_final_status',
                                                         '_self_interrogation_final_status'),
                                                        ('_self_interrogation_index_path',
                                                         '_self_interrogation_index_path'),
                                                        ('_self_interrogation_issue', '_self_interrogation_issue'),
                                                        ('_self_interrogation_record_issues',
                                                         '_self_interrogation_record_issues'),
                                                        ('_self_interrogation_status', '_self_interrogation_status'),
                                                        ('_write_router_owned_check_proof',
                                                         '_write_router_owned_check_proof'),
                                                        ('resolve_project_path', 'resolve_project_path'))}

def owner_exports_route() -> dict[RegistryKey, tuple[ExportSpec, ...]]:
    return OWNER_EXPORTS_ROUTE


__all__ = ["OWNER_EXPORTS_ROUTE", "owner_exports_route"]
