"""Decision enums, runtime flags, and event identity policies extracted from ``flowpilot_router_protocol_catalog.py``."""

from __future__ import annotations

from typing import Any, Iterable

import flowpilot_runtime_closure
import packet_runtime
import role_output_runtime

from flowpilot_router_protocol_schemas import *
from flowpilot_router_protocol_control_repair import *
from flowpilot_router_protocol_work_contracts import *

from flowpilot_router_protocol_decision_fields import *
from flowpilot_router_protocol_runtime_flags import *
from flowpilot_router_protocol_event_capabilities import *
from flowpilot_router_protocol_scoped_event_identity import *

__all__ = (
    'STARTUP_ANSWER_ENUMS',
    'STARTUP_ANSWER_BOOLEANS',
    'GATE_DECISION_REQUIRED_FIELDS',
    'PM_PRIOR_PATH_CONTEXT_REVIEW_REQUIRED_FIELDS',
    'PM_RESUME_CONTROLLER_REMINDER_REQUIRED_FIELDS',
    'PM_RESUME_DECISION_ALLOWED_VALUES',
    'PM_RESUME_DECISION_REQUIRED_BODY_FIELDS',
    'PM_PARENT_SEGMENT_DECISION_ALLOWED_VALUES',
    'PM_PARENT_SEGMENT_DECISION_REQUIRED_BODY_FIELDS',
    'PM_TERMINAL_CLOSURE_DECISION_ALLOWED_VALUES',
    'PM_TERMINAL_CLOSURE_DECISION_REQUIRED_BODY_FIELDS',
    'PM_SUGGESTION_FINAL_DISPOSITIONS',
    'PM_SUGGESTION_CLOSURE_STATUSES_BY_DISPOSITION',
    'PM_SUGGESTION_WORKER_ROLES',
    'PM_SUGGESTION_FLOWGUARD_OPERATOR_ROLES',
    'SELF_INTERROGATION_SCOPES',
    'SELF_INTERROGATION_HARD_SEVERITIES',
    'SELF_INTERROGATION_FINAL_DISPOSITIONS',
    'GATE_DECISION_ALLOWED_KINDS',
    'GATE_DECISION_ALLOWED_OWNER_ROLES',
    'GATE_DECISION_ALLOWED_RISKS',
    'GATE_DECISION_ALLOWED_STRENGTHS',
    'GATE_DECISION_ALLOWED_DECISIONS',
    'GATE_DECISION_ALLOWED_EVIDENCE_KINDS',
    'GATE_DECISION_ALLOWED_NEXT_ACTIONS',
    'GATE_DECISION_SEMANTIC_OVERREACH_FIELDS',
    'RUNTIME_ROLE_KEYS',
    'ROLE_CARD_KEYS',
    'RUNTIME_FLAG_DEFAULTS',
    'SAFE_RUN_UNTIL_WAIT_ACTION_TYPES',
    'ROUTER_INTERNAL_MECHANICAL_ACTION_TYPES',
    'ROUTER_INTERNAL_MECHANICAL_MAX_HOPS',
    'ROUTER_READY_PREEMPTION_ACTION_TYPES',
    'CURRENT_NODE_CYCLE_FLAGS',
    'MATERIAL_REPAIR_RECHECK_FLAGS',
    'MODEL_MISS_REVIEW_BLOCK_FLAGS',
    'MODEL_MISS_REVIEW_BLOCK_EVENTS',
    'MODEL_MISS_ROUTE_MUTATION_BLOCK_FLAGS',
    'MODEL_MISS_MATERIAL_DISPATCH_REPAIR_FLAGS',
    'MATERIAL_REPAIR_OUTCOME_EVENTS',
    'CONTROL_BLOCKER_REPAIR_NON_SUCCESS_EVENTS',
    'LEAF_CURRENT_NODE_EVENT_CAPABILITY_EVENTS',
    'PARENT_REPAIR_SAFE_EVENTS',
    'PARENT_NODE_EVENT_CAPABILITY_EVENTS',
    'ROUTE_COMPLETION_FLAGS',
    'SCOPED_EVENT_IDENTITY_POLICIES',
)
