"""Controller facade export manifest events shard."""

from __future__ import annotations

from typing import TypeAlias

ExportSpec: TypeAlias = tuple[str, str]
RegistryKey: TypeAlias = tuple[str, bool, bool]

OWNER_EXPORTS_CONTROLLER_EVENTS: dict[RegistryKey, tuple[ExportSpec, ...]] = {('flowpilot_router_event_dispatcher', False, True): (('_record_external_event_unchecked',
                                                       '_record_external_event_unchecked'),),
 ('flowpilot_router_event_identity', False, True): (('_active_control_blocker_for_identity',
                                                     '_active_control_blocker_for_identity'),
                                                    ('_already_recorded_external_event_result',
                                                     '_already_recorded_external_event_result'),
                                                    ('_check_scoped_event_retry_budget',
                                                     '_check_scoped_event_retry_budget'),
                                                    ('_control_blocker_repair_decision_identity_scope',
                                                     '_control_blocker_repair_decision_identity_scope'),
                                                    ('_control_blocker_repair_outcome_identity_scope',
                                                     '_control_blocker_repair_outcome_identity_scope'),
                                                    ('_current_node_completion_identity_scope',
                                                     '_current_node_completion_identity_scope'),
                                                    ('_current_node_result_identity_scope',
                                                     '_current_node_result_identity_scope'),
                                                    ('_currently_allowed_external_events',
                                                     '_currently_allowed_external_events'),
                                                    ('_event_identity_ledger',
                                                     '_event_identity_ledger'),
                                                    ('_external_event_flag_replay_requires_new_processing',
                                                     '_external_event_flag_replay_requires_new_processing'),
                                                    ('_frontier_for_event_identity',
                                                     '_frontier_for_event_identity'),
                                                    ('_gate_decision_identity_scope',
                                                     '_gate_decision_identity_scope'),
                                                    ('_load_file_backed_role_payload',
                                                     '_load_file_backed_role_payload'),
                                                    ('_load_file_backed_role_payload_if_present',
                                                     '_load_file_backed_role_payload_if_present'),
                                                    ('_load_record_event_envelope_ref',
                                                     '_load_record_event_envelope_ref'),
                                                    ('_looks_like_record_event_envelope',
                                                     '_looks_like_record_event_envelope'),
                                                    ('_mark_scoped_event_recorded',
                                                     '_mark_scoped_event_recorded'),
                                                    ('_normalize_record_event_payload',
                                                     '_normalize_record_event_payload'),
                                                    ('_payload_body_hash', '_payload_body_hash'),
                                                    ('_payload_requires_record_event_envelope_validation',
                                                     '_payload_requires_record_event_envelope_validation'),
                                                    ('_payload_view_for_event_identity',
                                                     '_payload_view_for_event_identity'),
                                                    ('_pm_role_work_request_identity_scope',
                                                     '_pm_role_work_request_identity_scope'),
                                                    ('_pm_role_work_result_decision_identity_scope',
                                                     '_pm_role_work_result_decision_identity_scope'),
                                                    ('_record_event_envelope_ref_from_payload',
                                                     '_record_event_envelope_ref_from_payload'),
                                                    ('_record_event_expected_role',
                                                     '_record_event_expected_role'),
                                                    ('_record_event_from_role_matches',
                                                     '_record_event_from_role_matches'),
                                                    ('_role_work_result_identity_scope',
                                                     '_role_work_result_identity_scope'),
                                                    ('_route_draft_identity_scope',
                                                     '_route_draft_identity_scope'),
                                                    ('_route_mutation_identity_scope',
                                                     '_route_mutation_identity_scope'),
                                                    ('_scoped_event_identity',
                                                     '_scoped_event_identity'),
                                                    ('_scoped_event_is_recorded',
                                                     '_scoped_event_is_recorded'),
                                                    ('_stable_identity_hash',
                                                     '_stable_identity_hash'),
                                                    ('_startup_repair_identity_scope',
                                                     '_startup_repair_identity_scope'),
                                                    ('_validate_record_event_envelope',
                                                     '_validate_record_event_envelope'))}

__all__ = ["OWNER_EXPORTS_CONTROLLER_EVENTS"]
