"""Decision-table child declarations for FlowPilot router protocol."""

from __future__ import annotations

RUNTIME_FLAG_DEFAULTS = {
    "resume_state_loaded": False,
    "resume_state_ambiguous": False,
    "resume_roles_restored": False,
    "resume_role_bindings_rehydrated": False,
    "role_binding_recovery_report_written": False,
    "role_recovery_requested": False,
    "role_recovery_state_loaded": False,
    "role_recovery_roles_restored": False,
    "role_recovery_report_written": False,
    "role_recovery_environment_blocked": False,
    "role_recovery_obligations_scanned": False,
    "role_recovery_obligation_replay_completed": False,
    "role_recovery_pm_escalation_required": False,
    "role_no_output_reissue_recorded": False,
    "role_no_output_pm_escalation_required": False,
    "continuation_binding_recorded": False,
    "controller_boundary_confirmation_written": False,
    "controller_role_confirmed_from_router_core": False,
    "controller_boundary_recovery_requested": False,
    "startup_mechanical_audit_written": False,
    "startup_pending_mail_suspended_after_dead_end": False,
    "startup_display_status_written": False,
    "route_history_index_refreshed": False,
    "pm_prior_path_context_refreshed": False,
    "research_packet_relayed": False,
    "research_result_relayed_to_reviewer": False,
    "research_result_relayed_to_pm": False,
    "research_result_disposition_recorded": False,
    "research_result_absorbed_for_review_by_pm": False,
    "current_node_packet_relayed": False,
    "current_node_result_relayed_to_reviewer": False,
    "current_node_result_relayed_to_pm": False,
    "current_node_result_disposition_recorded": False,
    "current_node_result_absorbed_by_pm": False,
    "current_node_write_grant_issued": False,
    "node_completion_ledger_updated": False,
    "task_completion_projection_published": False,
    "pm_role_work_request_registered": False,
    "pm_role_work_request_packet_relayed": False,
    "pm_role_work_result_returned": False,
    "pm_role_work_result_relayed_to_pm": False,
    "pm_role_work_result_absorbed": False,
    "model_miss_triage_followup_request_pending": False,
    "model_miss_triage_controlled_stop_recorded": False,
    "terminal_summary_card_delivered": False,
    "terminal_summary_written": False,
    "formal_router_daemon_started": False,
    "router_daemon_start_failed": False,
}
