"""Router facade export manifest shard.

The shard keeps registry rows grouped by domain while the aggregator preserves
the public OWNER_EXPORTS contract.
"""

from __future__ import annotations

from typing import TypeAlias

ExportSpec: TypeAlias = tuple[str, str]
RegistryKey: TypeAlias = tuple[str, bool, bool]

OWNER_EXPORTS_ACTIONS: dict[RegistryKey, tuple[ExportSpec, ...]] = {('flowpilot_router_action_factory', True, False): (('_action_is_startup_async_card_wait',
                                                     '_action_is_startup_async_card_wait'),
                                                    ('_action_is_startup_async_delivery',
                                                     '_action_is_startup_async_delivery'),
                                                    ('_apply_dispatch_recipient_gate',
                                                     '_apply_dispatch_recipient_gate'),
                                                    ('_apply_formal_work_packet_ack_preflight',
                                                     '_apply_formal_work_packet_ack_preflight'),
                                                    ('_committed_card_artifact_extra',
                                                     '_committed_card_artifact_extra'),
                                                    ('_controller_user_reporting_policy',
                                                     '_controller_user_reporting_policy'),
                                                    ('_current_node_scope_exit_reconciliation_blockers',
                                                     '_current_node_scope_exit_reconciliation_blockers'),
                                                    ('_current_scope_pre_review_reconciliation_action',
                                                     '_current_scope_pre_review_reconciliation_action'),
                                                    ('_current_scope_reconciliation_wait_still_blocked',
                                                     '_current_scope_reconciliation_wait_still_blocked'),
                                                    ('_dispatch_gate_action_is_ack_only_prompt',
                                                     '_dispatch_gate_action_is_ack_only_prompt'),
                                                    ('_dispatch_gate_action_work_class',
                                                     '_dispatch_gate_action_work_class'),
                                                    ('_dispatch_gate_card_entry', '_dispatch_gate_card_entry'),
                                                    ('_dispatch_gate_output_events_for_action',
                                                     '_dispatch_gate_output_events_for_action'),
                                                    ('_dispatch_gate_output_events_for_card_id',
                                                     '_dispatch_gate_output_events_for_card_id'),
                                                    ('_dispatch_gate_packet_blocker', '_dispatch_gate_packet_blocker'),
                                                    ('_dispatch_gate_passive_wait_blocker',
                                                     '_dispatch_gate_passive_wait_blocker'),
                                                    ('_dispatch_gate_pending_ack_wait',
                                                     '_dispatch_gate_pending_ack_wait'),
                                                    ('_dispatch_gate_pending_expected_output_blocker',
                                                     '_dispatch_gate_pending_expected_output_blocker'),
                                                    ('_dispatch_gate_pm_role_work_blocker',
                                                     '_dispatch_gate_pm_role_work_blocker'),
                                                    ('_dispatch_gate_same_obligation_instruction_context',
                                                     '_dispatch_gate_same_obligation_instruction_context'),
                                                    ('_dispatch_gate_wait_action', '_dispatch_gate_wait_action'),
                                                    ('_next_local_obligation_before_passive_wait',
                                                     '_next_local_obligation_before_passive_wait'),
                                                    ('_next_pending_card_return_action',
                                                     '_next_pending_card_return_action'),
                                                    ('_pending_card_return_blocker_for_event',
                                                     '_pending_card_return_blocker_for_event'),
                                                    ('_roles_from_action_to_role', '_roles_from_action_to_role'),
                                                    ('_startup_async_pending_returns',
                                                     '_startup_async_pending_returns'),
                                                    ('append_history', 'append_history'),
                                                    ('make_action', 'make_action')),
 ('flowpilot_router_action_handlers', False, True): (('_auto_commit_system_card_bundle_delivery_action',
                                                      'auto_commit_system_card_bundle_delivery_action'),),
 ('flowpilot_router_artifact_validation', True, False): (('_artifact_issue', '_artifact_issue'),
                                                         ('_validate_hash_if_present', '_validate_hash_if_present'),
                                                         ('_validate_role_output_hash_if_present',
                                                          '_validate_role_output_hash_if_present'),
                                                         ('validate_artifact', 'validate_artifact')),
 ('flowpilot_router_card_returns', False, True): (('_card_return_resolved_for_action',
                                                   '_card_return_resolved_for_action'),
                                                  ('_current_node_pre_review_reconciliation_blockers',
                                                   '_current_node_pre_review_reconciliation_blockers'),
                                                  ('_pending_card_return_ack_exists',
                                                   '_pending_card_return_ack_exists'),
                                                  ('_pending_return_card_ids', '_pending_return_card_ids'),
                                                  ('_pending_return_is_outside_active_node_scope',
                                                   '_pending_return_is_outside_active_node_scope'),
                                                  ('_pending_return_is_pre_review_startup_scope',
                                                   '_pending_return_is_pre_review_startup_scope'),
                                                  ('_pending_return_is_startup_async_scope',
                                                   '_pending_return_is_startup_async_scope'),
                                                  ('_pending_return_matches_active_node_scope',
                                                   '_pending_return_matches_active_node_scope'),
                                                  ('_pending_return_records', '_pending_return_records'),
                                                  ('_pre_review_reconciliation_blockers_for_trigger',
                                                   '_pre_review_reconciliation_blockers_for_trigger'),
                                                  ('_startup_pre_review_ack_join_clean',
                                                   '_startup_pre_review_ack_join_clean'),
                                                  ('_startup_pre_review_card_flags', '_startup_pre_review_card_flags'),
                                                  ('_startup_pre_review_cards_delivered',
                                                   '_startup_pre_review_cards_delivered'),
                                                  ('_startup_pre_review_pending_returns',
                                                   '_startup_pre_review_pending_returns'),
                                                  ('_startup_pre_review_reconciliation_blockers',
                                                   '_startup_pre_review_reconciliation_blockers')),
 ('flowpilot_router_child_skill_capability', True, False): (('_approve_child_skill_manifest_for_route',
                                                             '_approve_child_skill_manifest_for_route'),
                                                            ('_sync_capability_evidence', '_sync_capability_evidence'),
                                                            ('_sync_child_skill_manifest_review_approval',
                                                             '_sync_child_skill_manifest_review_approval')),
 ('flowpilot_router_cli', True, False): (('main', 'main'), ('parse_args', 'parse_args')),
 ('flowpilot_router_control_transactions', True, False): (('_control_transaction_contract_registry_path',
                                                           '_control_transaction_contract_registry_path'),
                                                          ('_control_transaction_registry_issues',
                                                           '_control_transaction_registry_issues'),
                                                          ('_control_transaction_registry_path',
                                                           '_control_transaction_registry_path'),
                                                          ('_control_transaction_registry_rows',
                                                           '_control_transaction_registry_rows'),
                                                          ('_control_transaction_row', '_control_transaction_row'),
                                                          ('_load_control_transaction_registry',
                                                           '_load_control_transaction_registry'),
                                                          ('_registered_output_contract_ids',
                                                           '_registered_output_contract_ids'),
                                                          ('_validate_control_transaction_registry',
                                                           '_validate_control_transaction_registry'),
                                                          ('_validate_control_transaction_requirements',
                                                           '_validate_control_transaction_requirements')),
 ('flowpilot_router_internal_actions', True, False): (('_action_is_router_internal_mechanical',
                                                       '_action_is_router_internal_mechanical'),
                                                      ('_append_router_internal_mechanical_record',
                                                       '_append_router_internal_mechanical_record'),
                                                      ('_consume_router_internal_mechanical_action',
                                                       '_consume_router_internal_mechanical_action'),
                                                      ('_router_internal_mechanical_identity',
                                                       '_router_internal_mechanical_identity')),
 ('flowpilot_router_proof_validation', True, False): (('_validate_router_owned_check_proof',
                                                       '_validate_router_owned_check_proof'),),
 ('flowpilot_router_role_output_bridge', True, False): (('_reconciled_card_delivery_context',
                                                         '_reconciled_card_delivery_context'),
                                                        ('_repair_prompt_delivery_contexts',
                                                         '_repair_prompt_delivery_contexts'),
                                                        ('_repair_role_output_envelope_hashes',
                                                         '_repair_role_output_envelope_hashes'),
                                                        ('_role_output_envelope_record',
                                                         '_role_output_envelope_record'),
                                                        ('_role_output_envelope_record_for_mutable_artifact',
                                                         '_role_output_envelope_record_for_mutable_artifact'),
                                                        ('_role_output_ledger_outputs', '_role_output_ledger_outputs'),
                                                        ('_role_output_snapshot_name', '_role_output_snapshot_name'),
                                                        ('_startup_fact_canonical_report_is_valid',
                                                         '_startup_fact_canonical_report_is_valid'),
                                                        ('_sync_current_and_index_status',
                                                         '_sync_current_and_index_status'),
                                                        ('_try_reconcile_direct_role_output_event_ledger',
                                                         '_try_reconcile_direct_role_output_event_ledger'),
                                                        ('_try_reconcile_startup_fact_role_output_ledger',
                                                         '_try_reconcile_startup_fact_role_output_ledger'),
                                                        ('write_role_output_envelope', 'write_role_output_envelope'))}

def owner_exports_actions() -> dict[RegistryKey, tuple[ExportSpec, ...]]:
    return OWNER_EXPORTS_ACTIONS


__all__ = ["OWNER_EXPORTS_ACTIONS", "owner_exports_actions"]
