"""Router facade export manifest shard.

The shard keeps registry rows grouped by domain while the aggregator preserves
the public OWNER_EXPORTS contract.
"""

from __future__ import annotations

from typing import TypeAlias

ExportSpec: TypeAlias = tuple[str, str]
RegistryKey: TypeAlias = tuple[str, bool, bool]

OWNER_EXPORTS_CONTROLLER: dict[RegistryKey, tuple[ExportSpec, ...]] = {('flowpilot_router_controller_repair', True, False): (('_close_waiting_controller_actions_for_external_event',
                                                        '_close_waiting_controller_actions_for_external_event'),
                                                       ('_controller_action_required_deliverables',
                                                        '_controller_action_required_deliverables'),
                                                       ('_controller_boundary_flags_synced',
                                                        '_controller_boundary_flags_synced'),
                                                       ('_controller_boundary_required_deliverable',
                                                        '_controller_boundary_required_deliverable'),
                                                       ('_controller_deliverable_contract',
                                                        '_controller_deliverable_contract'),
                                                       ('_controller_deliverable_failed_repair_ids',
                                                        '_controller_deliverable_failed_repair_ids'),
                                                       ('_controller_repair_action_is_pending',
                                                        '_controller_repair_action_is_pending'),
                                                       ('_count_unique_mail_deliveries',
                                                        '_count_unique_mail_deliveries'),
                                                       ('_defer_controller_postcondition_reconciliation_retry',
                                                        '_defer_controller_postcondition_reconciliation_retry'),
                                                       ('_done_controller_receipt_for_entry',
                                                        '_done_controller_receipt_for_entry'),
                                                       ('_ensure_mail_delivery_packet_released',
                                                        '_ensure_mail_delivery_packet_released'),
                                                       ('_find_mail_delivery', '_find_mail_delivery'),
                                                       ('_fold_mail_delivery_postcondition',
                                                        '_fold_mail_delivery_postcondition'),
                                                       ('_mail_delivery_action_envelope_path',
                                                        '_mail_delivery_action_envelope_path'),
                                                       ('_mail_delivery_matches', '_mail_delivery_matches'),
                                                       ('_mail_delivery_packet_released',
                                                        '_mail_delivery_packet_released'),
                                                       ('_mail_role_obligation_contract',
                                                        '_mail_role_obligation_contract'),
                                                       ('_mail_sequence_entry', '_mail_sequence_entry'),
                                                       ('_mark_controller_deliverable_repair_resolved',
                                                        '_mark_controller_deliverable_repair_resolved'),
                                                       ('_missing_deliverables_for_apply_result',
                                                        '_missing_deliverables_for_apply_result'),
                                                       ('_packet_record_for_mail_delivery',
                                                        '_packet_record_for_mail_delivery'),
                                                       ('_pending_action_postcondition',
                                                        '_pending_action_postcondition'),
                                                       ('_pending_action_postcondition_satisfied',
                                                        '_pending_action_postcondition_satisfied'),
                                                       ('_pending_controller_action_id',
                                                        '_pending_controller_action_id'),
                                                       ('_receipt_for_pending_controller_action',
                                                        '_receipt_for_pending_controller_action'),
                                                       ('_reclaim_router_owned_postcondition_from_artifact',
                                                        '_reclaim_router_owned_postcondition_from_artifact'),
                                                       ('_reconcile_controller_boundary_confirmation_projection',
                                                        '_reconcile_controller_boundary_confirmation_projection'),
                                                       ('_router_scheduler_row_for_controller_entry',
                                                        '_router_scheduler_row_for_controller_entry'),
                                                       ('_schedule_controller_deliverable_repair',
                                                        '_schedule_controller_deliverable_repair'),
                                                       ('_sync_controller_boundary_confirmation_from_artifact',
                                                        '_sync_controller_boundary_confirmation_from_artifact'),
                                                       ('_update_controller_action_entry_fields',
                                                        '_update_controller_action_entry_fields'),
                                                       ('_write_controller_deliverable_budget_blocker',
                                                        '_write_controller_deliverable_budget_blocker')),
 ('flowpilot_router_controller_runtime', True, False): (('_next_mail_action', '_next_mail_action'),
                                                        ('apply_action', 'apply_action'),
                                                        ('apply_controller_action', 'apply_controller_action'),
                                                        ('compute_controller_action', 'compute_controller_action'),
                                                        ('next_action', 'next_action'),
                                                        ('record_controller_action_receipt',
                                                         'record_controller_action_receipt'),
                                                        ('record_external_event', 'record_external_event'),
                                                        ('run_until_wait', 'run_until_wait')),
 ('flowpilot_router_controller_scheduler', False, True): (('_action_is_startup_scoped', '_action_is_startup_scoped'),
                                                          ('_apply_done_controller_receipt_effects',
                                                           '_apply_done_controller_receipt_effects'),
                                                          ('_apply_startup_bootloader_receipt_effects',
                                                           '_apply_startup_bootloader_receipt_effects'),
                                                          ('_apply_stateful_receipt_postcondition',
                                                           '_apply_stateful_receipt_postcondition'),
                                                          ('_apply_wait_target_reminder_receipt',
                                                           '_apply_wait_target_reminder_receipt'),
                                                          ('_backfill_scheduler_row_from_reconciled_controller_action',
                                                           '_backfill_scheduler_row_from_reconciled_controller_action'),
                                                          ('_boot_action_meta', '_boot_action_meta'),
                                                          ('_build_foreground_controller_standby_snapshot',
                                                           '_build_foreground_controller_standby_snapshot'),
                                                          ('_canonicalize_legacy_startup_daemon_reconciliation',
                                                           '_canonicalize_legacy_startup_daemon_reconciliation'),
                                                          ('_clear_pending_after_reconciled_controller_receipt',
                                                           '_clear_pending_after_reconciled_controller_receipt'),
                                                          ('_continuous_standby_release_conditions',
                                                           '_continuous_standby_release_conditions'),
                                                          ('_continuous_standby_task_payload',
                                                           '_continuous_standby_task_payload'),
                                                          ('_continuous_standby_watch_label',
                                                           '_continuous_standby_watch_label'),
                                                          ('_controller_action_completion_class',
                                                           '_controller_action_completion_class'),
                                                          ('_controller_action_ledger_has_prompt_header',
                                                           '_controller_action_ledger_has_prompt_header'),
                                                          ('_controller_action_ledger_summary',
                                                           '_controller_action_ledger_summary'),
                                                          ('_controller_action_open_for',
                                                           '_controller_action_open_for'),
                                                          ('_current_action_is_ordinary_controller_work',
                                                           '_current_action_is_ordinary_controller_work'),
                                                          ('_current_work_from_action', '_current_work_from_action'),
                                                          ('_current_work_from_packet_ledger',
                                                           '_current_work_from_packet_ledger'),
                                                          ('_current_work_from_passive_waits',
                                                           '_current_work_from_passive_waits'),
                                                          ('_current_work_owner_kind', '_current_work_owner_kind'),
                                                          ('_current_work_owner_label', '_current_work_owner_label'),
                                                          ('_current_work_payload', '_current_work_payload'),
                                                          ('_derive_current_work', '_derive_current_work'),
                                                          ('_elapsed_seconds_since', '_elapsed_seconds_since'),
                                                          ('_empty_router_ownership_ledger',
                                                           '_empty_router_ownership_ledger'),
                                                          ('_empty_router_scheduler_ledger',
                                                           '_empty_router_scheduler_ledger'),
                                                          ('_ensure_continuous_standby_controller_action',
                                                           '_ensure_continuous_standby_controller_action'),
                                                          ('_ensure_controller_action_ledger',
                                                           '_ensure_controller_action_ledger'),
                                                          ('_ensure_router_ownership_ledger',
                                                           '_ensure_router_ownership_ledger'),
                                                          ('_ensure_router_scheduler_ledger',
                                                           '_ensure_router_scheduler_ledger'),
                                                          ('_ensure_wait_target_reminder_controller_action',
                                                           '_ensure_wait_target_reminder_controller_action'),
                                                          ('_foreground_standby_pending_action_ids',
                                                           '_foreground_standby_pending_action_ids'),
                                                          ('_foreground_standby_waiting_action_ids',
                                                           '_foreground_standby_waiting_action_ids'),
                                                          ('_mark_pending_return_wait_reminded',
                                                           '_mark_pending_return_wait_reminded'),
                                                          ('_matching_bootstrap_pending_action',
                                                           '_matching_bootstrap_pending_action'),
                                                          ('_maybe_write_controller_receipt_for_pending',
                                                           '_maybe_write_controller_receipt_for_pending'),
                                                          ('_next_wait_target_reminder_action',
                                                           '_next_wait_target_reminder_action'),
                                                          ('_packet_status_allows_current_work',
                                                           '_packet_status_allows_current_work'),
                                                          ('_pending_return_matches_wait_target_reminder',
                                                           '_pending_return_matches_wait_target_reminder'),
                                                          ('_pending_wait_class', '_pending_wait_class'),
                                                          ('_pending_wait_summary', '_pending_wait_summary'),
                                                          ('_prepare_router_scheduled_action',
                                                           '_prepare_router_scheduled_action'),
                                                          ('_read_router_ownership_ledger',
                                                           '_read_router_ownership_ledger'),
                                                          ('_read_router_scheduler_ledger',
                                                           '_read_router_scheduler_ledger'),
                                                          ('_rebuild_controller_action_ledger',
                                                           '_rebuild_controller_action_ledger'),
                                                          ('_reconcile_controller_receipts',
                                                           '_reconcile_controller_receipts'),
                                                          ('_reconcile_pending_controller_action_receipt',
                                                           '_reconcile_pending_controller_action_receipt'),
                                                          ('_reconcile_scheduled_controller_action_receipts',
                                                           '_reconcile_scheduled_controller_action_receipts'),
                                                          ('_record_router_ownership_entry',
                                                           '_record_router_ownership_entry'),
                                                          ('_record_router_scheduler_row',
                                                           '_record_router_scheduler_row'),
                                                          ('_router_ownership_counts', '_router_ownership_counts'),
                                                          ('_router_ownership_ledger_summary',
                                                           '_router_ownership_ledger_summary'),
                                                          ('_router_scheduler_barrier_kind',
                                                           '_router_scheduler_barrier_kind'),
                                                          ('_router_scheduler_ledger_summary',
                                                           '_router_scheduler_ledger_summary'),
                                                          ('_router_scheduler_progress_class',
                                                           '_router_scheduler_progress_class'),
                                                          ('_router_scheduler_scope_for_action',
                                                           '_router_scheduler_scope_for_action'),
                                                          ('_scheduler_row_reconciliation_for_entry',
                                                           '_scheduler_row_reconciliation_for_entry'),
                                                          ('_should_refresh_continuous_standby_row',
                                                           '_should_refresh_continuous_standby_row'),
                                                          ('_update_router_scheduler_row',
                                                           '_update_router_scheduler_row'),
                                                          ('_wait_target_due_state', '_wait_target_due_state'),
                                                          ('_wait_target_identity', '_wait_target_identity'),
                                                          ('_wait_target_path_exists', '_wait_target_path_exists'),
                                                          ('_wait_target_reminder_payload_contract',
                                                           '_wait_target_reminder_payload_contract'),
                                                          ('_wait_target_reminder_text', '_wait_target_reminder_text'),
                                                          ('_wait_target_reminder_text_sha256',
                                                           '_wait_target_reminder_text_sha256'),
                                                          ('_write_controller_action_entry',
                                                           '_write_controller_action_entry'),
                                                          ('_write_controller_action_ledger',
                                                           '_write_controller_action_ledger'),
                                                          ('_write_controller_receipt', '_write_controller_receipt'),
                                                          ('_write_router_ownership_ledger',
                                                           '_write_router_ownership_ledger'),
                                                          ('_write_router_scheduler_ledger',
                                                           '_write_router_scheduler_ledger'),
                                                          ('controller_patrol_timer', 'controller_patrol_timer'),
                                                          ('foreground_controller_standby',
                                                           'foreground_controller_standby')),
 ('flowpilot_router_daemon_runtime', False, True): (('_acquire_router_daemon_lock', '_acquire_router_daemon_lock'),
                                                    ('_append_router_daemon_event', '_append_router_daemon_event'),
                                                    ('_ensure_daemon_runtime_state', '_ensure_daemon_runtime_state'),
                                                    ('_formal_router_daemon_ready', '_formal_router_daemon_ready'),
                                                    ('_mark_router_daemon_terminal', '_mark_router_daemon_terminal'),
                                                    ('_refresh_router_daemon_lock', '_refresh_router_daemon_lock'),
                                                    ('_release_router_daemon_lock', '_release_router_daemon_lock'),
                                                    ('_resolve_run_root_target', '_resolve_run_root_target'),
                                                    ('_router_daemon_can_continue_after_enqueued_action',
                                                     '_router_daemon_can_continue_after_enqueued_action'),
                                                    ('_router_daemon_fill_action_queue',
                                                     '_router_daemon_fill_action_queue'),
                                                    ('_router_daemon_resume_recovery_summary',
                                                     '_router_daemon_resume_recovery_summary'),
                                                    ('_router_daemon_tick', '_router_daemon_tick'),
                                                    ('_router_daemon_tick_requests_immediate_next_tick',
                                                     '_router_daemon_tick_requests_immediate_next_tick'),
                                                    ('_spawn_startup_router_daemon_process',
                                                     '_spawn_startup_router_daemon_process'),
                                                    ('_start_or_attach_formal_router_daemon',
                                                     '_start_or_attach_formal_router_daemon'),
                                                    ('_tail_text', '_tail_text'),
                                                    ('_write_router_daemon_status', '_write_router_daemon_status'),
                                                    ('run_router_daemon', 'run_router_daemon'),
                                                    ('stop_router_daemon', 'stop_router_daemon')),
 ('flowpilot_router_event_dispatcher', False, True): (('_record_external_event_unchecked',
                                                       '_record_external_event_unchecked'),),
 ('flowpilot_router_event_identity', False, True): (('_active_control_blocker_for_identity',
                                                     '_active_control_blocker_for_identity'),
                                                    ('_already_recorded_external_event_result',
                                                     '_already_recorded_external_event_result'),
                                                    ('_check_scoped_event_retry_budget',
                                                     '_check_scoped_event_retry_budget'),
                                                    ('_control_blocker_repair_decision_identity_scope',
                                                     '_control_blocker_repair_decision_identity_scope'),
                                                    ('_control_blocker_repair_outcome_identity_scope',
                                                     '_control_blocker_repair_outcome_identity_scope'),
                                                    ('_current_node_completion_identity_scope',
                                                     '_current_node_completion_identity_scope'),
                                                    ('_current_node_result_identity_scope',
                                                     '_current_node_result_identity_scope'),
                                                    ('_currently_allowed_external_events',
                                                     '_currently_allowed_external_events'),
                                                    ('_event_identity_ledger', '_event_identity_ledger'),
                                                    ('_external_event_flag_replay_requires_new_processing',
                                                     '_external_event_flag_replay_requires_new_processing'),
                                                    ('_frontier_for_event_identity', '_frontier_for_event_identity'),
                                                    ('_gate_decision_identity_scope', '_gate_decision_identity_scope'),
                                                    ('_load_file_backed_role_payload',
                                                     '_load_file_backed_role_payload'),
                                                    ('_load_file_backed_role_payload_if_present',
                                                     '_load_file_backed_role_payload_if_present'),
                                                    ('_load_record_event_envelope_ref',
                                                     '_load_record_event_envelope_ref'),
                                                    ('_looks_like_record_event_envelope',
                                                     '_looks_like_record_event_envelope'),
                                                    ('_mark_scoped_event_recorded', '_mark_scoped_event_recorded'),
                                                    ('_normalize_record_event_payload',
                                                     '_normalize_record_event_payload'),
                                                    ('_payload_body_hash', '_payload_body_hash'),
                                                    ('_payload_requires_record_event_envelope_validation',
                                                     '_payload_requires_record_event_envelope_validation'),
                                                    ('_payload_view_for_event_identity',
                                                     '_payload_view_for_event_identity'),
                                                    ('_pm_role_work_request_identity_scope',
                                                     '_pm_role_work_request_identity_scope'),
                                                    ('_pm_role_work_result_decision_identity_scope',
                                                     '_pm_role_work_result_decision_identity_scope'),
                                                    ('_record_event_envelope_ref_from_payload',
                                                     '_record_event_envelope_ref_from_payload'),
                                                    ('_record_event_expected_role', '_record_event_expected_role'),
                                                    ('_record_event_from_role_matches',
                                                     '_record_event_from_role_matches'),
                                                    ('_role_work_result_identity_scope',
                                                     '_role_work_result_identity_scope'),
                                                    ('_route_draft_identity_scope', '_route_draft_identity_scope'),
                                                    ('_route_mutation_identity_scope',
                                                     '_route_mutation_identity_scope'),
                                                    ('_scoped_event_identity', '_scoped_event_identity'),
                                                    ('_scoped_event_is_recorded', '_scoped_event_is_recorded'),
                                                    ('_stable_identity_hash', '_stable_identity_hash'),
                                                    ('_startup_repair_identity_scope',
                                                     '_startup_repair_identity_scope'),
                                                    ('_validate_record_event_envelope',
                                                     '_validate_record_event_envelope')),
 ('flowpilot_router_events_repair', False, True): (('_active_node_kind_for_event_capability',
                                                    '_active_node_kind_for_event_capability'),
                                                   ('_active_repair_transaction_for_event',
                                                    '_active_repair_transaction_for_event'),
                                                   ('_blocker_repair_policy_rows', '_blocker_repair_policy_rows'),
                                                   ('_blocker_repair_policy_snapshot_path',
                                                    '_blocker_repair_policy_snapshot_path'),
                                                   ('_classify_control_blocker', '_classify_control_blocker'),
                                                   ('_clear_successful_repair_lane_state',
                                                    '_clear_successful_repair_lane_state'),
                                                   ('_commit_material_scan_repair_generation',
                                                    '_commit_material_scan_repair_generation'),
                                                   ('_control_blocker_allowed_resolution_events',
                                                    '_control_blocker_allowed_resolution_events'),
                                                   ('_control_blocker_allows_resolution_event',
                                                    '_control_blocker_allows_resolution_event'),
                                                   ('_control_blocker_attempt_key', '_control_blocker_attempt_key'),
                                                   ('_control_blocker_direct_attempts_used',
                                                    '_control_blocker_direct_attempts_used'),
                                                   ('_control_blocker_error_code', '_control_blocker_error_code'),
                                                   ('_control_blocker_followup_target_role',
                                                    '_control_blocker_followup_target_role'),
                                                   ('_control_blocker_matches_reconciled_action',
                                                    '_control_blocker_matches_reconciled_action'),
                                                   ('_control_blocker_policy', '_control_blocker_policy'),
                                                   ('_control_blocker_policy_row', '_control_blocker_policy_row'),
                                                   ('_control_blocker_record', '_control_blocker_record'),
                                                   ('_control_blocker_repair_origin', '_control_blocker_repair_origin'),
                                                   ('_control_blocker_summary', '_control_blocker_summary'),
                                                   ('_control_blocker_wait_events', '_control_blocker_wait_events'),
                                                   ('_control_payload_public_view', '_control_payload_public_view'),
                                                   ('_control_resolution_event_name', '_control_resolution_event_name'),
                                                   ('_controller_wait_entries_for_event',
                                                    '_controller_wait_entries_for_event'),
                                                   ('_default_pm_recovery_option', '_default_pm_recovery_option'),
                                                   ('_event_already_recorded', '_event_already_recorded'),
                                                   ('_event_capability_issue', '_event_capability_issue'),
                                                   ('_event_producer_roles', '_event_producer_roles'),
                                                   ('_existing_event_producer_evidence',
                                                    '_existing_event_producer_evidence'),
                                                   ('_external_event_validation_issue',
                                                    '_external_event_validation_issue'),
                                                   ('_finalize_repair_transaction_outcome',
                                                    '_finalize_repair_transaction_outcome'),
                                                   ('_gate_decision_issue', '_gate_decision_issue'),
                                                   ('_gate_decision_issues', '_gate_decision_issues'),
                                                   ('_gate_decision_record_path', '_gate_decision_record_path'),
                                                   ('_gate_decision_safe_id', '_gate_decision_safe_id'),
                                                   ('_gate_decision_summary', '_gate_decision_summary'),
                                                   ('_infer_responsible_role', '_infer_responsible_role'),
                                                   ('_list_field', '_list_field'),
                                                   ('_make_controller_repair_work_packet_action',
                                                    '_make_controller_repair_work_packet_action'),
                                                   ('_make_operation_replay_action', '_make_operation_replay_action'),
                                                   ('_mark_control_blocker_delivered',
                                                    '_mark_control_blocker_delivered'),
                                                   ('_next_control_blocker_action', '_next_control_blocker_action'),
                                                   ('_next_repair_transaction_executable_action',
                                                    '_next_repair_transaction_executable_action'),
                                                   ('_nonnegative_int_or_none', '_nonnegative_int_or_none'),
                                                   ('_payload_source_paths', '_payload_source_paths'),
                                                   ('_pm_recovery_options_from_policy',
                                                    '_pm_recovery_options_from_policy'),
                                                   ('_policy_first_handler_target', '_policy_first_handler_target'),
                                                   ('_project_relative_if_possible', '_project_relative_if_possible'),
                                                   ('_repair_outcome_events', '_repair_outcome_events'),
                                                   ('_repair_outcome_table', '_repair_outcome_table'),
                                                   ('_repair_packet_specs_from_decision',
                                                    '_repair_packet_specs_from_decision'),
                                                   ('_repair_transaction_execution_plan',
                                                    '_repair_transaction_execution_plan'),
                                                   ('_repair_transaction_for_control_blocker',
                                                    '_repair_transaction_for_control_blocker'),
                                                   ('_repair_transaction_id', '_repair_transaction_id'),
                                                   ('_repair_transaction_index_path', '_repair_transaction_index_path'),
                                                   ('_repair_transaction_normalized_plan_kind',
                                                    '_repair_transaction_normalized_plan_kind'),
                                                   ('_repair_transaction_outcome_kind',
                                                    '_repair_transaction_outcome_kind'),
                                                   ('_repair_transaction_path', '_repair_transaction_path'),
                                                   ('_repair_transactions_root', '_repair_transactions_root'),
                                                   ('_resolve_control_blockers_for_reconciled_controller_action',
                                                    '_resolve_control_blockers_for_reconciled_controller_action'),
                                                   ('_resolve_delivered_control_blocker',
                                                    '_resolve_delivered_control_blocker'),
                                                   ('_resume_reentry_gate_pending', '_resume_reentry_gate_pending'),
                                                   ('_role_set', '_role_set'),
                                                   ('_run_state_with_assumed_flag', '_run_state_with_assumed_flag'),
                                                   ('_should_materialize_control_blocker',
                                                    '_should_materialize_control_blocker'),
                                                   ('_skill_observation_reminder', '_skill_observation_reminder'),
                                                   ('_supersede_prior_control_blockers',
                                                    '_supersede_prior_control_blockers'),
                                                   ('_supersede_queued_control_blocker_actions',
                                                    '_supersede_queued_control_blocker_actions'),
                                                   ('_sync_control_plane_indexes', '_sync_control_plane_indexes'),
                                                   ('_sync_protocol_blocker_index', '_sync_protocol_blocker_index'),
                                                   ('_validate_gate_decision', '_validate_gate_decision'),
                                                   ('_validate_model_miss_officer_report_refs',
                                                    '_validate_model_miss_officer_report_refs'),
                                                   ('_validate_repair_outcome_table', '_validate_repair_outcome_table'),
                                                   ('_validate_wait_event_producer_binding',
                                                    '_validate_wait_event_producer_binding'),
                                                   ('_validated_event_capability_names',
                                                    '_validated_event_capability_names'),
                                                   ('_validated_external_event_names',
                                                    '_validated_external_event_names'),
                                                   ('_write_blocker_repair_policy_snapshot',
                                                    '_write_blocker_repair_policy_snapshot'),
                                                   ('_write_control_blocker', '_write_control_blocker'),
                                                   ('_write_control_blocker_repair_decision',
                                                    '_write_control_blocker_repair_decision'),
                                                   ('_write_control_blocker_repair_packet',
                                                    '_write_control_blocker_repair_packet'),
                                                   ('_write_gate_decision', '_write_gate_decision'),
                                                   ('_write_model_miss_triage_decision',
                                                    '_write_model_miss_triage_decision'),
                                                   ('_write_repair_transaction_index',
                                                    '_write_repair_transaction_index')),
 ('flowpilot_router_expected_waits', True, False): (('_active_node_children_status', '_active_node_children_status'),
                                                    ('_event_applicable_for_active_node',
                                                     '_event_applicable_for_active_node'),
                                                    ('_event_wait_role', '_event_wait_role'),
                                                    ('_expected_role_decision_wait_action',
                                                     '_expected_role_decision_wait_action'),
                                                    ('_next_expected_role_decision_wait_action',
                                                     '_next_expected_role_decision_wait_action'),
                                                    ('_next_model_miss_controlled_stop_action',
                                                     '_next_model_miss_controlled_stop_action'),
                                                    ('_next_model_miss_followup_request_wait_action',
                                                     '_next_model_miss_followup_request_wait_action'),
                                                    ('_pending_expected_external_event_groups',
                                                     '_pending_expected_external_event_groups'),
                                                    ('_pending_role_decision_staleness',
                                                     '_pending_role_decision_staleness'),
                                                    ('_reconcile_pending_role_wait_from_packet_status',
                                                     '_reconcile_pending_role_wait_from_packet_status'),
                                                    ('_record_router_reconciled_external_event',
                                                     '_record_router_reconciled_external_event'),
                                                    ('_run_state_has_event', '_run_state_has_event'),
                                                    ('_try_reconcile_current_node_results',
                                                     '_try_reconcile_current_node_results'),
                                                    ('_try_reconcile_material_scan_body_delivery',
                                                     '_try_reconcile_material_scan_body_delivery'),
                                                    ('_try_reconcile_material_scan_results',
                                                     '_try_reconcile_material_scan_results'),
                                                    ('_try_reconcile_pm_role_work_results',
                                                     '_try_reconcile_pm_role_work_results')),
 ('flowpilot_router_lifecycle_requests', True, False): (('_clear_active_control_blocker_for_terminal_lifecycle',
                                                         '_clear_active_control_blocker_for_terminal_lifecycle'),
                                                        ('_reconcile_terminal_lifecycle_authorities',
                                                         '_reconcile_terminal_lifecycle_authorities'),
                                                        ('_run_lifecycle_terminal_action',
                                                         '_run_lifecycle_terminal_action'),
                                                        ('_try_write_control_blocker_for_exception',
                                                         '_try_write_control_blocker_for_exception'),
                                                        ('_write_protocol_dead_end_lifecycle',
                                                         '_write_protocol_dead_end_lifecycle'),
                                                        ('_write_run_lifecycle_request',
                                                         '_write_run_lifecycle_request')),
 ('flowpilot_router_lifecycle_support', True, False): (('_lifecycle_record_path', '_lifecycle_record_path'),
                                                       ('_reset_resume_cycle_for_wakeup',
                                                        '_reset_resume_cycle_for_wakeup'),
                                                       ('_write_host_heartbeat_binding',
                                                        '_write_host_heartbeat_binding'))}

def owner_exports_controller() -> dict[RegistryKey, tuple[ExportSpec, ...]]:
    return OWNER_EXPORTS_CONTROLLER


__all__ = ["OWNER_EXPORTS_CONTROLLER", "owner_exports_controller"]
