"""Explicit owner-export registry for the FlowPilot router skeleton.

This module replaces hundreds of hand-written compatibility wrappers in
``flowpilot_router.py`` with one auditable registry. The exported names are
transitional internal owner lookups, not the documented public API.
"""

from __future__ import annotations

import importlib
from types import ModuleType
from typing import Any, Callable

ExportSpec = tuple[str, str]
RegistryKey = tuple[str, bool, bool]

OWNER_EXPORTS: dict[RegistryKey, tuple[ExportSpec, ...]] = {
    ('flowpilot_router_action_factory', True, False): (
        ('_action_is_startup_async_card_wait', '_action_is_startup_async_card_wait'),
        ('_action_is_startup_async_delivery', '_action_is_startup_async_delivery'),
        ('_apply_dispatch_recipient_gate', '_apply_dispatch_recipient_gate'),
        ('_apply_formal_work_packet_ack_preflight', '_apply_formal_work_packet_ack_preflight'),
        ('_committed_card_artifact_extra', '_committed_card_artifact_extra'),
        ('_controller_user_reporting_policy', '_controller_user_reporting_policy'),
        ('_current_node_scope_exit_reconciliation_blockers', '_current_node_scope_exit_reconciliation_blockers'),
        ('_current_scope_pre_review_reconciliation_action', '_current_scope_pre_review_reconciliation_action'),
        ('_current_scope_reconciliation_wait_still_blocked', '_current_scope_reconciliation_wait_still_blocked'),
        ('_dispatch_gate_action_is_ack_only_prompt', '_dispatch_gate_action_is_ack_only_prompt'),
        ('_dispatch_gate_action_work_class', '_dispatch_gate_action_work_class'),
        ('_dispatch_gate_card_entry', '_dispatch_gate_card_entry'),
        ('_dispatch_gate_output_events_for_action', '_dispatch_gate_output_events_for_action'),
        ('_dispatch_gate_output_events_for_card_id', '_dispatch_gate_output_events_for_card_id'),
        ('_dispatch_gate_packet_blocker', '_dispatch_gate_packet_blocker'),
        ('_dispatch_gate_passive_wait_blocker', '_dispatch_gate_passive_wait_blocker'),
        ('_dispatch_gate_pending_ack_wait', '_dispatch_gate_pending_ack_wait'),
        ('_dispatch_gate_pending_expected_output_blocker', '_dispatch_gate_pending_expected_output_blocker'),
        ('_dispatch_gate_pm_role_work_blocker', '_dispatch_gate_pm_role_work_blocker'),
        ('_dispatch_gate_same_obligation_instruction_context', '_dispatch_gate_same_obligation_instruction_context'),
        ('_dispatch_gate_wait_action', '_dispatch_gate_wait_action'),
        ('_next_local_obligation_before_passive_wait', '_next_local_obligation_before_passive_wait'),
        ('_next_pending_card_return_action', '_next_pending_card_return_action'),
        ('_pending_card_return_blocker_for_event', '_pending_card_return_blocker_for_event'),
        ('_roles_from_action_to_role', '_roles_from_action_to_role'),
        ('_startup_async_pending_returns', '_startup_async_pending_returns'),
        ('append_history', 'append_history'),
        ('make_action', 'make_action'),
    ),
    ('flowpilot_router_action_handlers', False, True): (
        ('_auto_commit_system_card_bundle_delivery_action', 'auto_commit_system_card_bundle_delivery_action'),
    ),
    ('flowpilot_router_artifact_validation', True, False): (
        ('_artifact_issue', '_artifact_issue'),
        ('_validate_hash_if_present', '_validate_hash_if_present'),
        ('_validate_role_output_hash_if_present', '_validate_role_output_hash_if_present'),
        ('validate_artifact', 'validate_artifact'),
    ),
    ('flowpilot_router_card_returns', False, True): (
        ('_card_return_resolved_for_action', '_card_return_resolved_for_action'),
        ('_current_node_pre_review_reconciliation_blockers', '_current_node_pre_review_reconciliation_blockers'),
        ('_pending_card_return_ack_exists', '_pending_card_return_ack_exists'),
        ('_pending_return_card_ids', '_pending_return_card_ids'),
        ('_pending_return_is_outside_active_node_scope', '_pending_return_is_outside_active_node_scope'),
        ('_pending_return_is_pre_review_startup_scope', '_pending_return_is_pre_review_startup_scope'),
        ('_pending_return_is_startup_async_scope', '_pending_return_is_startup_async_scope'),
        ('_pending_return_matches_active_node_scope', '_pending_return_matches_active_node_scope'),
        ('_pending_return_records', '_pending_return_records'),
        ('_pre_review_reconciliation_blockers_for_trigger', '_pre_review_reconciliation_blockers_for_trigger'),
        ('_startup_pre_review_ack_join_clean', '_startup_pre_review_ack_join_clean'),
        ('_startup_pre_review_card_flags', '_startup_pre_review_card_flags'),
        ('_startup_pre_review_cards_delivered', '_startup_pre_review_cards_delivered'),
        ('_startup_pre_review_pending_returns', '_startup_pre_review_pending_returns'),
        ('_startup_pre_review_reconciliation_blockers', '_startup_pre_review_reconciliation_blockers'),
    ),
    ('flowpilot_router_child_skill_capability', True, False): (
        ('_approve_child_skill_manifest_for_route', '_approve_child_skill_manifest_for_route'),
        ('_sync_capability_evidence', '_sync_capability_evidence'),
        ('_sync_child_skill_manifest_review_approval', '_sync_child_skill_manifest_review_approval'),
    ),
    ('flowpilot_router_cli', True, False): (
        ('main', 'main'),
        ('parse_args', 'parse_args'),
    ),
    ('flowpilot_router_control_transactions', True, False): (
        ('_control_transaction_contract_registry_path', '_control_transaction_contract_registry_path'),
        ('_control_transaction_registry_issues', '_control_transaction_registry_issues'),
        ('_control_transaction_registry_path', '_control_transaction_registry_path'),
        ('_control_transaction_registry_rows', '_control_transaction_registry_rows'),
        ('_control_transaction_row', '_control_transaction_row'),
        ('_load_control_transaction_registry', '_load_control_transaction_registry'),
        ('_registered_output_contract_ids', '_registered_output_contract_ids'),
        ('_validate_control_transaction_registry', '_validate_control_transaction_registry'),
        ('_validate_control_transaction_requirements', '_validate_control_transaction_requirements'),
    ),
    ('flowpilot_router_controller_repair', True, False): (
        ('_close_waiting_controller_actions_for_external_event', '_close_waiting_controller_actions_for_external_event'),
        ('_controller_action_required_deliverables', '_controller_action_required_deliverables'),
        ('_controller_boundary_flags_synced', '_controller_boundary_flags_synced'),
        ('_controller_boundary_required_deliverable', '_controller_boundary_required_deliverable'),
        ('_controller_deliverable_contract', '_controller_deliverable_contract'),
        ('_controller_deliverable_failed_repair_ids', '_controller_deliverable_failed_repair_ids'),
        ('_controller_repair_action_is_pending', '_controller_repair_action_is_pending'),
        ('_count_unique_mail_deliveries', '_count_unique_mail_deliveries'),
        ('_defer_controller_postcondition_reconciliation_retry', '_defer_controller_postcondition_reconciliation_retry'),
        ('_done_controller_receipt_for_entry', '_done_controller_receipt_for_entry'),
        ('_ensure_mail_delivery_packet_released', '_ensure_mail_delivery_packet_released'),
        ('_find_mail_delivery', '_find_mail_delivery'),
        ('_fold_mail_delivery_postcondition', '_fold_mail_delivery_postcondition'),
        ('_mail_delivery_action_envelope_path', '_mail_delivery_action_envelope_path'),
        ('_mail_delivery_matches', '_mail_delivery_matches'),
        ('_mail_delivery_packet_released', '_mail_delivery_packet_released'),
        ('_mail_role_obligation_contract', '_mail_role_obligation_contract'),
        ('_mail_sequence_entry', '_mail_sequence_entry'),
        ('_mark_controller_deliverable_repair_resolved', '_mark_controller_deliverable_repair_resolved'),
        ('_missing_deliverables_for_apply_result', '_missing_deliverables_for_apply_result'),
        ('_packet_record_for_mail_delivery', '_packet_record_for_mail_delivery'),
        ('_pending_action_postcondition', '_pending_action_postcondition'),
        ('_pending_action_postcondition_satisfied', '_pending_action_postcondition_satisfied'),
        ('_pending_controller_action_id', '_pending_controller_action_id'),
        ('_receipt_for_pending_controller_action', '_receipt_for_pending_controller_action'),
        ('_reclaim_router_owned_postcondition_from_artifact', '_reclaim_router_owned_postcondition_from_artifact'),
        ('_reconcile_controller_boundary_confirmation_projection', '_reconcile_controller_boundary_confirmation_projection'),
        ('_router_scheduler_row_for_controller_entry', '_router_scheduler_row_for_controller_entry'),
        ('_schedule_controller_deliverable_repair', '_schedule_controller_deliverable_repair'),
        ('_sync_controller_boundary_confirmation_from_artifact', '_sync_controller_boundary_confirmation_from_artifact'),
        ('_update_controller_action_entry_fields', '_update_controller_action_entry_fields'),
        ('_write_controller_deliverable_budget_blocker', '_write_controller_deliverable_budget_blocker'),
    ),
    ('flowpilot_router_controller_runtime', True, False): (
        ('_next_mail_action', '_next_mail_action'),
        ('apply_action', 'apply_action'),
        ('apply_controller_action', 'apply_controller_action'),
        ('compute_controller_action', 'compute_controller_action'),
        ('next_action', 'next_action'),
        ('record_controller_action_receipt', 'record_controller_action_receipt'),
        ('record_external_event', 'record_external_event'),
        ('run_until_wait', 'run_until_wait'),
    ),
    ('flowpilot_router_controller_scheduler', False, True): (
        ('_action_is_startup_scoped', '_action_is_startup_scoped'),
        ('_apply_done_controller_receipt_effects', '_apply_done_controller_receipt_effects'),
        ('_apply_startup_bootloader_receipt_effects', '_apply_startup_bootloader_receipt_effects'),
        ('_apply_stateful_receipt_postcondition', '_apply_stateful_receipt_postcondition'),
        ('_apply_wait_target_reminder_receipt', '_apply_wait_target_reminder_receipt'),
        ('_backfill_scheduler_row_from_reconciled_controller_action', '_backfill_scheduler_row_from_reconciled_controller_action'),
        ('_boot_action_meta', '_boot_action_meta'),
        ('_build_foreground_controller_standby_snapshot', '_build_foreground_controller_standby_snapshot'),
        ('_canonicalize_legacy_startup_daemon_reconciliation', '_canonicalize_legacy_startup_daemon_reconciliation'),
        ('_clear_pending_after_reconciled_controller_receipt', '_clear_pending_after_reconciled_controller_receipt'),
        ('_continuous_standby_release_conditions', '_continuous_standby_release_conditions'),
        ('_continuous_standby_task_payload', '_continuous_standby_task_payload'),
        ('_continuous_standby_watch_label', '_continuous_standby_watch_label'),
        ('_controller_action_completion_class', '_controller_action_completion_class'),
        ('_controller_action_ledger_has_prompt_header', '_controller_action_ledger_has_prompt_header'),
        ('_controller_action_ledger_summary', '_controller_action_ledger_summary'),
        ('_controller_action_open_for', '_controller_action_open_for'),
        ('_current_action_is_ordinary_controller_work', '_current_action_is_ordinary_controller_work'),
        ('_current_work_from_action', '_current_work_from_action'),
        ('_current_work_from_packet_ledger', '_current_work_from_packet_ledger'),
        ('_current_work_from_passive_waits', '_current_work_from_passive_waits'),
        ('_current_work_owner_kind', '_current_work_owner_kind'),
        ('_current_work_owner_label', '_current_work_owner_label'),
        ('_current_work_payload', '_current_work_payload'),
        ('_derive_current_work', '_derive_current_work'),
        ('_elapsed_seconds_since', '_elapsed_seconds_since'),
        ('_empty_router_ownership_ledger', '_empty_router_ownership_ledger'),
        ('_empty_router_scheduler_ledger', '_empty_router_scheduler_ledger'),
        ('_ensure_continuous_standby_controller_action', '_ensure_continuous_standby_controller_action'),
        ('_ensure_controller_action_ledger', '_ensure_controller_action_ledger'),
        ('_ensure_router_ownership_ledger', '_ensure_router_ownership_ledger'),
        ('_ensure_router_scheduler_ledger', '_ensure_router_scheduler_ledger'),
        ('_ensure_wait_target_reminder_controller_action', '_ensure_wait_target_reminder_controller_action'),
        ('_foreground_standby_pending_action_ids', '_foreground_standby_pending_action_ids'),
        ('_foreground_standby_waiting_action_ids', '_foreground_standby_waiting_action_ids'),
        ('_mark_pending_return_wait_reminded', '_mark_pending_return_wait_reminded'),
        ('_matching_bootstrap_pending_action', '_matching_bootstrap_pending_action'),
        ('_maybe_write_controller_receipt_for_pending', '_maybe_write_controller_receipt_for_pending'),
        ('_next_wait_target_reminder_action', '_next_wait_target_reminder_action'),
        ('_packet_status_allows_current_work', '_packet_status_allows_current_work'),
        ('_pending_return_matches_wait_target_reminder', '_pending_return_matches_wait_target_reminder'),
        ('_pending_wait_class', '_pending_wait_class'),
        ('_pending_wait_summary', '_pending_wait_summary'),
        ('_prepare_router_scheduled_action', '_prepare_router_scheduled_action'),
        ('_read_router_ownership_ledger', '_read_router_ownership_ledger'),
        ('_read_router_scheduler_ledger', '_read_router_scheduler_ledger'),
        ('_rebuild_controller_action_ledger', '_rebuild_controller_action_ledger'),
        ('_reconcile_controller_receipts', '_reconcile_controller_receipts'),
        ('_reconcile_pending_controller_action_receipt', '_reconcile_pending_controller_action_receipt'),
        ('_reconcile_scheduled_controller_action_receipts', '_reconcile_scheduled_controller_action_receipts'),
        ('_record_router_ownership_entry', '_record_router_ownership_entry'),
        ('_record_router_scheduler_row', '_record_router_scheduler_row'),
        ('_router_ownership_counts', '_router_ownership_counts'),
        ('_router_ownership_ledger_summary', '_router_ownership_ledger_summary'),
        ('_router_scheduler_barrier_kind', '_router_scheduler_barrier_kind'),
        ('_router_scheduler_ledger_summary', '_router_scheduler_ledger_summary'),
        ('_router_scheduler_progress_class', '_router_scheduler_progress_class'),
        ('_router_scheduler_scope_for_action', '_router_scheduler_scope_for_action'),
        ('_scheduler_row_reconciliation_for_entry', '_scheduler_row_reconciliation_for_entry'),
        ('_should_refresh_continuous_standby_row', '_should_refresh_continuous_standby_row'),
        ('_update_router_scheduler_row', '_update_router_scheduler_row'),
        ('_wait_target_due_state', '_wait_target_due_state'),
        ('_wait_target_identity', '_wait_target_identity'),
        ('_wait_target_path_exists', '_wait_target_path_exists'),
        ('_wait_target_reminder_payload_contract', '_wait_target_reminder_payload_contract'),
        ('_wait_target_reminder_text', '_wait_target_reminder_text'),
        ('_wait_target_reminder_text_sha256', '_wait_target_reminder_text_sha256'),
        ('_write_controller_action_entry', '_write_controller_action_entry'),
        ('_write_controller_action_ledger', '_write_controller_action_ledger'),
        ('_write_controller_receipt', '_write_controller_receipt'),
        ('_write_router_ownership_ledger', '_write_router_ownership_ledger'),
        ('_write_router_scheduler_ledger', '_write_router_scheduler_ledger'),
        ('controller_patrol_timer', 'controller_patrol_timer'),
        ('foreground_controller_standby', 'foreground_controller_standby'),
    ),
    ('flowpilot_router_daemon_runtime', False, True): (
        ('_acquire_router_daemon_lock', '_acquire_router_daemon_lock'),
        ('_append_router_daemon_event', '_append_router_daemon_event'),
        ('_ensure_daemon_runtime_state', '_ensure_daemon_runtime_state'),
        ('_formal_router_daemon_ready', '_formal_router_daemon_ready'),
        ('_mark_router_daemon_terminal', '_mark_router_daemon_terminal'),
        ('_refresh_router_daemon_lock', '_refresh_router_daemon_lock'),
        ('_release_router_daemon_lock', '_release_router_daemon_lock'),
        ('_resolve_run_root_target', '_resolve_run_root_target'),
        ('_router_daemon_can_continue_after_enqueued_action', '_router_daemon_can_continue_after_enqueued_action'),
        ('_router_daemon_fill_action_queue', '_router_daemon_fill_action_queue'),
        ('_router_daemon_resume_recovery_summary', '_router_daemon_resume_recovery_summary'),
        ('_router_daemon_tick', '_router_daemon_tick'),
        ('_router_daemon_tick_requests_immediate_next_tick', '_router_daemon_tick_requests_immediate_next_tick'),
        ('_spawn_startup_router_daemon_process', '_spawn_startup_router_daemon_process'),
        ('_start_or_attach_formal_router_daemon', '_start_or_attach_formal_router_daemon'),
        ('_tail_text', '_tail_text'),
        ('_write_router_daemon_status', '_write_router_daemon_status'),
        ('run_router_daemon', 'run_router_daemon'),
        ('stop_router_daemon', 'stop_router_daemon'),
    ),
    ('flowpilot_router_event_dispatcher', False, True): (
        ('_record_external_event_unchecked', '_record_external_event_unchecked'),
    ),
    ('flowpilot_router_event_identity', False, True): (
        ('_active_control_blocker_for_identity', '_active_control_blocker_for_identity'),
        ('_already_recorded_external_event_result', '_already_recorded_external_event_result'),
        ('_check_scoped_event_retry_budget', '_check_scoped_event_retry_budget'),
        ('_control_blocker_repair_decision_identity_scope', '_control_blocker_repair_decision_identity_scope'),
        ('_control_blocker_repair_outcome_identity_scope', '_control_blocker_repair_outcome_identity_scope'),
        ('_current_node_completion_identity_scope', '_current_node_completion_identity_scope'),
        ('_current_node_result_identity_scope', '_current_node_result_identity_scope'),
        ('_currently_allowed_external_events', '_currently_allowed_external_events'),
        ('_event_identity_ledger', '_event_identity_ledger'),
        ('_external_event_flag_replay_requires_new_processing', '_external_event_flag_replay_requires_new_processing'),
        ('_frontier_for_event_identity', '_frontier_for_event_identity'),
        ('_gate_decision_identity_scope', '_gate_decision_identity_scope'),
        ('_load_file_backed_role_payload', '_load_file_backed_role_payload'),
        ('_load_file_backed_role_payload_if_present', '_load_file_backed_role_payload_if_present'),
        ('_load_record_event_envelope_ref', '_load_record_event_envelope_ref'),
        ('_looks_like_record_event_envelope', '_looks_like_record_event_envelope'),
        ('_mark_scoped_event_recorded', '_mark_scoped_event_recorded'),
        ('_normalize_record_event_payload', '_normalize_record_event_payload'),
        ('_payload_body_hash', '_payload_body_hash'),
        ('_payload_requires_record_event_envelope_validation', '_payload_requires_record_event_envelope_validation'),
        ('_payload_view_for_event_identity', '_payload_view_for_event_identity'),
        ('_pm_role_work_request_identity_scope', '_pm_role_work_request_identity_scope'),
        ('_pm_role_work_result_decision_identity_scope', '_pm_role_work_result_decision_identity_scope'),
        ('_record_event_envelope_ref_from_payload', '_record_event_envelope_ref_from_payload'),
        ('_record_event_expected_role', '_record_event_expected_role'),
        ('_record_event_from_role_matches', '_record_event_from_role_matches'),
        ('_role_work_result_identity_scope', '_role_work_result_identity_scope'),
        ('_route_draft_identity_scope', '_route_draft_identity_scope'),
        ('_route_mutation_identity_scope', '_route_mutation_identity_scope'),
        ('_scoped_event_identity', '_scoped_event_identity'),
        ('_scoped_event_is_recorded', '_scoped_event_is_recorded'),
        ('_stable_identity_hash', '_stable_identity_hash'),
        ('_startup_repair_identity_scope', '_startup_repair_identity_scope'),
        ('_validate_record_event_envelope', '_validate_record_event_envelope'),
    ),
    ('flowpilot_router_events_repair', False, True): (
        ('_active_node_kind_for_event_capability', '_active_node_kind_for_event_capability'),
        ('_active_repair_transaction_for_event', '_active_repair_transaction_for_event'),
        ('_blocker_repair_policy_rows', '_blocker_repair_policy_rows'),
        ('_blocker_repair_policy_snapshot_path', '_blocker_repair_policy_snapshot_path'),
        ('_classify_control_blocker', '_classify_control_blocker'),
        ('_clear_successful_repair_lane_state', '_clear_successful_repair_lane_state'),
        ('_commit_material_scan_repair_generation', '_commit_material_scan_repair_generation'),
        ('_control_blocker_allowed_resolution_events', '_control_blocker_allowed_resolution_events'),
        ('_control_blocker_allows_resolution_event', '_control_blocker_allows_resolution_event'),
        ('_control_blocker_attempt_key', '_control_blocker_attempt_key'),
        ('_control_blocker_direct_attempts_used', '_control_blocker_direct_attempts_used'),
        ('_control_blocker_error_code', '_control_blocker_error_code'),
        ('_control_blocker_followup_target_role', '_control_blocker_followup_target_role'),
        ('_control_blocker_matches_reconciled_action', '_control_blocker_matches_reconciled_action'),
        ('_control_blocker_policy', '_control_blocker_policy'),
        ('_control_blocker_policy_row', '_control_blocker_policy_row'),
        ('_control_blocker_record', '_control_blocker_record'),
        ('_control_blocker_repair_origin', '_control_blocker_repair_origin'),
        ('_control_blocker_summary', '_control_blocker_summary'),
        ('_control_blocker_wait_events', '_control_blocker_wait_events'),
        ('_control_payload_public_view', '_control_payload_public_view'),
        ('_control_resolution_event_name', '_control_resolution_event_name'),
        ('_controller_wait_entries_for_event', '_controller_wait_entries_for_event'),
        ('_default_pm_recovery_option', '_default_pm_recovery_option'),
        ('_event_already_recorded', '_event_already_recorded'),
        ('_event_capability_issue', '_event_capability_issue'),
        ('_event_producer_roles', '_event_producer_roles'),
        ('_existing_event_producer_evidence', '_existing_event_producer_evidence'),
        ('_external_event_validation_issue', '_external_event_validation_issue'),
        ('_finalize_repair_transaction_outcome', '_finalize_repair_transaction_outcome'),
        ('_gate_decision_issue', '_gate_decision_issue'),
        ('_gate_decision_issues', '_gate_decision_issues'),
        ('_gate_decision_record_path', '_gate_decision_record_path'),
        ('_gate_decision_safe_id', '_gate_decision_safe_id'),
        ('_gate_decision_summary', '_gate_decision_summary'),
        ('_infer_responsible_role', '_infer_responsible_role'),
        ('_list_field', '_list_field'),
        ('_make_controller_repair_work_packet_action', '_make_controller_repair_work_packet_action'),
        ('_make_operation_replay_action', '_make_operation_replay_action'),
        ('_mark_control_blocker_delivered', '_mark_control_blocker_delivered'),
        ('_next_control_blocker_action', '_next_control_blocker_action'),
        ('_next_repair_transaction_executable_action', '_next_repair_transaction_executable_action'),
        ('_nonnegative_int_or_none', '_nonnegative_int_or_none'),
        ('_payload_source_paths', '_payload_source_paths'),
        ('_pm_recovery_options_from_policy', '_pm_recovery_options_from_policy'),
        ('_policy_first_handler_target', '_policy_first_handler_target'),
        ('_project_relative_if_possible', '_project_relative_if_possible'),
        ('_repair_outcome_events', '_repair_outcome_events'),
        ('_repair_outcome_table', '_repair_outcome_table'),
        ('_repair_packet_specs_from_decision', '_repair_packet_specs_from_decision'),
        ('_repair_transaction_execution_plan', '_repair_transaction_execution_plan'),
        ('_repair_transaction_for_control_blocker', '_repair_transaction_for_control_blocker'),
        ('_repair_transaction_id', '_repair_transaction_id'),
        ('_repair_transaction_index_path', '_repair_transaction_index_path'),
        ('_repair_transaction_normalized_plan_kind', '_repair_transaction_normalized_plan_kind'),
        ('_repair_transaction_outcome_kind', '_repair_transaction_outcome_kind'),
        ('_repair_transaction_path', '_repair_transaction_path'),
        ('_repair_transactions_root', '_repair_transactions_root'),
        ('_resolve_control_blockers_for_reconciled_controller_action', '_resolve_control_blockers_for_reconciled_controller_action'),
        ('_resolve_delivered_control_blocker', '_resolve_delivered_control_blocker'),
        ('_resume_reentry_gate_pending', '_resume_reentry_gate_pending'),
        ('_role_set', '_role_set'),
        ('_run_state_with_assumed_flag', '_run_state_with_assumed_flag'),
        ('_should_materialize_control_blocker', '_should_materialize_control_blocker'),
        ('_skill_observation_reminder', '_skill_observation_reminder'),
        ('_supersede_prior_control_blockers', '_supersede_prior_control_blockers'),
        ('_supersede_queued_control_blocker_actions', '_supersede_queued_control_blocker_actions'),
        ('_sync_control_plane_indexes', '_sync_control_plane_indexes'),
        ('_sync_protocol_blocker_index', '_sync_protocol_blocker_index'),
        ('_validate_gate_decision', '_validate_gate_decision'),
        ('_validate_model_miss_officer_report_refs', '_validate_model_miss_officer_report_refs'),
        ('_validate_repair_outcome_table', '_validate_repair_outcome_table'),
        ('_validate_wait_event_producer_binding', '_validate_wait_event_producer_binding'),
        ('_validated_event_capability_names', '_validated_event_capability_names'),
        ('_validated_external_event_names', '_validated_external_event_names'),
        ('_write_blocker_repair_policy_snapshot', '_write_blocker_repair_policy_snapshot'),
        ('_write_control_blocker', '_write_control_blocker'),
        ('_write_control_blocker_repair_decision', '_write_control_blocker_repair_decision'),
        ('_write_control_blocker_repair_packet', '_write_control_blocker_repair_packet'),
        ('_write_gate_decision', '_write_gate_decision'),
        ('_write_model_miss_triage_decision', '_write_model_miss_triage_decision'),
        ('_write_repair_transaction_index', '_write_repair_transaction_index'),
    ),
    ('flowpilot_router_expected_waits', True, False): (
        ('_active_node_children_status', '_active_node_children_status'),
        ('_event_applicable_for_active_node', '_event_applicable_for_active_node'),
        ('_event_wait_role', '_event_wait_role'),
        ('_expected_role_decision_wait_action', '_expected_role_decision_wait_action'),
        ('_next_expected_role_decision_wait_action', '_next_expected_role_decision_wait_action'),
        ('_next_model_miss_controlled_stop_action', '_next_model_miss_controlled_stop_action'),
        ('_next_model_miss_followup_request_wait_action', '_next_model_miss_followup_request_wait_action'),
        ('_pending_expected_external_event_groups', '_pending_expected_external_event_groups'),
        ('_pending_role_decision_staleness', '_pending_role_decision_staleness'),
        ('_reconcile_pending_role_wait_from_packet_status', '_reconcile_pending_role_wait_from_packet_status'),
        ('_record_router_reconciled_external_event', '_record_router_reconciled_external_event'),
        ('_run_state_has_event', '_run_state_has_event'),
        ('_try_reconcile_current_node_results', '_try_reconcile_current_node_results'),
        ('_try_reconcile_material_scan_body_delivery', '_try_reconcile_material_scan_body_delivery'),
        ('_try_reconcile_material_scan_results', '_try_reconcile_material_scan_results'),
        ('_try_reconcile_pm_role_work_results', '_try_reconcile_pm_role_work_results'),
    ),
    ('flowpilot_router_internal_actions', True, False): (
        ('_action_is_router_internal_mechanical', '_action_is_router_internal_mechanical'),
        ('_append_router_internal_mechanical_record', '_append_router_internal_mechanical_record'),
        ('_consume_router_internal_mechanical_action', '_consume_router_internal_mechanical_action'),
        ('_router_internal_mechanical_identity', '_router_internal_mechanical_identity'),
    ),
    ('flowpilot_router_lifecycle_requests', True, False): (
        ('_clear_active_control_blocker_for_terminal_lifecycle', '_clear_active_control_blocker_for_terminal_lifecycle'),
        ('_reconcile_terminal_lifecycle_authorities', '_reconcile_terminal_lifecycle_authorities'),
        ('_run_lifecycle_terminal_action', '_run_lifecycle_terminal_action'),
        ('_try_write_control_blocker_for_exception', '_try_write_control_blocker_for_exception'),
        ('_write_protocol_dead_end_lifecycle', '_write_protocol_dead_end_lifecycle'),
        ('_write_run_lifecycle_request', '_write_run_lifecycle_request'),
    ),
    ('flowpilot_router_lifecycle_support', True, False): (
        ('_lifecycle_record_path', '_lifecycle_record_path'),
        ('_reset_resume_cycle_for_wakeup', '_reset_resume_cycle_for_wakeup'),
        ('_write_host_heartbeat_binding', '_write_host_heartbeat_binding'),
    ),
    ('flowpilot_router_model_gate_state', True, False): (
        ('_active_model_miss_review_block_flags', '_active_model_miss_review_block_flags'),
        ('_require_single_active_model_miss_review_block', '_require_single_active_model_miss_review_block'),
        ('_sync_model_gate_alias_flags', '_sync_model_gate_alias_flags'),
    ),
    ('flowpilot_router_payload_contracts', True, False): (
        ('_display_surface_receipt_payload_contract', '_display_surface_receipt_payload_contract'),
        ('_heartbeat_payload_contract', '_heartbeat_payload_contract'),
        ('_payload_contract', '_payload_contract'),
        ('_pm_decision_payload_contract_for_card', '_pm_decision_payload_contract_for_card'),
        ('_pm_model_miss_triage_payload_contract', '_pm_model_miss_triage_payload_contract'),
        ('_pm_parent_segment_decision_payload_contract', '_pm_parent_segment_decision_payload_contract'),
        ('_pm_resume_decision_payload_contract', '_pm_resume_decision_payload_contract'),
        ('_pm_terminal_closure_payload_contract', '_pm_terminal_closure_payload_contract'),
        ('_resume_role_rehydration_payload_contract', '_resume_role_rehydration_payload_contract'),
        ('_role_decision_payload_contract_for_events', '_role_decision_payload_contract_for_events'),
        ('_role_slots_payload_contract', '_role_slots_payload_contract'),
        ('_startup_answers_payload_contract', '_startup_answers_payload_contract'),
        ('_terminal_summary_payload_contract', '_terminal_summary_payload_contract'),
    ),
    ('flowpilot_router_pm_role_followup', True, False): (
        ('_model_miss_followup_expectation', '_model_miss_followup_expectation'),
        ('_pm_role_work_channel_open', '_pm_role_work_channel_open'),
        ('_validate_pm_role_work_request_against_followup', '_validate_pm_role_work_request_against_followup'),
    ),
    ('flowpilot_router_proof_validation', True, False): (
        ('_validate_router_owned_check_proof', '_validate_router_owned_check_proof'),
    ),
    ('flowpilot_router_resume', False, True): (
        ('_append_heartbeat_tick', 'append_heartbeat_tick'),
    ),
    ('flowpilot_router_role_output_bridge', True, False): (
        ('_reconciled_card_delivery_context', '_reconciled_card_delivery_context'),
        ('_repair_prompt_delivery_contexts', '_repair_prompt_delivery_contexts'),
        ('_repair_role_output_envelope_hashes', '_repair_role_output_envelope_hashes'),
        ('_role_output_envelope_record', '_role_output_envelope_record'),
        ('_role_output_envelope_record_for_mutable_artifact', '_role_output_envelope_record_for_mutable_artifact'),
        ('_role_output_ledger_outputs', '_role_output_ledger_outputs'),
        ('_role_output_snapshot_name', '_role_output_snapshot_name'),
        ('_startup_fact_canonical_report_is_valid', '_startup_fact_canonical_report_is_valid'),
        ('_sync_current_and_index_status', '_sync_current_and_index_status'),
        ('_try_reconcile_startup_fact_role_output_ledger', '_try_reconcile_startup_fact_role_output_ledger'),
        ('write_role_output_envelope', 'write_role_output_envelope'),
    ),
    ('flowpilot_router_route_artifacts', True, False): (
        ('_clear_active_gate_outcome_block_for_pass', '_clear_active_gate_outcome_block_for_pass'),
        ('_freeze_root_acceptance_contract', '_freeze_root_acceptance_contract'),
        ('_gate_outcome_path_from_token', '_gate_outcome_path_from_token'),
        ('_route_payload_from_reviewed_draft', '_route_payload_from_reviewed_draft'),
        ('_validate_current_node_packet_envelope', '_validate_current_node_packet_envelope'),
        ('_validate_current_node_packet_event', '_validate_current_node_packet_event'),
        ('_validate_current_node_result_event', '_validate_current_node_result_event'),
        ('_validate_current_node_reviewer_pass', '_validate_current_node_reviewer_pass'),
        ('_validate_selected_child_skills', '_validate_selected_child_skills'),
        ('_write_capabilities_manifest', '_write_capabilities_manifest'),
        ('_write_child_skill_gate_manifest', '_write_child_skill_gate_manifest'),
        ('_write_child_skill_selection', '_write_child_skill_selection'),
        ('_write_compatibility_alias_artifact', '_write_compatibility_alias_artifact'),
        ('_write_dependency_policy', '_write_dependency_policy'),
        ('_write_evidence_quality_package', '_write_evidence_quality_package'),
        ('_write_gate_outcome_block_report', '_write_gate_outcome_block_report'),
        ('_write_material_dispatch_repair', '_write_material_dispatch_repair'),
        ('_write_node_acceptance_plan', '_write_node_acceptance_plan'),
        ('_write_parent_backward_replay', '_write_parent_backward_replay'),
        ('_write_parent_backward_targets', '_write_parent_backward_targets'),
        ('_write_parent_segment_decision', '_write_parent_segment_decision'),
        ('_write_pm_model_decision', '_write_pm_model_decision'),
        ('_write_pm_process_route_model_decision', '_write_pm_process_route_model_decision'),
        ('_write_pm_product_behavior_model_decision', '_write_pm_product_behavior_model_decision'),
        ('_write_pm_research_absorption', '_write_pm_research_absorption'),
        ('_write_pm_resume_decision', '_write_pm_resume_decision'),
        ('_write_pm_review_block_repair', '_write_pm_review_block_repair'),
        ('_write_pm_revised_node_acceptance_plan', '_write_pm_revised_node_acceptance_plan'),
        ('_write_product_behavior_model_report', '_write_product_behavior_model_report'),
        ('_write_product_function_architecture', '_write_product_function_architecture'),
        ('_write_role_block_report', '_write_role_block_report'),
        ('_write_role_gate_report', '_write_role_gate_report'),
        ('_write_root_acceptance_contract', '_write_root_acceptance_contract'),
        ('_write_route_activation', '_write_route_activation'),
        ('_write_route_mutation', '_write_route_mutation'),
        ('_write_route_process_issue_report', '_write_route_process_issue_report'),
        ('_write_route_process_pass_report', '_write_route_process_pass_report'),
        ('_write_route_product_pass_report', '_write_route_product_pass_report'),
    ),
    ('flowpilot_router_route_completion_support', True, False): (
        ('_active_node_acceptance_plan_path', '_active_node_acceptance_plan_path'),
        ('_active_node_completion_ledger_path', '_active_node_completion_ledger_path'),
        ('_active_node_completion_write_missing', '_active_node_completion_write_missing'),
        ('_active_node_packet_index_path', '_active_node_packet_index_path'),
        ('_active_node_root', '_active_node_root'),
        ('_active_node_write_grant_path', '_active_node_write_grant_path'),
        ('_inline_child_nodes', '_inline_child_nodes'),
        ('_node_completion_event_advanced_to_next_node', '_node_completion_event_advanced_to_next_node'),
        ('_node_identifier', '_node_identifier'),
        ('_raw_route_nodes', '_raw_route_nodes'),
        ('_reset_flags', '_reset_flags'),
        ('_resume_decision_path', '_resume_decision_path'),
        ('_resume_mechanical_replay_completed_without_pm', '_resume_mechanical_replay_completed_without_pm'),
        ('_resume_waits_for_pm_decision', '_resume_waits_for_pm_decision'),
        ('_task_completion_projection_path', '_task_completion_projection_path'),
    ),
    ('flowpilot_router_route_frontier', False, True): (
        ('_active_frontier', '_active_frontier'),
        ('_active_node_definition', '_active_node_definition'),
        ('_active_node_definition_from_route', '_active_node_definition_from_route'),
        ('_active_node_has_children', '_active_node_has_children'),
        ('_active_route_flow', '_active_route_flow'),
        ('_active_route_path', '_active_route_path'),
        ('_active_route_payload', '_active_route_payload'),
        ('_active_ui_task_catalog', '_active_ui_task_catalog'),
        ('_build_current_status_summary', '_build_current_status_summary'),
        ('_build_progress_summary', '_build_progress_summary'),
        ('_build_route_state_snapshot', '_build_route_state_snapshot'),
        ('_card_delivery_phase', '_card_delivery_phase'),
        ('_card_required_source_paths', '_card_required_source_paths'),
        ('_controller_delivery_fact_for_pending_return', '_controller_delivery_fact_for_pending_return'),
        ('_current_display_plan', '_current_display_plan'),
        ('_current_route_draft_path', '_current_route_draft_path'),
        ('_current_status_active_batch_summary', '_current_status_active_batch_summary'),
        ('_current_status_summary_path', '_current_status_summary_path'),
        ('_display_plan_path', '_display_plan_path'),
        ('_display_plan_projection', '_display_plan_projection'),
        ('_display_plan_sync_payload', '_display_plan_sync_payload'),
        ('_display_route_nodes', '_display_route_nodes'),
        ('_effective_child_ids', '_effective_child_ids'),
        ('_effective_route_nodes', '_effective_route_nodes'),
        ('_enter_next_child_node', '_enter_next_child_node'),
        ('_event_markers', '_event_markers'),
        ('_filter_events_by_legal_route_actions', '_filter_events_by_legal_route_actions'),
        ('_first_incomplete_child_node_id', '_first_incomplete_child_node_id'),
        ('_flatten_route_nodes', '_flatten_route_nodes'),
        ('_frontier_completed_node_ids', '_frontier_completed_node_ids'),
        ('_is_leaf_readiness_passed', '_is_leaf_readiness_passed'),
        ('_is_route_root_like_node_id', '_is_route_root_like_node_id'),
        ('_is_route_root_node', '_is_route_root_node'),
        ('_iter_route_nodes', '_iter_route_nodes'),
        ('_latest_event_payload', '_latest_event_payload'),
        ('_latest_pre_route_phase', '_latest_pre_route_phase'),
        ('_legal_next_action_context', '_legal_next_action_context'),
        ('_legal_next_action_ids', '_legal_next_action_ids'),
        ('_legal_route_action_allowed', '_legal_route_action_allowed'),
        ('_live_card_delivery_context', '_live_card_delivery_context'),
        ('_load_route_action_policy_registry', '_load_route_action_policy_registry'),
        ('_mark_current_node_packet_records_completed', '_mark_current_node_packet_records_completed'),
        ('_mark_display_plan_dirty', '_mark_display_plan_dirty'),
        ('_mark_frontier_node_completed', '_mark_frontier_node_completed'),
        ('_matching_controller_delivery_actions', '_matching_controller_delivery_actions'),
        ('_next_effective_node_id', '_next_effective_node_id'),
        ('_next_parent_child_entry_action', '_next_parent_child_entry_action'),
        ('_node_child_ids', '_node_child_ids'),
        ('_node_completion_ledger_current', '_node_completion_ledger_current'),
        ('_node_completion_ledger_path_for', '_node_completion_ledger_path_for'),
        ('_node_kind', '_node_kind'),
        ('_optional_source_path', '_optional_source_path'),
        ('_parent_segment_decision_value', '_parent_segment_decision_value'),
        ('_plan_item_status', '_plan_item_status'),
        ('_pm_context_action_extra', '_pm_context_action_extra'),
        ('_pm_prior_path_context_path', '_pm_prior_path_context_path'),
        ('_process_route_model_report_path', '_process_route_model_report_path'),
        ('_product_behavior_model_compatibility_report_path', '_product_behavior_model_compatibility_report_path'),
        ('_product_behavior_model_report_path', '_product_behavior_model_report_path'),
        ('_ready_parent_scope_after_child_completion', '_ready_parent_scope_after_child_completion'),
        ('_reconcile_non_current_running_index_entries', '_reconcile_non_current_running_index_entries'),
        ('_refresh_route_memory', '_refresh_route_memory'),
        ('_require_legal_route_action', '_require_legal_route_action'),
        ('_require_pm_prior_path_context', '_require_pm_prior_path_context'),
        ('_require_process_route_model_report', '_require_process_route_model_report'),
        ('_require_product_behavior_model_report', '_require_product_behavior_model_report'),
        ('_require_route_process_pass', '_require_route_process_pass'),
        ('_require_route_product_pass', '_require_route_product_pass'),
        ('_reset_route_hard_gate_approvals_for_recheck', '_reset_route_hard_gate_approvals_for_recheck'),
        ('_reset_route_review_after_route_draft_repair', '_reset_route_review_after_route_draft_repair'),
        ('_route_action_for_card', '_route_action_for_card'),
        ('_route_action_for_event', '_route_action_for_event'),
        ('_route_action_policy_by_id', '_route_action_policy_by_id'),
        ('_route_action_policy_issues', '_route_action_policy_issues'),
        ('_route_action_policy_registry_path', '_route_action_policy_registry_path'),
        ('_route_action_policy_rows', '_route_action_policy_rows'),
        ('_route_active_path', '_route_active_path'),
        ('_route_descendant_node_ids', '_route_descendant_node_ids'),
        ('_route_display_depth', '_route_display_depth'),
        ('_route_display_refresh_path', '_route_display_refresh_path'),
        ('_route_hidden_leaf_progress', '_route_hidden_leaf_progress'),
        ('_route_history_index_path', '_route_history_index_path'),
        ('_route_item_status', '_route_item_status'),
        ('_route_memory_ready', '_route_memory_ready'),
        ('_route_memory_root', '_route_memory_root'),
        ('_route_mutation_review_lane', '_route_mutation_review_lane'),
        ('_route_mutation_superseded_nodes', '_route_mutation_superseded_nodes'),
        ('_route_node_checklist', '_route_node_checklist'),
        ('_route_node_depth', '_route_node_depth'),
        ('_route_node_history', '_route_node_history'),
        ('_route_node_label', '_route_node_label'),
        ('_route_node_map', '_route_node_map'),
        ('_route_nodes', '_route_nodes'),
        ('_route_process_check_path', '_route_process_check_path'),
        ('_route_product_check_path', '_route_product_check_path'),
        ('_route_progress_completed_ids', '_route_progress_completed_ids'),
        ('_route_progress_parent_map', '_route_progress_parent_map'),
        ('_route_progress_path_nodes', '_route_progress_path_nodes'),
        ('_route_state_snapshot_path', '_route_state_snapshot_path'),
        ('_run_elapsed_seconds', '_run_elapsed_seconds'),
        ('_status_summary_waiting_for', '_status_summary_waiting_for'),
        ('_supersede_active_current_node_packet_for_route_mutation', '_supersede_active_current_node_packet_for_route_mutation'),
        ('_sync_derived_run_views', '_sync_derived_run_views'),
        ('_sync_execution_frontier_phase', '_sync_execution_frontier_phase'),
        ('_update_display_plan_current_node', '_update_display_plan_current_node'),
        ('_validate_route_action_policy_registry', '_validate_route_action_policy_registry'),
        ('_validate_route_mutation_phase_boundary', '_validate_route_mutation_phase_boundary'),
        ('_waiting_for_pm_display_plan', '_waiting_for_pm_display_plan'),
        ('_write_current_status_summary', '_write_current_status_summary'),
        ('_write_display_plan_from_pm_payload', '_write_display_plan_from_pm_payload'),
        ('_write_display_plan_from_route', '_write_display_plan_from_route'),
        ('_write_node_completion_ledger', '_write_node_completion_ledger'),
        ('_write_pre_route_phase_display_plan_if_needed', '_write_pre_route_phase_display_plan_if_needed'),
        ('_write_route_draft', '_write_route_draft'),
        ('_write_route_state_snapshot', '_write_route_state_snapshot'),
    ),
    ('flowpilot_router_runtime_state', False, True): (
        ('_active_packet_ledger_record', '_active_packet_ledger_record'),
        ('_append_role_memory_delta', '_append_role_memory_delta'),
        ('_build_continuation_quarantine_record', '_build_continuation_quarantine_record'),
        ('_continuation_binding_path', '_continuation_binding_path'),
        ('_continuation_quarantine_path', '_continuation_quarantine_path'),
        ('_create_empty_execution_frontier', '_create_empty_execution_frontier'),
        ('_create_empty_packet_ledger', '_create_empty_packet_ledger'),
        ('_create_empty_role_memory', '_create_empty_role_memory'),
        ('_create_run_id', '_create_run_id'),
        ('_create_startup_bootstrap_state', '_create_startup_bootstrap_state'),
        ('_derive_resume_next_recipient_from_packet_ledger', '_derive_resume_next_recipient_from_packet_ledger'),
        ('_load_existing_bootstrap_state', '_load_existing_bootstrap_state'),
        ('_packet_ledger_record_by_id', '_packet_ledger_record_by_id'),
        ('_role_memory_event_role', '_role_memory_event_role'),
        ('_scheduled_continuation_requested', '_scheduled_continuation_requested'),
        ('_set_pre_route_frontier_phase', '_set_pre_route_frontier_phase'),
        ('_startup_answers_from_run', '_startup_answers_from_run'),
        ('_write_continuation_quarantine', '_write_continuation_quarantine'),
        ('active_run_root', 'active_run_root'),
        ('load_bootstrap_state', 'load_bootstrap_state'),
        ('load_run_state', 'load_run_state'),
        ('load_run_state_from_run_root', 'load_run_state_from_run_root'),
        ('new_bootstrap_state', 'new_bootstrap_state'),
        ('new_run_state', 'new_run_state'),
        ('run_state_path', 'run_state_path'),
        ('save_bootstrap_state', 'save_bootstrap_state'),
        ('save_run_state', 'save_run_state'),
    ),
    ('flowpilot_router_self_interrogation', True, False): (
        ('_evidence_path_record', '_evidence_path_record'),
        ('_format_self_interrogation_status_issue', '_format_self_interrogation_status_issue'),
        ('_pm_suggestion_ledger_path', '_pm_suggestion_ledger_path'),
        ('_pm_suggestion_ledger_status', '_pm_suggestion_ledger_status'),
        ('_read_pm_suggestion_ledger', '_read_pm_suggestion_ledger'),
        ('_require_clean_self_interrogation', '_require_clean_self_interrogation'),
        ('_router_owned_check_proof_path', '_router_owned_check_proof_path'),
        ('_self_interrogation_entry_path', '_self_interrogation_entry_path'),
        ('_self_interrogation_final_status', '_self_interrogation_final_status'),
        ('_self_interrogation_index_path', '_self_interrogation_index_path'),
        ('_self_interrogation_issue', '_self_interrogation_issue'),
        ('_self_interrogation_record_issues', '_self_interrogation_record_issues'),
        ('_self_interrogation_status', '_self_interrogation_status'),
        ('_write_router_owned_check_proof', '_write_router_owned_check_proof'),
        ('resolve_project_path', 'resolve_project_path'),
    ),
    ('flowpilot_router_startup_bootloader', True, True): (
        ('_bootstrap_startup_cancelled', '_bootstrap_startup_cancelled'),
        ('_complete_startup_daemon_bootloader_row', '_complete_startup_daemon_bootloader_row'),
        ('_daemon_scheduled_bootloader_action', '_daemon_scheduled_bootloader_action'),
        ('_ensure_pending', '_ensure_pending'),
        ('_finish_bootloader_action', '_finish_bootloader_action'),
        ('_fold_stable_startup_role_flags_from_bootstrap', '_fold_stable_startup_role_flags_from_bootstrap'),
        ('_next_boot_action', '_next_boot_action'),
        ('_set_boot_flag', '_set_boot_flag'),
        ('_startup_bootloader_action_depends_on_role_slots', '_startup_bootloader_action_depends_on_role_slots'),
        ('_startup_bootloader_entry_is_nonblocking', '_startup_bootloader_entry_is_nonblocking'),
        ('_startup_bootloader_has_remaining_work', '_startup_bootloader_has_remaining_work'),
        ('_startup_bootloader_open_entries_by_action_type', '_startup_bootloader_open_entries_by_action_type'),
        ('_startup_daemon_controls_bootstrap', '_startup_daemon_controls_bootstrap'),
        ('_startup_daemon_schedule_bootloader_action', '_startup_daemon_schedule_bootloader_action'),
        ('_startup_open_entry_progress_class', '_startup_open_entry_progress_class'),
        ('_startup_run_state_if_ready', '_startup_run_state_if_ready'),
        ('_sync_startup_bootstrap_flags_to_run_state', '_sync_startup_bootstrap_flags_to_run_state'),
        ('apply_bootloader_action', 'apply_bootloader_action'),
        ('compute_bootloader_action', 'compute_bootloader_action'),
    ),
    ('flowpilot_router_startup_closure', True, True): (
        ('_closure_reconciliation_blocker_message', '_closure_reconciliation_blocker_message'),
        ('_closure_reconciliation_entries', '_closure_reconciliation_entries'),
        ('_continuation_quarantine_reconciliation_status', '_continuation_quarantine_reconciliation_status'),
        ('_current_closure_state_clean', '_current_closure_state_clean'),
        ('_defect_ledger_reconciliation_status', '_defect_ledger_reconciliation_status'),
        ('_host_heartbeat_binding_ready', '_host_heartbeat_binding_ready'),
        ('_invalidate_route_completion_if_dirty_before_closure', '_invalidate_route_completion_if_dirty_before_closure'),
        ('_role_memory_reconciliation_status', '_role_memory_reconciliation_status'),
        ('_terminal_closure_reconciliation_status', '_terminal_closure_reconciliation_status'),
    ),
    ('flowpilot_router_startup_display', True, True): (
        ('_append_user_dialog_display_ledger', '_append_user_dialog_display_ledger'),
        ('_apply_sync_display_plan_state', '_apply_sync_display_plan_state'),
        ('_display_confirmation_for_action', '_display_confirmation_for_action'),
        ('_display_plan_chat_markdown', '_display_plan_chat_markdown'),
        ('_display_plan_display_kind', '_display_plan_display_kind'),
        ('_display_plan_sync_action_summary', '_display_plan_sync_action_summary'),
        ('_display_plan_user_dialog_fields', '_display_plan_user_dialog_fields'),
        ('_display_route_sign_user_dialog_fields', '_display_route_sign_user_dialog_fields'),
        ('_display_surface_receipt_from_payload', '_display_surface_receipt_from_payload'),
        ('_display_text_hash', '_display_text_hash'),
        ('_next_display_plan_action', '_next_display_plan_action'),
        ('_next_startup_display_action', '_next_startup_display_action'),
        ('_route_map_route_sign_payload', '_route_map_route_sign_payload'),
        ('_route_sign_has_canonical_route', '_route_sign_has_canonical_route'),
        ('_route_sign_payload', '_route_sign_payload'),
        ('_startup_banner_display', '_startup_banner_display'),
        ('_startup_route_sign_payload', '_startup_route_sign_payload'),
        ('_startup_waiting_internal_display_fields', '_startup_waiting_internal_display_fields'),
        ('_user_dialog_display_gate', '_user_dialog_display_gate'),
        ('_validate_display_confirmation', '_validate_display_confirmation'),
        ('_write_display_surface_status', '_write_display_surface_status'),
    ),
    ('flowpilot_router_startup_fact_boundary', True, True): (
        ('_continuation_has_host_bound_automation_receipt', '_continuation_has_host_bound_automation_receipt'),
        ('_controller_boundary_confirmation_body', '_controller_boundary_confirmation_body'),
        ('_controller_boundary_confirmation_context', '_controller_boundary_confirmation_context'),
        ('_controller_boundary_confirmation_path', '_controller_boundary_confirmation_path'),
        ('_controller_boundary_constraints', '_controller_boundary_constraints'),
        ('_controller_boundary_runtime_evidence_context', '_controller_boundary_runtime_evidence_context'),
        ('_controller_boundary_sources', '_controller_boundary_sources'),
        ('_legacy_pm_reset_boundary_confirmed', '_legacy_pm_reset_boundary_confirmed'),
        ('_next_controller_boundary_confirmation_action', '_next_controller_boundary_confirmation_action'),
        ('_next_startup_mechanical_audit_action', '_next_startup_mechanical_audit_action'),
        ('_record_controller_boundary_confirmation_from_core_load', '_record_controller_boundary_confirmation_from_core_load'),
        ('_role_slots_have_host_spawn_receipts', '_role_slots_have_host_spawn_receipts'),
        ('_run_manifest_path', '_run_manifest_path'),
        ('_startup_external_fact_requirements', '_startup_external_fact_requirements'),
        ('_startup_fact_checks', '_startup_fact_checks'),
        ('_startup_fact_review_ownership', '_startup_fact_review_ownership'),
        ('_startup_intake_record_context', '_startup_intake_record_context'),
        ('_startup_mechanical_audit_action_extra', '_startup_mechanical_audit_action_extra'),
        ('_startup_mechanical_audit_context', '_startup_mechanical_audit_context'),
        ('_validate_startup_external_fact_review', '_validate_startup_external_fact_review'),
        ('_write_controller_boundary_confirmation', '_write_controller_boundary_confirmation'),
        ('_write_startup_activation', '_write_startup_activation'),
        ('_write_startup_fact_report', '_write_startup_fact_report'),
        ('_write_startup_mechanical_audit', '_write_startup_mechanical_audit'),
        ('_write_startup_protocol_dead_end', '_write_startup_protocol_dead_end'),
        ('_write_startup_repair_request', '_write_startup_repair_request'),
    ),
    ('flowpilot_router_startup_intake', True, True): (
        ('_apply_startup_intake_result_to_bootstrap', '_apply_startup_intake_result_to_bootstrap'),
        ('_build_user_intake_body_from_ref', '_build_user_intake_body_from_ref'),
        ('_confirmed_startup_intake', '_confirmed_startup_intake'),
        ('_copy_startup_intake_file', '_copy_startup_intake_file'),
        ('_deterministic_bootstrap_seed_evidence_path', '_deterministic_bootstrap_seed_evidence_path'),
        ('_forbidden_startup_intake_body_fields', '_forbidden_startup_intake_body_fields'),
        ('_initialize_mailbox_foundation', '_initialize_mailbox_foundation'),
        ('_materialize_startup_intake_record', '_materialize_startup_intake_record'),
        ('_normalize_startup_question_stop_boundary', '_normalize_startup_question_stop_boundary'),
        ('_record_startup_user_request_ref', '_record_startup_user_request_ref'),
        ('_require_interactive_startup_intake_artifact', '_require_interactive_startup_intake_artifact'),
        ('_resolve_existing_project_file', '_resolve_existing_project_file'),
        ('_run_deterministic_startup_bootstrap_seed', '_run_deterministic_startup_bootstrap_seed'),
        ('_same_project_file', '_same_project_file'),
        ('_startup_intake_output_dir_ref', '_startup_intake_output_dir_ref'),
        ('_startup_intake_result_path_from_payload', '_startup_intake_result_path_from_payload'),
        ('_startup_intake_result_payload_contract', '_startup_intake_result_payload_contract'),
        ('_startup_intake_ui_action_extra', '_startup_intake_ui_action_extra'),
        ('_startup_intake_ui_launcher_ref', '_startup_intake_ui_launcher_ref'),
        ('_user_request_ref_from_startup_intake', '_user_request_ref_from_startup_intake'),
        ('_validate_startup_answer_interpretation', '_validate_startup_answer_interpretation'),
        ('_validate_startup_answers', '_validate_startup_answers'),
        ('_validate_startup_intake_result_payload', '_validate_startup_intake_result_payload'),
        ('_validate_user_request', '_validate_user_request'),
        ('_write_startup_answers_record', '_write_startup_answers_record'),
        ('_write_startup_user_intake_scaffold', '_write_startup_user_intake_scaffold'),
    ),
    ('flowpilot_router_startup_role_recovery', True, True): (
        ('_controller_action_entry_view', '_controller_action_entry_view'),
        ('_controller_action_wait_roles', '_controller_action_wait_roles'),
        ('_current_crew_generation', '_current_crew_generation'),
        ('_latest_resume_tick_id', '_latest_resume_tick_id'),
        ('_latest_role_recovery_transaction', '_latest_role_recovery_transaction'),
        ('_load_role_recovery_state', '_load_role_recovery_state'),
        ('_mark_controller_action_done_by_role_recovery', '_mark_controller_action_done_by_role_recovery'),
        ('_next_resume_action', '_next_resume_action'),
        ('_next_role_recovery_action', '_next_role_recovery_action'),
        ('_next_startup_heartbeat_binding_action', '_next_startup_heartbeat_binding_action'),
        ('_normalize_resume_role_agent_records', '_normalize_resume_role_agent_records'),
        ('_normalize_role_agent_records', '_normalize_role_agent_records'),
        ('_normalize_role_recovery_agent_records', '_normalize_role_recovery_agent_records'),
        ('_open_role_recovery_transaction', '_open_role_recovery_transaction'),
        ('_path_hash', '_path_hash'),
        ('_payload_indicates_role_no_output', '_payload_indicates_role_no_output'),
        ('_plan_role_recovery_obligation_replay', '_plan_role_recovery_obligation_replay'),
        ('_reclaim_role_recovery_postcondition_from_report', '_reclaim_role_recovery_postcondition_from_report'),
        ('_record_role_no_output_reissue', '_record_role_no_output_reissue'),
        ('_resume_liveness_probe_batch_id', '_resume_liveness_probe_batch_id'),
        ('_resume_role_context', '_resume_role_context'),
        ('_resume_role_contexts', '_resume_role_contexts'),
        ('_resume_role_rehydration_action_extra', '_resume_role_rehydration_action_extra'),
        ('_role_core_prompt_delivery_payload', '_role_core_prompt_delivery_payload'),
        ('_role_core_prompt_path', '_role_core_prompt_path'),
        ('_role_memory_path', '_role_memory_path'),
        ('_role_no_output_liveness_result', '_role_no_output_liveness_result'),
        ('_role_no_output_reissue_attempt', '_role_no_output_reissue_attempt'),
        ('_role_no_output_replacement_action', '_role_no_output_replacement_action'),
        ('_role_no_output_target_roles', '_role_no_output_target_roles'),
        ('_role_no_output_wait_candidate', '_role_no_output_wait_candidate'),
        ('_role_recovery_action_sort_key', '_role_recovery_action_sort_key'),
        ('_role_recovery_dir', '_role_recovery_dir'),
        ('_role_recovery_existing_event_for_wait', '_role_recovery_existing_event_for_wait'),
        ('_role_recovery_latest_transaction_path', '_role_recovery_latest_transaction_path'),
        ('_role_recovery_obligation_replay_path', '_role_recovery_obligation_replay_path'),
        ('_role_recovery_payload_contract', '_role_recovery_payload_contract'),
        ('_role_recovery_pending_return_for_action', '_role_recovery_pending_return_for_action'),
        ('_role_recovery_ready_context', '_role_recovery_ready_context'),
        ('_role_recovery_replacement_action', '_role_recovery_replacement_action'),
        ('_role_recovery_report_path', '_role_recovery_report_path'),
        ('_role_recovery_state_path', '_role_recovery_state_path'),
        ('_role_recovery_target_roles', '_role_recovery_target_roles'),
        ('_role_recovery_wait_candidates', '_role_recovery_wait_candidates'),
        ('_role_spawn_action_extra', '_role_spawn_action_extra'),
        ('_settle_role_recovery_candidate_if_evidence_exists', '_settle_role_recovery_candidate_if_evidence_exists'),
        ('_stable_resume_launcher_contract', '_stable_resume_launcher_contract'),
        ('_supersede_role_no_output_original_wait', '_supersede_role_no_output_original_wait'),
        ('_supersede_role_recovery_original_wait', '_supersede_role_recovery_original_wait'),
        ('_write_initial_continuation_binding', '_write_initial_continuation_binding'),
        ('_write_resume_role_rehydration_report', '_write_resume_role_rehydration_report'),
        ('_write_role_recovery_report', '_write_role_recovery_report'),
    ),
    ('flowpilot_router_startup_support', True, False): (
        ('_active_agent_id_for_role', '_active_agent_id_for_role'),
        ('_controller_wait_allowed_external_events', '_controller_wait_allowed_external_events'),
        ('_ensure_startup_run_state', '_ensure_startup_run_state'),
        ('_external_event_payload_digest', '_external_event_payload_digest'),
        ('_json_safe', '_json_safe'),
        ('load_manifest_from_run', 'load_manifest_from_run'),
        ('manifest_card', 'manifest_card'),
    ),
    ('flowpilot_router_system_cards', True, False): (
        ('_apply_card_bundle_return_event_check', '_apply_card_bundle_return_event_check'),
        ('_apply_card_return_event_check', '_apply_card_return_event_check'),
        ('_auto_commit_system_card_delivery_action', '_auto_commit_system_card_delivery_action'),
        ('_clear_stale_role_wait_for_quarantined_report', '_clear_stale_role_wait_for_quarantined_report'),
        ('_commit_system_card_bundle_delivery_artifact', '_commit_system_card_bundle_delivery_artifact'),
        ('_commit_system_card_delivery_artifact', '_commit_system_card_delivery_artifact'),
        ('_committed_card_bundle_artifact_extra', '_committed_card_bundle_artifact_extra'),
        ('_direct_router_ack_token_for_bundle', '_direct_router_ack_token_for_bundle'),
        ('_direct_router_ack_token_for_card', '_direct_router_ack_token_for_card'),
        ('_mark_card_return_pending_explicit_check', '_mark_card_return_pending_explicit_check'),
        ('_next_quarantined_role_report_path', '_next_quarantined_role_report_path'),
        ('_next_system_card_action', '_next_system_card_action'),
        ('_next_system_card_bundle_action', '_next_system_card_bundle_action'),
        ('_pending_bundle_return_record_for_action', '_pending_bundle_return_record_for_action'),
        ('_pending_card_return_matches_event_dependency', '_pending_card_return_matches_event_dependency'),
        ('_pending_return_card_delivery_flags', '_pending_return_card_delivery_flags'),
        ('_pending_return_record_for_action', '_pending_return_record_for_action'),
        ('_preconsume_pending_card_return_ack_before_external_event', '_preconsume_pending_card_return_ack_before_external_event'),
        ('_quarantine_missing_ack_report_before_external_event', '_quarantine_missing_ack_report_before_external_event'),
        ('_reconcile_card_bundle_wait_rows', '_reconcile_card_bundle_wait_rows'),
        ('_reconcile_card_wait_rows', '_reconcile_card_wait_rows'),
        ('_reconcile_durable_wait_evidence', '_reconcile_durable_wait_evidence'),
        ('_record_card_return_event_from_external_entrypoint', '_record_card_return_event_from_external_entrypoint'),
        ('_role_list', '_role_list'),
        ('_router_release_startup_user_intake_to_pm', '_router_release_startup_user_intake_to_pm'),
        ('_run_router_return_settlement_finalizers', '_run_router_return_settlement_finalizers'),
        ('_startup_pm_card_bundle_ack_record', '_startup_pm_card_bundle_ack_record'),
        ('_system_card_bundle_candidate_actions', '_system_card_bundle_candidate_actions'),
        ('_system_card_delivery_flag', '_system_card_delivery_flag'),
        ('_system_card_to_role', '_system_card_to_role'),
        ('_try_auto_consume_pending_card_return_ack', '_try_auto_consume_pending_card_return_ack'),
    ),
    ('flowpilot_router_terminal_ledger', False, True): (
        ('_build_source_of_truth_final_entries', '_build_source_of_truth_final_entries'),
        ('_final_ledger_traceability_issues', '_final_ledger_traceability_issues'),
        ('_node_acceptance_traceability_issues', '_node_acceptance_traceability_issues'),
        ('_recover_terminal_status_from_run_authorities', '_recover_terminal_status_from_run_authorities'),
        ('_repair_legacy_material_packet_contracts', '_repair_legacy_material_packet_contracts'),
        ('_requirement_trace_closure_from_root_replay', '_requirement_trace_closure_from_root_replay'),
        ('_root_requirement_ids', '_root_requirement_ids'),
        ('_route_mutation_completion_issues', '_route_mutation_completion_issues'),
        ('_route_nodes_with_requirement_trace', '_route_nodes_with_requirement_trace'),
        ('_string_list', '_string_list'),
        ('_terminal_closure_suite_is_closed', '_terminal_closure_suite_is_closed'),
        ('_terminal_summary_action', '_terminal_summary_action'),
        ('_terminal_summary_index_entry', '_terminal_summary_index_entry'),
        ('_terminal_summary_written', '_terminal_summary_written'),
        ('_validate_terminal_summary_payload', '_validate_terminal_summary_payload'),
        ('_validated_root_replay', '_validated_root_replay'),
        ('_write_final_route_wide_ledger', '_write_final_route_wide_ledger'),
        ('_write_task_completion_projection', '_write_task_completion_projection'),
        ('_write_terminal_backward_replay', '_write_terminal_backward_replay'),
        ('_write_terminal_closure_suite', '_write_terminal_closure_suite'),
        ('_write_terminal_summary', '_write_terminal_summary'),
        ('reconcile_current_run', 'reconcile_current_run'),
    ),
    ('flowpilot_router_work_packets', False, True): (
        ('_active_child_skill_bindings_from_plan', '_active_child_skill_bindings_from_plan'),
        ('_active_child_skill_source_paths', '_active_child_skill_source_paths'),
        ('_active_current_node_packet_records', '_active_current_node_packet_records'),
        ('_active_holder_frontier_version', '_active_holder_frontier_version'),
        ('_active_parallel_packet_batch', '_active_parallel_packet_batch'),
        ('_active_pm_role_work_batch_records', '_active_pm_role_work_batch_records'),
        ('_active_pm_role_work_request', '_active_pm_role_work_request'),
        ('_agent_role_map_from_crew_ledger', '_agent_role_map_from_crew_ledger'),
        ('_apply_pm_role_work_gate_mappings', '_apply_pm_role_work_gate_mappings'),
        ('_controller_status_packet_path_from_packet_envelope', '_controller_status_packet_path_from_packet_envelope'),
        ('_current_node_active_holder_lease_plan', '_current_node_active_holder_lease_plan'),
        ('_current_node_batch_packet_record', '_current_node_batch_packet_record'),
        ('_current_node_missing_result_roles', '_current_node_missing_result_roles'),
        ('_current_node_packet_context', '_current_node_packet_context'),
        ('_current_node_packet_records', '_current_node_packet_records'),
        ('_current_node_result_context', '_current_node_result_context'),
        ('_current_node_results_complete', '_current_node_results_complete'),
        ('_empty_officer_request_lifecycle_index', '_empty_officer_request_lifecycle_index'),
        ('_empty_pm_role_work_request_index', '_empty_pm_role_work_request_index'),
        ('_ensure_barrier_bundles_ready', '_ensure_barrier_bundles_ready'),
        ('_issue_current_node_active_holder_leases', '_issue_current_node_active_holder_leases'),
        ('_issue_packet_active_holder_leases', '_issue_packet_active_holder_leases'),
        ('_load_officer_request_lifecycle_index', '_load_officer_request_lifecycle_index'),
        ('_load_packet_index', '_load_packet_index'),
        ('_load_parallel_packet_batch', '_load_parallel_packet_batch'),
        ('_load_pm_role_work_request_index', '_load_pm_role_work_request_index'),
        ('_mark_parallel_batch_packets_relayed', '_mark_parallel_batch_packets_relayed'),
        ('_mark_parallel_batch_results_joined', '_mark_parallel_batch_results_joined'),
        ('_mark_parallel_batch_reviewed', '_mark_parallel_batch_reviewed'),
        ('_material_packet_body_text_from_spec', '_material_packet_body_text_from_spec'),
        ('_material_scan_index_path', '_material_scan_index_path'),
        ('_merge_agent_role_maps', '_merge_agent_role_maps'),
        ('_metadata_binding_ids', '_metadata_binding_ids'),
        ('_metadata_string_list', '_metadata_string_list'),
        ('_next_current_node_packet_action', '_next_current_node_packet_action'),
        ('_next_material_packet_action', '_next_material_packet_action'),
        ('_next_pm_role_work_request_action', '_next_pm_role_work_request_action'),
        ('_next_research_packet_action', '_next_research_packet_action'),
        ('_normalize_pm_role_work_result_recipient', '_normalize_pm_role_work_result_recipient'),
        ('_officer_lifecycle_entry', '_officer_lifecycle_entry'),
        ('_officer_request_lifecycle_index_path', '_officer_request_lifecycle_index_path'),
        ('_packet_active_holder_lease_plan', '_packet_active_holder_lease_plan'),
        ('_packet_envelope_path', '_packet_envelope_path'),
        ('_packet_envelope_path_from_record', '_packet_envelope_path_from_record'),
        ('_packet_paths', '_packet_paths'),
        ('_packet_record_from_envelope', '_packet_record_from_envelope'),
        ('_parallel_batch_record_result_exists', '_parallel_batch_record_result_exists'),
        ('_parallel_packet_batch_member_summary', '_parallel_packet_batch_member_summary'),
        ('_parallel_packet_batch_path', '_parallel_packet_batch_path'),
        ('_parallel_packet_batch_ref_path', '_parallel_packet_batch_ref_path'),
        ('_parallel_packet_batch_root', '_parallel_packet_batch_root'),
        ('_pm_role_work_gate_mapping_alias_specs', '_pm_role_work_gate_mapping_alias_specs'),
        ('_pm_role_work_gate_mapping_artifact_path', '_pm_role_work_gate_mapping_artifact_path'),
        ('_pm_role_work_gate_mapping_candidates', '_pm_role_work_gate_mapping_candidates'),
        ('_pm_role_work_gate_mappings_for_decision', '_pm_role_work_gate_mappings_for_decision'),
        ('_pm_role_work_output_contract', '_pm_role_work_output_contract'),
        ('_pm_role_work_packet_type_from_contract', '_pm_role_work_packet_type_from_contract'),
        ('_pm_role_work_record_is_nonblocking', '_pm_role_work_record_is_nonblocking'),
        ('_pm_role_work_records_are_nonblocking', '_pm_role_work_records_are_nonblocking'),
        ('_pm_role_work_records_dependency_class', '_pm_role_work_records_dependency_class'),
        ('_pm_role_work_request_body_text', '_pm_role_work_request_body_text'),
        ('_pm_role_work_request_index_path', '_pm_role_work_request_index_path'),
        ('_pm_role_work_request_record', '_pm_role_work_request_record'),
        ('_pm_role_work_result_decision_payload_contract', '_pm_role_work_result_decision_payload_contract'),
        ('_pm_role_work_target_gate_contract', '_pm_role_work_target_gate_contract'),
        ('_record_officer_lifecycle_pm_decision', '_record_officer_lifecycle_pm_decision'),
        ('_record_officer_lifecycle_request', '_record_officer_lifecycle_request'),
        ('_record_officer_lifecycle_result_returned', '_record_officer_lifecycle_result_returned'),
        ('_record_officer_lifecycle_status', '_record_officer_lifecycle_status'),
        ('_refresh_all_parallel_packet_batches_from_durable_results', '_refresh_all_parallel_packet_batches_from_durable_results'),
        ('_refresh_parallel_packet_batch_from_durable_results', '_refresh_parallel_packet_batch_from_durable_results'),
        ('_relay_packet_records', '_relay_packet_records'),
        ('_relay_result_records', '_relay_result_records'),
        ('_research_packet_index_path', '_research_packet_index_path'),
        ('_result_envelope_path', '_result_envelope_path'),
        ('_result_envelope_path_from_packet_record', '_result_envelope_path_from_packet_record'),
        ('_role_output_status_packet_path_for_wait', '_role_output_status_packet_path_for_wait'),
        ('_safe_packet_id_component', '_safe_packet_id_component'),
        ('_unresolved_advisory_pm_role_work_records', '_unresolved_advisory_pm_role_work_records'),
        ('_unresolved_pm_role_work_requests', '_unresolved_pm_role_work_requests'),
        ('_upsert_officer_lifecycle_entry', '_upsert_officer_lifecycle_entry'),
        ('_validate_packet_bodies_opened_by_targets', '_validate_packet_bodies_opened_by_targets'),
        ('_validate_packet_group_for_reviewer', '_validate_packet_group_for_reviewer'),
        ('_validate_pm_role_work_process_contract_binding', '_validate_pm_role_work_process_contract_binding'),
        ('_validate_result_bodies_opened_by_pm', '_validate_result_bodies_opened_by_pm'),
        ('_validate_results_exist_for_packets', '_validate_results_exist_for_packets'),
        ('_validate_role_work_result_process_binding', '_validate_role_work_result_process_binding'),
        ('_write_material_dispatch_block_report', '_write_material_dispatch_block_report'),
        ('_write_material_dispatch_recheck_protocol_blocker', '_write_material_dispatch_recheck_protocol_blocker'),
        ('_write_material_scan_packets', '_write_material_scan_packets'),
        ('_write_material_sufficiency_report', '_write_material_sufficiency_report'),
        ('_write_material_understanding', '_write_material_understanding'),
        ('_write_officer_request_lifecycle_index', '_write_officer_request_lifecycle_index'),
        ('_write_parallel_packet_batch', '_write_parallel_packet_batch'),
        ('_write_parallel_packet_batch_state', '_write_parallel_packet_batch_state'),
        ('_write_pm_package_result_disposition', '_write_pm_package_result_disposition'),
        ('_write_pm_role_work_request', '_write_pm_role_work_request'),
        ('_write_pm_role_work_request_index', '_write_pm_role_work_request_index'),
        ('_write_pm_role_work_result_decision', '_write_pm_role_work_result_decision'),
        ('_write_research_capability_decision', '_write_research_capability_decision'),
        ('_write_research_package', '_write_research_package'),
        ('_write_role_work_result_returned', '_write_role_work_result_returned'),
        ('_write_worker_research_report', '_write_worker_research_report'),
    ),
}

PUBLIC_EXPORT_NAMES = frozenset(
    public_name
    for exports in OWNER_EXPORTS.values()
    for public_name, _target_name in exports
)

def _owner_target(module_name: str, target_name: str, router_module: ModuleType, bind_router: bool) -> Callable[..., Any]:
    module = importlib.import_module(module_name)
    if bind_router and hasattr(module, "_bind_router"):
        module._bind_router(router_module)
    return getattr(module, target_name)

def _make_proxy(
    public_name: str,
    module_name: str,
    target_name: str,
    *,
    router_module: ModuleType,
    bind_router: bool,
    inject_router: bool,
) -> Callable[..., Any]:
    def _proxy(*args: Any, **kwargs: Any) -> Any:
        target = _owner_target(module_name, target_name, router_module, bind_router)
        if inject_router:
            return target(router_module, *args, **kwargs)
        return target(*args, **kwargs)

    _proxy.__name__ = public_name
    _proxy.__qualname__ = public_name
    _proxy.__module__ = router_module.__name__
    _proxy.__doc__ = f"Transitional owner export for {module_name}.{target_name}."
    return _proxy

def resolve_facade_export(name: str, router_module: ModuleType) -> Callable[..., Any]:
    for (module_name, bind_router, inject_router), exports in OWNER_EXPORTS.items():
        for public_name, target_name in exports:
            if public_name == name:
                return _make_proxy(public_name, module_name, target_name, router_module=router_module, bind_router=bind_router, inject_router=inject_router)
    raise AttributeError(name)

def install_facade_exports(router_module: ModuleType, namespace: dict[str, Any]) -> None:
    for (module_name, bind_router, inject_router), exports in OWNER_EXPORTS.items():
        for public_name, target_name in exports:
            namespace[public_name] = _make_proxy(public_name, module_name, target_name, router_module=router_module, bind_router=bind_router, inject_router=inject_router)
