"""Router facade export manifest shard.

The shard keeps registry rows grouped by domain while the aggregator preserves
the public OWNER_EXPORTS contract.
"""

from __future__ import annotations

from typing import TypeAlias

ExportSpec: TypeAlias = tuple[str, str]
RegistryKey: TypeAlias = tuple[str, bool, bool]

OWNER_EXPORTS_STARTUP: dict[RegistryKey, tuple[ExportSpec, ...]] = {('flowpilot_router_startup_bootloader', True, True): (('_bootstrap_startup_cancelled', '_bootstrap_startup_cancelled'),
                                                       ('_complete_startup_daemon_bootloader_row',
                                                        '_complete_startup_daemon_bootloader_row'),
                                                       ('_daemon_scheduled_bootloader_action',
                                                        '_daemon_scheduled_bootloader_action'),
                                                       ('_ensure_pending', '_ensure_pending'),
                                                       ('_finish_bootloader_action', '_finish_bootloader_action'),
                                                       ('_fold_stable_startup_role_flags_from_bootstrap',
                                                        '_fold_stable_startup_role_flags_from_bootstrap'),
                                                       ('_next_boot_action', '_next_boot_action'),
                                                       ('_set_boot_flag', '_set_boot_flag'),
                                                       ('_startup_bootloader_action_depends_on_role_slots',
                                                        '_startup_bootloader_action_depends_on_role_slots'),
                                                       ('_startup_bootloader_entry_is_nonblocking',
                                                        '_startup_bootloader_entry_is_nonblocking'),
                                                       ('_startup_bootloader_has_remaining_work',
                                                        '_startup_bootloader_has_remaining_work'),
                                                       ('_startup_bootloader_open_entries_by_action_type',
                                                        '_startup_bootloader_open_entries_by_action_type'),
                                                       ('_startup_daemon_controls_bootstrap',
                                                        '_startup_daemon_controls_bootstrap'),
                                                       ('_startup_daemon_schedule_bootloader_action',
                                                        '_startup_daemon_schedule_bootloader_action'),
                                                       ('_startup_open_entry_progress_class',
                                                        '_startup_open_entry_progress_class'),
                                                       ('_startup_run_state_if_ready', '_startup_run_state_if_ready'),
                                                       ('_sync_startup_bootstrap_flags_to_run_state',
                                                        '_sync_startup_bootstrap_flags_to_run_state'),
                                                       ('apply_bootloader_action', 'apply_bootloader_action'),
                                                       ('compute_bootloader_action', 'compute_bootloader_action')),
 ('flowpilot_router_startup_closure', True, True): (('_closure_reconciliation_blocker_message',
                                                     '_closure_reconciliation_blocker_message'),
                                                    ('_closure_reconciliation_entries',
                                                     '_closure_reconciliation_entries'),
                                                    ('_continuation_quarantine_reconciliation_status',
                                                     '_continuation_quarantine_reconciliation_status'),
                                                    ('_current_closure_state_clean', '_current_closure_state_clean'),
                                                    ('_defect_ledger_reconciliation_status',
                                                     '_defect_ledger_reconciliation_status'),
                                                    ('_host_heartbeat_binding_ready', '_host_heartbeat_binding_ready'),
                                                    ('_invalidate_route_completion_if_dirty_before_closure',
                                                     '_invalidate_route_completion_if_dirty_before_closure'),
                                                    ('_role_memory_reconciliation_status',
                                                     '_role_memory_reconciliation_status'),
                                                    ('_terminal_closure_reconciliation_status',
                                                     '_terminal_closure_reconciliation_status')),
 ('flowpilot_router_startup_display', True, True): (('_append_user_dialog_display_ledger',
                                                     '_append_user_dialog_display_ledger'),
                                                    ('_apply_sync_display_plan_state',
                                                     '_apply_sync_display_plan_state'),
                                                    ('_display_confirmation_for_action',
                                                     '_display_confirmation_for_action'),
                                                    ('_display_plan_chat_markdown', '_display_plan_chat_markdown'),
                                                    ('_display_plan_display_kind', '_display_plan_display_kind'),
                                                    ('_display_plan_sync_action_summary',
                                                     '_display_plan_sync_action_summary'),
                                                    ('_display_plan_user_dialog_fields',
                                                     '_display_plan_user_dialog_fields'),
                                                    ('_display_route_sign_user_dialog_fields',
                                                     '_display_route_sign_user_dialog_fields'),
                                                    ('_display_surface_receipt_from_payload',
                                                     '_display_surface_receipt_from_payload'),
                                                    ('_display_text_hash', '_display_text_hash'),
                                                    ('_next_display_plan_action', '_next_display_plan_action'),
                                                    ('_next_startup_display_action', '_next_startup_display_action'),
                                                    ('_route_map_route_sign_payload', '_route_map_route_sign_payload'),
                                                    ('_route_sign_has_canonical_route',
                                                     '_route_sign_has_canonical_route'),
                                                    ('_route_sign_payload', '_route_sign_payload'),
                                                    ('_startup_banner_display', '_startup_banner_display'),
                                                    ('_startup_route_sign_payload', '_startup_route_sign_payload'),
                                                    ('_startup_waiting_internal_display_fields',
                                                     '_startup_waiting_internal_display_fields'),
                                                    ('_user_dialog_display_gate', '_user_dialog_display_gate'),
                                                    ('_validate_display_confirmation',
                                                     '_validate_display_confirmation'),
                                                    ('_write_display_surface_status', '_write_display_surface_status')),
 ('flowpilot_router_startup_fact_boundary', True, True): (('_continuation_has_host_bound_automation_receipt',
                                                           '_continuation_has_host_bound_automation_receipt'),
                                                          ('_controller_boundary_confirmation_body',
                                                           '_controller_boundary_confirmation_body'),
                                                          ('_controller_boundary_confirmation_context',
                                                           '_controller_boundary_confirmation_context'),
                                                          ('_controller_boundary_confirmation_path',
                                                           '_controller_boundary_confirmation_path'),
                                                          ('_controller_boundary_constraints',
                                                           '_controller_boundary_constraints'),
                                                          ('_controller_boundary_runtime_evidence_context',
                                                           '_controller_boundary_runtime_evidence_context'),
                                                          ('_controller_boundary_sources',
                                                           '_controller_boundary_sources'),
                                                          ('_legacy_pm_reset_boundary_confirmed',
                                                           '_legacy_pm_reset_boundary_confirmed'),
                                                          ('_next_controller_boundary_confirmation_action',
                                                           '_next_controller_boundary_confirmation_action'),
                                                          ('_next_startup_mechanical_audit_action',
                                                           '_next_startup_mechanical_audit_action'),
                                                          ('_record_controller_boundary_confirmation_from_core_load',
                                                           '_record_controller_boundary_confirmation_from_core_load'),
                                                          ('_role_slots_have_host_spawn_receipts',
                                                           '_role_slots_have_host_spawn_receipts'),
                                                          ('_run_manifest_path', '_run_manifest_path'),
                                                          ('_startup_external_fact_requirements',
                                                           '_startup_external_fact_requirements'),
                                                          ('_startup_fact_checks', '_startup_fact_checks'),
                                                          ('_startup_fact_review_ownership',
                                                           '_startup_fact_review_ownership'),
                                                          ('_startup_intake_record_context',
                                                           '_startup_intake_record_context'),
                                                          ('_startup_mechanical_audit_action_extra',
                                                           '_startup_mechanical_audit_action_extra'),
                                                          ('_startup_mechanical_audit_context',
                                                           '_startup_mechanical_audit_context'),
                                                          ('_validate_startup_external_fact_review',
                                                           '_validate_startup_external_fact_review'),
                                                          ('_write_controller_boundary_confirmation',
                                                           '_write_controller_boundary_confirmation'),
                                                          ('_write_startup_activation', '_write_startup_activation'),
                                                          ('_write_startup_fact_report', '_write_startup_fact_report'),
                                                          ('_write_startup_mechanical_audit',
                                                           '_write_startup_mechanical_audit'),
                                                          ('_write_startup_protocol_dead_end',
                                                           '_write_startup_protocol_dead_end'),
                                                          ('_write_startup_repair_request',
                                                           '_write_startup_repair_request')),
 ('flowpilot_router_startup_intake', True, True): (('_apply_startup_intake_result_to_bootstrap',
                                                    '_apply_startup_intake_result_to_bootstrap'),
                                                   ('_build_user_intake_body_from_ref',
                                                    '_build_user_intake_body_from_ref'),
                                                   ('_confirmed_startup_intake', '_confirmed_startup_intake'),
                                                   ('_copy_startup_intake_file', '_copy_startup_intake_file'),
                                                   ('_deterministic_bootstrap_seed_evidence_path',
                                                    '_deterministic_bootstrap_seed_evidence_path'),
                                                   ('_forbidden_startup_intake_body_fields',
                                                    '_forbidden_startup_intake_body_fields'),
                                                   ('_initialize_mailbox_foundation', '_initialize_mailbox_foundation'),
                                                   ('_materialize_startup_intake_record',
                                                    '_materialize_startup_intake_record'),
                                                   ('_normalize_startup_question_stop_boundary',
                                                    '_normalize_startup_question_stop_boundary'),
                                                   ('_record_startup_user_request_ref',
                                                    '_record_startup_user_request_ref'),
                                                   ('_require_interactive_startup_intake_artifact',
                                                    '_require_interactive_startup_intake_artifact'),
                                                   ('_resolve_existing_project_file', '_resolve_existing_project_file'),
                                                   ('_run_deterministic_startup_bootstrap_seed',
                                                    '_run_deterministic_startup_bootstrap_seed'),
                                                   ('_same_project_file', '_same_project_file'),
                                                   ('_startup_intake_output_dir_ref', '_startup_intake_output_dir_ref'),
                                                   ('_startup_intake_result_path_from_payload',
                                                    '_startup_intake_result_path_from_payload'),
                                                   ('_startup_intake_result_payload_contract',
                                                    '_startup_intake_result_payload_contract'),
                                                   ('_startup_intake_ui_action_extra',
                                                    '_startup_intake_ui_action_extra'),
                                                   ('_startup_intake_ui_launcher_ref',
                                                    '_startup_intake_ui_launcher_ref'),
                                                   ('_user_request_ref_from_startup_intake',
                                                    '_user_request_ref_from_startup_intake'),
                                                   ('_validate_startup_answer_interpretation',
                                                    '_validate_startup_answer_interpretation'),
                                                   ('_validate_startup_answers', '_validate_startup_answers'),
                                                   ('_validate_startup_intake_result_payload',
                                                    '_validate_startup_intake_result_payload'),
                                                   ('_validate_user_request', '_validate_user_request'),
                                                   ('_write_startup_answers_record', '_write_startup_answers_record'),
                                                   ('_write_startup_user_intake_scaffold',
                                                    '_write_startup_user_intake_scaffold')),
 ('flowpilot_router_startup_role_recovery', True, True): (('_controller_action_entry_view',
                                                           '_controller_action_entry_view'),
                                                          ('_controller_action_wait_roles',
                                                           '_controller_action_wait_roles'),
                                                          ('_current_crew_generation', '_current_crew_generation'),
                                                          ('_latest_resume_tick_id', '_latest_resume_tick_id'),
                                                          ('_latest_role_recovery_transaction',
                                                           '_latest_role_recovery_transaction'),
                                                          ('_load_role_recovery_state', '_load_role_recovery_state'),
                                                          ('_mark_controller_action_done_by_role_recovery',
                                                           '_mark_controller_action_done_by_role_recovery'),
                                                          ('_next_resume_action', '_next_resume_action'),
                                                          ('_next_role_recovery_action', '_next_role_recovery_action'),
                                                          ('_next_startup_heartbeat_binding_action',
                                                           '_next_startup_heartbeat_binding_action'),
                                                          ('_normalize_resume_role_agent_records',
                                                           '_normalize_resume_role_agent_records'),
                                                          ('_normalize_role_agent_records',
                                                           '_normalize_role_agent_records'),
                                                          ('_normalize_role_recovery_agent_records',
                                                           '_normalize_role_recovery_agent_records'),
                                                          ('_open_role_recovery_transaction',
                                                           '_open_role_recovery_transaction'),
                                                          ('_path_hash', '_path_hash'),
                                                          ('_payload_indicates_role_no_output',
                                                           '_payload_indicates_role_no_output'),
                                                          ('_plan_role_recovery_obligation_replay',
                                                           '_plan_role_recovery_obligation_replay'),
                                                          ('_reclaim_role_recovery_postcondition_from_report',
                                                           '_reclaim_role_recovery_postcondition_from_report'),
                                                          ('_record_role_no_output_reissue',
                                                           '_record_role_no_output_reissue'),
                                                          ('_resume_liveness_probe_batch_id',
                                                           '_resume_liveness_probe_batch_id'),
                                                          ('_resume_role_context', '_resume_role_context'),
                                                          ('_resume_role_contexts', '_resume_role_contexts'),
                                                          ('_resume_role_rehydration_action_extra',
                                                           '_resume_role_rehydration_action_extra'),
                                                          ('_role_core_prompt_delivery_payload',
                                                           '_role_core_prompt_delivery_payload'),
                                                          ('_role_core_prompt_path', '_role_core_prompt_path'),
                                                          ('_role_memory_path', '_role_memory_path'),
                                                          ('_role_no_output_liveness_result',
                                                           '_role_no_output_liveness_result'),
                                                          ('_role_no_output_reissue_attempt',
                                                           '_role_no_output_reissue_attempt'),
                                                          ('_role_no_output_replacement_action',
                                                           '_role_no_output_replacement_action'),
                                                          ('_role_no_output_target_roles',
                                                           '_role_no_output_target_roles'),
                                                          ('_role_no_output_wait_candidate',
                                                           '_role_no_output_wait_candidate'),
                                                          ('_role_recovery_action_sort_key',
                                                           '_role_recovery_action_sort_key'),
                                                          ('_role_recovery_dir', '_role_recovery_dir'),
                                                          ('_role_recovery_existing_event_for_wait',
                                                           '_role_recovery_existing_event_for_wait'),
                                                          ('_role_recovery_latest_transaction_path',
                                                           '_role_recovery_latest_transaction_path'),
                                                          ('_role_recovery_obligation_replay_path',
                                                           '_role_recovery_obligation_replay_path'),
                                                          ('_role_recovery_payload_contract',
                                                           '_role_recovery_payload_contract'),
                                                          ('_role_recovery_pending_return_for_action',
                                                           '_role_recovery_pending_return_for_action'),
                                                          ('_role_recovery_ready_context',
                                                           '_role_recovery_ready_context'),
                                                          ('_role_recovery_replacement_action',
                                                           '_role_recovery_replacement_action'),
                                                          ('_role_recovery_report_path', '_role_recovery_report_path'),
                                                          ('_role_recovery_state_path', '_role_recovery_state_path'),
                                                          ('_role_recovery_target_roles',
                                                           '_role_recovery_target_roles'),
                                                          ('_role_recovery_wait_candidates',
                                                           '_role_recovery_wait_candidates'),
                                                          ('_role_spawn_action_extra', '_role_spawn_action_extra'),
                                                          ('_settle_role_recovery_candidate_if_evidence_exists',
                                                           '_settle_role_recovery_candidate_if_evidence_exists'),
                                                          ('_stable_resume_launcher_contract',
                                                           '_stable_resume_launcher_contract'),
                                                          ('_supersede_role_no_output_original_wait',
                                                           '_supersede_role_no_output_original_wait'),
                                                          ('_supersede_role_recovery_original_wait',
                                                           '_supersede_role_recovery_original_wait'),
                                                          ('_write_initial_continuation_binding',
                                                           '_write_initial_continuation_binding'),
                                                          ('_write_resume_role_rehydration_report',
                                                           '_write_resume_role_rehydration_report'),
                                                          ('_write_role_recovery_report',
                                                           '_write_role_recovery_report')),
 ('flowpilot_router_startup_support', True, False): (('_active_agent_id_for_role', '_active_agent_id_for_role'),
                                                     ('_controller_wait_allowed_external_events',
                                                      '_controller_wait_allowed_external_events'),
                                                     ('_ensure_startup_run_state', '_ensure_startup_run_state'),
                                                     ('_external_event_payload_digest',
                                                      '_external_event_payload_digest'),
                                                     ('_json_safe', '_json_safe'),
                                                     ('load_manifest_from_run', 'load_manifest_from_run'),
                                                     ('manifest_card', 'manifest_card'))}

def owner_exports_startup() -> dict[RegistryKey, tuple[ExportSpec, ...]]:
    return OWNER_EXPORTS_STARTUP


__all__ = ["OWNER_EXPORTS_STARTUP", "owner_exports_startup"]
