"""Router facade export manifest shard.

The shard keeps registry rows grouped by domain while the aggregator preserves
the public OWNER_EXPORTS contract.
"""

from __future__ import annotations

from typing import TypeAlias

ExportSpec: TypeAlias = tuple[str, str]
RegistryKey: TypeAlias = tuple[str, bool, bool]

OWNER_EXPORTS_TERMINAL_WORK: dict[RegistryKey, tuple[ExportSpec, ...]] = {('flowpilot_router_pm_role_followup', True, False): (('_model_miss_followup_expectation',
                                                       '_model_miss_followup_expectation'),
                                                      ('_pm_role_work_channel_open', '_pm_role_work_channel_open'),
                                                      ('_validate_pm_role_work_request_against_followup',
                                                       '_validate_pm_role_work_request_against_followup')),
 ('flowpilot_router_system_cards', True, False): (('_apply_card_bundle_return_event_check',
                                                   '_apply_card_bundle_return_event_check'),
                                                  ('_apply_card_return_event_check', '_apply_card_return_event_check'),
                                                  ('_auto_commit_system_card_delivery_action',
                                                   '_auto_commit_system_card_delivery_action'),
                                                  ('_clear_stale_role_wait_for_quarantined_report',
                                                   '_clear_stale_role_wait_for_quarantined_report'),
                                                  ('_commit_system_card_bundle_delivery_artifact',
                                                   '_commit_system_card_bundle_delivery_artifact'),
                                                  ('_commit_system_card_delivery_artifact',
                                                   '_commit_system_card_delivery_artifact'),
                                                  ('_committed_card_bundle_artifact_extra',
                                                   '_committed_card_bundle_artifact_extra'),
                                                  ('_direct_router_ack_token_for_bundle',
                                                   '_direct_router_ack_token_for_bundle'),
                                                  ('_direct_router_ack_token_for_card',
                                                   '_direct_router_ack_token_for_card'),
                                                  ('_mark_card_return_pending_explicit_check',
                                                   '_mark_card_return_pending_explicit_check'),
                                                  ('_next_quarantined_role_report_path',
                                                   '_next_quarantined_role_report_path'),
                                                  ('_next_system_card_action', '_next_system_card_action'),
                                                  ('_next_system_card_bundle_action',
                                                   '_next_system_card_bundle_action'),
                                                  ('_pending_bundle_return_record_for_action',
                                                   '_pending_bundle_return_record_for_action'),
                                                  ('_pending_card_return_matches_event_dependency',
                                                   '_pending_card_return_matches_event_dependency'),
                                                  ('_pending_return_card_delivery_flags',
                                                   '_pending_return_card_delivery_flags'),
                                                  ('_pending_return_record_for_action',
                                                   '_pending_return_record_for_action'),
                                                  ('_preconsume_pending_card_return_ack_before_external_event',
                                                   '_preconsume_pending_card_return_ack_before_external_event'),
                                                  ('_quarantine_missing_ack_report_before_external_event',
                                                   '_quarantine_missing_ack_report_before_external_event'),
                                                  ('_reconcile_card_bundle_wait_rows',
                                                   '_reconcile_card_bundle_wait_rows'),
                                                  ('_reconcile_card_wait_rows', '_reconcile_card_wait_rows'),
                                                  ('_reconcile_durable_wait_evidence',
                                                   '_reconcile_durable_wait_evidence'),
                                                  ('_record_card_return_event_from_external_entrypoint',
                                                   '_record_card_return_event_from_external_entrypoint'),
                                                  ('_role_list', '_role_list'),
                                                  ('_router_release_startup_user_intake_to_pm',
                                                   '_router_release_startup_user_intake_to_pm'),
                                                  ('_run_router_return_settlement_finalizers',
                                                   '_run_router_return_settlement_finalizers'),
                                                  ('_startup_pm_card_bundle_ack_record',
                                                   '_startup_pm_card_bundle_ack_record'),
                                                  ('_system_card_bundle_candidate_actions',
                                                   '_system_card_bundle_candidate_actions'),
                                                  ('_system_card_delivery_flag', '_system_card_delivery_flag'),
                                                  ('_system_card_to_role', '_system_card_to_role'),
                                                  ('_try_auto_consume_pending_card_return_ack',
                                                   '_try_auto_consume_pending_card_return_ack')),
 ('flowpilot_router_terminal_ledger', False, True): (('_build_source_of_truth_final_entries',
                                                      '_build_source_of_truth_final_entries'),
                                                     ('_final_ledger_traceability_issues',
                                                      '_final_ledger_traceability_issues'),
                                                     ('_node_acceptance_traceability_issues',
                                                      '_node_acceptance_traceability_issues'),
                                                     ('_recover_terminal_status_from_run_authorities',
                                                      '_recover_terminal_status_from_run_authorities'),
                                                     ('_repair_legacy_material_packet_contracts',
                                                      '_repair_legacy_material_packet_contracts'),
                                                     ('_requirement_trace_closure_from_root_replay',
                                                      '_requirement_trace_closure_from_root_replay'),
                                                     ('_root_requirement_ids', '_root_requirement_ids'),
                                                     ('_route_mutation_completion_issues',
                                                      '_route_mutation_completion_issues'),
                                                     ('_route_nodes_with_requirement_trace',
                                                      '_route_nodes_with_requirement_trace'),
                                                     ('_string_list', '_string_list'),
                                                     ('_terminal_closure_suite_is_closed',
                                                      '_terminal_closure_suite_is_closed'),
                                                     ('_terminal_summary_action', '_terminal_summary_action'),
                                                     ('_terminal_summary_index_entry', '_terminal_summary_index_entry'),
                                                     ('_terminal_summary_written', '_terminal_summary_written'),
                                                     ('_validate_terminal_summary_payload',
                                                      '_validate_terminal_summary_payload'),
                                                     ('_validated_root_replay', '_validated_root_replay'),
                                                     ('_write_final_route_wide_ledger',
                                                      '_write_final_route_wide_ledger'),
                                                     ('_write_task_completion_projection',
                                                      '_write_task_completion_projection'),
                                                     ('_write_terminal_backward_replay',
                                                      '_write_terminal_backward_replay'),
                                                     ('_write_terminal_closure_suite', '_write_terminal_closure_suite'),
                                                     ('_write_terminal_summary', '_write_terminal_summary'),
                                                     ('reconcile_current_run', 'reconcile_current_run')),
 ('flowpilot_router_work_packets', False, True): (('_active_child_skill_bindings_from_plan',
                                                   '_active_child_skill_bindings_from_plan'),
                                                  ('_active_child_skill_source_paths',
                                                   '_active_child_skill_source_paths'),
                                                  ('_active_current_node_packet_records',
                                                   '_active_current_node_packet_records'),
                                                  ('_active_holder_frontier_version',
                                                   '_active_holder_frontier_version'),
                                                  ('_active_parallel_packet_batch', '_active_parallel_packet_batch'),
                                                  ('_active_pm_role_work_batch_records',
                                                   '_active_pm_role_work_batch_records'),
                                                  ('_active_pm_role_work_request', '_active_pm_role_work_request'),
                                                  ('_agent_role_map_from_crew_ledger',
                                                   '_agent_role_map_from_crew_ledger'),
                                                  ('_apply_pm_role_work_gate_mappings',
                                                   '_apply_pm_role_work_gate_mappings'),
                                                  ('_controller_status_packet_path_from_packet_envelope',
                                                   '_controller_status_packet_path_from_packet_envelope'),
                                                  ('_current_node_active_holder_lease_plan',
                                                   '_current_node_active_holder_lease_plan'),
                                                  ('_current_node_batch_packet_record',
                                                   '_current_node_batch_packet_record'),
                                                  ('_current_node_missing_result_roles',
                                                   '_current_node_missing_result_roles'),
                                                  ('_current_node_packet_context', '_current_node_packet_context'),
                                                  ('_current_node_packet_records', '_current_node_packet_records'),
                                                  ('_current_node_result_context', '_current_node_result_context'),
                                                  ('_current_node_results_complete', '_current_node_results_complete'),
                                                  ('_empty_officer_request_lifecycle_index',
                                                   '_empty_officer_request_lifecycle_index'),
                                                  ('_empty_pm_role_work_request_index',
                                                   '_empty_pm_role_work_request_index'),
                                                  ('_ensure_barrier_bundles_ready', '_ensure_barrier_bundles_ready'),
                                                  ('_issue_current_node_active_holder_leases',
                                                   '_issue_current_node_active_holder_leases'),
                                                  ('_issue_packet_active_holder_leases',
                                                   '_issue_packet_active_holder_leases'),
                                                  ('_load_officer_request_lifecycle_index',
                                                   '_load_officer_request_lifecycle_index'),
                                                  ('_load_packet_index', '_load_packet_index'),
                                                  ('_load_parallel_packet_batch', '_load_parallel_packet_batch'),
                                                  ('_load_pm_role_work_request_index',
                                                   '_load_pm_role_work_request_index'),
                                                  ('_mark_parallel_batch_packets_relayed',
                                                   '_mark_parallel_batch_packets_relayed'),
                                                  ('_mark_parallel_batch_results_joined',
                                                   '_mark_parallel_batch_results_joined'),
                                                  ('_mark_parallel_batch_reviewed', '_mark_parallel_batch_reviewed'),
                                                  ('_material_packet_body_text_from_spec',
                                                   '_material_packet_body_text_from_spec'),
                                                  ('_material_scan_index_path', '_material_scan_index_path'),
                                                  ('_merge_agent_role_maps', '_merge_agent_role_maps'),
                                                  ('_metadata_binding_ids', '_metadata_binding_ids'),
                                                  ('_metadata_string_list', '_metadata_string_list'),
                                                  ('_next_current_node_packet_action',
                                                   '_next_current_node_packet_action'),
                                                  ('_next_material_packet_action', '_next_material_packet_action'),
                                                  ('_next_pm_role_work_request_action',
                                                   '_next_pm_role_work_request_action'),
                                                  ('_next_research_packet_action', '_next_research_packet_action'),
                                                  ('_normalize_pm_role_work_result_recipient',
                                                   '_normalize_pm_role_work_result_recipient'),
                                                  ('_officer_lifecycle_entry', '_officer_lifecycle_entry'),
                                                  ('_officer_request_lifecycle_index_path',
                                                   '_officer_request_lifecycle_index_path'),
                                                  ('_packet_active_holder_lease_plan',
                                                   '_packet_active_holder_lease_plan'),
                                                  ('_packet_envelope_path', '_packet_envelope_path'),
                                                  ('_packet_envelope_path_from_record',
                                                   '_packet_envelope_path_from_record'),
                                                  ('_packet_paths', '_packet_paths'),
                                                  ('_packet_record_from_envelope', '_packet_record_from_envelope'),
                                                  ('_parallel_batch_record_result_exists',
                                                   '_parallel_batch_record_result_exists'),
                                                  ('_parallel_packet_batch_member_summary',
                                                   '_parallel_packet_batch_member_summary'),
                                                  ('_parallel_packet_batch_path', '_parallel_packet_batch_path'),
                                                  ('_parallel_packet_batch_ref_path',
                                                   '_parallel_packet_batch_ref_path'),
                                                  ('_parallel_packet_batch_root', '_parallel_packet_batch_root'),
                                                  ('_pm_role_work_gate_mapping_alias_specs',
                                                   '_pm_role_work_gate_mapping_alias_specs'),
                                                  ('_pm_role_work_gate_mapping_artifact_path',
                                                   '_pm_role_work_gate_mapping_artifact_path'),
                                                  ('_pm_role_work_gate_mapping_candidates',
                                                   '_pm_role_work_gate_mapping_candidates'),
                                                  ('_pm_role_work_gate_mappings_for_decision',
                                                   '_pm_role_work_gate_mappings_for_decision'),
                                                  ('_pm_role_work_output_contract', '_pm_role_work_output_contract'),
                                                  ('_pm_role_work_packet_type_from_contract',
                                                   '_pm_role_work_packet_type_from_contract'),
                                                  ('_pm_role_work_record_is_nonblocking',
                                                   '_pm_role_work_record_is_nonblocking'),
                                                  ('_pm_role_work_records_are_nonblocking',
                                                   '_pm_role_work_records_are_nonblocking'),
                                                  ('_pm_role_work_records_dependency_class',
                                                   '_pm_role_work_records_dependency_class'),
                                                  ('_pm_role_work_request_body_text',
                                                   '_pm_role_work_request_body_text'),
                                                  ('_pm_role_work_request_index_path',
                                                   '_pm_role_work_request_index_path'),
                                                  ('_pm_role_work_request_record', '_pm_role_work_request_record'),
                                                  ('_pm_role_work_result_decision_payload_contract',
                                                   '_pm_role_work_result_decision_payload_contract'),
                                                  ('_pm_role_work_target_gate_contract',
                                                   '_pm_role_work_target_gate_contract'),
                                                  ('_record_officer_lifecycle_pm_decision',
                                                   '_record_officer_lifecycle_pm_decision'),
                                                  ('_record_officer_lifecycle_request',
                                                   '_record_officer_lifecycle_request'),
                                                  ('_record_officer_lifecycle_result_returned',
                                                   '_record_officer_lifecycle_result_returned'),
                                                  ('_record_officer_lifecycle_status',
                                                   '_record_officer_lifecycle_status'),
                                                  ('_refresh_all_parallel_packet_batches_from_durable_results',
                                                   '_refresh_all_parallel_packet_batches_from_durable_results'),
                                                  ('_refresh_parallel_packet_batch_from_durable_results',
                                                   '_refresh_parallel_packet_batch_from_durable_results'),
                                                  ('_relay_packet_records', '_relay_packet_records'),
                                                  ('_relay_result_records', '_relay_result_records'),
                                                  ('_research_packet_index_path', '_research_packet_index_path'),
                                                  ('_result_envelope_path', '_result_envelope_path'),
                                                  ('_result_envelope_path_from_packet_record',
                                                   '_result_envelope_path_from_packet_record'),
                                                  ('_role_output_status_packet_path_for_wait',
                                                   '_role_output_status_packet_path_for_wait'),
                                                  ('_safe_packet_id_component', '_safe_packet_id_component'),
                                                  ('_unresolved_advisory_pm_role_work_records',
                                                   '_unresolved_advisory_pm_role_work_records'),
                                                  ('_unresolved_pm_role_work_requests',
                                                   '_unresolved_pm_role_work_requests'),
                                                  ('_upsert_officer_lifecycle_entry',
                                                   '_upsert_officer_lifecycle_entry'),
                                                  ('_validate_packet_bodies_opened_by_targets',
                                                   '_validate_packet_bodies_opened_by_targets'),
                                                  ('_validate_packet_group_for_reviewer',
                                                   '_validate_packet_group_for_reviewer'),
                                                  ('_validate_pm_role_work_process_contract_binding',
                                                   '_validate_pm_role_work_process_contract_binding'),
                                                  ('_validate_result_bodies_opened_by_pm',
                                                   '_validate_result_bodies_opened_by_pm'),
                                                  ('_validate_results_exist_for_packets',
                                                   '_validate_results_exist_for_packets'),
                                                  ('_validate_role_work_result_process_binding',
                                                   '_validate_role_work_result_process_binding'),
                                                  ('_write_material_dispatch_block_report',
                                                   '_write_material_dispatch_block_report'),
                                                  ('_write_material_dispatch_recheck_protocol_blocker',
                                                   '_write_material_dispatch_recheck_protocol_blocker'),
                                                  ('_write_material_scan_packets', '_write_material_scan_packets'),
                                                  ('_write_material_sufficiency_report',
                                                   '_write_material_sufficiency_report'),
                                                  ('_write_material_understanding', '_write_material_understanding'),
                                                  ('_write_officer_request_lifecycle_index',
                                                   '_write_officer_request_lifecycle_index'),
                                                  ('_write_parallel_packet_batch', '_write_parallel_packet_batch'),
                                                  ('_write_parallel_packet_batch_state',
                                                   '_write_parallel_packet_batch_state'),
                                                  ('_write_pm_package_result_disposition',
                                                   '_write_pm_package_result_disposition'),
                                                  ('_write_pm_role_work_request', '_write_pm_role_work_request'),
                                                  ('_write_pm_role_work_request_index',
                                                   '_write_pm_role_work_request_index'),
                                                  ('_write_pm_role_work_result_decision',
                                                   '_write_pm_role_work_result_decision'),
                                                  ('_write_research_capability_decision',
                                                   '_write_research_capability_decision'),
                                                  ('_write_research_package', '_write_research_package'),
                                                  ('_write_role_work_result_returned',
                                                   '_write_role_work_result_returned'),
                                                  ('_write_worker_research_report', '_write_worker_research_report'))}

__all__ = ["OWNER_EXPORTS_TERMINAL_WORK"]
