"""Compatibility reset flag exports derived from the gate registry."""

from __future__ import annotations

from flowpilot_router_protocol_gate_registry import (
    CHILD_SKILL_GATE_REPAIR_RESET_FLAGS,
    EVIDENCE_QUALITY_REPAIR_RESET_FLAGS,
    FINAL_BACKWARD_REPAIR_RESET_FLAGS,
    PARENT_BACKWARD_REPAIR_RESET_FLAGS,
    PRODUCT_ARCHITECTURE_REPAIR_RESET_FLAGS,
    RESEARCH_GATE_REPAIR_RESET_FLAGS,
    ROOT_CONTRACT_REPAIR_RESET_FLAGS,
    ROUTE_GATE_REPAIR_RESET_FLAGS,
)

__all__ = (
    'PRODUCT_ARCHITECTURE_REPAIR_RESET_FLAGS',
    'ROOT_CONTRACT_REPAIR_RESET_FLAGS',
    'CHILD_SKILL_GATE_REPAIR_RESET_FLAGS',
    'ROUTE_GATE_REPAIR_RESET_FLAGS',
    'RESEARCH_GATE_REPAIR_RESET_FLAGS',
    'PARENT_BACKWARD_REPAIR_RESET_FLAGS',
    'EVIDENCE_QUALITY_REPAIR_RESET_FLAGS',
    'FINAL_BACKWARD_REPAIR_RESET_FLAGS',
)
