"""Family-level FlowPilot model-test alignment plans."""

from __future__ import annotations

from typing import Any

from flowpilot_model_test_alignment_common import *

def build_alignment_plan_entries() -> list[dict[str, Any]]:
    """Build major FlowPilot model/test-family alignment plans."""

    startup = ModelTestAlignmentPlan(
        model_id="startup",
        obligations=(
            _obligation(
                "startup.questions.pause_before_work",
                obligation_type="contract",
                description="Startup asks the three questions, waits for answers, and blocks banner/controller work until the answer boundary is satisfied.",
                required_test_kinds=(HAPPY, NEGATIVE),
            ),
            _obligation(
                "startup.run_isolation_and_activation",
                obligation_type="scenario",
                description="Startup creates prompt-isolated current-run state and requires reviewer facts plus PM approval before work beyond startup.",
                required_test_kinds=(HAPPY, FAILURE),
            ),
        ),
        test_evidence=(
            _evidence(
                "startup.happy.prompt_isolated_run",
                test_name="test_startup_sequence_creates_prompt_isolated_run",
                path="tests/router_runtime/startup_bootstrap.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_startup_daemon",
                test_kind=HAPPY,
                covers=("startup.run_isolation_and_activation",),
            ),
            _evidence(
                "startup.negative.waits_for_answers",
                test_name="test_startup_waits_for_answers_before_banner_or_controller",
                path="tests/router_runtime/startup_bootstrap.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_startup_daemon",
                test_kind=NEGATIVE,
                covers=("startup.questions.pause_before_work",),
            ),
            _evidence(
                "startup.happy.answer_boundary",
                test_name="test_record_startup_answers_accepts_ai_interpretation_with_reviewer_receipt",
                path="tests/router_runtime/startup_bootstrap.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_startup_daemon",
                test_kind=HAPPY,
                covers=("startup.questions.pause_before_work",),
            ),
            _evidence(
                "startup.failure.activation_requires_reviewer",
                test_name="test_startup_activation_requires_reviewer_facts_before_work",
                path="tests/router_runtime/startup_bootstrap.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_startup_daemon",
                test_kind=FAILURE,
                covers=("startup.run_isolation_and_activation",),
            ),
        ),
    )

    packet_card_ack = ModelTestAlignmentPlan(
        model_id="packet_card_ack",
        obligations=(
            _obligation(
                "packet.physical_body_boundary",
                obligation_type="contract",
                description="Packet envelopes, bodies, result files, hashes, and recipient reads stay physically separated from Controller relay text.",
                required_test_kinds=(HAPPY, NEGATIVE),
            ),
            _obligation(
                "card.ack_identity_and_bundle",
                obligation_type="hazard",
                description="Card and bundle ACKs require correct role, token, receipt, hash, and per-card completion before advancing.",
                required_test_kinds=(HAPPY, NEGATIVE),
            ),
            _obligation(
                "ack.return_wait_preconsumption",
                obligation_type="transition",
                description="Router preconsumes valid ACK/return events and blocks incomplete or invalid pre-ACK reports without advancing stale waits.",
                required_test_kinds=(EDGE, FAILURE),
            ),
            _obligation(
                "packet_control_plane.facade_split_integrity",
                obligation_type="contract",
                description="Packet control-plane model keeps its facade import path while state, transition, and invariant owners remain executable.",
                required_test_kinds=(HAPPY,),
            ),
        ),
        test_evidence=(
            _evidence(
                "packet.happy.physical_files",
                test_name="test_pm_issue_writes_physical_envelope_body_and_ledger",
                path="tests/test_flowpilot_packet_runtime.py",
                command="python -m unittest tests.test_flowpilot_packet_runtime",
                test_kind=HAPPY,
                covers=("packet.physical_body_boundary",),
            ),
            _evidence(
                "packet.negative.controller_body_exclusion",
                test_name="test_controller_handoff_contains_envelope_only_not_body_content",
                path="tests/test_flowpilot_packet_runtime.py",
                command="python -m unittest tests.test_flowpilot_packet_runtime",
                test_kind=NEGATIVE,
                covers=("packet.physical_body_boundary",),
            ),
            _evidence(
                "card.happy.card_ack",
                test_name="test_card_runtime_opens_card_and_submits_ack",
                path="tests/test_flowpilot_card_runtime.py",
                command="python -m pytest tests/test_flowpilot_card_runtime.py",
                test_kind=HAPPY,
                covers=("card.ack_identity_and_bundle",),
            ),
            _evidence(
                "card.negative.wrong_role_ack",
                test_name="test_card_runtime_rejects_wrong_role_and_ack_without_receipt",
                path="tests/test_flowpilot_card_runtime.py",
                command="python -m pytest tests/test_flowpilot_card_runtime.py",
                test_kind=NEGATIVE,
                covers=("card.ack_identity_and_bundle",),
            ),
            _evidence(
                "ack.edge.preconsume_valid_ack",
                test_name="test_record_external_event_preconsumes_valid_card_ack_before_blocking",
                path="tests/router_runtime/ack_return.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_ack_return",
                test_kind=EDGE,
                covers=("ack.return_wait_preconsumption",),
            ),
            _evidence(
                "ack.failure.incomplete_bundle",
                test_name="test_record_external_event_does_not_preconsume_incomplete_bundle_ack",
                path="tests/router_runtime/ack_return.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_ack_return",
                test_kind=FAILURE,
                covers=("ack.return_wait_preconsumption",),
            ),
            _evidence(
                "packet_control_plane.happy.split_runner",
                test_name="run_packet_control_plane_checks",
                path="skills/flowpilot/assets/run_packet_control_plane_checks.py",
                command="python skills/flowpilot/assets/run_packet_control_plane_checks.py",
                test_kind=HAPPY,
                covers=("packet_control_plane.facade_split_integrity",),
            ),
        ),
    )

    route_mutation = ModelTestAlignmentPlan(
        model_id="route_mutation",
        obligations=(
            _obligation(
                "route_mutation.topology_and_recheck",
                obligation_type="contract",
                description="Route mutation declares topology, affected nodes, process/product rechecks, and old packet supersession before activation.",
                required_test_kinds=(HAPPY, NEGATIVE),
            ),
            _obligation(
                "route_mutation.sibling_replacement_stales_old_evidence",
                obligation_type="hazard",
                description="Sibling branch replacement marks old sibling evidence stale and projects replacement/replay scope in the route display.",
                required_test_kinds=(NEGATIVE, EDGE),
            ),
        ),
        test_evidence=(
            _evidence(
                "route_mutation.happy.contract_fixture",
                test_name="TestRouteMutationChildContractFixture",
                path="tests/flowpilot_route_mutation_contracts.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_route_mutation",
                test_kind=HAPPY,
                covers=("route_mutation.topology_and_recheck",),
            ),
            _evidence(
                "route_mutation.negative.required_preconditions",
                test_name="test_route_mutation_and_final_ledger_have_required_preconditions",
                path="tests/router_runtime/route_mutation_preconditions.py",
                command="python -m unittest tests.router_runtime.route_mutation_preconditions.RouteMutationPreconditionRuntimeTests.test_route_mutation_and_final_ledger_have_required_preconditions",
                test_kind=NEGATIVE,
                covers=("route_mutation.topology_and_recheck",),
            ),
            _evidence(
                "route_mutation.edge.sibling_replacement_display",
                test_name="test_sibling_branch_replacement_draws_replacement_and_replay_scope",
                path="tests/test_flowpilot_user_flow_diagram.py",
                command="python -m unittest tests.test_flowpilot_user_flow_diagram.FlowPilotUserFlowDiagramTests.test_sibling_branch_replacement_draws_replacement_and_replay_scope",
                test_kind=EDGE,
                covers=("route_mutation.sibling_replacement_stales_old_evidence",),
            ),
            _evidence(
                "route_mutation.negative.old_sibling_proof",
                test_name="test_route_mutation_sibling_branch_replacement_blocks_old_sibling_proof",
                path="tests/router_runtime/route_mutation_sibling_replacement.py",
                command="python -m unittest tests.router_runtime.route_mutation_sibling_replacement.RouteMutationSiblingReplacementRuntimeTests.test_route_mutation_sibling_branch_replacement_blocks_old_sibling_proof",
                test_kind=NEGATIVE,
                covers=("route_mutation.sibling_replacement_stales_old_evidence",),
            ),
        ),
    )

    terminal_closure_resume = ModelTestAlignmentPlan(
        model_id="terminal_closure_resume",
        obligations=(
            _obligation(
                "terminal.final_ledger_and_backward_replay",
                obligation_type="invariant",
                description="Terminal completion requires a clean PM-built final ledger, delivered-product backward replay, and PM completion approval.",
                required_test_kinds=(HAPPY, NEGATIVE),
            ),
            _obligation(
                "closure.dirty_ledgers_block_completion",
                obligation_type="hazard",
                description="Closure blocks dirty defect, PM-suggestion, role-memory, quarantine, or source-of-truth state after terminal replay.",
                required_test_kinds=(FAILURE,),
            ),
            _obligation(
                "resume.current_run_reentry",
                obligation_type="transition",
                description="Resume re-entry loads current-run state, frontier, packet ledger, daemon/owner state, role memory, and recovery evidence before PM work.",
                required_test_kinds=(HAPPY, FAILURE),
            ),
        ),
        test_evidence=(
            _evidence(
                "terminal.happy.replay_segments",
                test_name="test_terminal_replay_requires_reviewed_segments_and_pm_segment_decisions",
                path="tests/router_runtime/terminal.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_terminal",
                test_kind=HAPPY,
                covers=("terminal.final_ledger_and_backward_replay",),
            ),
            _evidence(
                "terminal.negative.final_ledger_sources",
                test_name="test_final_ledger_rejects_missing_source_of_truth_entries_and_contract_replay",
                path="tests/router_runtime/terminal.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_terminal",
                test_kind=NEGATIVE,
                covers=("terminal.final_ledger_and_backward_replay",),
            ),
            _evidence(
                "closure.failure.dirty_defect_ledger",
                test_name="test_terminal_closure_blocks_dirty_defect_ledger_after_terminal_replay",
                path="tests/router_runtime/closure.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_closure",
                test_kind=FAILURE,
                covers=("closure.dirty_ledgers_block_completion",),
            ),
            _evidence(
                "resume.happy.loads_state",
                test_name="test_resume_reentry_loads_state_before_resume_cards",
                path="tests/router_runtime/resume.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_resume",
                test_kind=HAPPY,
                covers=("resume.current_run_reentry",),
            ),
            _evidence(
                "resume.failure.ambiguous_state",
                test_name="test_resume_ambiguous_state_blocks_continue_without_recovery_evidence",
                path="tests/router_runtime/resume.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_resume",
                test_kind=FAILURE,
                covers=("resume.current_run_reentry",),
            ),
        ),
    )

    role_output = ModelTestAlignmentPlan(
        model_id="role_output_contracts",
        obligations=(
            _obligation(
                "role_output.registry_authority",
                obligation_type="contract",
                description="Role outputs are registry-bound, role-authored, authority-checked, and submitted only through current Router waits.",
                required_test_kinds=(HAPPY, NEGATIVE),
            ),
            _obligation(
                "output_contract.packet_binding",
                obligation_type="contract",
                description="Output contracts are repeated in packet envelope/body/ledger/result and rejected for wrong recipients.",
                required_test_kinds=(HAPPY, NEGATIVE),
            ),
            _obligation(
                "output_contract.self_check_required_fields",
                obligation_type="hazard",
                description="Role-output self-checks expose exact missing required fields and do not treat a heading or wrong field name as a completed worker contract.",
                required_test_kinds=(NEGATIVE,),
            ),
        ),
        test_evidence=(
            _evidence(
                "role_output.happy.registry_preparable",
                test_name="test_registry_backed_output_types_are_preparable",
                path="tests/test_flowpilot_role_output_runtime.py",
                command="python -m unittest tests.test_flowpilot_role_output_runtime",
                test_kind=HAPPY,
                covers=("role_output.registry_authority",),
            ),
            _evidence(
                "role_output.negative.wrong_role",
                test_name="test_runtime_rejects_wrong_role_and_role_key_agent_id",
                path="tests/test_flowpilot_role_output_runtime.py",
                command="python -m unittest tests.test_flowpilot_role_output_runtime",
                test_kind=NEGATIVE,
                covers=("role_output.registry_authority",),
            ),
            _evidence(
                "output_contract.happy.packet_binding",
                test_name="test_pm_packet_repeats_output_contract_in_envelope_body_ledger_and_result",
                path="tests/test_flowpilot_output_contracts.py",
                command="python -m unittest tests.test_flowpilot_output_contracts",
                test_kind=HAPPY,
                covers=("output_contract.packet_binding",),
            ),
            _evidence(
                "output_contract.negative.wrong_recipient",
                test_name="test_packet_rejects_contract_for_wrong_recipient",
                path="tests/test_flowpilot_output_contracts.py",
                command="python -m unittest tests.test_flowpilot_output_contracts",
                test_kind=NEGATIVE,
                covers=("output_contract.packet_binding",),
            ),
            _evidence(
                "output_contract.negative.live_worker_missing_fields",
                test_name="test_contract_self_check_metadata_reports_live_worker_missing_fields",
                path="tests/test_flowpilot_output_contracts.py",
                command="python -m unittest tests.test_flowpilot_output_contracts",
                test_kind=NEGATIVE,
                covers=("output_contract.self_check_required_fields",),
            ),
        ),
    )

    router_loop_daemon = ModelTestAlignmentPlan(
        model_id="router_loop_daemon",
        obligations=(
            _obligation(
                "router_loop.packet_result_review_loop",
                obligation_type="transition",
                description="The current-node loop dispatches packets only after direct-dispatch preflight and routes results through PM/reviewer gates.",
                required_test_kinds=(HAPPY, FAILURE),
            ),
            _obligation(
                "router_loop.e2e_synthetic_chaos_replay",
                obligation_type="scenario",
                description="Daemon-driven fake AI replays cross startup, packet dispatch, repair, proof, parallel-run isolation, and terminal closure without treating bad packages as completion.",
                required_test_kinds=(HAPPY, FAILURE, EDGE),
            ),
            _obligation(
                "router_loop.real_router_dry_run_rehearsal",
                obligation_type="scenario",
                description="Prepared fake AI work packages exercise the real Router CLI/runtime, card ACK, packet active-holder, role-output, resume, proof, and terminal lifecycle boundaries before coverage is claimed.",
                required_test_kinds=(HAPPY, EDGE, NEGATIVE),
            ),
            _obligation(
                "router_loop.real_router_cli_boundary",
                obligation_type="contract",
                description="The public Router CLI can start, inspect, advance, apply, and record prepared role-output events without bypassing runtime payload requirements.",
                required_test_kinds=(HAPPY,),
            ),
            _obligation(
                "router_loop.control_plane_failure_canary",
                obligation_type="hazard",
                description="Bounded control-plane canaries cover locks, corrupt runtime persistence, daemon liveness, duplicate resume wakes, peer-run authority, terminal fences, and background proof artifacts.",
                required_test_kinds=(HAPPY, FAILURE, EDGE),
            ),
            _obligation(
                "router_loop.shadow_launcher_chaos_regression",
                obligation_type="scenario",
                description="Shadow launcher chaos regressions drive fake AI packages through an installed launcher copy, real Router/daemon state, recovery, peer isolation, legacy pointer loading, malformed package rejection, and bounded cleanup loops.",
                required_test_kinds=(HAPPY, EDGE, NEGATIVE),
            ),
            _obligation(
                "router_loop.historical_live_run_replay_package_suite",
                obligation_type="scenario",
                description="Historical live-run replay packages bind prior real failure shapes to real Router, packet/runtime, resume, background proof, install, route evidence, display projection, and filesystem gates without claiming arbitrary live AI semantic quality.",
                required_test_kinds=(HAPPY, EDGE, NEGATIVE),
            ),
            _obligation(
                "router_loop.known_friction_regression_gate",
                obligation_type="hazard",
                description="The six accepted historical friction surfaces are pinned to current runtime-backed regressions and reject model-only, stale, progress-only, or skipped evidence overclaims.",
                required_test_kinds=(HAPPY, NEGATIVE),
            ),
            _obligation(
                "router_loop.package_disposition_repair_owned_role_output_replay",
                obligation_type="hazard",
                description="PM package-disposition conflict replay from role-output storage is classified as repair-owned audit evidence across material, research, and current-node paths instead of becoming a fresh disposition.",
                required_test_kinds=(EDGE, NEGATIVE),
            ),
            _obligation(
                "router_loop.package_disposition_repair_owned_daemon_replay",
                obligation_type="hazard",
                description="Daemon tick replay of repair-owned package-disposition conflicts quarantines stale evidence, preserves the legal owner wait, and does not enter daemon_error.",
                required_test_kinds=(EDGE, NEGATIVE),
            ),
            _obligation(
                "daemon.lock_status_and_queue_progress",
                obligation_type="invariant",
                description="The persistent Router daemon owns one run lock, records status, waits on fresh locks, and does not reactivate released locks.",
                required_test_kinds=(HAPPY, EDGE),
            ),
            _obligation(
                "daemon.parent_child_mesh",
                obligation_type="contract",
                description="Parent hierarchy consumes thin daemon child evidence for startup/lock, Controller actions, waits/liveness, and terminal/projection while retaining the compatibility full daemon model.",
                required_test_kinds=(HAPPY, NEGATIVE),
            ),
        ),
        test_evidence=(
            _evidence(
                "router_loop.happy.direct_dispatch",
                test_name="test_current_node_packet_relay_uses_router_direct_dispatch",
                path="tests/router_runtime/packets.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_packets",
                test_kind=HAPPY,
                covers=("router_loop.packet_result_review_loop",),
            ),
            _evidence(
                "router_loop.failure.reviewer_audit",
                test_name="test_current_node_completion_requires_reviewer_passed_packet_audit",
                path="tests/router_runtime/packets.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_packets",
                test_kind=FAILURE,
                covers=("router_loop.packet_result_review_loop",),
            ),
            _evidence(
                "router_loop.e2e.happy.startup_to_terminal",
                test_name="test_e2e_golden_fake_ai_run_reaches_clean_terminal_lifecycle",
                path="tests/test_flowpilot_e2e_synthetic_chaos_replay.py",
                command="python -m pytest tests/test_flowpilot_e2e_synthetic_chaos_replay.py",
                test_kind=HAPPY,
                covers=("router_loop.e2e_synthetic_chaos_replay",),
            ),
            _evidence(
                "router_loop.e2e.failure.worker_repair",
                test_name="test_e2e_worker_bad_package_then_repair_continues_to_terminal",
                path="tests/test_flowpilot_e2e_synthetic_chaos_replay.py",
                command="python -m pytest tests/test_flowpilot_e2e_synthetic_chaos_replay.py",
                test_kind=FAILURE,
                covers=("router_loop.e2e_synthetic_chaos_replay",),
            ),
            _evidence(
                "router_loop.e2e.edge.parallel_isolation",
                test_name="test_e2e_parallel_run_peer_stop_does_not_mutate_current_run",
                path="tests/test_flowpilot_e2e_synthetic_chaos_replay.py",
                command="python -m pytest tests/test_flowpilot_e2e_synthetic_chaos_replay.py",
                test_kind=EDGE,
                covers=("router_loop.e2e_synthetic_chaos_replay",),
            ),
            _evidence(
                "router_loop.real_router.happy.full_rehearsal",
                test_name="test_real_router_full_fake_ai_package_rehearsal_reaches_terminal_standard_state",
                path="tests/test_flowpilot_real_router_dry_run_rehearsal.py",
                command="python -m pytest tests/test_flowpilot_real_router_dry_run_rehearsal.py",
                test_kind=HAPPY,
                covers=("router_loop.real_router_dry_run_rehearsal",),
            ),
            _evidence(
                "router_loop.real_router.happy.cli_boundary",
                test_name="test_router_cli_boundary_runs_fake_role_output_through_public_commands",
                path="tests/test_flowpilot_real_router_dry_run_rehearsal.py",
                command="python -m pytest tests/test_flowpilot_real_router_dry_run_rehearsal.py",
                test_kind=HAPPY,
                covers=("router_loop.real_router_cli_boundary",),
            ),
            _evidence(
                "router_loop.real_router.edge.resume_and_proof",
                test_name="test_recovery_rehearsal_resume_idempotency_and_background_proof_gate",
                path="tests/test_flowpilot_real_router_dry_run_rehearsal.py",
                command="python -m pytest tests/test_flowpilot_real_router_dry_run_rehearsal.py",
                test_kind=EDGE,
                covers=("router_loop.real_router_dry_run_rehearsal",),
            ),
            _evidence(
                "router_loop.real_router.negative.known_bad_matrix",
                test_name="test_known_bad_rows_are_rejected",
                path="tests/test_flowpilot_real_router_dry_run_rehearsal_matrix.py",
                command="python -m pytest tests/test_flowpilot_real_router_dry_run_rehearsal_matrix.py",
                test_kind=NEGATIVE,
                covers=("router_loop.real_router_dry_run_rehearsal",),
            ),
            _evidence(
                "router_loop.canary.happy.duplicate_resume",
                test_name="test_canary_duplicate_heartbeat_resume_is_idempotent",
                path="tests/test_flowpilot_control_plane_failure_canary_replay.py",
                command="python -m pytest tests/test_flowpilot_control_plane_failure_canary_replay.py",
                test_kind=HAPPY,
                covers=("router_loop.control_plane_failure_canary",),
            ),
            _evidence(
                "router_loop.canary.failure.lock_and_corrupt_persistence",
                test_name="test_canary_corrupt_scheduler_ledger_marks_daemon_error_not_live",
                path="tests/test_flowpilot_control_plane_failure_canary_replay.py",
                command="python -m pytest tests/test_flowpilot_control_plane_failure_canary_replay.py",
                test_kind=FAILURE,
                covers=("router_loop.control_plane_failure_canary",),
            ),
            _evidence(
                "router_loop.canary.edge.peer_stop_and_proof_gate",
                test_name="test_canary_peer_run_stop_does_not_mutate_current_run",
                path="tests/test_flowpilot_control_plane_failure_canary_replay.py",
                command="python -m pytest tests/test_flowpilot_control_plane_failure_canary_replay.py",
                test_kind=EDGE,
                covers=("router_loop.control_plane_failure_canary",),
            ),
            _evidence(
                "router_loop.shadow_launcher.happy.installed_start",
                test_name="test_installed_launcher_shadow_start_reaches_releasable_standard_state",
                path="tests/test_flowpilot_shadow_launcher_chaos_replay.py",
                command="python -m pytest tests/test_flowpilot_shadow_launcher_chaos_replay.py",
                test_kind=HAPPY,
                covers=("router_loop.shadow_launcher_chaos_regression",),
            ),
            _evidence(
                "router_loop.shadow_launcher.edge.recovery_peer_soak",
                test_name="test_crash_recovery_bundle_handles_dead_daemon_duplicate_resume_and_progress_only_proof",
                path="tests/test_flowpilot_shadow_launcher_chaos_replay.py",
                command="python -m pytest tests/test_flowpilot_shadow_launcher_chaos_replay.py",
                test_kind=EDGE,
                covers=("router_loop.shadow_launcher_chaos_regression",),
            ),
            _evidence(
                "router_loop.shadow_launcher.negative.bad_packages",
                test_name="test_malformed_fake_ai_package_generator_rejects_finite_bad_classes",
                path="tests/test_flowpilot_shadow_launcher_chaos_replay.py",
                command="python -m pytest tests/test_flowpilot_shadow_launcher_chaos_replay.py",
                test_kind=NEGATIVE,
                covers=("router_loop.shadow_launcher_chaos_regression",),
            ),
            _evidence(
                "router_loop.historical_live_run.happy.package_matrix",
                test_name="test_historical_live_run_rows_cover_required_surfaces",
                path="tests/test_flowpilot_historical_live_run_replay_matrix.py",
                command="python -m pytest tests/test_flowpilot_historical_live_run_replay_matrix.py",
                test_kind=HAPPY,
                covers=("router_loop.historical_live_run_replay_package_suite",),
            ),
            _evidence(
                "router_loop.historical_live_run.edge.snapshot_background_lifecycle",
                test_name="test_historical_snapshot_and_background_packages_reject_stale_or_incomplete_evidence",
                path="tests/test_flowpilot_historical_live_run_replay.py",
                command="python -m pytest tests/test_flowpilot_historical_live_run_replay.py",
                test_kind=EDGE,
                covers=("router_loop.historical_live_run_replay_package_suite",),
            ),
            _evidence(
                "router_loop.historical_live_run.negative.relay_semantic_overclaim",
                test_name="test_relay_lifecycle_and_semantic_contract_packages_block_overclaims",
                path="tests/test_flowpilot_historical_live_run_replay.py",
                command="python -m pytest tests/test_flowpilot_historical_live_run_replay.py",
                test_kind=NEGATIVE,
                covers=("router_loop.historical_live_run_replay_package_suite",),
            ),
            _evidence(
                "router_loop.known_friction.happy.matrix",
                test_name="test_known_friction_rows_cover_required_historical_failures",
                path="tests/test_flowpilot_known_friction_regression_matrix.py",
                command="python -m unittest tests.test_flowpilot_known_friction_regression_matrix",
                test_kind=HAPPY,
                covers=("router_loop.known_friction_regression_gate",),
            ),
            _evidence(
                "router_loop.known_friction.negative.known_bad",
                test_name="test_known_bad_cases_are_rejected",
                path="tests/test_flowpilot_known_friction_regression_matrix.py",
                command="python -m unittest tests.test_flowpilot_known_friction_regression_matrix",
                test_kind=NEGATIVE,
                covers=("router_loop.known_friction_regression_gate",),
            ),
            _evidence(
                "router_loop.package_disposition_repair_owned_replay.edge.role_output",
                test_name="test_repair_owned_package_disposition_conflict_replay_is_quarantined_without_daemon_error",
                path="tests/test_flowpilot_role_output_reconciliation.py",
                command="python -m pytest tests/test_flowpilot_role_output_reconciliation.py -k package_disposition_conflict",
                test_kind=EDGE,
                covers=("router_loop.package_disposition_repair_owned_role_output_replay",),
            ),
            _evidence(
                "router_loop.package_disposition_repair_owned_replay.edge.daemon_tick",
                test_name="test_daemon_tick_quarantines_repair_owned_package_conflict_without_erasing_wait",
                path="tests/test_flowpilot_role_output_reconciliation.py",
                command="python -m pytest tests/test_flowpilot_role_output_reconciliation.py -k package_disposition_conflict",
                test_kind=EDGE,
                covers=("router_loop.package_disposition_repair_owned_daemon_replay",),
            ),
            _evidence(
                "router_loop.package_disposition_repair_owned_replay.negative.classifier",
                test_name="test_pm_package_disposition_conflict_classifier_marks_repair_owned_replay",
                path="tests/test_flowpilot_control_plane_contracts.py",
                command="python -m pytest tests/test_flowpilot_control_plane_contracts.py -k pm_package_disposition",
                test_kind=NEGATIVE,
                covers=(
                    "router_loop.package_disposition_repair_owned_role_output_replay",
                    "router_loop.package_disposition_repair_owned_daemon_replay",
                ),
            ),
            _evidence(
                "daemon.happy.formal_startup",
                test_name="test_formal_startup_starts_router_daemon_before_controller_core",
                path="tests/router_runtime/startup_bootstrap.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_startup_daemon",
                test_kind=HAPPY,
                covers=("daemon.lock_status_and_queue_progress",),
            ),
            _evidence(
                "daemon.edge.fresh_lock_wait",
                test_name="test_router_daemon_waits_on_fresh_scheduler_write_lock_before_error",
                path="tests/router_runtime/startup_daemon.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_startup_daemon",
                test_kind=EDGE,
                covers=("daemon.lock_status_and_queue_progress",),
            ),
            _evidence(
                "daemon.happy.thin_child_mesh",
                test_name="test_daemon_child_reports_are_thin_and_green",
                path="tests/test_flowpilot_daemon_child_mesh.py",
                command="python -m unittest tests.test_flowpilot_daemon_child_mesh",
                test_kind=HAPPY,
                covers=("daemon.parent_child_mesh",),
            ),
            _evidence(
                "daemon.negative.parent_no_longer_consumes_large_compat_model",
                test_name="test_parent_ledger_consumes_split_daemon_children_not_large_compat_model",
                path="tests/test_flowpilot_daemon_child_mesh.py",
                command="python -m unittest tests.test_flowpilot_daemon_child_mesh",
                test_kind=NEGATIVE,
                covers=("daemon.parent_child_mesh",),
            ),
        ),
    )

    repair_transactions = ModelTestAlignmentPlan(
        model_id="repair_transactions",
        obligations=(
            _obligation(
                "repair_transactions.executable_plan_required",
                obligation_type="invariant",
                description="A committed PM repair transaction has a concrete queued action, existing producer, Router handler, fresh packet generation, or terminal stop.",
                required_test_kinds=(HAPPY, NEGATIVE),
            ),
            _obligation(
                "repair_transactions.material_rework_requires_fresh_producer",
                obligation_type="hazard",
                description="Material-dispatch repair cannot commit a role reissue or existing-event wait that only observes stale worker result flags instead of producing fresh repair work.",
                required_test_kinds=(NEGATIVE,),
            ),
            _obligation(
                "repair_transactions.legacy_replay_requires_existing_producer",
                obligation_type="hazard",
                description="A repair transaction cannot replay a legacy event unless the current run has a matching existing producer for that event.",
                required_test_kinds=(NEGATIVE,),
            ),
            _obligation(
                "repair_transactions.empty_transaction_returns_to_pm_repair",
                obligation_type="contract",
                description="An empty delivered repair transaction falls back to the PM repair-decision wait instead of being counted as executable repair work.",
                required_test_kinds=(NEGATIVE,),
            ),
            _obligation(
                "repair_transactions.pm_decision_flag_atomicity",
                obligation_type="hazard",
                description="A PM repair decision makes its required flag visible before daemon-readable post-decision wait events are exposed.",
                required_test_kinds=(EDGE,),
            ),
            _obligation(
                "repair_transactions.multiround_fake_ai_no_producer_recovery",
                obligation_type="scenario",
                description="Prepared fake AI replay rejects a no-producer PM repair and then accepts a corrected packet reissue with current producer evidence.",
                required_test_kinds=(HAPPY, NEGATIVE),
            ),
        ),
        test_evidence=(
            _evidence(
                "repair_transactions.happy.material_packet_reissue",
                test_name="test_pm_repair_transaction_commits_material_reissue_generation",
                path="tests/router_runtime/material_modeling.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_material_modeling",
                test_kind=HAPPY,
                covers=("repair_transactions.executable_plan_required",),
            ),
            _evidence(
                "repair_transactions.negative.material_role_reissue_no_producer",
                test_name="test_pm_material_repair_rejects_role_reissue_without_fresh_packet_producer",
                path="tests/router_runtime/material_modeling.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_material_modeling",
                test_kind=NEGATIVE,
                covers=("repair_transactions.material_rework_requires_fresh_producer",),
            ),
            _evidence(
                "repair_transactions.negative.legacy_replay_no_producer",
                test_name="test_pm_repair_decision_rejects_legacy_event_replay_without_existing_producer",
                path="tests/router_runtime/control_blockers.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_control_blockers",
                test_kind=NEGATIVE,
                covers=("repair_transactions.legacy_replay_requires_existing_producer",),
            ),
            _evidence(
                "repair_transactions.negative.empty_followup_wait_fallback",
                test_name="test_delivered_control_blocker_with_empty_repair_transaction_falls_back_to_pm_repair_decision",
                path="tests/router_runtime/control_blockers.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_control_blockers",
                test_kind=NEGATIVE,
                covers=(
                    "repair_transactions.executable_plan_required",
                    "repair_transactions.empty_transaction_returns_to_pm_repair",
                ),
            ),
            _evidence(
                "repair_transactions.edge.pm_decision_side_effect_atomicity",
                test_name="test_pm_repair_decision_side_effect_exposes_flag_before_wait_events",
                path="tests/router_runtime/material_modeling.py",
                command="python -m unittest tests.test_flowpilot_router_runtime_material_modeling",
                test_kind=EDGE,
                covers=("repair_transactions.pm_decision_flag_atomicity",),
            ),
            _evidence(
                "repair_transactions.e2e.no_producer_then_packet_reissue",
                test_name="test_e2e_no_producer_pm_repair_then_packet_reissue_exposes_producer_evidence",
                path="tests/test_flowpilot_e2e_synthetic_chaos_replay.py",
                command="python -m unittest tests.test_flowpilot_e2e_synthetic_chaos_replay.FlowPilotEndToEndSyntheticChaosReplayTests.test_e2e_no_producer_pm_repair_then_packet_reissue_exposes_producer_evidence",
                test_kind=HAPPY,
                covers=("repair_transactions.multiround_fake_ai_no_producer_recovery",),
            ),
            _evidence(
                "repair_transactions.real_router.producer_proof_recovery",
                test_name="test_real_router_repair_rehearsal_rejects_no_producer_then_accepts_packet_reissue",
                path="tests/test_flowpilot_real_router_dry_run_rehearsal.py",
                command="python -m unittest tests.test_flowpilot_real_router_dry_run_rehearsal.FlowPilotRealRouterDryRunRehearsalTests.test_real_router_repair_rehearsal_rejects_no_producer_then_accepts_packet_reissue",
                test_kind=NEGATIVE,
                covers=("repair_transactions.multiround_fake_ai_no_producer_recovery",),
            ),
        ),
    )

    tiering = ModelTestAlignmentPlan(
        model_id="test_tiering_slow_contracts",
        obligations=(
            _obligation(
                "test_tiering.foreground_fast_scope",
                obligation_type="contract",
                description="Fast/router tiers are scoped, foreground-safe, and exclude release-only, coverage sweep, and legacy full regressions.",
                required_test_kinds=(HAPPY, NEGATIVE),
            ),
            _obligation(
                "test_tiering.background_artifact_contract",
                obligation_type="hazard",
                description="Background validation needs final out/err/combined/exit/meta artifacts; progress lines alone are not pass evidence.",
                required_test_kinds=(NEGATIVE,),
            ),
            _obligation(
                "slow_test.parent_child_contracts",
                obligation_type="contract",
                description="Slow-test parents declare child owners and I/O contracts and do not replay child internals as parent proof.",
                required_test_kinds=(HAPPY, NEGATIVE),
            ),
        ),
        test_evidence=(
            _evidence(
                "tiering.happy.fast_scope",
                test_name="test_fast_tier_excludes_release_coverage_and_legacy_full",
                path="tests/test_flowpilot_test_tiers.py",
                command="python -m unittest tests.test_flowpilot_test_tiers",
                test_kind=HAPPY,
                covers=("test_tiering.foreground_fast_scope",),
            ),
            _evidence(
                "tiering.negative.release_exclusion",
                test_name="test_fast_and_router_tiers_do_not_contain_release_only_commands",
                path="tests/test_flowpilot_test_tiers.py",
                command="python -m unittest tests.test_flowpilot_test_tiers",
                test_kind=NEGATIVE,
                covers=("test_tiering.foreground_fast_scope",),
            ),
            _evidence(
                "tiering.negative.progress_only",
                test_name="test_tiering_flowguard_model_rejects_known_bad_hazards",
                path="tests/test_flowpilot_test_tiers.py",
                command="python -m unittest tests.test_flowpilot_test_tiers.FlowPilotTestTierTests.test_tiering_flowguard_model_rejects_known_bad_hazards",
                test_kind=NEGATIVE,
                covers=("test_tiering.background_artifact_contract",),
            ),
            _evidence(
                "slow_contract.happy.valid_contracts",
                test_name="test_slow_test_contract_flowguard_model_rejects_parent_child_hazards",
                path="tests/test_flowpilot_test_tiers.py",
                command="python -m unittest tests.test_flowpilot_test_tiers.FlowPilotTestTierTests.test_slow_test_contract_flowguard_model_rejects_parent_child_hazards",
                test_kind=HAPPY,
                covers=("slow_test.parent_child_contracts",),
            ),
            _evidence(
                "slow_contract.negative.parent_child_hazards",
                test_name="test_slow_test_contract_flowguard_model_rejects_parent_child_hazards",
                path="tests/test_flowpilot_test_tiers.py",
                command="python -m unittest tests.test_flowpilot_test_tiers.FlowPilotTestTierTests.test_slow_test_contract_flowguard_model_rejects_parent_child_hazards",
                test_kind=NEGATIVE,
                covers=("slow_test.parent_child_contracts",),
            ),
        ),
    )

    meta_capability = ModelTestAlignmentPlan(
        model_id="meta_capability_parents",
        obligations=(
            _obligation(
                "meta_parent.thin_default_and_layered_full_boundary",
                obligation_type="contract",
                description="Meta parent routine evidence uses thin-parent proof by default and layered full proof only when explicitly requested.",
                required_test_kinds=(HAPPY, NEGATIVE),
            ),
            _obligation(
                "capability_parent.proof_reuse_and_fast_boundary",
                obligation_type="contract",
                description="Capability parent evidence rejects stale proof reuse and keeps fast smoke on the non-legacy path.",
                required_test_kinds=(HAPPY, NEGATIVE),
            ),
            _obligation(
                "parents.abstract_not_ordinary_conformance",
                obligation_type="invariant",
                description="Meta/Capability parent model evidence stays bounded as abstract model-hierarchy confidence, not ordinary production conformance.",
                required_test_kinds=(EDGE,),
            ),
        ),
        test_evidence=(
            _evidence(
                "meta_parent.happy.thin_default",
                test_name="test_default_meta_runner_uses_thin_parent_without_full_graph",
                path="tests/test_flowpilot_thin_parent_checks.py",
                command="python -m unittest tests.test_flowpilot_thin_parent_checks",
                test_kind=HAPPY,
                covers=("meta_parent.thin_default_and_layered_full_boundary",),
            ),
            _evidence(
                "meta_parent.negative.legacy_explicit_only",
                test_name="test_legacy_full_meta_runner_preserves_monolithic_path",
                path="tests/test_flowpilot_thin_parent_checks.py",
                command="python -m unittest tests.test_flowpilot_thin_parent_checks",
                test_kind=NEGATIVE,
                covers=("meta_parent.thin_default_and_layered_full_boundary",),
            ),
            _evidence(
                "capability_parent.happy.proof_reuse_guard",
                test_name="test_capability_result_proof_rejects_stale_reuse",
                path="tests/test_flowguard_result_proof.py",
                command="python -m unittest tests.test_flowguard_result_proof",
                test_kind=HAPPY,
                covers=("capability_parent.proof_reuse_and_fast_boundary",),
            ),
            _evidence(
                "capability_parent.negative.fast_smoke_no_legacy",
                test_name="test_smoke_fast_only_marks_slow_model_checks_fast",
                path="tests/test_flowguard_result_proof.py",
                command="python -m unittest tests.test_flowguard_result_proof",
                test_kind=NEGATIVE,
                covers=("capability_parent.proof_reuse_and_fast_boundary",),
            ),
            _evidence(
                "parents.edge.control_gate_unit_checks",
                test_name="FlowPilotControlGateTests meta/capability invariant checks",
                path="tests/test_flowpilot_control_gates.py",
                command="python -m unittest tests.test_flowpilot_control_gates",
                test_kind=EDGE,
                covers=("parents.abstract_not_ordinary_conformance",),
            ),
        ),
    )

    return [
        _plan_entry(
            "startup",
            startup,
            model_checks=(
                "python simulations/run_flowpilot_startup_control_checks.py",
                "python simulations/run_flowpilot_deterministic_startup_bootstrap_checks.py",
            ),
            coverage_boundary="Startup alignment covers ordinary runtime and unit tests for the startup gate. It does not rerun UI smoke or long parent graphs.",
        ),
        _plan_entry(
            "packet/card/ack",
            packet_card_ack,
            model_checks=(
                "python simulations/run_flowpilot_packet_lifecycle_checks.py",
                "python simulations/run_flowpilot_card_envelope_checks.py",
                "python simulations/run_flowpilot_event_contract_checks.py",
                "python skills/flowpilot/assets/run_packet_control_plane_checks.py",
            ),
            coverage_boundary="Packet/card/ACK alignment covers mechanical handoff, identity, hash, receipt, and ACK/return hazards. It does not treat ACK as semantic role approval.",
        ),
        _plan_entry(
            "route mutation",
            route_mutation,
            model_checks=("python simulations/run_flowpilot_route_mutation_activation_checks.py",),
            coverage_boundary="Route-mutation alignment covers activation preconditions, sibling replacement, stale evidence, and route-sign projection for ordinary tests.",
        ),
        _plan_entry(
            "terminal/closure/resume",
            terminal_closure_resume,
            model_checks=(
                "python simulations/run_flowpilot_runtime_closure_checks.py",
                "python simulations/run_flowpilot_recursive_closure_reconciliation_checks.py",
                "python simulations/run_flowpilot_resume_checks.py",
            ),
            coverage_boundary="Terminal, closure, and resume alignment covers runtime tests for ledger closure and re-entry. It is not a production replay adapter.",
        ),
        _plan_entry(
            "role/output contracts",
            role_output,
            model_checks=(
                "python simulations/run_output_contract_checks.py",
                "python simulations/run_flowpilot_role_output_runtime_checks.py",
            ),
            coverage_boundary="Role/output alignment covers mechanical role-output and packet-output contracts. It does not judge task semantic quality.",
        ),
        _plan_entry(
            "router loop/daemon",
            router_loop_daemon,
            model_checks=(
                "python simulations/run_flowpilot_router_loop_checks.py",
                "python simulations/run_flowpilot_persistent_router_daemon_checks.py",
                "python simulations/run_flowpilot_daemon_startup_lock_checks.py",
                "python simulations/run_flowpilot_daemon_controller_actions_checks.py",
                "python simulations/run_flowpilot_daemon_wait_liveness_checks.py",
                "python simulations/run_flowpilot_daemon_terminal_projection_checks.py",
            ),
            coverage_boundary="Router-loop/daemon alignment covers foreground unit/runtime tests for queue, lock, and packet-loop behavior. It does not run long daemon soak tests.",
        ),
        _plan_entry(
            "repair transactions",
            repair_transactions,
            model_checks=("python simulations/run_flowpilot_repair_transaction_checks.py",),
            coverage_boundary="Repair-transaction alignment covers executable producer/action/handler/stop evidence and focused material-dispatch stale-wait regressions. It does not prove semantic quality of replacement packet contents.",
        ),
        _plan_entry(
            "test tiering/slow-test contracts",
            tiering,
            model_checks=(
                "python simulations/run_flowpilot_test_tiering_checks.py",
                "python simulations/run_flowpilot_slow_test_contract_checks.py",
            ),
            coverage_boundary="Test-tiering alignment covers test-plan mechanics and slow-test parent/child contracts, including progress-only background hazards.",
        ),
        _plan_entry(
            "meta/capability parents",
            meta_capability,
            model_checks=(
                "python simulations/run_meta_checks.py",
                "python simulations/run_capability_checks.py",
                "python simulations/run_meta_checks.py --full --fast",
                "python simulations/run_capability_checks.py --full --fast",
            ),
            coverage_boundary="Meta/Capability alignment covers parent-runner proof boundaries and control-gate unit evidence only. Parent results remain abstract model confidence, not ordinary production conformance.",
        ),
    ]
