"""FlowGuard TestMesh and model-test alignment plans for complete FlowPilot."""

from __future__ import annotations

from flowguard import (
    CodeContract,
    ModelObligation,
    ModelTestAlignmentPlan,
    TestEvidence,
    TestMeshPlan,
    TestPartitionItem,
    TestSuiteEvidence,
    TestTargetSplitDerivation,
)


TESTMESH_ID = "flowpilot_complete_system_testmesh"
ALIGNMENT_ID = "flowpilot_complete_system_alignment"


def build_testmesh_plan(*, release_evidence: bool = False, live_host_evidence: bool = False) -> TestMeshPlan:
    items = (
        TestPartitionItem("openspec_contract", "contract", "openspec", "child", "Complete-system OpenSpec validation."),
        TestPartitionItem("development_model", "model", "development_model", "child", "Development-process FlowGuard model."),
        TestPartitionItem("structure_model", "model", "structure_model", "child", "Code-structure recommendation model."),
        TestPartitionItem("ui_model", "model", "ui_model", "child", "UI-flow and Cockpit journey model."),
        TestPartitionItem("runtime_unit", "behavior", "runtime_unit", "child", "Complete runtime unit coverage."),
        TestPartitionItem("fake_agent_chaos", "chaos", "fake_agent_chaos", "child", "Multiround fake-agent and chaos coverage."),
        TestPartitionItem("historical_replay", "historical", "historical_replay", "child", "Historical known-bad replay."),
        TestPartitionItem("background_meta_capability", "release", "background_meta_capability", "child", "Meta/Capability background regressions."),
        TestPartitionItem("install_sync", "release", "install_sync", "child", "Installed skill parity checks."),
        TestPartitionItem("live_host", "live", "live_host", "child", "Real host-agent live evidence boundary."),
    )
    child_suites = (
        TestSuiteEvidence(
            "openspec",
            command="openspec validate complete-black-box-flowpilot-system --strict",
            result_status="passed",
            evidence_tier="external_contract",
            test_count=1,
            exit_code=0,
            result_path="openspec/changes/complete-black-box-flowpilot-system",
        ),
        TestSuiteEvidence(
            "development_model",
            command="python simulations/run_flowpilot_complete_system_development_checks.py",
            result_status="passed",
            evidence_tier="executable_flowguard",
            test_count=3,
            exit_code=0,
            result_path="simulations/flowpilot_complete_system_development_results.json",
        ),
        TestSuiteEvidence(
            "structure_model",
            command="python simulations/run_flowpilot_complete_system_structure_checks.py",
            result_status="passed",
            evidence_tier="flowguard_recommendation",
            test_count=2,
            exit_code=0,
            result_path="simulations/flowpilot_complete_system_structure_results.json",
        ),
        TestSuiteEvidence(
            "ui_model",
            command="python simulations/run_flowpilot_complete_system_ui_checks.py",
            result_status="passed",
            evidence_tier="flowguard_ui_model",
            test_count=3,
            exit_code=0,
            result_path="simulations/flowpilot_complete_system_ui_results.json",
        ),
        TestSuiteEvidence(
            "runtime_unit",
            command="python -m pytest tests/test_flowpilot_complete_system_runtime.py",
            result_status="passed" if release_evidence else "not_run",
            evidence_tier="external_contract" if release_evidence else "candidate_only",
            test_count=1 if release_evidence else 0,
            exit_code=0 if release_evidence else None,
            result_path="tests/test_flowpilot_complete_system_runtime.py" if release_evidence else "",
            release_required=True,
            not_run_reason="" if release_evidence else "runtime implementation tests are added in the next phase",
        ),
        TestSuiteEvidence(
            "fake_agent_chaos",
            command="python simulations/run_flowpilot_complete_system_runtime_checks.py",
            result_status="passed" if release_evidence else "not_run",
            evidence_tier="external_contract" if release_evidence else "candidate_only",
            test_count=1 if release_evidence else 0,
            exit_code=0 if release_evidence else None,
            result_path="simulations/flowpilot_complete_system_runtime_results.json" if release_evidence else "",
            release_required=True,
            not_run_reason="" if release_evidence else "full fake-agent runtime scenarios are added in the next phase",
        ),
        TestSuiteEvidence(
            "historical_replay",
            command="python simulations/run_flowpilot_complete_system_historical_replay_checks.py",
            result_status="passed" if release_evidence else "not_run",
            evidence_tier="external_contract" if release_evidence else "candidate_only",
            test_count=1 if release_evidence else 0,
            exit_code=0 if release_evidence else None,
            result_path="simulations/flowpilot_complete_system_historical_replay_results.json" if release_evidence else "",
            release_required=True,
            not_run_reason="" if release_evidence else "historical replay is required before full-system confidence",
        ),
        TestSuiteEvidence(
            "background_meta_capability",
            command="python simulations/run_meta_checks.py; python simulations/run_capability_checks.py",
            result_status="passed" if release_evidence else "not_run",
            evidence_tier="external_contract" if release_evidence else "candidate_only",
            test_count=2 if release_evidence else 0,
            exit_code=0 if release_evidence else None,
            result_path="tmp/flowguard_background/run_meta_checks.*; tmp/flowguard_background/run_capability_checks.*" if release_evidence else "",
            log_root="tmp/flowguard_background",
            background=True,
            release_required=True,
            not_run_reason="" if release_evidence else "background release regressions must be inspected later",
        ),
        TestSuiteEvidence(
            "install_sync",
            command="python scripts/install_flowpilot.py --sync-repo-owned --skip-self-check --json; python scripts/audit_local_install_sync.py --json; python scripts/install_flowpilot.py --check --json",
            result_status="passed" if release_evidence else "not_run",
            evidence_tier="external_contract" if release_evidence else "candidate_only",
            test_count=3 if release_evidence else 0,
            exit_code=0 if release_evidence else None,
            result_path="local installed skill parity" if release_evidence else "",
            release_required=True,
            not_run_reason="" if release_evidence else "install sync/check must run after code changes",
        ),
        TestSuiteEvidence(
            "live_host",
            command="python simulations/run_flowpilot_complete_system_live_host_readiness_checks.py",
            result_status="passed" if live_host_evidence else "not_run",
            evidence_tier="external_contract" if live_host_evidence else "candidate_only",
            test_count=1 if live_host_evidence else 0,
            exit_code=0 if live_host_evidence else None,
            result_path="simulations/flowpilot_complete_system_live_host_results.json" if live_host_evidence else "",
            release_required=True,
            not_run_reason="" if live_host_evidence else "real host-agent evidence is not yet available",
        ),
    )
    return TestMeshPlan(
        parent_suite_id=TESTMESH_ID,
        partition_items=items,
        child_suites=child_suites,
        target_split_derivation=TestTargetSplitDerivation(
            source_model_id="flowpilot_complete_system_development_process",
            source_model_path="simulations/flowpilot_complete_system_development_model.py",
            target_suite_ids=tuple(suite.suite_id for suite in child_suites),
            covered_partition_item_ids=tuple(item.item_id for item in items),
            state_owner_fields=("routine", "release", "live_host"),
            side_effect_owner_fields=("install_sync", "background_logs", "host_agents"),
            rationale="Complete-system validation is split by evidence freshness and confidence boundary.",
            derived_from_flowguard_model=True,
        ),
        required_evidence_tier="external_contract",
        decision_scope="routine",
        release_deferred_allowed=True,
    )


def build_alignment_plan(*, implementation_evidence: bool = False) -> ModelTestAlignmentPlan:
    obligations = (
        ModelObligation(
            "current_run_shell_persistence",
            description="A new run creates .flowpilot/current.json, index.json, run ledger, event log, and projection artifacts without trusting old state.",
            required_test_kinds=("scenario", "boundary"),
            risk_level="high",
            external_inputs=("goal", "acceptance_contract", "old_state"),
            external_outputs=("current_pointer", "run_ledger", "event_log"),
            state_writes=(".flowpilot/current.json", ".flowpilot/index.json", ".flowpilot/runs/<run-id>/ledger.json"),
            exact_external_contract=True,
        ),
        ModelObligation(
            "startup_intake_sealed_authority",
            description="Startup intake is consumed only as a confirmed sealed body/hash record copied into the current run.",
            required_test_kinds=("scenario", "boundary"),
            risk_level="high",
            external_inputs=("startup_intake_result", "startup_body"),
            external_outputs=("current_run_startup_record", "body_hash_match", "sealed_controller_boundary"),
            state_writes=("ledger.startup_intake", ".flowpilot/runs/<run-id>/startup_intake"),
            exact_external_contract=True,
        ),
        ModelObligation(
            "ledger_authority",
            description="Current-run ledger is the only authority for completion.",
            required_test_kinds=("scenario", "boundary"),
            risk_level="high",
            external_inputs=("chat_claim", "old_state", "current_ledger"),
            external_outputs=("incomplete", "complete"),
            state_writes=("ledger.closure",),
            exact_external_contract=True,
        ),
        ModelObligation(
            "dynamic_lease_lifecycle",
            description="Dynamic responsibility leases expire, close, replace, and quarantine late output.",
            required_test_kinds=("scenario", "same_class"),
            risk_level="high",
            external_inputs=("lease_event", "result_submission"),
            external_outputs=("accepted", "quarantined", "replace_lease"),
            state_writes=("ledger.leases", "ledger.results"),
            requires_same_class_test_evidence=True,
        ),
        ModelObligation(
            "flowguard_target_scheduler",
            description="FlowGuard reports satisfy gates only when modeled target matches.",
            required_test_kinds=("scenario",),
            risk_level="high",
            external_inputs=("modeled_target", "flowguard_report"),
            external_outputs=("accepted_report", "blocked_report"),
            state_writes=("ledger.flowguard",),
            exact_external_contract=True,
        ),
        ModelObligation(
            "run_artifact_materialization",
            description="Packets, results, leases, FlowGuard orders, reviews, evidence, and status projections materialize under the current run.",
            required_test_kinds=("scenario", "boundary"),
            risk_level="high",
            external_inputs=("ledger_state",),
            external_outputs=("run_artifact_files", "public_status_projection"),
            state_writes=(".flowpilot/runs/<run-id>/packets", ".flowpilot/runs/<run-id>/flowguard", ".flowpilot/runs/<run-id>/reviews", ".flowpilot/runs/<run-id>/console/status.json"),
            exact_external_contract=True,
        ),
        ModelObligation(
            "cockpit_projection_only",
            description="Cockpit renders public projection and submits typed events only.",
            required_test_kinds=("ui", "boundary"),
            risk_level="high",
            external_inputs=("ui_event", "sealed_body"),
            external_outputs=("public_status", "blocked_direct_write"),
            state_writes=("ledger.user_events",),
            side_effects=("render_status",),
            exact_external_contract=True,
        ),
        ModelObligation(
            "full_evidence_gate",
            description="Full completion is blocked until routine, release, historical, install, background, and live boundaries are current.",
            required_test_kinds=("scenario", "release_gate"),
            risk_level="high",
            external_inputs=("evidence_rows",),
            external_outputs=("scoped_confidence", "full_confidence"),
            state_writes=("ledger.cutover_gate", "ledger.closure"),
            exact_external_contract=True,
        ),
    )
    code_contracts = (
        CodeContract(
            "run_shell_create_contract",
            path="skills/flowpilot/assets/flowpilot_core_runtime/run_shell.py",
            symbol="create_run_shell",
            implements_obligations=("current_run_shell_persistence",),
            external_inputs=("goal", "acceptance_contract", "old_state"),
            external_outputs=("current_pointer", "run_ledger", "event_log"),
            state_writes=(".flowpilot/current.json", ".flowpilot/index.json", ".flowpilot/runs/<run-id>/ledger.json"),
        ),
        CodeContract(
            "startup_intake_import_contract",
            path="skills/flowpilot/assets/flowpilot_core_runtime/run_shell.py",
            symbol="record_startup_intake_result",
            implements_obligations=("startup_intake_sealed_authority",),
            external_inputs=("startup_intake_result", "startup_body"),
            external_outputs=("current_run_startup_record", "body_hash_match", "sealed_controller_boundary"),
            state_writes=("ledger.startup_intake", ".flowpilot/runs/<run-id>/startup_intake"),
        ),
        CodeContract(
            "run_artifact_materialization_contract",
            path="skills/flowpilot/assets/flowpilot_core_runtime/run_shell.py",
            symbol="materialize_run_artifacts",
            implements_obligations=("run_artifact_materialization",),
            external_inputs=("ledger_state",),
            external_outputs=("run_artifact_files", "public_status_projection"),
            state_writes=(".flowpilot/runs/<run-id>/packets", ".flowpilot/runs/<run-id>/flowguard", ".flowpilot/runs/<run-id>/reviews", ".flowpilot/runs/<run-id>/console/status.json"),
        ),
        CodeContract(
            "runtime_ledger_contract",
            path="skills/flowpilot/assets/flowpilot_core_runtime/runtime.py",
            symbol="new_ledger",
            implements_obligations=("ledger_authority",),
            external_inputs=("chat_claim", "old_state", "current_ledger"),
            external_outputs=("incomplete", "complete"),
            state_writes=("ledger.closure",),
        ),
        CodeContract(
            "runtime_lease_contract",
            path="skills/flowpilot/assets/flowpilot_core_runtime/runtime.py",
            symbol="lease_agent",
            implements_obligations=("dynamic_lease_lifecycle",),
            external_inputs=("lease_event", "result_submission"),
            external_outputs=("accepted", "quarantined", "replace_lease"),
            state_writes=("ledger.leases", "ledger.results"),
        ),
        CodeContract(
            "runtime_flowguard_contract",
            path="skills/flowpilot/assets/flowpilot_core_runtime/runtime.py",
            symbol="create_flowguard_work_order",
            implements_obligations=("flowguard_target_scheduler",),
            external_inputs=("modeled_target", "flowguard_report"),
            external_outputs=("accepted_report", "blocked_report"),
            state_writes=("ledger.flowguard",),
        ),
        CodeContract(
            "runtime_console_contract",
            path="skills/flowpilot/assets/flowpilot_core_runtime/runtime.py",
            symbol="render_console",
            implements_obligations=("cockpit_projection_only",),
            external_inputs=("ui_event", "sealed_body"),
            external_outputs=("public_status", "blocked_direct_write"),
            state_writes=("ledger.user_events",),
            side_effects=("render_status",),
        ),
        CodeContract(
            "runtime_closure_contract",
            path="skills/flowpilot/assets/flowpilot_core_runtime/runtime.py",
            symbol="attempt_final_closure",
            implements_obligations=("full_evidence_gate",),
            external_inputs=("evidence_rows",),
            external_outputs=("scoped_confidence", "full_confidence"),
            state_writes=("ledger.cutover_gate", "ledger.closure"),
        ),
    )
    status = "passed" if implementation_evidence else "not_run"
    evidence_current = implementation_evidence
    test_evidence = [
        TestEvidence(
            "test_current_run_shell_persistence",
            test_name="test_run_shell_creates_current_run_authority_without_old_state",
            path="tests/test_flowpilot_complete_system_runtime.py",
            command="python -m pytest tests/test_flowpilot_complete_system_runtime.py",
            result_status="passed",
            evidence_current=True,
            test_kind="scenario",
            covered_obligations=("current_run_shell_persistence",),
            covered_code_contracts=("run_shell_create_contract",),
        ),
        TestEvidence(
            "test_current_run_shell_boundary",
            test_name="test_run_shell_creates_current_run_authority_without_old_state",
            path="tests/test_flowpilot_complete_system_runtime.py",
            command="python -m pytest tests/test_flowpilot_complete_system_runtime.py",
            result_status="passed",
            evidence_current=True,
            test_kind="boundary",
            covered_obligations=("current_run_shell_persistence",),
            covered_code_contracts=("run_shell_create_contract",),
        ),
        TestEvidence(
            "test_startup_intake_sealed_scenario",
            test_name="test_startup_intake_result_is_copied_as_current_run_sealed_evidence",
            path="tests/test_flowpilot_complete_system_runtime.py",
            command="python -m pytest tests/test_flowpilot_complete_system_runtime.py",
            result_status="passed",
            evidence_current=True,
            test_kind="scenario",
            covered_obligations=("startup_intake_sealed_authority",),
            covered_code_contracts=("startup_intake_import_contract",),
        ),
        TestEvidence(
            "test_startup_intake_sealed_authority",
            test_name="test_startup_intake_result_is_copied_as_current_run_sealed_evidence",
            path="tests/test_flowpilot_complete_system_runtime.py",
            command="python -m pytest tests/test_flowpilot_complete_system_runtime.py",
            result_status="passed",
            evidence_current=True,
            test_kind="boundary",
            covered_obligations=("startup_intake_sealed_authority",),
            covered_code_contracts=("startup_intake_import_contract",),
        ),
        TestEvidence(
            "test_run_artifact_materialization_boundary",
            test_name="test_current_run_save_materializes_sealed_envelopes_orders_reviews_and_status",
            path="tests/test_flowpilot_complete_system_runtime.py",
            command="python -m pytest tests/test_flowpilot_complete_system_runtime.py",
            result_status="passed",
            evidence_current=True,
            test_kind="boundary",
            covered_obligations=("run_artifact_materialization",),
            covered_code_contracts=("run_artifact_materialization_contract",),
        ),
        TestEvidence(
            "test_run_artifact_materialization",
            test_name="test_current_run_save_materializes_sealed_envelopes_orders_reviews_and_status",
            path="tests/test_flowpilot_complete_system_runtime.py",
            command="python -m pytest tests/test_flowpilot_complete_system_runtime.py",
            result_status="passed",
            evidence_current=True,
            test_kind="scenario",
            covered_obligations=("run_artifact_materialization", "cockpit_projection_only"),
            covered_code_contracts=("run_artifact_materialization_contract", "runtime_console_contract"),
        ),
        TestEvidence(
            "test_ledger_authority",
            test_name="test_router_closes_only_after_backward_chain_and_validation",
            path="tests/test_flowpilot_core_runtime.py",
            command="python -m pytest tests/test_flowpilot_core_runtime.py",
            result_status="passed",
            evidence_current=True,
            test_kind="scenario",
            covered_obligations=("ledger_authority", "full_evidence_gate"),
            covered_code_contracts=("runtime_ledger_contract", "runtime_closure_contract"),
        ),
        TestEvidence(
            "test_ledger_boundary",
            test_name="test_runtime_testmesh_does_not_overclaim_release_evidence",
            path="tests/test_flowpilot_core_runtime.py",
            command="python -m pytest tests/test_flowpilot_core_runtime.py",
            result_status="passed",
            evidence_current=True,
            test_kind="boundary",
            covered_obligations=("ledger_authority",),
            covered_code_contracts=("runtime_ledger_contract",),
        ),
        TestEvidence(
            "test_lease_scenario",
            test_name="test_ack_and_progress_do_not_complete_packet",
            path="tests/test_flowpilot_core_runtime.py",
            command="python -m pytest tests/test_flowpilot_core_runtime.py",
            result_status="passed",
            evidence_current=True,
            test_kind="scenario",
            covered_obligations=("dynamic_lease_lifecycle",),
            covered_code_contracts=("runtime_lease_contract",),
            closure_evidence_role="observed_regression",
        ),
        TestEvidence(
            "test_lease_lifecycle",
            test_name="test_replacement_worker_can_finish_but_closed_worker_late_output_is_blocked",
            path="tests/test_flowpilot_core_runtime.py",
            command="python -m pytest tests/test_flowpilot_core_runtime.py",
            result_status="passed",
            evidence_current=True,
            test_kind="same_class",
            covered_obligations=("dynamic_lease_lifecycle",),
            covered_code_contracts=("runtime_lease_contract",),
            closure_evidence_role="same_class_generalized",
        ),
        TestEvidence(
            "test_flowguard_target",
            test_name="test_wrong_flowguard_target_self_review_stale_route_and_stale_evidence_block",
            path="tests/test_flowpilot_core_runtime.py",
            command="python -m pytest tests/test_flowpilot_core_runtime.py",
            result_status="passed",
            evidence_current=True,
            test_kind="scenario",
            covered_obligations=("flowguard_target_scheduler",),
            covered_code_contracts=("runtime_flowguard_contract",),
        ),
        TestEvidence(
            "test_cockpit_projection",
            test_name="test_public_console_hides_sealed_bodies",
            path="tests/test_flowpilot_core_runtime.py",
            command="python -m pytest tests/test_flowpilot_core_runtime.py",
            result_status="passed",
            evidence_current=True,
            test_kind="ui",
            covered_obligations=("cockpit_projection_only",),
            covered_code_contracts=("runtime_console_contract",),
        ),
        TestEvidence(
            "test_cockpit_boundary",
            test_name="test_public_console_hides_sealed_bodies",
            path="tests/test_flowpilot_core_runtime.py",
            command="python -m pytest tests/test_flowpilot_core_runtime.py",
            result_status="passed",
            evidence_current=True,
            test_kind="boundary",
            covered_obligations=("cockpit_projection_only",),
            covered_code_contracts=("runtime_console_contract",),
        ),
        TestEvidence(
            "test_scoped_release_gate",
            test_name="test_runtime_testmesh_does_not_overclaim_release_evidence",
            path="tests/test_flowpilot_core_runtime.py",
            command="python -m pytest tests/test_flowpilot_core_runtime.py",
            result_status="passed",
            evidence_current=True,
            test_kind="release_gate",
            covered_obligations=("full_evidence_gate",),
            covered_code_contracts=("runtime_closure_contract",),
        ),
    ]
    return ModelTestAlignmentPlan(
        ALIGNMENT_ID,
        obligations=obligations,
        code_contracts=code_contracts,
        test_evidence=tuple(test_evidence),
        require_code_contracts=True,
        allow_orphan_tests=False,
        allow_orphan_code_contracts=False,
    )
