"""Router facade split target maps and known-bad hazards."""

from __future__ import annotations

ROUTER_FACADE_TARGET_RATIONALES = {
    "router_facade": "Keeps the executable router file as a small public skeleton with no behavior bodies.",
    "facade_exports": "Owns the registry resolver and installer for transitional internal lookups.",
    "facade_export_manifest": "Owns the explicit transitional owner-export registry that replaces hand-written wrappers.",
    "facade_export_manifest_actions": "Owns action-domain owner-export registry rows.",
    "facade_export_manifest_controller": "Owns controller-domain owner-export registry rows.",
    "facade_export_manifest_route": "Owns route-domain owner-export registry rows.",
    "facade_export_manifest_startup": "Owns startup-domain owner-export registry rows.",
    "facade_export_manifest_terminal_work": "Owns terminal and work-packet owner-export registry rows.",
    "cli": "Owns command parsing and CLI JSON/error envelope behavior.",
    "controller_runtime": "Owns the high-level next/apply/event controller loop entrypoints.",
    "artifact_validation": "Owns artifact validation and hash checks exposed through the CLI/API.",
    "control_transactions": "Owns control transaction registry validation and contract coverage.",
    "internal_actions": "Owns Router-internal mechanical action guards and consumption.",
    "role_output_bridge": "Owns role-output envelope bridge behavior and startup fact reconciliation.",
    "startup_support": "Owns startup run-state support and prompt manifest/card lookup helpers.",
    "lifecycle_support": "Owns heartbeat binding and lifecycle support helpers moved out of the skeleton.",
    "child_skill_capability": "Owns child-skill manifest approval and capability evidence sync.",
    "route_completion_support": "Owns active-node completion helper paths and resume predicates.",
    "model_gate_state": "Owns model gate alias flag sync and model-miss block checks.",
    "pm_role_followup": "Owns PM role-work follow-up validation for model-miss repair flows.",
    "proof_validation": "Owns router-owned proof validation.",
    "prompt_store": "Owns prompt manifest loading, template rendering, and prompt hash authority.",
    "prompt_delivery": "Owns prompt-backed delivery text used by cards, controller tables, and startup heartbeats.",
    "prompt_assets": "Owns external prompt asset files and install-time prompt freshness evidence.",
    "controller_ledger": "Owns controller ledger paths and scheduler projection helper contracts.",
    "card_delivery": "Owns card ledger read/write contract and delivery attempt identity helpers.",
    "card_returns": "Owns ACK return settlement and output-bearing work clearance rules.",
    "role_io_protocol": "Owns role I/O envelope protocol, injection receipts, and lifecycle hash authority.",
    "event_identity": "Owns event idempotency and scoped retry-budget behavior.",
    "daemon_runtime": "Owns daemon lock, status, and tick lifecycle helpers.",
    "process_liveness": "Owns the shared pid liveness probe used by lock owners without taking over lock-domain decisions.",
    "runtime_state": "Owns bootstrap and run-state factories plus persistence wrappers.",
    "protocol_catalog": "Owns router schemas, action catalogs, event metadata, gate contracts, and alias tables.",
    "startup_flow": "Groups startup owner-module binding without retaining action bodies.",
    "startup_bootloader": "Owns bootloader action ordering and daemon-control bootstrap behavior.",
    "startup_intake": "Owns startup answer validation, intake UI materialization, and bootstrap seed capture.",
    "startup_display": "Owns startup display plans, user-dialogue projection, and route-sign synchronization.",
    "startup_role_recovery": "Owns resume, role recovery, role spawn normalization, and continuation binding rehydration.",
    "startup_closure": "Owns startup closure reconciliation and heartbeat binding readiness checks.",
    "startup_fact_boundary": "Owns startup fact audit, controller-boundary confirmation, and mechanical-audit repair actions.",
    "controller_scheduler": "Owns controller scheduling, receipt reconciliation, standby, and patrol behavior.",
    "controller_scheduler_receipt_writes": "Owns Controller action and receipt write helpers.",
    "controller_scheduler_receipt_effects": "Owns Controller receipt postcondition effect helpers.",
    "controller_scheduler_receipt_pending": "Owns pending Controller action receipt reconciliation helpers.",
    "controller_scheduler_receipt_scheduled": "Owns scheduled Controller action reconciliation and scheduler backfill helpers.",
    "controller_repair": "Owns controller deliverable repair, postcondition reclaim, and mail-delivery folding.",
    "action_factory": "Owns action envelope construction and dispatch-recipient gate policy.",
    "action_factory_reconciliation": "Owns scope reconciliation wait and ACK preflight helpers.",
    "action_factory_dispatch": "Owns dispatch-recipient gate and blocker helpers.",
    "action_factory_envelope": "Owns final action envelope construction and Controller user-reporting policy.",
    "work_packets": "Owns material, research, current-node, and PM role-work packet flow.",
    "pm_role_work_gates": "Owns PM role-work gate mapping and targeted result contract helpers.",
    "pm_role_work_writes": "Owns PM role-work request, result, and disposition writes.",
    "pm_role_work_lifecycle": "Owns PM role-work request indexes and officer lifecycle records.",
    "pm_role_work_actions": "Owns PM role-work next-action selection and result reconciliation.",
    "route_artifacts": "Owns PM route, product, node-acceptance, and evidence artifact writes.",
    "events_repair": "Owns control blockers, repair transactions, and gate-decision validation.",
    "lifecycle_requests": "Owns run lifecycle requests, protocol dead-end records, and exception blocker routing.",
    "event_dispatcher": "Owns external event dispatch routing and event-finalizer delegation.",
    "system_cards": "Owns system-card action selection, bundle delivery, and direct ACK tokens.",
    "expected_waits": "Owns expected role waits, pending event grouping, and stale-wait reconciliation.",
    "route_frontier": "Owns route/frontier projection and node-completion lifecycle.",
    "payload_contracts": "Owns payload contract builder helpers for startup, PM, display, and terminal actions.",
    "self_interrogation": "Owns self-interrogation status, issue, and PM suggestion cleanliness helpers.",
    "terminal_ledger": "Owns terminal ledger, replay, closure, and reconciliation outputs.",
    "terminal_ledger_summary": "Owns terminal summary validation and writes.",
    "terminal_ledger_traceability": "Owns final ledger traceability and source-of-truth entries.",
    "terminal_ledger_closure": "Owns terminal backward replay and closure suite writes.",
    "terminal_ledger_recovery": "Owns terminal status recovery and legacy packet repair.",
}


ROUTER_FACADE_FUNCTION_BLOCK_MAP = (
    ("public_api_allowlist", "router_facade"),
    ("owner_export_registry", "facade_export_manifest"),
    ("owner_export_manifest_actions", "facade_export_manifest_actions"),
    ("owner_export_manifest_controller", "facade_export_manifest_controller"),
    ("owner_export_manifest_route", "facade_export_manifest_route"),
    ("owner_export_manifest_startup", "facade_export_manifest_startup"),
    ("owner_export_manifest_terminal_work", "facade_export_manifest_terminal_work"),
    ("owner_export_installer", "facade_exports"),
    ("parse_args", "cli"),
    ("main", "cli"),
    ("next_action", "controller_runtime"),
    ("apply_action", "controller_runtime"),
    ("apply_controller_action", "controller_runtime"),
    ("record_external_event", "controller_runtime"),
    ("run_until_wait", "controller_runtime"),
    ("validate_artifact", "artifact_validation"),
    ("control_transaction_registry", "control_transactions"),
    ("router_internal_mechanical_actions", "internal_actions"),
    ("role_output_bridge", "role_output_bridge"),
    ("startup_support", "startup_support"),
    ("lifecycle_support", "lifecycle_support"),
    ("child_skill_capability", "child_skill_capability"),
    ("route_completion_support", "route_completion_support"),
    ("model_gate_state", "model_gate_state"),
    ("pm_role_followup", "pm_role_followup"),
    ("proof_validation", "proof_validation"),
    ("prompt_manifest_loading", "prompt_store"),
    ("card_post_ack_policy", "prompt_delivery"),
    ("controller_table_prompt", "prompt_delivery"),
    ("startup_heartbeat_prompt", "prompt_delivery"),
    ("packet_identity_prompt", "prompt_assets"),
    ("packet_result_identity_prompt", "prompt_assets"),
    ("packet_output_contract_prompt", "prompt_assets"),
    ("controller_ledger_paths", "controller_ledger"),
    ("router_scheduler_projection", "controller_ledger"),
    ("card_delivery_ledgers", "card_delivery"),
    ("card_return_settlement", "card_returns"),
    ("role_io_protocol", "role_io_protocol"),
    ("event_identity", "event_identity"),
    ("daemon_runtime", "daemon_runtime"),
    ("process_liveness_probe", "process_liveness"),
    ("runtime_state", "runtime_state"),
    ("_public_gate_contract", "protocol_catalog"),
    ("_gate_contract_for_id", "protocol_catalog"),
    ("_gate_contract_for_card", "protocol_catalog"),
    ("_gate_contract_for_event", "protocol_catalog"),
    ("_gate_completion_wait_group", "protocol_catalog"),
    ("startup_flow_group", "startup_flow"),
    ("startup_bootloader", "startup_bootloader"),
    ("startup_intake", "startup_intake"),
    ("startup_display", "startup_display"),
    ("startup_role_recovery", "startup_role_recovery"),
    ("startup_closure", "startup_closure"),
    ("startup_fact_boundary", "startup_fact_boundary"),
    ("self_interrogation", "self_interrogation"),
    ("payload_contracts", "payload_contracts"),
    ("controller_scheduler", "controller_scheduler"),
    ("controller_receipt_writes", "controller_scheduler_receipt_writes"),
    ("controller_receipt_effects", "controller_scheduler_receipt_effects"),
    ("controller_receipt_pending", "controller_scheduler_receipt_pending"),
    ("controller_receipt_scheduled", "controller_scheduler_receipt_scheduled"),
    ("controller_repair", "controller_repair"),
    ("action_factory", "action_factory"),
    ("action_factory_reconciliation", "action_factory_reconciliation"),
    ("action_factory_dispatch", "action_factory_dispatch"),
    ("action_factory_envelope", "action_factory_envelope"),
    ("work_packets", "work_packets"),
    ("pm_role_work_gates", "pm_role_work_gates"),
    ("pm_role_work_writes", "pm_role_work_writes"),
    ("pm_role_work_lifecycle", "pm_role_work_lifecycle"),
    ("pm_role_work_actions", "pm_role_work_actions"),
    ("route_artifacts", "route_artifacts"),
    ("events_repair", "events_repair"),
    ("lifecycle_requests", "lifecycle_requests"),
    ("event_dispatcher", "event_dispatcher"),
    ("system_cards", "system_cards"),
    ("expected_waits", "expected_waits"),
    ("route_frontier", "route_frontier"),
    ("terminal_ledger", "terminal_ledger"),
    ("terminal_ledger_summary", "terminal_ledger_summary"),
    ("terminal_ledger_traceability", "terminal_ledger_traceability"),
    ("terminal_ledger_closure", "terminal_ledger_closure"),
    ("terminal_ledger_recovery", "terminal_ledger_recovery"),
)


SPLIT_HAZARDS = (
    "micro_module_explosion",
    "one_function_file_split",
    "missing_coarse_phase_owner",
    "facade_line_budget_exceeded",
    "facade_function_budget_exceeded",
    "retained_obsolete_compat_wrapper",
    "owner_export_registry_missing",
    "missing_public_api_whitelist_entry",
    "missing_prompt_asset",
    "stale_prompt_hash",
    "unsafe_inline_prompt_fallback",
    "prompt_asset_not_installed",
    "undeclared_prompt_template_variables",
)
