"""Model StructureMesh catalog for FlowPilot maintenance."""

from __future__ import annotations

from flowguard import (
    EVIDENCE_ABSTRACT_GREEN,
    EVIDENCE_CONFORMANCE_GREEN,
    ModuleStructureEvidence,
    PublicEntrypointEvidence,
    StructurePartitionItem,
)

MODEL_PUBLIC_ENTRYPOINTS = (
    PublicEntrypointEvidence(
        "prompt_isolation_model_import",
        old_path="simulations/prompt_isolation_model.py",
        new_path="simulations/prompt_isolation_model.py",
        parity_evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        evidence_path="simulations/prompt_isolation_results.json",
        release_required=True,
    ),
    PublicEntrypointEvidence(
        "cross_plane_friction_model_import",
        old_path="simulations/flowpilot_cross_plane_friction_model.py",
        new_path="simulations/flowpilot_cross_plane_friction_model.py",
        parity_evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        evidence_path="simulations/flowpilot_cross_plane_friction_results.json",
        release_required=True,
    ),
    PublicEntrypointEvidence(
        "persistent_router_daemon_model_import",
        old_path="simulations/flowpilot_persistent_router_daemon_model.py",
        new_path="simulations/flowpilot_persistent_router_daemon_model.py",
        parity_evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        evidence_path="simulations/flowpilot_persistent_router_daemon_results.json",
        release_required=True,
    ),
    PublicEntrypointEvidence(
        "packet_control_plane_model_import",
        old_path="skills/flowpilot/assets/packet_control_plane_model.py",
        new_path="skills/flowpilot/assets/packet_control_plane_model.py",
        parity_evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        evidence_path="skills/flowpilot/assets/packet_control_plane_results.json",
        release_required=True,
    ),
)

MODEL_STRUCTURE_PARTITIONS = (
    StructurePartitionItem(
        "prompt_isolation_public_facade",
        item_type="public_entrypoint",
        owner_module_id="prompt_isolation_facade",
        ownership="parent",
        old_path="prompt_isolation_model",
        new_path="prompt_isolation_model",
    ),
    StructurePartitionItem(
        "prompt_isolation_state",
        item_type="state",
        owner_module_id="prompt_isolation_state",
        old_path="prompt_isolation_model.State",
        new_path="prompt_isolation_model_state",
    ),
    StructurePartitionItem(
        "prompt_isolation_transitions",
        item_type="function_cluster",
        owner_module_id="prompt_isolation_transitions",
        old_path="prompt_isolation_model.next_safe_states",
        new_path="prompt_isolation_model_transitions",
    ),
    StructurePartitionItem(
        "prompt_isolation_invariants",
        item_type="invariant_cluster",
        owner_module_id="prompt_isolation_invariants",
        old_path="prompt_isolation_model.invariant_failures",
        new_path="prompt_isolation_model_invariants",
    ),
    StructurePartitionItem(
        "prompt_isolation_hazards",
        item_type="hazard_cluster",
        owner_module_id="prompt_isolation_hazards",
        old_path="prompt_isolation_model.hazard_states",
        new_path="prompt_isolation_model_hazards",
    ),
    StructurePartitionItem(
        "cross_plane_public_facade",
        item_type="public_entrypoint",
        owner_module_id="cross_plane_facade",
        ownership="parent",
        old_path="flowpilot_cross_plane_friction_model",
        new_path="flowpilot_cross_plane_friction_model",
    ),
    StructurePartitionItem(
        "cross_plane_state",
        item_type="state",
        owner_module_id="cross_plane_state",
        old_path="flowpilot_cross_plane_friction_model.State",
        new_path="flowpilot_cross_plane_friction_model_state",
    ),
    StructurePartitionItem(
        "cross_plane_transitions",
        item_type="function_cluster",
        owner_module_id="cross_plane_transitions",
        old_path="flowpilot_cross_plane_friction_model.next_safe_states",
        new_path="flowpilot_cross_plane_friction_model_transitions",
    ),
    StructurePartitionItem(
        "cross_plane_invariants",
        item_type="invariant_cluster",
        owner_module_id="cross_plane_invariants",
        old_path="flowpilot_cross_plane_friction_model.invariant_failures",
        new_path="flowpilot_cross_plane_friction_model_invariants",
    ),
    StructurePartitionItem(
        "cross_plane_hazards",
        item_type="hazard_cluster",
        owner_module_id="cross_plane_hazards",
        old_path="flowpilot_cross_plane_friction_model.hazard_states",
        new_path="flowpilot_cross_plane_friction_model_hazards",
    ),
    StructurePartitionItem(
        "cross_plane_live_audit",
        item_type="adapter",
        owner_module_id="cross_plane_audit",
        old_path="flowpilot_cross_plane_friction_model.audit_live_run",
        new_path="flowpilot_cross_plane_friction_model_audit",
    ),
    StructurePartitionItem(
        "cross_plane_repair_strategy",
        item_type="strategy",
        owner_module_id="cross_plane_strategy",
        old_path="flowpilot_cross_plane_friction_model.minimal_repair_strategy",
        new_path="flowpilot_cross_plane_friction_model_strategy",
    ),
    StructurePartitionItem(
        "persistent_daemon_public_facade",
        item_type="public_entrypoint",
        owner_module_id="persistent_daemon_facade",
        ownership="parent",
        old_path="flowpilot_persistent_router_daemon_model",
        new_path="flowpilot_persistent_router_daemon_model",
    ),
    StructurePartitionItem(
        "persistent_daemon_state",
        item_type="state",
        owner_module_id="persistent_daemon_state",
        old_path="flowpilot_persistent_router_daemon_model.State",
        new_path="flowpilot_persistent_router_daemon_model_state",
    ),
    StructurePartitionItem(
        "persistent_daemon_transitions",
        item_type="function_cluster",
        owner_module_id="persistent_daemon_transitions",
        old_path="flowpilot_persistent_router_daemon_model.next_safe_states",
        new_path="flowpilot_persistent_router_daemon_model_transitions",
    ),
    StructurePartitionItem(
        "persistent_daemon_invariants",
        item_type="invariant_cluster",
        owner_module_id="persistent_daemon_invariants",
        old_path="flowpilot_persistent_router_daemon_model.invariant_failures",
        new_path="flowpilot_persistent_router_daemon_model_invariants",
    ),
    StructurePartitionItem(
        "persistent_daemon_hazards",
        item_type="hazard_cluster",
        owner_module_id="persistent_daemon_hazards",
        old_path="flowpilot_persistent_router_daemon_model.hazard_states",
        new_path="flowpilot_persistent_router_daemon_model_hazards",
    ),
    StructurePartitionItem(
        "packet_control_plane_public_facade",
        item_type="public_entrypoint",
        owner_module_id="packet_control_plane_facade",
        ownership="parent",
        old_path="packet_control_plane_model",
        new_path="packet_control_plane_model",
    ),
    StructurePartitionItem(
        "packet_control_plane_state",
        item_type="state",
        owner_module_id="packet_control_plane_state",
        old_path="packet_control_plane_model state dataclasses",
        new_path="packet_control_plane_model_state",
    ),
    StructurePartitionItem(
        "packet_control_plane_transitions",
        item_type="function_cluster",
        owner_module_id="packet_control_plane_transitions",
        old_path="packet_control_plane_model transition classes",
        new_path="packet_control_plane_model_transitions",
    ),
    StructurePartitionItem(
        "packet_control_plane_transition_children",
        item_type="function_cluster",
        owner_module_id="packet_control_plane_transitions",
        old_path="packet_control_plane_model_transitions mixed transition classes",
        new_path="packet_control_plane_model_transitions_*",
    ),
    StructurePartitionItem(
        "packet_control_plane_invariants",
        item_type="invariant_cluster",
        owner_module_id="packet_control_plane_invariants",
        old_path="packet_control_plane_model invariants",
        new_path="packet_control_plane_model_invariants",
    ),
)

MODEL_STRUCTURE_MODULES = (
    ModuleStructureEvidence(
        "prompt_isolation_facade",
        path="simulations/prompt_isolation_model.py",
        layer="parent",
        owns_functions=("build_workflow", "next_states", "is_terminal", "is_success"),
        behavior_contracts=("legacy import path", "runner compatibility"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "prompt_isolation_state",
        path="simulations/prompt_isolation_model_state.py",
        owns_functions=("initial_state",),
        owns_state=("prompt_isolation_state",),
        behavior_contracts=("immutable prompt-isolation state shape",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "prompt_isolation_transitions",
        path="simulations/prompt_isolation_model_transitions.py",
        owns_functions=("PromptIsolationStep", "next_safe_states"),
        behavior_contracts=("prompt-isolation transition labels",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "prompt_isolation_invariants",
        path="simulations/prompt_isolation_model_invariants.py",
        owns_functions=("invariant_failures", "prompt_isolation_invariant"),
        behavior_contracts=("prompt-isolation invariant messages",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "prompt_isolation_hazards",
        path="simulations/prompt_isolation_model_hazards.py",
        owns_functions=("hazard_states",),
        behavior_contracts=("prompt-isolation known-bad states",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "cross_plane_facade",
        path="simulations/flowpilot_cross_plane_friction_model.py",
        layer="parent",
        owns_functions=("build_workflow", "next_states", "is_terminal", "is_success"),
        behavior_contracts=("legacy import path", "runner compatibility"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "cross_plane_state",
        path="simulations/flowpilot_cross_plane_friction_model_state.py",
        owns_functions=("initial_state",),
        owns_state=("cross_plane_state",),
        behavior_contracts=("cross-plane state shape and constants",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "cross_plane_transitions",
        path="simulations/flowpilot_cross_plane_friction_model_transitions.py",
        owns_functions=("CrossPlaneReconciliationStep", "next_safe_states"),
        behavior_contracts=("cross-plane transition labels",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "cross_plane_invariants",
        path="simulations/flowpilot_cross_plane_friction_model_invariants.py",
        owns_functions=("invariant_failures",),
        behavior_contracts=("cross-plane invariant messages",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "cross_plane_hazards",
        path="simulations/flowpilot_cross_plane_friction_model_hazards.py",
        owns_functions=("hazard_states", "repair_solution_state"),
        behavior_contracts=("cross-plane known-bad states",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "cross_plane_audit",
        path="simulations/flowpilot_cross_plane_friction_model_audit.py",
        owns_functions=("audit_live_run", "state_from_findings"),
        behavior_contracts=("envelope-only live audit adapter",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "cross_plane_strategy",
        path="simulations/flowpilot_cross_plane_friction_model_strategy.py",
        owns_functions=("minimal_repair_strategy",),
        behavior_contracts=("minimal repair action table",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "persistent_daemon_facade",
        path="simulations/flowpilot_persistent_router_daemon_model.py",
        layer="parent",
        owns_functions=("build_workflow", "next_states", "is_terminal", "is_success"),
        behavior_contracts=("legacy import path", "runner compatibility"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "persistent_daemon_state",
        path="simulations/flowpilot_persistent_router_daemon_model_state.py",
        owns_functions=("initial_state",),
        owns_state=("persistent_daemon_state",),
        behavior_contracts=("persistent daemon state shape",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "persistent_daemon_transitions",
        path="simulations/flowpilot_persistent_router_daemon_model_transitions.py",
        owns_functions=("PersistentRouterDaemonStep", "next_safe_states"),
        behavior_contracts=("persistent daemon transition labels",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "persistent_daemon_invariants",
        path="simulations/flowpilot_persistent_router_daemon_model_invariants.py",
        owns_functions=("invariant_failures",),
        behavior_contracts=("persistent daemon invariant messages",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "persistent_daemon_hazards",
        path="simulations/flowpilot_persistent_router_daemon_model_hazards.py",
        owns_functions=("hazard_states",),
        behavior_contracts=("persistent daemon known-bad states",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "packet_control_plane_facade",
        path="skills/flowpilot/assets/packet_control_plane_model.py",
        layer="parent",
        owns_functions=("build_workflow",),
        behavior_contracts=("legacy packet control-plane model import path", "runner compatibility"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "packet_control_plane_state",
        path="skills/flowpilot/assets/packet_control_plane_model_state.py",
        owns_functions=("_packet_from_id",),
        owns_state=("packet_control_plane_state",),
        behavior_contracts=("packet control-plane immutable state shape", "case dataclass identity"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "packet_control_plane_transitions",
        path="skills/flowpilot/assets/packet_control_plane_model_transitions.py",
        owns_functions=(
            "PMIssuePacket",
            "PacketRuntimeWrite",
            "RouterDirectDispatch",
            "ReviewerResult",
            "PMAdvance",
        ),
        dependencies=("packet_control_plane_state",),
        behavior_contracts=("packet control-plane transition labels", "packet lifecycle progress cases"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "packet_control_plane_transitions_issue_resume",
        path="skills/flowpilot/assets/packet_control_plane_model_transitions_issue_resume.py",
        owns_functions=("PMIssuePacket", "HeartbeatResumeLoad", "ControllerAskPMOnResume", "PMResumeDecision"),
        dependencies=("packet_control_plane_state",),
        behavior_contracts=("packet issue and heartbeat resume transition labels",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "packet_control_plane_transitions_packet_relay",
        path="skills/flowpilot/assets/packet_control_plane_model_transitions_packet_relay.py",
        owns_functions=("PacketRuntimeWrite", "ControllerReminderCheck", "ControllerEnvelopeOnlyHandoff", "ControllerEnvelopeRelay"),
        dependencies=("packet_control_plane_state",),
        behavior_contracts=("packet runtime write and Controller relay transition labels",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "packet_control_plane_transitions_dispatch_results",
        path="skills/flowpilot/assets/packet_control_plane_model_transitions_dispatch_results.py",
        owns_functions=("RouterDirectDispatch", "WorkerOrControllerResult", "ControllerResultRelay"),
        dependencies=("packet_control_plane_state",),
        behavior_contracts=("dispatch and result relay transition labels",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "packet_control_plane_transitions_review_pm",
        path="skills/flowpilot/assets/packet_control_plane_model_transitions_review_pm.py",
        owns_functions=("ReviewerResultEnvelopeCheck", "ReviewerResult", "PMRepairAfterInvalidOrigin", "PMAdvance"),
        dependencies=("packet_control_plane_state", "packet_control_plane_invariants"),
        behavior_contracts=("reviewer and PM outcome transition labels",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "packet_control_plane_invariants",
        path="skills/flowpilot/assets/packet_control_plane_model_invariants.py",
        owns_functions=("no_advance_from_controller_artifact", "advance_requires_review_pass"),
        dependencies=("packet_control_plane_state",),
        behavior_contracts=("packet control-plane invariant checks", "known stuck-loop blockers"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
)
