"""Information-flow alignment code-contract catalog."""

from __future__ import annotations

from typing import Any

from flowpilot_model_test_alignment_common import _contract
from flowpilot_information_flow_alignment_obligations import (
    OBL_BLOCKER_PAYLOAD,
    OBL_BREAK_GLASS,
    OBL_CLOSURE_STOP,
    OBL_FLOWGUARD_EVIDENCE_CONSISTENCY,
    OBL_FORMAL_REPAIR_IDENTITY,
    OBL_RECHECK_FOLLOWUP,
    OBL_REOPEN_HISTORY,
    OBL_REQUIRED_REPAIR,
    OBL_RESUME_CURRENT,
    OBL_ROLE_ASSIGNMENT,
    OBL_ROUTE_MUTATION,
    OBL_WORKER_DELTA,
)


def _code_contracts() -> tuple[Any, ...]:
    runtime = "skills/flowpilot/assets/flowpilot_core_runtime/runtime.py"
    new_run_commands = "skills/flowpilot/assets/flowpilot_new_run_commands.py"
    new_role_commands = "skills/flowpilot/assets/flowpilot_new_role_commands.py"
    router_role_misc = "skills/flowpilot/assets/flowpilot_router_action_handlers_role_misc.py"
    pm_role_result = (
        "skills/flowpilot/assets/"
        "flowpilot_router_work_packets_pm_role_writes_decisions_role_result.py"
    )
    break_glass = "skills/flowpilot/assets/flowpilot_controller_break_glass.py"
    break_glass_recovery = (
        "skills/flowpilot/assets/flowpilot_controller_break_glass_recovery.py"
    )
    closure = "skills/flowpilot/assets/flowpilot_closure_kernel.py"
    return (
        _contract(
            "info_flow.runtime.ensure_pm_repair_packet",
            path=runtime,
            symbol="_ensure_pm_repair_decision_packet_for_blocker",
            implements=(OBL_BLOCKER_PAYLOAD, OBL_REQUIRED_REPAIR),
            external_inputs=("ledger", "blocker_id"),
            external_outputs=("pm_repair_packet_id",),
            state_reads=("current_blocker", "role_result", "packet_ledger"),
            state_writes=("pm_repair_packet", "packet_ledger"),
        ),
        _contract(
            "info_flow.runtime.apply_pm_repair_decision",
            path=runtime,
            symbol="_apply_pm_repair_decision",
            implements=(OBL_FORMAL_REPAIR_IDENTITY, OBL_REQUIRED_REPAIR, OBL_WORKER_DELTA),
            external_inputs=("ledger", "blocker_id", "decision_id"),
            external_outputs=("repair_packet_or_route_mutation",),
            state_reads=("pm_repair_decision", "active_blocker"),
            state_writes=("repair_packet", "blocker_status", "route_mutation"),
        ),
        _contract(
            "info_flow.runtime.issue_current_scope_repair_packet",
            path=runtime,
            symbol="_issue_current_scope_repair_packet",
            implements=(OBL_FORMAL_REPAIR_IDENTITY, OBL_WORKER_DELTA),
            external_inputs=("ledger", "blocker", "decision"),
            external_outputs=("fresh_repair_packet",),
            state_reads=("current_packet", "active_blocker"),
            state_writes=("packet_ledger",),
        ),
        _contract(
            "info_flow.runtime.recent_role_reports",
            path=runtime,
            symbol="_pm_packet_body_with_recent_role_reports",
            implements=(OBL_BLOCKER_PAYLOAD, OBL_REQUIRED_REPAIR),
            external_inputs=("ledger", "body"),
            external_outputs=("pm_packet_body",),
            state_reads=("role_results",),
        ),
        _contract(
            "info_flow.runtime.authorized_result_reads",
            path=runtime,
            symbol="_attach_authorized_result_reads_to_packet",
            implements=(OBL_BLOCKER_PAYLOAD,),
            external_inputs=("ledger", "packet_id", "reads"),
            external_outputs=("updated_packet",),
            state_reads=("result_envelopes",),
            state_writes=("packet_envelope",),
        ),
        _contract(
            "info_flow.runtime.open_packet_authorized_material_delivery",
            path=runtime,
            symbol="open_authorized_input_materials_for_role",
            implements=(OBL_BLOCKER_PAYLOAD, OBL_REQUIRED_REPAIR),
            external_inputs=("ledger", "packet_id", "lease_id"),
            external_outputs=("authorized_input_materials",),
            state_reads=("authorized_result_reads", "result_body", "lease", "packet_assignment"),
            state_writes=("authorized_result_read_receipts",),
        ),
        _contract(
            "info_flow.runtime.pm_opened_result_bodies",
            path=pm_role_result,
            symbol="_validate_result_bodies_opened_by_pm",
            implements=(OBL_BLOCKER_PAYLOAD, OBL_REQUIRED_REPAIR),
            external_inputs=("records",),
            external_outputs=("validation_or_error",),
            state_reads=("result_body_opened_by_role",),
        ),
        _contract(
            "info_flow.runtime.required_recheck_packet",
            path=runtime,
            symbol="_issue_required_recheck_packet_for_stopped_blocker",
            implements=(OBL_FORMAL_REPAIR_IDENTITY, OBL_RECHECK_FOLLOWUP),
            external_inputs=("ledger", "blocker_id"),
            external_outputs=("reviewer_recheck_packet",),
            state_reads=("active_blocker",),
            state_writes=("packet_ledger",),
        ),
        _contract(
            "info_flow.runtime.packet_repair_blocker_id",
            path=runtime,
            symbol="_packet_repair_blocker_id",
            implements=(OBL_FORMAL_REPAIR_IDENTITY,),
            external_inputs=("ledger", "packet_id"),
            external_outputs=("current_repair_blocker_id",),
            state_reads=("packet_ledger", "active_blockers"),
        ),
        _contract(
            "info_flow.runtime.attach_staged_effect",
            path=runtime,
            symbol="_attach_staged_effect",
            implements=(OBL_FORMAL_REPAIR_IDENTITY,),
            external_inputs=("record", "effect_kind", "source_packet_id", "source_result_id", "blocker_id"),
            external_outputs=("staged_effect"),
            state_writes=("result_or_gate_record",),
        ),
        _contract(
            "info_flow.runtime.build_current_handoff_contract",
            path=runtime,
            symbol="_build_current_handoff_contract",
            implements=(OBL_FORMAL_REPAIR_IDENTITY,),
            external_inputs=("ledger", "packet_envelope", "authorized_result_reads"),
            external_outputs=("current_handoff_contract"),
            state_reads=("packet_envelope", "active_blocker", "repair_blocker_id"),
        ),
        _contract(
            "info_flow.runtime.formal_repair_identity_gate",
            path=runtime,
            symbol="_formal_repair_identity_blockers",
            implements=(OBL_FORMAL_REPAIR_IDENTITY,),
            external_inputs=("packet",),
            external_outputs=("mechanical_blockers",),
            state_reads=("packet", "packet_envelope", "current_handoff_contract"),
        ),
        _contract(
            "info_flow.runtime.flowguard_evidence_consistency_gate",
            path=runtime,
            symbol="_flowguard_evidence_consistency_violation",
            implements=(OBL_FLOWGUARD_EVIDENCE_CONSISTENCY,),
            external_inputs=("packet", "result"),
            external_outputs=("contract_check",),
            state_reads=("flowguard_result_body",),
        ),
        _contract(
            "info_flow.runtime.review_packet_requires_matching_flowguard_report",
            path=runtime,
            symbol="_ensure_review_packet_for_task_result",
            implements=(OBL_FLOWGUARD_EVIDENCE_CONSISTENCY,),
            external_inputs=("ledger", "subject_packet_id"),
            external_outputs=("review_packet_id",),
            state_reads=("flowguard_work_orders", "flowguard_result"),
            state_writes=("review_packet",),
        ),
        _contract(
            "info_flow.new_runtime.resume_entrypoint",
            path=new_run_commands,
            symbol="resume",
            implements=(OBL_RESUME_CURRENT,),
            external_inputs=("root", "reason"),
            external_outputs=("lifecycle_guard", "foreground_duty", "next_action"),
            state_reads=("current_run_shell", "current_run_ledger"),
            state_writes=("resume_request", "resume_reconciliation", "lifecycle_guard"),
        ),
        _contract(
            "info_flow.runtime.record_resume_request",
            path=runtime,
            symbol="record_resume_request",
            implements=(OBL_RESUME_CURRENT,),
            external_inputs=("ledger", "reason"),
            external_outputs=("resume_request_record",),
            state_writes=("resume_request",),
        ),
        _contract(
            "info_flow.runtime.reconcile_resume_request",
            path=runtime,
            symbol="reconcile_resume_request",
            implements=(OBL_RESUME_CURRENT, OBL_REOPEN_HISTORY),
            external_inputs=("ledger", "resume_source"),
            external_outputs=("resume_reconciliation",),
            state_reads=("current_run", "packet_ledger", "active_blockers"),
            state_writes=("resume_state",),
        ),
        _contract(
            "info_flow.new_runtime.dispatch_current_role",
            path=new_role_commands,
            symbol="dispatch_current_role",
            implements=(OBL_ROLE_ASSIGNMENT,),
            external_inputs=("root", "packet_id", "responsibility", "host_kind", "agent_id"),
            external_outputs=("role_assignment", "lease_id", "role_handoff"),
            state_reads=("current_run_ledger", "current_packet", "role_continuity"),
            state_writes=("role_assignments", "lease", "packet_assignment", "role_continuity"),
        ),
        _contract(
            "info_flow.runtime.resolve_role_assignment",
            path=runtime,
            symbol="resolve_role_assignment",
            implements=(OBL_ROLE_ASSIGNMENT,),
            external_inputs=("ledger", "responsibility", "packet_id", "host_kind"),
            external_outputs=("role_assignment",),
            state_reads=("current_packet", "role_continuity", "same_responsibility_lease_history"),
            state_writes=("role_assignments",),
        ),
        _contract(
            "info_flow.runtime.lease_agent",
            path=runtime,
            symbol="lease_agent",
            implements=(OBL_ROLE_ASSIGNMENT,),
            external_inputs=("ledger", "responsibility", "packet_id", "assignment_id", "agent_id"),
            external_outputs=("lease_id",),
            state_reads=("role_assignment", "role_memory_seed"),
            state_writes=("leases", "role_continuity"),
        ),
        _contract(
            "info_flow.router.controller_repair_work_packet",
            path=router_role_misc,
            symbol="_apply_controller_repair_work_packet",
            implements=(OBL_BREAK_GLASS, OBL_WORKER_DELTA),
            external_inputs=("repair_transaction_id", "payload"),
            external_outputs=("controller_repair_work_packet_result",),
            state_reads=("control_blocker", "repair_transaction"),
            state_writes=("repair_transaction",),
        ),
        _contract(
            "info_flow.break_glass.open_incident",
            path=break_glass,
            symbol="open_incident",
            implements=(OBL_BREAK_GLASS,),
            external_inputs=("incident_id", "trigger", "sources"),
            external_outputs=("incident_record",),
            state_writes=("controller_break_glass/incidents",),
        ),
        _contract(
            "info_flow.break_glass.record_control_plane_blocker",
            path=break_glass,
            symbol="record_control_plane_blocker",
            implements=(OBL_BREAK_GLASS,),
            external_inputs=("blocker_id", "summary", "sources"),
            external_outputs=("control_plane_blocker_record",),
            state_writes=("control_plane_blocker_ledger",),
        ),
        _contract(
            "info_flow.break_glass.close_incident",
            path=break_glass,
            symbol="close_incident",
            implements=(OBL_BREAK_GLASS,),
            external_inputs=("incident_id", "disposition"),
            external_outputs=("closed_or_blocked_incident",),
            state_reads=("validation_evidence", "recovery_transactions"),
            state_writes=("controller_break_glass/index",),
        ),
        _contract(
            "info_flow.break_glass.open_recovery_transaction",
            path=break_glass_recovery,
            symbol="open_recovery_transaction",
            implements=(OBL_BREAK_GLASS,),
            external_inputs=("transaction_id", "incident_id", "failure_kind"),
            external_outputs=("recovery_transaction",),
            state_writes=("controller_break_glass/recovery_transactions",),
        ),
        _contract(
            "info_flow.break_glass.record_controller_reinjection",
            path=break_glass_recovery,
            symbol="record_controller_reinjection",
            implements=(OBL_BREAK_GLASS,),
            external_inputs=("previous_generation_id", "next_generation_id"),
            external_outputs=("controller_reinjection",),
            state_reads=("boundary_proof",),
            state_writes=("controller_reinjections",),
        ),
        _contract(
            "info_flow.break_glass.close_recovery_transaction",
            path=break_glass_recovery,
            symbol="close_recovery_transaction",
            implements=(OBL_BREAK_GLASS,),
            external_inputs=("transaction_id", "same_family_evidence"),
            external_outputs=("closed_recovery_transaction",),
            state_reads=("controller_reinjection",),
            state_writes=("recovery_transaction",),
        ),
        _contract(
            "info_flow.runtime.redesign_route_from_pm_decision",
            path=runtime,
            symbol="_redesign_route_from_pm_decision",
            implements=(OBL_ROUTE_MUTATION,),
            external_inputs=("ledger", "blocker", "decision"),
            external_outputs=("route_mutation",),
            state_reads=("active_blocker", "route_memory", "stale_evidence"),
            state_writes=("route_version", "execution_frontier"),
        ),
        _contract(
            "info_flow.closure.classify_control_blocker",
            path=closure,
            symbol="classify_control_blocker",
            implements=(OBL_CLOSURE_STOP, OBL_RECHECK_FOLLOWUP),
            external_inputs=("control_blocker_record",),
            external_outputs=("closure_decision",),
            state_reads=("control_blocker_status",),
        ),
        _contract(
            "info_flow.closure.closure_blocks_progress",
            path=closure,
            symbol="closure_blocks_progress",
            implements=(OBL_CLOSURE_STOP,),
            external_inputs=("record_kind", "record"),
            external_outputs=("blocks_progress",),
            state_reads=("terminal_or_unresolved_status",),
        ),
    )
