"""Hazard-state constructors for ``flowpilot_control_plane_friction_model``."""

from __future__ import annotations

from dataclasses import replace

from flowpilot_control_plane_friction_model_state import State


def _safe_base(**changes: object) -> State:
    return replace(
        State(
            status="running",
            controller_boundary_confirmed=True,
            mode="expanded",
            stateful_controller_receipt_done=True,
            stateful_controller_postcondition_declared=True,
            stateful_controller_postcondition_evidence_written=True,
            stateful_controller_advanced_from_receipt=True,
            controller_delivery_receipt_done=True,
            controller_delivery_host_status="delivered",
            controller_delivery_target_role_wait_started=True,
            controller_delivery_used_as_role_completion=False,
            controller_delivery_missing_role_output_blocker=False,
            pm_role_work_identity_includes_batch_request_packet_role=True,
            pm_role_work_closed_identity_reused_for_distinct_request=False,
            pm_role_work_request_postcondition_scoped=True,
            pm_role_work_open_request_masked_by_global_flag=False,
            active_holder_lease_issued=True,
            active_holder_agent_identity_recorded=True,
            active_holder_agent_host_live=True,
            active_holder_packet_role_matches=True,
            packet_ledger_write_atomic=True,
            packet_ledger_write_locked_or_cas=True,
            packet_ledger_readback_validated=True,
            packet_ledger_corruption_recoverable=True,
            packet_ledger_corrupt_read_crashed_daemon=False,
            router_owned_artifact_exists=True,
            router_owned_artifact_proof_valid=True,
            router_owned_postcondition_reclaimed_from_artifact=True,
            router_tick_saw_receipt_before_flag=True,
            router_tick_escalated_before_reclaim=False,
            controller_display_work_soft_recorded=True,
            controller_display_work_hard_postcondition=False,
            controller_display_work_escalated_to_pm=False,
            external_keepalive_confirmation_required=True,
            external_keepalive_confirmed=True,
            signed_envelope_relayed=True,
            signed_envelope_rewritten_after_relay=False,
            signed_envelope_migration_sidecar_written=True,
            signed_envelope_mutable_indexes_backfilled=True,
            control_blocker_action_identity_includes_blocker=True,
            controller_action_closed_identity_reused=False,
            control_blocker_receipt_postcondition_declared=True,
            control_blocker_receipt_effect_applied=True,
            current_wait_derived_from_obligation=True,
            stale_run_state_save_seen=True,
            latest_state_cleared_wait=True,
            stale_run_state_pending_matches_loaded_wait=True,
            stale_run_state_preserved_wait_clear=True,
            stale_run_state_resurrected_closed_wait=False,
            self_check_template_status_pass_allowed=True,
            self_check_parser_status_pass_accepted=True,
            material_gate_depends_on_result_body=True,
            result_self_check_machine_parseable=True,
            result_reader_authority_matches_runtime=True,
            pm_research_package_written=True,
            research_package_has_decision_question=True,
            research_package_has_allowed_sources=True,
            research_package_has_stop_conditions=True,
            research_capability_decision_recorded=True,
            worker_packet_written=True,
            worker_packet_preserves_research_fields=True,
            material_dispatch_requested=True,
            material_dispatch_reviewed=True,
            material_dispatch_allowed=True,
            material_dispatch_phase_context_consistent=True,
            material_dispatch_output_contract_consistent=True,
            material_dispatch_write_target_explicit=True,
            material_dispatch_single_canonical_body=True,
            pm_repair_reissue_spec_written=False,
            pm_repair_reissue_packet_files_materialized=True,
            pm_repair_reissue_packets_registered_in_ledger=True,
            pm_repair_reissue_dispatch_index_updated=True,
            pm_repair_allowed_success_only=False,
            pm_repair_non_success_outcome_routable=True,
            current_repair_target_gate_checked=True,
            result_submitted_repair_target_seen=True,
            result_submitted_repair_target_replaced=True,
            result_submitted_repair_target_superseded=True,
            active_blocker_points_noncurrent_packet=True,
            current_target_gate_blocks_stale_target=True,
            blocked_pm_repair_decision_packet_seen=True,
            blocked_pm_repair_decision_packet_reused=False,
            fresh_pm_repair_decision_packet_issued=True,
            fallback_responsibility_used=False,
            staged_effect_same_family_repeated=True,
            same_family_expansion_stopped=True,
            expected_role_decision_requires_unsatisfied_flag=False,
            reviewer_recheck_protocol_blocker_written=False,
            reviewer_recheck_protocol_blocker_routable=True,
            packet_delivered=True,
            packet_body_open_receipt=True,
            result_returned=True,
            result_routed_to_pm=True,
            result_body_open_receipt=True,
            pm_result_disposition_recorded=True,
            pm_formal_review_package_released=True,
            pm_formal_review_package_has_artifact=True,
            pm_formal_review_package_hash_recorded=True,
            pm_formal_review_package_scope_declared=True,
            reviewer_report_written=True,
            reviewer_report_accepted=True,
            pm_material_understanding_written=True,
            pm_material_understanding_source_available=True,
            product_architecture_card_delivered=True,
            product_architecture_delivery_has_material_context=True,
            protocol_blocker_file_written=False,
            protocol_blocker_registered_in_router_state=False,
            control_blocker_artifact_status_written=False,
            control_blocker_router_index_matches_artifact=True,
            pm_repair_decision_recorded=False,
            control_blocker_followup_event_matchable=True,
            control_resolution_predicate_normalized=True,
            followup_event_expected_role="none",
            followup_event_from_role="none",
            valid_role_output_waiting=False,
            no_legal_next_control_blocker_materialized=False,
            duplicate_pm_repair_decision_seen=False,
            duplicate_repair_created_new_blocker=False,
            phase_dependency_cards_delivered=True,
            phase_required_sources_complete=True,
            delivered_card_phase_context_fresh=True,
            terminal_snapshot_published=False,
            terminal_snapshot_flags_consistent=True,
            child_skill_gate_review_recorded=False,
            child_skill_gate_manifest_synced_with_review=True,
            child_skill_gate_repair_flow_started=False,
            child_skill_gate_pm_rewrote_after_block=False,
            gate_card_requires_semantic_outcome=False,
            card_ack_consumed=False,
            semantic_gate_wait_exposed_after_ack=True,
            gate_outcome_block_active=False,
            gate_outcome_block_gate_key="none",
            gate_outcome_pass_recorded=False,
            gate_outcome_pass_gate_key="none",
            gate_outcome_same_generation=True,
            gate_outcome_clear_target_matches_pass_gate=True,
            terminal_continuation_cleanup_recorded=False,
            terminal_host_automation_cleanup_proven=True,
            role_output_envelopes_recorded=False,
            role_output_hashes_replayable=True,
            stage_advanced_after_material_scan=True,
            frontier_fresh_after_stage_advance=True,
            product_stage_view_published=True,
            product_stage_view_fresh=True,
            route_draft_written=True,
            route_draft_has_nodes=True,
            route_draft_single_canonical_source=True,
            route_draft_shadow_source_used=False,
            route_process_check_card_delivered=True,
            route_process_check_passed=True,
            route_draft_repaired_after_check=False,
            route_review_flags_reset_after_draft_repair=True,
            status_summary_published=True,
            status_summary_fresh_against_frontier_and_packet=True,
            status_summary_metadata_only=True,
            status_summary_blocker_state_consistent=True,
            controller_user_reporting_policy_present=True,
            router_action_user_reporting_reminder_present=True,
            controller_table_prompt_user_language_guidance_present=True,
            controller_reporting_budget_present=True,
            quiet_internal_progress_silent=True,
            routine_process_aside_relayed_to_user=False,
            user_report_limited_to_meaningful_change=True,
            user_report_plain_language=True,
            user_report_internal_metadata_exposed=False,
            router_action_user_reporting_reminder_displayed_to_user=False,
            status_summary_progress_facts_present=True,
            status_summary_progress_level_count_valid=True,
            status_summary_progress_counts_valid=True,
            status_summary_progress_elapsed_valid_or_null=True,
            status_summary_progress_metadata_only=True,
            role_identity_checked=True,
            hash_verified=True,
            optimized_card_ack_transaction=True,
            card_ack_validated=True,
            card_ack_role_checked=True,
            card_ack_hash_checked=True,
            pending_card_return_kind="system_card",
            pending_card_return_ack_file_present=True,
            pending_card_return_ack_valid=True,
            pending_card_return_ack_role_checked=True,
            pending_card_return_ack_hash_checked=True,
            pending_card_return_bundle_receipts_complete=True,
            card_return_ledger_resolved=True,
            role_event_arrived_while_ack_pending=False,
            pre_event_card_ack_auto_consumed=True,
            role_event_blocked_by_unresolved_card_return=False,
            pre_event_role_wait_authority_present=True,
            pre_event_role_wait_authority_preserved=True,
            role_event_accepted_after_pre_event_ack=False,
            pre_event_ack_selected_matching_pending_return=True,
            duplicate_completed_return_written=False,
            missing_ack_report_arrived=False,
            missing_ack_report_quarantined=False,
            same_role_ack_recovery_requested=False,
            missing_ack_report_event_flag_set=False,
            quarantined_report_used_as_evidence=False,
            old_pre_ack_report_revived=False,
            report_submitted_after_valid_ack=True,
            pending_return_dependency_matches_report=True,
            missing_ack_generic_pm_blocker_created=False,
            repeated_ack_recovery_failed=False,
            pm_escalated_after_repeated_ack_failure=False,
            pending_wait_reconciled=True,
            pending_wait_reconciliation_uses_packet_ledger=True,
            pending_wait_reconciliation_uses_status_packet=True,
            pending_wait_reconciliation_role_verified=True,
            pending_wait_reconciliation_hash_verified=True,
            pending_wait_reconciliation_from_chat=False,
            stale_wait_pending=True,
            durable_result_evidence_exists=True,
            stale_wait_reissued_without_reconciliation=False,
            partial_batch_active=True,
            partial_batch_packet_count=2,
            partial_batch_results_returned=1,
            partial_batch_result_refreshed_from_members=True,
            partial_batch_missing_role_summary_accurate=True,
            status_summary_waiting_role_matches_partial_batch=True,
            duplicate_reconciliation_incremented_count=False,
            pm_role_work_result_normalized=True,
            pm_role_work_result_routes_to_pm=True,
            current_node_result_routes_to_pm=True,
            model_miss_flowguard_operator_report_complete=True,
            model_miss_pm_decision_from_single_report=True,
            role_memory_delta_written=True,
            role_memory_used_for_authority=False,
            role_output_status_prepared_only=False,
            role_output_status_used_as_event_evidence=False,
            role_output_event_submitted=True,
            role_output_event_accepted=True,
            role_output_file_backed_body_path_present=True,
            role_output_body_hash_verified=True,
            material_repair_generation_protocol_checked=True,
            operation_replay_fresh_controller_action_id=True,
            operation_replay_targets_current_generation=True,
            operation_replay_ledger_io_authorized=True,
            controller_repair_work_packet_receipt_folded=True,
            controller_repair_work_packet_facade_exported=True,
            pm_material_disposition_generation_scoped=True,
            pm_material_disposition_matches_current_generation=True,
            stale_pm_material_disposition_restored=False,
            material_progress_projection_generation_scoped=True,
            material_global_progress_flags_match_active_generation=True,
            material_next_action_derived_from_active_batch=True,
            material_reissue_clears_or_quarantines_stale_progress_flags=True,
            stale_run_state_save_preserves_material_generation_flag_clear=True,
            material_dispatch_block_matches_active_generation=True,
            role_output_event_deduped_by_body_ref=True,
            role_output_current_generation_not_short_circuited_by_global_flag=True,
            duplicate_role_event_side_effect_written=False,
            packet_result_author_identity_replayable=True,
            packet_result_author_matches_current_role=True,
            break_glass_patch_validation_finalized=True,
        ),
        **changes,
    )

def hazard_states() -> dict[str, State]:
    return {
        "research_package_scope_dropped": _safe_base(worker_packet_preserves_research_fields=False),
        "material_dispatch_phase_mismatch": _safe_base(
            material_dispatch_phase_context_consistent=False,
        ),
        "material_dispatch_output_contract_mismatch": _safe_base(
            material_dispatch_output_contract_consistent=False,
        ),
        "material_dispatch_write_target_missing": _safe_base(
            material_dispatch_write_target_explicit=False,
        ),
        "material_dispatch_duplicate_canonical_body": _safe_base(
            material_dispatch_single_canonical_body=False,
        ),
        "material_dispatch_allowed_without_preflight": _safe_base(
            material_dispatch_reviewed=False,
            material_dispatch_allowed=True,
        ),
        "signed_material_envelope_rewritten_after_relay": _safe_base(
            signed_envelope_relayed=True,
            signed_envelope_rewritten_after_relay=True,
        ),
        "signed_material_migration_sidecar_missing": _safe_base(
            signed_envelope_relayed=True,
            signed_envelope_mutable_indexes_backfilled=True,
            signed_envelope_migration_sidecar_written=False,
        ),
        "control_blocker_identity_missing_blocker_id": _safe_base(
            control_blocker_action_identity_includes_blocker=False,
            control_blocker_receipt_postcondition_declared=True,
        ),
        "closed_controller_action_reused_for_different_identity": _safe_base(
            controller_action_closed_identity_reused=True,
        ),
        "pm_role_work_closed_identity_reused_for_distinct_batch": _safe_base(
            pm_role_work_closed_identity_reused_for_distinct_request=True,
            pm_role_work_identity_includes_batch_request_packet_role=False,
        ),
        "pm_role_work_wait_identity_missing_request_packet_role": _safe_base(
            role_work_wait_pending=True,
            pm_role_work_identity_includes_batch_request_packet_role=False,
        ),
        "pm_role_work_global_postcondition_masks_open_request": _safe_base(
            pm_role_work_open_request_masked_by_global_flag=True,
            pm_role_work_request_postcondition_scoped=False,
        ),
        "control_blocker_done_receipt_without_delivery_postcondition": _safe_base(
            control_blocker_receipt_postcondition_declared=True,
            control_blocker_receipt_effect_applied=False,
        ),
        "stale_run_state_resurrects_closed_wait_projection": _safe_base(
            current_wait_derived_from_obligation=True,
            stale_run_state_save_seen=True,
            latest_state_cleared_wait=True,
            stale_run_state_pending_matches_loaded_wait=True,
            stale_run_state_preserved_wait_clear=False,
            stale_run_state_resurrected_closed_wait=True,
        ),
        "self_check_status_pass_rejected": _safe_base(
            self_check_template_status_pass_allowed=True,
            self_check_parser_status_pass_accepted=False,
        ),
        "material_gate_result_self_check_unparseable": _safe_base(
            material_gate_depends_on_result_body=True,
            result_self_check_machine_parseable=False,
        ),
        "material_gate_result_reader_not_runtime_backed": _safe_base(
            material_gate_depends_on_result_body=True,
            result_reader_authority_matches_runtime=False,
        ),
        "pm_formal_gate_package_missing_artifact": _safe_base(
            pm_formal_review_package_released=True,
            pm_formal_review_package_has_artifact=False,
        ),
        "reviewer_report_without_result_open_receipt": _safe_base(result_body_open_receipt=False),
        "missing_receipt_blocker_escalated_to_pm": _safe_base(
            receipt_missing_blocker=True,
            control_blocker_lane="pm_repair_decision_required",
            control_blocker_target_role="project_manager",
        ),
        "stopped_run_with_active_heartbeat": _safe_base(
            current_status_stopped=True,
            continuation_heartbeat_active=True,
            frontier_terminal=True,
        ),
        "stopped_run_with_active_packet_loop": _safe_base(
            current_status_stopped=True,
            packet_loop_active=True,
            frontier_terminal=True,
        ),
        "stopped_run_without_terminal_frontier": _safe_base(
            current_status_stopped=True,
            frontier_terminal=False,
        ),
        "stale_snapshot_published_as_active": _safe_base(
            snapshot_published_as_active=True,
            snapshot_fresh_against_frontier_and_ledger=False,
        ),
        "product_architecture_delivery_missing_material_context": _safe_base(
            product_architecture_delivery_has_material_context=False,
        ),
        "protocol_blocker_file_unregistered": _safe_base(
            protocol_blocker_file_written=True,
            protocol_blocker_registered_in_router_state=False,
        ),
        "control_blocker_index_stale_after_artifact_update": _safe_base(
            control_blocker_artifact_status_written=True,
            control_blocker_router_index_matches_artifact=False,
        ),
        "display_work_hard_postcondition_gate": _safe_base(
            controller_display_work_soft_recorded=True,
            controller_display_work_hard_postcondition=True,
            controller_display_work_escalated_to_pm=False,
        ),
        "display_work_escalated_to_pm_repair": _safe_base(
            controller_display_work_soft_recorded=True,
            controller_display_work_hard_postcondition=True,
            controller_display_work_escalated_to_pm=True,
        ),
        "external_keepalive_unconfirmed": _safe_base(
            external_keepalive_confirmation_required=True,
            external_keepalive_confirmed=False,
        ),
        "stateful_receipt_done_without_postcondition_evidence": _safe_base(
            stateful_controller_receipt_done=True,
            stateful_controller_postcondition_declared=True,
            stateful_controller_postcondition_evidence_written=False,
            stateful_controller_advanced_from_receipt=False,
        ),
        "stateful_receipt_advanced_without_postcondition_evidence": _safe_base(
            stateful_controller_receipt_done=True,
            stateful_controller_postcondition_declared=True,
            stateful_controller_postcondition_evidence_written=False,
            stateful_controller_advanced_from_receipt=True,
        ),
        "controller_delivery_receipt_treated_as_role_completion": _safe_base(
            controller_delivery_receipt_done=True,
            controller_delivery_target_role_wait_started=False,
            controller_delivery_used_as_role_completion=True,
            controller_delivery_missing_role_output_blocker=False,
        ),
        "controller_delivery_receipt_missing_role_output_blocker": _safe_base(
            controller_delivery_receipt_done=True,
            controller_delivery_host_status="delivered",
            controller_delivery_target_role_wait_started=False,
            controller_delivery_used_as_role_completion=False,
            controller_delivery_missing_role_output_blocker=True,
        ),
        "controller_delivery_failed_marked_done": _safe_base(
            controller_delivery_receipt_done=True,
            controller_delivery_host_status="failed_agent_not_found",
            controller_delivery_target_role_wait_started=True,
        ),
        "active_holder_lease_without_host_liveness": _safe_base(
            active_holder_lease_issued=True,
            active_holder_agent_identity_recorded=True,
            active_holder_agent_host_live=False,
            active_holder_packet_role_matches=True,
        ),
        "active_holder_lease_to_wrong_packet_role": _safe_base(
            active_holder_lease_issued=True,
            active_holder_agent_identity_recorded=True,
            active_holder_agent_host_live=True,
            active_holder_packet_role_matches=False,
        ),
        "packet_ledger_write_without_atomic_lock": _safe_base(
            packet_delivered=True,
            packet_ledger_write_atomic=False,
            packet_ledger_write_locked_or_cas=False,
            packet_ledger_readback_validated=True,
        ),
        "packet_ledger_corrupt_read_crashes_daemon": _safe_base(
            packet_ledger_corrupt_read_crashed_daemon=True,
            packet_ledger_corruption_recoverable=False,
        ),
        "valid_router_owned_artifact_not_reclaimed_before_blocker": _safe_base(
            router_owned_artifact_exists=True,
            router_owned_artifact_proof_valid=True,
            router_owned_postcondition_reclaimed_from_artifact=False,
            router_tick_saw_receipt_before_flag=True,
            router_tick_escalated_before_reclaim=True,
            stateful_controller_receipt_done=True,
            stateful_controller_postcondition_declared=True,
            stateful_controller_postcondition_evidence_written=False,
            stateful_controller_advanced_from_receipt=False,
        ),
        "daemon_tick_semicomplete_receipt_escalates_before_reclaim": _safe_base(
            router_owned_artifact_exists=True,
            router_owned_artifact_proof_valid=True,
            router_owned_postcondition_reclaimed_from_artifact=False,
            router_tick_saw_receipt_before_flag=True,
            router_tick_escalated_before_reclaim=True,
        ),
        "router_internal_postcondition_role_wait_dead_end": _safe_base(
            router_internal_postcondition_due=True,
            router_internal_postcondition_inputs_ready=True,
            router_internal_postcondition_materialized=False,
            router_internal_postcondition_blocker_materialized=False,
            router_internal_postcondition_exposed_as_role_wait=True,
            router_internal_postcondition_expected_evidence_exists=False,
            router_internal_postcondition_executable_action_pending=False,
        ),
        "router_internal_postcondition_unmaterialized_after_ready_inputs": _safe_base(
            router_internal_postcondition_due=True,
            router_internal_postcondition_inputs_ready=True,
            router_internal_postcondition_materialized=False,
            router_internal_postcondition_blocker_materialized=False,
            router_internal_postcondition_exposed_as_role_wait=False,
            router_internal_postcondition_expected_evidence_exists=False,
            router_internal_postcondition_executable_action_pending=False,
        ),
        "resolved_obligation_projection_still_live": _safe_base(
            resolved_obligation_evidence_exists=True,
            resolved_obligation_live_passive_wait=True,
            resolved_obligation_live_blocked_reminder=True,
            resolved_obligation_projection_reconciled=False,
        ),
        "role_output_event_missing_file_backed_body": _safe_base(
            role_output_event_submitted=True,
            role_output_event_accepted=True,
            role_output_file_backed_body_path_present=False,
            role_output_body_hash_verified=False,
        ),
        "role_output_status_prepared_used_as_decision": _safe_base(
            role_output_status_prepared_only=True,
            role_output_status_used_as_event_evidence=True,
            role_output_event_accepted=True,
        ),
        "pm_repair_followup_event_unmatchable": _safe_base(
            control_blocker_lane="pm_repair_decision_required",
            control_blocker_target_role="project_manager",
            pm_repair_decision_recorded=True,
            control_blocker_followup_event_matchable=False,
        ),
        "pm_repair_followup_event_not_normalized": _safe_base(
            control_blocker_lane="pm_repair_decision_required",
            control_blocker_target_role="project_manager",
            pm_repair_decision_recorded=True,
            control_blocker_followup_event_matchable=True,
            control_resolution_predicate_normalized=False,
        ),
        "fatal_repair_followup_event_unmatchable": _safe_base(
            control_blocker_lane="fatal_protocol_violation",
            control_blocker_target_role="project_manager",
            pm_repair_decision_recorded=True,
            control_blocker_followup_event_matchable=False,
        ),
        "fatal_repair_followup_event_not_normalized": _safe_base(
            control_blocker_lane="fatal_protocol_violation",
            control_blocker_target_role="project_manager",
            pm_repair_decision_recorded=True,
            control_blocker_followup_event_matchable=True,
            control_resolution_predicate_normalized=False,
        ),
        "pm_repair_reissue_specs_not_materialized": _safe_base(
            control_blocker_lane="pm_repair_decision_required",
            control_blocker_target_role="project_manager",
            pm_repair_decision_recorded=True,
            pm_repair_reissue_spec_written=True,
            pm_repair_reissue_packet_files_materialized=False,
            pm_repair_reissue_packets_registered_in_ledger=False,
            pm_repair_reissue_dispatch_index_updated=False,
        ),
        "pm_repair_success_only_gate_after_unmaterialized_reissue": _safe_base(
            control_blocker_lane="pm_repair_decision_required",
            control_blocker_target_role="project_manager",
            pm_repair_decision_recorded=True,
            pm_repair_reissue_spec_written=True,
            pm_repair_reissue_packet_files_materialized=False,
            pm_repair_allowed_success_only=True,
            pm_repair_non_success_outcome_routable=False,
        ),
        "reviewer_recheck_protocol_blocker_unroutable": _safe_base(
            control_blocker_lane="pm_repair_decision_required",
            control_blocker_target_role="project_manager",
            pm_repair_decision_recorded=True,
            pm_repair_reissue_spec_written=True,
            reviewer_recheck_protocol_blocker_written=True,
            reviewer_recheck_protocol_blocker_routable=False,
            pm_repair_allowed_success_only=True,
            pm_repair_non_success_outcome_routable=False,
        ),
        "result_submitted_repair_target_not_superseded": _safe_base(
            result_submitted_repair_target_seen=True,
            result_submitted_repair_target_replaced=True,
            result_submitted_repair_target_superseded=False,
        ),
        "active_blocker_noncurrent_target_not_blocked": _safe_base(
            active_blocker_points_noncurrent_packet=True,
            current_target_gate_blocks_stale_target=False,
        ),
        "blocked_pm_repair_decision_reused": _safe_base(
            blocked_pm_repair_decision_packet_seen=True,
            blocked_pm_repair_decision_packet_reused=True,
            fresh_pm_repair_decision_packet_issued=False,
        ),
        "blocked_pm_repair_decision_not_reissued": _safe_base(
            blocked_pm_repair_decision_packet_seen=True,
            blocked_pm_repair_decision_packet_reused=False,
            fresh_pm_repair_decision_packet_issued=False,
        ),
        "fallback_responsibility_used": _safe_base(
            fallback_responsibility_used=True,
        ),
        "same_family_staged_effect_expansion_not_stopped": _safe_base(
            staged_effect_same_family_repeated=True,
            same_family_expansion_stopped=False,
        ),
        "repair_transaction_stale_after_success": _safe_base(
            active_repair_transaction_stale=True,
            repair_recheck_pending_action_stale=True,
        ),
        "role_decision_wait_requires_unsatisfied_flag": _safe_base(
            expected_role_decision_requires_unsatisfied_flag=True,
        ),
        "phase_card_missing_required_upstream_source": _safe_base(
            phase_dependency_cards_delivered=True,
            phase_required_sources_complete=False,
        ),
        "delivered_card_phase_context_stale": _safe_base(
            phase_dependency_cards_delivered=True,
            delivered_card_phase_context_fresh=False,
        ),
        "terminal_snapshot_flag_mismatch": _safe_base(
            terminal_snapshot_published=True,
            terminal_snapshot_flags_consistent=False,
        ),
        "child_skill_gate_manifest_review_unsynced": _safe_base(
            child_skill_gate_review_recorded=True,
            child_skill_gate_manifest_synced_with_review=False,
        ),
        "gate_pass_left_active_block": _safe_base(
            child_skill_gate_review_recorded=True,
            child_skill_gate_manifest_synced_with_review=True,
            gate_outcome_block_active=True,
            gate_outcome_block_gate_key="child_skill_gate_manifest",
            gate_outcome_pass_recorded=True,
            gate_outcome_pass_gate_key="child_skill_gate_manifest",
            gate_outcome_same_generation=True,
            gate_outcome_clear_target_matches_pass_gate=True,
        ),
        "gate_pass_cleared_wrong_block": _safe_base(
            child_skill_gate_review_recorded=True,
            child_skill_gate_manifest_synced_with_review=True,
            gate_outcome_block_active=False,
            gate_outcome_block_gate_key="route_check",
            gate_outcome_pass_recorded=True,
            gate_outcome_pass_gate_key="child_skill_gate_manifest",
            gate_outcome_same_generation=True,
            gate_outcome_clear_target_matches_pass_gate=False,
        ),
        "ack_consumed_semantic_wait_lost": _safe_base(
            gate_card_requires_semantic_outcome=True,
            card_ack_consumed=True,
            semantic_gate_wait_exposed_after_ack=False,
        ),
        "pm_impersonates_reviewer_followup": _safe_base(
            control_blocker_lane="pm_repair_decision_required",
            control_blocker_target_role="project_manager",
            pm_repair_decision_recorded=True,
            control_blocker_followup_event_matchable=True,
            followup_event_expected_role="human_like_reviewer",
            followup_event_from_role="project_manager",
        ),
        "no_legal_next_with_valid_role_output": _safe_base(
            valid_role_output_waiting=True,
            no_legal_next_control_blocker_materialized=True,
        ),
        "duplicate_pm_repair_created_new_blocker": _safe_base(
            pm_repair_decision_recorded=True,
            duplicate_pm_repair_decision_seen=True,
            duplicate_repair_created_new_blocker=True,
        ),
        "terminal_heartbeat_cleanup_unproven": _safe_base(
            terminal_continuation_cleanup_recorded=True,
            terminal_host_automation_cleanup_proven=False,
        ),
        "role_output_hash_replay_mismatch": _safe_base(
            role_output_envelopes_recorded=True,
            role_output_hashes_replayable=False,
        ),
        "frontier_stale_after_product_architecture_delivery": _safe_base(
            frontier_fresh_after_stage_advance=False,
        ),
        "display_view_stale_after_product_architecture_delivery": _safe_base(
            product_stage_view_fresh=False,
        ),
        "status_summary_stale": _safe_base(
            status_summary_published=True,
            status_summary_fresh_against_frontier_and_packet=False,
        ),
        "status_summary_leaks_sealed_or_source_fields": _safe_base(
            status_summary_published=True,
            status_summary_metadata_only=False,
        ),
        "status_summary_hides_unresolved_blocker": _safe_base(
            status_summary_published=True,
            status_summary_blocker_state_consistent=False,
        ),
        "controller_user_reporting_policy_missing": _safe_base(
            controller_user_reporting_policy_present=False,
        ),
        "router_action_user_reporting_reminder_missing": _safe_base(
            router_action_user_reporting_reminder_present=False,
        ),
        "controller_table_prompt_user_language_guidance_missing": _safe_base(
            controller_table_prompt_user_language_guidance_present=False,
        ),
        "controller_reporting_budget_missing": _safe_base(
            controller_reporting_budget_present=False,
        ),
        "quiet_internal_progress_user_chatter": _safe_base(
            quiet_internal_progress_silent=False,
        ),
        "routine_aside_relayed_to_user": _safe_base(
            routine_process_aside_relayed_to_user=True,
        ),
        "user_report_not_limited_to_meaningful_change": _safe_base(
            user_report_limited_to_meaningful_change=False,
        ),
        "controller_user_report_internal_metadata_exposed": _safe_base(
            user_report_internal_metadata_exposed=True,
        ),
        "router_action_user_reporting_reminder_displayed": _safe_base(
            router_action_user_reporting_reminder_displayed_to_user=True,
        ),
        "status_summary_missing_progress_facts": _safe_base(
            status_summary_progress_facts_present=False,
        ),
        "status_summary_progress_counts_invalid": _safe_base(
            status_summary_progress_counts_valid=False,
        ),
        "status_summary_progress_exposes_internal_metadata": _safe_base(
            status_summary_progress_metadata_only=False,
        ),
        "route_process_check_on_empty_route_draft": _safe_base(
            route_draft_has_nodes=False,
            route_process_check_card_delivered=True,
        ),
        "route_process_check_on_shadow_route_draft": _safe_base(
            route_draft_has_nodes=True,
            route_draft_single_canonical_source=False,
            route_draft_shadow_source_used=True,
            route_process_check_card_delivered=True,
        ),
        "route_draft_repair_kept_stale_route_checks": _safe_base(
            route_draft_repaired_after_check=True,
            route_review_flags_reset_after_draft_repair=False,
            route_process_check_card_delivered=True,
            route_process_check_passed=True,
        ),
        "node_local_block_route_mutated_without_reason": _safe_base(
            review_block_observed=True,
            review_block_scope="node_local",
            pm_selected_route_mutation=True,
            current_node_cannot_contain_repair_reason_present=False,
        ),
        "same_node_repair_path_unroutable": _safe_base(
            review_block_observed=True,
            review_block_scope="node_local",
            pm_selected_same_node_repair=True,
            same_node_repair_path_routable=False,
        ),
        "route_invalidating_block_handled_as_same_node_repair": _safe_base(
            review_block_observed=True,
            review_block_scope="route_invalidating",
            pm_selected_same_node_repair=True,
        ),
        "same_node_repair_reuses_stale_blocked_evidence": _safe_base(
            review_block_observed=True,
            review_block_scope="node_local",
            pm_selected_same_node_repair=True,
            fresh_repair_evidence_written=False,
            stale_blocked_evidence_reused_as_pass=True,
        ),
        "same_node_repair_without_reviewer_recheck": _safe_base(
            review_block_observed=True,
            review_block_scope="node_local",
            pm_selected_same_node_repair=True,
            fresh_repair_evidence_written=True,
            same_review_class_rechecked_repair=False,
            role_work_wait_pending=True,
        ),
        "route_mutation_without_current_node_incapability_reason": _safe_base(
            review_block_observed=True,
            review_block_scope="route_invalidating",
            pm_selected_route_mutation=True,
            current_node_cannot_contain_repair_reason_present=False,
        ),
        "route_mutation_continues_without_route_recheck": _safe_base(
            review_block_observed=True,
            review_block_scope="route_invalidating",
            pm_selected_route_mutation=True,
            current_node_cannot_contain_repair_reason_present=True,
            route_draft_repaired_after_check=False,
            role_work_wait_pending=True,
        ),
        "multiple_active_tasks_without_explicit_active_set": _safe_base(
            multiple_running_index_entries_visible=True,
            active_task_authority="current_focus_only",
        ),
        "role_work_wait_without_status_packet_read": _safe_base(
            role_work_wait_pending=True,
            role_work_status_packet_exists=True,
            role_work_status_packet_read_allowed=False,
            role_work_status_visibility_grant="none",
        ),
        "role_work_status_grants_packet_dir": _safe_base(
            role_work_wait_pending=True,
            role_work_status_packet_exists=True,
            role_work_status_packet_read_allowed=True,
            role_work_status_visibility_grant="packet_dir",
        ),
        "role_work_status_leaks_findings": _safe_base(
            role_work_wait_pending=True,
            role_work_status_packet_exists=True,
            role_work_status_packet_read_allowed=True,
            role_work_status_visibility_grant="single_status_packet",
            role_work_status_message_safe=False,
        ),
        "role_work_progress_manual_write": _safe_base(
            role_work_wait_pending=True,
            role_work_progress_observed=True,
            role_work_progress_runtime_written=False,
        ),
        "role_work_progress_nonnumeric": _safe_base(
            role_work_wait_pending=True,
            role_work_progress_observed=True,
            role_work_progress_numeric=False,
        ),
        "progress_default_packet_only": _safe_base(
            role_work_wait_pending=True,
            work_package_progress_default_scope="packet_only",
        ),
        "role_output_progress_prompt_missing": _safe_base(
            role_output_wait_pending=True,
            role_output_progress_prompt_inherited=False,
        ),
        "role_output_wait_without_status_packet_read": _safe_base(
            role_output_wait_pending=True,
            role_output_status_packet_exists=True,
            role_output_status_packet_read_allowed=False,
            role_output_status_visibility_grant="none",
        ),
        "role_output_status_grants_output_dir": _safe_base(
            role_output_wait_pending=True,
            role_output_status_packet_exists=True,
            role_output_status_packet_read_allowed=True,
            role_output_status_visibility_grant="output_dir",
        ),
        "role_output_status_leaks_findings": _safe_base(
            role_output_wait_pending=True,
            role_output_status_packet_exists=True,
            role_output_status_packet_read_allowed=True,
            role_output_status_visibility_grant="single_status_packet",
            role_output_status_message_safe=False,
        ),
        "role_output_progress_manual_write": _safe_base(
            role_output_wait_pending=True,
            role_output_progress_observed=True,
            role_output_progress_runtime_written=False,
        ),
        "role_output_progress_nonnumeric": _safe_base(
            role_output_wait_pending=True,
            role_output_progress_observed=True,
            role_output_progress_numeric=False,
        ),
        "progress_status_used_as_decision": _safe_base(
            role_output_wait_pending=True,
            role_output_progress_observed=True,
            progress_status_used_as_decision_evidence=True,
        ),
        "optimized_transaction_without_hash_check": _safe_base(
            mode="optimized",
            optimized_relay_transaction=True,
            optimized_transaction_records_delivery=True,
            optimized_transaction_records_open_receipts=True,
            optimized_transaction_records_result_return=True,
            hash_verified=False,
        ),
        "optimized_ack_without_role_check": _safe_base(
            optimized_card_ack_transaction=True,
            card_ack_validated=True,
            card_ack_role_checked=False,
            card_ack_hash_checked=True,
        ),
        "optimized_ack_without_hash_check": _safe_base(
            optimized_card_ack_transaction=True,
            card_ack_validated=True,
            card_ack_role_checked=True,
            card_ack_hash_checked=False,
        ),
        "valid_card_ack_file_present_role_event_blocked": _safe_base(
            pending_card_return_kind="system_card",
            pending_card_return_ack_file_present=True,
            pending_card_return_ack_valid=True,
            pending_card_return_ack_role_checked=True,
            pending_card_return_ack_hash_checked=True,
            pending_card_return_bundle_receipts_complete=True,
            card_return_ledger_resolved=False,
            role_event_arrived_while_ack_pending=True,
            pre_event_card_ack_auto_consumed=False,
            role_event_blocked_by_unresolved_card_return=True,
        ),
        "valid_card_bundle_ack_file_present_role_event_blocked": _safe_base(
            pending_card_return_kind="system_card_bundle",
            pending_card_return_ack_file_present=True,
            pending_card_return_ack_valid=True,
            pending_card_return_ack_role_checked=True,
            pending_card_return_ack_hash_checked=True,
            pending_card_return_bundle_receipts_complete=True,
            card_return_ledger_resolved=False,
            role_event_arrived_while_ack_pending=True,
            pre_event_card_ack_auto_consumed=False,
            role_event_blocked_by_unresolved_card_return=True,
        ),
        "pre_event_ack_auto_consumed_without_validation": _safe_base(
            pending_card_return_kind="system_card_bundle",
            pending_card_return_ack_file_present=True,
            pending_card_return_ack_valid=True,
            pending_card_return_ack_role_checked=True,
            pending_card_return_ack_hash_checked=False,
            pending_card_return_bundle_receipts_complete=True,
            card_return_ledger_resolved=True,
            role_event_arrived_while_ack_pending=True,
            pre_event_card_ack_auto_consumed=True,
            role_event_blocked_by_unresolved_card_return=False,
        ),
        "pre_event_invalid_ack_accepted_role_event": _safe_base(
            pending_card_return_kind="system_card",
            pending_card_return_ack_file_present=True,
            pending_card_return_ack_valid=False,
            pending_card_return_ack_role_checked=True,
            pending_card_return_ack_hash_checked=True,
            pending_card_return_bundle_receipts_complete=True,
            card_return_ledger_resolved=False,
            role_event_arrived_while_ack_pending=True,
            pre_event_card_ack_auto_consumed=False,
            role_event_blocked_by_unresolved_card_return=False,
            role_event_accepted_after_pre_event_ack=True,
        ),
        "pre_event_incomplete_bundle_ack_accepted_role_event": _safe_base(
            pending_card_return_kind="system_card_bundle",
            pending_card_return_ack_file_present=True,
            pending_card_return_ack_valid=True,
            pending_card_return_ack_role_checked=True,
            pending_card_return_ack_hash_checked=True,
            pending_card_return_bundle_receipts_complete=False,
            card_return_ledger_resolved=False,
            role_event_arrived_while_ack_pending=True,
            pre_event_card_ack_auto_consumed=False,
            role_event_blocked_by_unresolved_card_return=False,
            role_event_accepted_after_pre_event_ack=True,
        ),
        "pre_event_ack_cleared_role_wait_authority": _safe_base(
            pending_card_return_kind="system_card_bundle",
            pending_card_return_ack_file_present=True,
            pending_card_return_ack_valid=True,
            pending_card_return_ack_role_checked=True,
            pending_card_return_ack_hash_checked=True,
            pending_card_return_bundle_receipts_complete=True,
            card_return_ledger_resolved=True,
            role_event_arrived_while_ack_pending=True,
            pre_event_card_ack_auto_consumed=True,
            card_ack_consumed=True,
            role_event_blocked_by_unresolved_card_return=False,
            pre_event_role_wait_authority_present=True,
            pre_event_role_wait_authority_preserved=False,
        ),
        "pre_event_ack_wrote_duplicate_completed_return": _safe_base(
            pending_card_return_kind="system_card_bundle",
            pending_card_return_ack_file_present=True,
            pending_card_return_ack_valid=True,
            pending_card_return_ack_role_checked=True,
            pending_card_return_ack_hash_checked=True,
            pending_card_return_bundle_receipts_complete=True,
            card_return_ledger_resolved=True,
            role_event_arrived_while_ack_pending=True,
            pre_event_card_ack_auto_consumed=True,
            card_ack_consumed=True,
            role_event_blocked_by_unresolved_card_return=False,
            duplicate_completed_return_written=True,
        ),
        "pre_event_ack_selected_wrong_pending_return": _safe_base(
            pending_card_return_kind="system_card_bundle",
            pending_card_return_ack_file_present=True,
            pending_card_return_ack_valid=True,
            pending_card_return_ack_role_checked=True,
            pending_card_return_ack_hash_checked=True,
            pending_card_return_bundle_receipts_complete=True,
            card_return_ledger_resolved=True,
            role_event_arrived_while_ack_pending=True,
            pre_event_card_ack_auto_consumed=True,
            card_ack_consumed=True,
            role_event_blocked_by_unresolved_card_return=False,
            pre_event_ack_selected_matching_pending_return=False,
        ),
        "missing_ack_report_accepted_without_ack": _safe_base(
            pending_card_return_ack_file_present=False,
            card_return_ledger_resolved=False,
            role_event_arrived_while_ack_pending=True,
            missing_ack_report_arrived=True,
            missing_ack_report_event_flag_set=True,
            role_event_accepted_after_pre_event_ack=True,
            report_submitted_after_valid_ack=False,
        ),
        "missing_ack_recovery_without_quarantine": _safe_base(
            pending_card_return_ack_file_present=False,
            card_return_ledger_resolved=False,
            role_event_arrived_while_ack_pending=True,
            missing_ack_report_arrived=True,
            missing_ack_report_quarantined=False,
            same_role_ack_recovery_requested=True,
        ),
        "quarantined_report_used_as_evidence": _safe_base(
            missing_ack_report_arrived=True,
            missing_ack_report_quarantined=True,
            quarantined_report_used_as_evidence=True,
        ),
        "old_pre_ack_report_revived_after_ack": _safe_base(
            missing_ack_report_arrived=True,
            missing_ack_report_quarantined=True,
            card_return_ledger_resolved=True,
            card_ack_consumed=True,
            role_event_accepted_after_pre_event_ack=True,
            old_pre_ack_report_revived=True,
            report_submitted_after_valid_ack=False,
        ),
        "first_missing_ack_escalated_to_pm_blocker": _safe_base(
            pending_card_return_ack_file_present=False,
            card_return_ledger_resolved=False,
            missing_ack_report_arrived=True,
            pending_return_dependency_matches_report=True,
            repeated_ack_recovery_failed=False,
            missing_ack_generic_pm_blocker_created=True,
        ),
        "unrelated_pending_ack_quarantined_report": _safe_base(
            pending_card_return_ack_file_present=False,
            card_return_ledger_resolved=False,
            missing_ack_report_arrived=True,
            missing_ack_report_quarantined=True,
            pending_return_dependency_matches_report=False,
        ),
        "repeated_missing_ack_recovery_not_escalated": _safe_base(
            pending_card_return_ack_file_present=False,
            card_return_ledger_resolved=False,
            missing_ack_report_arrived=True,
            pending_return_dependency_matches_report=True,
            repeated_ack_recovery_failed=True,
            pm_escalated_after_repeated_ack_failure=False,
        ),
        "pending_wait_reconciled_from_chat": _safe_base(
            pending_wait_reconciled=True,
            pending_wait_reconciliation_from_chat=True,
        ),
        "pending_wait_reconciled_without_status_packet": _safe_base(
            pending_wait_reconciled=True,
            pending_wait_reconciliation_uses_packet_ledger=True,
            pending_wait_reconciliation_uses_status_packet=False,
            pending_wait_reconciliation_role_verified=True,
            pending_wait_reconciliation_hash_verified=True,
        ),
        "pending_wait_not_reconciled_despite_existing_result": _safe_base(
            stale_wait_pending=True,
            durable_result_evidence_exists=True,
            pending_wait_reconciled=False,
        ),
        "stale_wait_reissued_after_existing_result": _safe_base(
            stale_wait_pending=True,
            durable_result_evidence_exists=True,
            pending_wait_reconciled=False,
            stale_wait_reissued_without_reconciliation=True,
        ),
        "partial_batch_result_count_not_refreshed": _safe_base(
            partial_batch_active=True,
            partial_batch_packet_count=2,
            partial_batch_results_returned=1,
            partial_batch_result_refreshed_from_members=False,
        ),
        "partial_batch_missing_role_summary_stale": _safe_base(
            partial_batch_active=True,
            partial_batch_packet_count=2,
            partial_batch_results_returned=1,
            partial_batch_missing_role_summary_accurate=False,
        ),
        "status_summary_waits_for_completed_partial_batch_role": _safe_base(
            status_summary_published=True,
            partial_batch_active=True,
            partial_batch_packet_count=2,
            partial_batch_results_returned=1,
            status_summary_waiting_role_matches_partial_batch=False,
        ),
        "duplicate_result_reconciliation_incremented_count": _safe_base(
            pending_wait_reconciled=True,
            partial_batch_active=True,
            partial_batch_packet_count=2,
            partial_batch_results_returned=1,
            duplicate_reconciliation_incremented_count=True,
        ),
        "role_work_result_routed_to_reviewer": _safe_base(
            pm_role_work_result_normalized=True,
            pm_role_work_result_routes_to_pm=False,
            current_node_result_routes_to_pm=True,
        ),
        "current_node_result_routed_to_reviewer": _safe_base(
            pm_role_work_result_normalized=True,
            pm_role_work_result_routes_to_pm=True,
            current_node_result_routes_to_pm=False,
        ),
        "pm_decides_from_incomplete_model_miss_report": _safe_base(
            model_miss_flowguard_operator_report_complete=False,
            model_miss_pm_decision_from_single_report=True,
        ),
        "role_memory_used_as_completion_authority": _safe_base(
            role_memory_delta_written=True,
            role_memory_used_for_authority=True,
        ),
        "operation_replay_reuses_controller_action_id": _safe_base(
            operation_replay_fresh_controller_action_id=False,
        ),
        "operation_replay_targets_superseded_generation": _safe_base(
            operation_replay_targets_current_generation=False,
        ),
        "material_result_relay_replay_without_ledger_authority": _safe_base(
            operation_replay_ledger_io_authorized=False,
        ),
        "controller_repair_work_packet_receipt_not_folded": _safe_base(
            controller_repair_work_packet_receipt_folded=False,
        ),
        "controller_repair_work_packet_facade_export_missing": _safe_base(
            controller_repair_work_packet_facade_exported=False,
        ),
        "pm_material_disposition_generation_blind": _safe_base(
            pm_material_disposition_generation_scoped=False,
        ),
        "stale_pm_material_disposition_restored": _safe_base(
            stale_pm_material_disposition_restored=True,
        ),
        "material_progress_flags_not_generation_scoped": _safe_base(
            material_progress_projection_generation_scoped=False,
            material_global_progress_flags_match_active_generation=False,
        ),
        "material_next_action_uses_stale_global_flags": _safe_base(
            material_next_action_derived_from_active_batch=False,
        ),
        "material_reissue_keeps_stale_progress_flags": _safe_base(
            material_reissue_clears_or_quarantines_stale_progress_flags=False,
        ),
        "stale_material_progress_flags_resurrected_by_save": _safe_base(
            stale_run_state_save_preserves_material_generation_flag_clear=False,
        ),
        "material_dispatch_block_stale_generation": _safe_base(
            material_dispatch_block_matches_active_generation=False,
        ),
        "role_output_duplicate_not_deduped": _safe_base(
            role_output_event_deduped_by_body_ref=False,
            duplicate_role_event_side_effect_written=True,
        ),
        "role_output_current_generation_short_circuited_by_global_flag": _safe_base(
            role_output_current_generation_not_short_circuited_by_global_flag=False,
        ),
        "pm_package_disposition_reconciled_without_domain_commit": _safe_base(
            role_output_package_disposition_domain_first_commit=False,
        ),
        "pm_package_disposition_not_semantic_deduped": _safe_base(
            pm_package_disposition_semantic_identity_deduped=False,
        ),
        "pm_package_disposition_conflict_unchecked": _safe_base(
            pm_package_disposition_body_hash_conflict_checked=False,
        ),
        "pm_package_repair_owned_conflict_replay_not_quarantined": _safe_base(
            pm_package_repair_owned_conflict_replay_quarantined=False,
        ),
        "pm_package_repair_owned_conflict_replay_lost_wait": _safe_base(
            pm_package_repair_owned_conflict_preserves_wait=False,
        ),
        "pm_package_repair_owned_conflict_replay_crashed_daemon": _safe_base(
            pm_package_repair_owned_conflict_crashed_daemon=True,
        ),
        "pm_package_repair_owned_conflict_accepted_as_success": _safe_base(
            pm_package_repair_owned_conflict_accepted_as_success=True,
        ),
        "pm_package_repair_owned_conflict_duplicate_blocker": _safe_base(
            pm_package_repair_owned_conflict_duplicate_blocker=True,
        ),
        "pm_package_stale_unowned_conflict_replay_not_quarantined": _safe_base(
            pm_package_stale_unowned_conflict_replay_quarantined=False,
        ),
        "pm_package_stale_unowned_conflict_replay_reverted_canonical": _safe_base(
            pm_package_stale_unowned_conflict_preserves_canonical=False,
        ),
        "pm_package_stale_unowned_conflict_replay_crashed_daemon": _safe_base(
            pm_package_stale_unowned_conflict_crashed_daemon=True,
        ),
        "pm_package_stale_unowned_conflict_accepted_as_success": _safe_base(
            pm_package_stale_unowned_conflict_accepted_as_success=True,
        ),
        "pm_package_disposition_packet_outcomes_missing": _safe_base(
            pm_package_packet_outcomes_recorded=False,
        ),
        "pm_package_authority_split_lost_wait": _safe_base(
            pm_package_authority_split_preserves_wait=False,
            pm_package_authority_split_repairs_domain_commit=False,
        ),
        "pm_package_authority_split_crashed_daemon": _safe_base(
            pm_package_authority_split_crashed_daemon=True,
        ),
        "pm_package_authority_split_accepted_as_success": _safe_base(
            pm_package_authority_split_accepted_as_success=True,
        ),
        "packet_result_author_identity_not_replayable": _safe_base(
            packet_result_author_identity_replayable=False,
            packet_result_author_matches_current_role=False,
        ),
        "break_glass_patch_validation_pending": _safe_base(
            break_glass_patch_validation_finalized=False,
        ),
        "controller_reads_sealed_body": _safe_base(controller_read_sealed_body=True),
    }


__all__ = [
    "hazard_states",
]
