"""Known-bad hazards for the FlowPilot persistent Router daemon model."""

from __future__ import annotations

from dataclasses import replace

from flowpilot_persistent_router_daemon_model_state import State


def hazard_states() -> dict[str, State]:
    safe_active = State(
        lifecycle="active",
        formal_startup_started=True,
        startup_daemon_step_completed=True,
        daemon_mode_enabled=True,
        daemon_alive=True,
        daemon_lock_state="live",
        daemon_writer_count=1,
        daemon_tick_seconds=1,
        controller_core_loaded=True,
        startup_controller_receipt_present=True,
        startup_controller_receipt_consumed=True,
        startup_bootstrap_flag_current=True,
        startup_router_row_reconciled=True,
        startup_next_row_scheduled_after_receipt=True,
        controller_attached=True,
        roles_live=True,
        manual_resume_binding_active=True,
        route_work_allowed=True,
    )
    return {
        "ack_wait_without_daemon": replace(
            safe_active,
            daemon_alive=False,
            daemon_lock_state="none",
            daemon_writer_count=0,
            current_wait="ack",
            mailbox_evidence_present=True,
        ),
        "duplicate_router_writers": replace(
            safe_active,
            daemon_writer_count=2,
            daemon_lock_state="duplicate",
        ),
        "router_scheduler_ledger_corrupted_by_partial_write": replace(
            safe_active,
            router_scheduler_ledger_valid_json=False,
            durable_ledger_writes_atomic=False,
            daemon_crashed_after_ledger_decode_error=True,
        ),
        "fresh_runtime_ledger_write_lock_reported_corrupt": replace(
            safe_active,
            router_scheduler_ledger_valid_json=False,
            runtime_ledger_write_lock_fresh=True,
            runtime_ledger_write_lock_owner="live",
            daemon_deferred_for_runtime_ledger_write=False,
            daemon_crashed_after_ledger_decode_error=True,
        ),
        "nested_write_lock_wait_became_daemon_error": replace(
            safe_active,
            nested_wait_status_write_lock=True,
            daemon_deferred_after_nested_write_lock=False,
            daemon_crashed_after_ledger_decode_error=True,
        ),
        "runtime_write_lock_promoted_to_pm_semantic_blocker": replace(
            safe_active,
            runtime_write_lock_promoted_to_pm_semantic_blocker=True,
            runtime_write_lock_mechanical_settlement_recorded=False,
        ),
        "runtime_write_lock_wait_missing_mechanical_evidence": replace(
            safe_active,
            daemon_deferred_for_runtime_ledger_write=True,
            runtime_write_lock_mechanical_settlement_recorded=False,
        ),
        "self_owned_stale_write_lock_deferred_as_live_owner": replace(
            safe_active,
            runtime_ledger_write_lock_fresh=False,
            runtime_ledger_write_lock_stale=True,
            runtime_ledger_write_lock_owner="self",
            runtime_write_lock_target_valid_json=True,
            runtime_write_lock_tmp_file_present=False,
            daemon_deferred_for_runtime_ledger_write=True,
            self_owned_write_lock_takeover_recorded=False,
            runtime_write_lock_cleanup_failure_recorded=False,
        ),
        "self_owned_stale_write_lock_missing_cleanup_diagnostics": replace(
            safe_active,
            runtime_ledger_write_lock_fresh=False,
            runtime_ledger_write_lock_stale=False,
            runtime_ledger_write_lock_owner="none",
            self_owned_write_lock_takeover_recorded=True,
            self_owned_write_lock_recovery_rejoined_flow=True,
            runtime_write_lock_cleanup_failure_recorded=False,
        ),
        "self_owned_stale_write_lock_cleared_with_tmp_file_present": replace(
            safe_active,
            runtime_ledger_write_lock_fresh=False,
            runtime_ledger_write_lock_stale=False,
            runtime_ledger_write_lock_owner="none",
            runtime_write_lock_target_valid_json=True,
            runtime_write_lock_tmp_file_present=True,
            self_owned_write_lock_takeover_recorded=True,
            self_owned_write_lock_recovery_rejoined_flow=True,
            runtime_write_lock_cleanup_failure_recorded=True,
        ),
        "runtime_write_lock_cleanup_error_swallowed": replace(
            safe_active,
            runtime_write_lock_cleanup_error_swallowed=True,
            runtime_write_lock_cleanup_failure_recorded=False,
        ),
        "self_owned_stale_write_lock_recovery_did_not_rejoin_flow": replace(
            safe_active,
            runtime_ledger_write_lock_fresh=False,
            runtime_ledger_write_lock_stale=False,
            runtime_ledger_write_lock_owner="none",
            self_owned_write_lock_takeover_recorded=True,
            self_owned_write_lock_recovery_rejoined_flow=False,
            runtime_write_lock_cleanup_failure_recorded=True,
        ),
        "fresh_dead_owner_write_lock_deferred_as_live_writer": replace(
            safe_active,
            router_scheduler_ledger_valid_json=False,
            runtime_ledger_write_lock_fresh=True,
            runtime_ledger_write_lock_owner="dead",
            daemon_deferred_for_runtime_ledger_write=True,
            writer_died_while_holding_runtime_lock=True,
            dead_owner_write_lock_takeover_recorded=False,
        ),
        "fresh_dead_owner_write_lock_missing_takeover_evidence": replace(
            safe_active,
            router_scheduler_ledger_valid_json=False,
            runtime_ledger_write_lock_fresh=True,
            runtime_ledger_write_lock_owner="dead",
            daemon_deferred_for_runtime_ledger_write=False,
            writer_died_while_holding_runtime_lock=True,
            dead_owner_write_lock_takeover_recorded=False,
        ),
        "writer_died_holding_runtime_lock_without_incident": replace(
            safe_active,
            writer_died_while_holding_runtime_lock=True,
            dead_owner_write_lock_takeover_recorded=False,
        ),
        "dead_owner_recovery_did_not_rejoin_flow": replace(
            safe_active,
            writer_died_while_holding_runtime_lock=True,
            dead_owner_write_lock_takeover_recorded=True,
            dead_owner_recovery_rejoined_flow=False,
        ),
        "controller_action_ledger_corrupted_by_partial_write": replace(
            safe_active,
            controller_action_ledger_valid_json=False,
            durable_ledger_writes_atomic=False,
        ),
        "daemon_status_active_after_lock_error": replace(
            safe_active,
            daemon_alive=False,
            daemon_lock_state="error",
            daemon_writer_count=0,
            daemon_status_active_after_lock_error=True,
        ),
        "daemon_status_active_without_process": replace(
            safe_active,
            daemon_alive=False,
            daemon_lock_state="live",
            daemon_writer_count=1,
            daemon_status_active_without_process=True,
        ),
        "router_scheduler_ledger_multi_writer": replace(
            safe_active,
            router_scheduler_single_writer=False,
            daemon_writer_count=2,
            daemon_lock_state="duplicate",
        ),
        "duplicate_ack_consumption": replace(
            safe_active,
            current_wait="none",
            mailbox_evidence_consumed=True,
            mailbox_consumption_count=2,
        ),
        "controller_done_without_receipt": replace(
            safe_active,
            controller_action_pending=True,
            controller_action_done=True,
            controller_receipt_present=False,
            controller_marked_done_without_receipt=True,
        ),
        "controller_stopped_at_ordinary_wait": replace(
            safe_active,
            current_wait="ack",
            wait_target_metadata_present=True,
            wait_target_names_role=True,
            wait_target_expected_evidence_visible=True,
            wait_target_reminder_text_present=True,
            controller_attached=False,
            controller_finaled_at_wait=True,
        ),
        "foreground_controller_ended_during_live_daemon_wait": replace(
            safe_active,
            current_wait="report",
            wait_target_metadata_present=True,
            wait_target_names_role=True,
            wait_target_expected_evidence_visible=True,
            wait_target_reminder_text_present=True,
            foreground_standby_active=False,
            foreground_controller_ended_turn_while_daemon_waiting=True,
        ),
        "role_wait_missing_wait_target_metadata": replace(
            safe_active,
            current_wait="report",
            wait_target_metadata_present=False,
            wait_target_names_role=False,
            wait_target_expected_evidence_visible=False,
            wait_target_reminder_text_present=False,
        ),
        "report_reminder_without_fresh_liveness_probe": replace(
            safe_active,
            current_wait="report",
            wait_target_metadata_present=True,
            wait_target_names_role=True,
            wait_target_expected_evidence_visible=True,
            wait_target_reminder_text_present=True,
            report_reminder_sent=True,
            liveness_check_required=True,
            liveness_probe_fresh=False,
        ),
        "wait_target_reminder_without_controller_action": replace(
            safe_active,
            current_wait="ack",
            wait_target_metadata_present=True,
            wait_target_names_role=True,
            wait_target_expected_evidence_visible=True,
            wait_target_reminder_text_present=True,
            ack_wait_age_minutes=3,
            ack_wait_reminder_sent=True,
            wait_target_reminder_controller_action_ready=False,
            wait_target_reminder_receipt_recorded=False,
            wait_target_reminder_updates_wait_metadata=False,
        ),
        "cached_liveness_trusted_as_current_truth": replace(
            safe_active,
            current_wait="report",
            wait_target_metadata_present=True,
            wait_target_names_role=True,
            wait_target_expected_evidence_visible=True,
            wait_target_reminder_text_present=True,
            stale_liveness_cached_as_truth=True,
        ),
        "ack_wait_ten_minutes_without_blocker": replace(
            safe_active,
            current_wait="ack",
            wait_target_metadata_present=True,
            wait_target_names_role=True,
            wait_target_expected_evidence_visible=True,
            wait_target_reminder_text_present=True,
            ack_wait_age_minutes=10,
            ack_wait_reminder_sent=True,
            ack_wait_blocker_recorded=False,
            mailbox_evidence_present=False,
        ),
        "lost_role_without_pm_blocker": replace(
            safe_active,
            current_wait="report",
            wait_target_metadata_present=True,
            wait_target_names_role=True,
            wait_target_expected_evidence_visible=True,
            wait_target_reminder_text_present=True,
            report_reminder_sent=True,
            liveness_check_required=True,
            liveness_probe_fresh=True,
            liveness_probe_outcome="lost",
            role_liveness_blocker_recorded=False,
        ),
        "recorded_external_event_left_wait_row_open": replace(
            safe_active,
            current_wait="report",
            event_wait_action_open=True,
            external_event_recorded=True,
            external_event_matches_wait=True,
            event_wait_closed_by_router=False,
            stale_event_wait_row_open=True,
            wait_target_metadata_present=True,
            wait_target_names_role=True,
            wait_target_expected_evidence_visible=True,
            wait_target_reminder_text_present=True,
        ),
        "next_wait_opened_before_satisfied_wait_closed": replace(
            safe_active,
            current_wait="report",
            event_wait_action_open=True,
            external_event_recorded=True,
            external_event_matches_wait=True,
            event_wait_closed_by_router=False,
            stale_event_wait_row_open=True,
            next_wait_opened_before_event_wait_closed=True,
            wait_target_metadata_present=True,
            wait_target_names_role=True,
            wait_target_expected_evidence_visible=True,
            wait_target_reminder_text_present=True,
        ),
        "controller_closed_external_event_wait": replace(
            safe_active,
            current_wait="none",
            event_wait_action_open=False,
            external_event_recorded=True,
            external_event_matches_wait=True,
            event_wait_closed_by_router=False,
            controller_closed_event_wait=True,
        ),
        "controller_local_wait_reminded_itself": replace(
            safe_active,
            current_wait="controller_local",
            wait_target_metadata_present=True,
            wait_target_expected_evidence_visible=True,
            controller_reminded_itself=True,
        ),
        "packet_holder_projection_missing_current_work": replace(
            safe_active,
            current_wait="none",
            unsupported_historical_waiting_for_role_null=True,
            active_packet_holder="project_manager",
            packet_holder_projection_needed=True,
            current_work_owner_kind="none",
            current_work_owner_key="",
            current_work_task_visible=False,
            current_work_source="none",
        ),
        "passive_reconciliation_projection_missing_current_work": replace(
            safe_active,
            current_wait="none",
            unsupported_historical_waiting_for_role_null=True,
            passive_reconciliation_wait_open=True,
            current_work_owner_kind="none",
            current_work_owner_key="",
            current_work_task_visible=False,
            current_work_source="none",
        ),
        "router_internal_projection_missing_current_work": replace(
            safe_active,
            current_wait="none",
            unsupported_historical_waiting_for_role_null=True,
            router_internal_projection_needed=True,
            current_work_owner_kind="none",
            current_work_owner_key="",
            current_work_task_visible=False,
            current_work_source="none",
        ),
        "foreground_controller_ended_with_pending_controller_action": replace(
            safe_active,
            current_wait="controller_receipt",
            controller_action_pending=True,
            controller_action_ready=True,
            controller_receipt_present=False,
            foreground_controller_ended_while_controller_action_pending=True,
        ),
        "foreground_controller_ended_while_daemon_active_no_action": replace(
            safe_active,
            current_wait="none",
            controller_action_pending=False,
            controller_action_ready=False,
            controller_attached=False,
            foreground_controller_ended_while_daemon_active_no_action=True,
        ),
        "router_cleared_controller_receipt_without_internal_fact": replace(
            safe_active,
            current_wait="none",
            controller_action_done=True,
            controller_receipt_present=True,
            controller_rescanned_after_receipt=True,
            router_internal_action_fact_current=False,
            router_internal_fact_updated_from_receipt=False,
            router_cleared_pending_without_internal_fact=True,
        ),
        "startup_done_receipt_reissued_from_stale_bootstrap_pending": replace(
            safe_active,
            controller_core_loaded=False,
            controller_attached=False,
            route_work_allowed=False,
            startup_bootstrap_pending_action_open=True,
            startup_controller_receipt_present=True,
            startup_controller_receipt_consumed=True,
            startup_bootstrap_flag_current=False,
            startup_router_row_reconciled=False,
            startup_next_row_scheduled_after_receipt=False,
            startup_same_action_reissue_count=2,
        ),
        "stateful_controller_receipt_done_without_postcondition_evidence": replace(
            safe_active,
            current_wait="controller_receipt",
            controller_action_pending=True,
            controller_action_ready=True,
            controller_action_requires_stateful_postcondition=True,
            controller_action_done=False,
            controller_receipt_present=True,
            controller_stateful_postcondition_evidence_written=False,
            controller_boundary_confirmation_written=False,
            controller_role_confirmed=False,
        ),
        "stateful_missing_deliverable_escalated_before_repair_budget": replace(
            safe_active,
            current_wait="controller_receipt",
            controller_action_pending=True,
            controller_action_ready=True,
            controller_action_requires_stateful_postcondition=True,
            controller_action_done=False,
            controller_receipt_present=True,
            controller_stateful_postcondition_evidence_written=False,
            controller_boundary_confirmation_written=False,
            controller_role_confirmed=False,
            controller_missing_deliverable_repair_attempts=1,
            controller_missing_deliverable_repair_failed_receipts=1,
            controller_missing_deliverable_blocker_recorded=True,
            controller_missing_deliverable_escalated_before_budget=True,
        ),
        "stateful_missing_deliverable_exhausted_without_blocker": replace(
            safe_active,
            current_wait="controller_receipt",
            controller_action_pending=True,
            controller_action_ready=True,
            controller_action_requires_stateful_postcondition=True,
            controller_action_done=False,
            controller_receipt_present=True,
            controller_stateful_postcondition_evidence_written=False,
            controller_boundary_confirmation_written=False,
            controller_role_confirmed=False,
            controller_missing_deliverable_repair_pending=False,
            controller_missing_deliverable_repair_attempts=2,
            controller_missing_deliverable_repair_failed_receipts=2,
            controller_missing_deliverable_blocker_recorded=False,
        ),
        "stateful_missing_deliverable_blocker_while_second_repair_pending": replace(
            safe_active,
            current_wait="controller_receipt",
            controller_action_pending=True,
            controller_action_ready=True,
            controller_action_requires_stateful_postcondition=True,
            controller_action_done=False,
            controller_receipt_present=True,
            controller_stateful_postcondition_evidence_written=False,
            controller_boundary_confirmation_written=False,
            controller_role_confirmed=False,
            controller_missing_deliverable_repair_pending=True,
            controller_missing_deliverable_repair_attempts=2,
            controller_missing_deliverable_repair_failed_receipts=1,
            controller_missing_deliverable_pending_attempt=2,
            controller_missing_deliverable_blocker_recorded=True,
        ),
        "stateful_missing_deliverable_issue_count_treated_as_failure_count": replace(
            safe_active,
            current_wait="controller_receipt",
            controller_action_pending=True,
            controller_action_ready=True,
            controller_action_requires_stateful_postcondition=True,
            controller_action_done=False,
            controller_receipt_present=True,
            controller_stateful_postcondition_evidence_written=False,
            controller_boundary_confirmation_written=False,
            controller_role_confirmed=False,
            controller_missing_deliverable_repair_pending=False,
            controller_missing_deliverable_repair_attempts=2,
            controller_missing_deliverable_repair_failed_receipts=1,
            controller_missing_deliverable_pending_attempt=0,
            controller_missing_deliverable_blocker_recorded=True,
        ),
        "router_cleared_stateful_receipt_without_postcondition_evidence": replace(
            safe_active,
            current_wait="none",
            controller_action_pending=False,
            controller_action_ready=False,
            controller_action_requires_stateful_postcondition=True,
            controller_action_done=True,
            controller_receipt_present=True,
            controller_stateful_postcondition_evidence_written=False,
            controller_boundary_confirmation_written=False,
            controller_role_confirmed=False,
            router_internal_action_fact_current=True,
            router_internal_fact_updated_from_receipt=True,
            router_cleared_stateful_receipt_without_postcondition_evidence=True,
        ),
        "controller_role_confirmed_without_boundary_artifact": replace(
            safe_active,
            controller_action_requires_stateful_postcondition=True,
            controller_stateful_postcondition_evidence_written=True,
            controller_boundary_confirmation_written=False,
            controller_role_confirmed=True,
        ),
        "same_controller_action_reissued_after_done_receipt": replace(
            safe_active,
            current_wait="controller_receipt",
            controller_action_pending=True,
            controller_action_ready=True,
            controller_action_done=False,
            controller_receipt_present=True,
            router_internal_action_fact_current=False,
            same_controller_action_reissue_count=2,
        ),
        "controller_core_loaded_after_skipped_daemon_start": replace(
            safe_active,
            startup_daemon_step_completed=False,
            daemon_mode_enabled=False,
            daemon_alive=False,
            daemon_lock_state="none",
            daemon_writer_count=0,
        ),
        "formal_startup_continued_after_daemon_failure": replace(
            safe_active,
            startup_daemon_failed=True,
            startup_daemon_step_completed=False,
            daemon_mode_enabled=False,
            daemon_alive=False,
            daemon_lock_state="none",
            daemon_writer_count=0,
        ),
        "controller_used_router_next_as_metronome": replace(
            safe_active,
            controller_called_router_next_as_metronome=True,
        ),
        "patrol_started_second_live_daemon": replace(
            safe_active,
            manual_resume_woke=True,
            patrol_started_second_daemon=True,
            daemon_writer_count=2,
        ),
        "terminal_stop_scheduled_startup_row": replace(
            safe_active,
            lifecycle="terminal",
            terminal_fence_written=True,
            terminal_projection_refreshed=True,
            terminal_next_step_cleared=True,
            daemon_alive=False,
            daemon_lock_state="terminal",
            daemon_writer_count=0,
            controller_attached=False,
            roles_live=False,
            manual_resume_binding_active=False,
            route_work_allowed=False,
            startup_row_scheduled_after_terminal_fence=True,
        ),
        "terminal_stop_scheduled_patrol_binding": replace(
            safe_active,
            lifecycle="terminal",
            terminal_fence_written=True,
            terminal_projection_refreshed=True,
            terminal_next_step_cleared=True,
            daemon_alive=False,
            daemon_lock_state="terminal",
            daemon_writer_count=0,
            controller_attached=False,
            roles_live=False,
            manual_resume_binding_active=False,
            route_work_allowed=False,
            patrol_binding_scheduled_after_terminal_fence=True,
        ),
        "terminal_projection_stale_next_step": replace(
            safe_active,
            lifecycle="terminal",
            terminal_fence_written=True,
            terminal_projection_refreshed=True,
            terminal_next_step_cleared=False,
            daemon_alive=False,
            daemon_lock_state="terminal",
            daemon_writer_count=0,
            controller_attached=False,
            roles_live=False,
            manual_resume_binding_active=False,
            route_work_allowed=False,
        ),
        "terminal_cleanup_lock_blocked_fence": replace(
            safe_active,
            lifecycle="terminal",
            terminal_fence_written=False,
            terminal_controller_cleanup_best_effort_failed=True,
            terminal_projection_refreshed=True,
            terminal_next_step_cleared=True,
            daemon_alive=False,
            daemon_lock_state="terminal",
            daemon_writer_count=0,
            controller_attached=False,
            roles_live=False,
            manual_resume_binding_active=False,
            route_work_allowed=False,
        ),
        "terminal_left_runtime_active": State(
            lifecycle="terminal",
            formal_startup_started=True,
            startup_daemon_step_completed=True,
            daemon_mode_enabled=True,
            daemon_alive=True,
            daemon_lock_state="live",
            daemon_writer_count=1,
            controller_core_loaded=True,
            controller_attached=True,
            roles_live=True,
            manual_resume_binding_active=True,
            route_work_allowed=True,
            current_wait="ack",
        ),
    }

