"""Known-bad hazard states for ``flowpilot_router_loop_model``."""

from __future__ import annotations

from dataclasses import replace

from flowpilot_router_loop_model_state import State
from flowpilot_router_loop_model_transitions import expected_wait_hazard_states

def _active_packet_loop(**changes: object) -> State:
    base = State(
        status="running",
        holder="reviewer",
        route_version=1,
        controller_boundary_confirmed=True,
        route_activated=True,
        officer_packet_card_delivered=True,
        officer_packet_relayed=True,
        officer_packet_identity_boundary_present=True,
        officer_result_returned=True,
        officer_result_identity_boundary_present=True,
        officer_result_ledger_checked=True,
        officer_result_routed_to_pm=True,
        pm_absorbed_officer_result=True,
        officer_lifecycle_flags_current=True,
        route_history_context_refreshed=True,
        pm_prior_path_context_reviewed=True,
        node_acceptance_plan_prior_context_used=True,
        pm_node_high_standard_gate_opened=True,
        pm_node_high_standard_risks_reviewed=True,
        node_acceptance_plan_written=True,
        reviewer_node_acceptance_plan_reviewed=True,
        current_node_packet_registered=True,
        write_grant_issued=True,
        reviewer_dispatch_allowed=True,
        worker_dispatched=True,
        worker_project_write_performed=True,
        worker_packet_identity_boundary_present=True,
        active_holder_lease_issued=True,
        active_holder_contact_attempted=True,
        active_holder_ack_recorded=True,
        active_holder_packet_opened_through_runtime=True,
        active_holder_progress_recorded=True,
        fast_lane_initial_result_submitted=True,
        fast_lane_mechanical_reject_recorded=True,
        fast_lane_result_resubmitted=True,
        fast_lane_result_mechanics_passed=True,
        fast_lane_controller_notice_written=True,
        worker_result_returned=True,
        worker_result_identity_boundary_present=True,
        worker_result_ledger_checked=True,
        worker_result_routed_to_pm=True,
        pm_result_disposition_recorded=True,
        pm_formal_node_gate_package_released=True,
        reviewer_worker_result_card_delivered=True,
    )
    return replace(base, **changes)


def _reviewer_passed(**changes: object) -> State:
    return _active_packet_loop(reviewer_decision="pass", **changes)


def _reviewer_blocked(**changes: object) -> State:
    return _active_packet_loop(
        reviewer_decision="block",
        reviewer_block_seen=True,
        **changes,
    )


def _mutated(**changes: object) -> State:
    base = State(
        status="running",
        holder="pm",
        route_version=2,
        controller_boundary_confirmed=True,
        route_mutation_count=1,
        reviewer_block_seen=True,
        pm_prior_path_context_used_for_route_mutation=True,
        stale_evidence_marked=True,
        frontier_marked_stale=True,
        route_history_context_stale=True,
    )
    return replace(base, **changes)


def _active_holder_leased(**changes: object) -> State:
    base = State(
        status="running",
        holder="worker",
        route_version=1,
        controller_boundary_confirmed=True,
        route_activated=True,
        officer_lifecycle_flags_current=True,
        officer_packet_card_delivered=True,
        officer_packet_relayed=True,
        officer_packet_identity_boundary_present=True,
        officer_result_returned=True,
        officer_result_identity_boundary_present=True,
        officer_result_ledger_checked=True,
        officer_result_routed_to_pm=True,
        pm_absorbed_officer_result=True,
        route_history_context_refreshed=True,
        pm_prior_path_context_reviewed=True,
        node_acceptance_plan_prior_context_used=True,
        pm_node_high_standard_gate_opened=True,
        pm_node_high_standard_risks_reviewed=True,
        node_acceptance_plan_written=True,
        reviewer_node_acceptance_plan_reviewed=True,
        current_node_packet_registered=True,
        write_grant_issued=True,
        reviewer_dispatch_allowed=True,
        worker_dispatched=True,
        worker_packet_identity_boundary_present=True,
        active_holder_lease_issued=True,
    )
    return replace(base, **changes)


def _generalized_active_holder_leased(packet_family: str, **changes: object) -> State:
    base = State(
        status="running",
        holder="worker",
        route_version=1,
        controller_boundary_confirmed=True,
        route_activated=True,
        active_holder_lease_issued=True,
        active_holder_packet_family=packet_family,
        generalized_packet_registered=True,
        generalized_packet_relayed=True,
        generalized_packet_identity_boundary_present=True,
        generalized_packet_live_holder_known=True,
        generalized_result_target_is_pm=True,
    )
    return replace(base, **changes)


def _node_completed(**changes: object) -> State:
    return _reviewer_passed(
        pm_node_completion_card_delivered=True,
        pm_node_completed=True,
        node_completion_ledger_updated=True,
        **changes,
    )


def _parent_completed(**changes: object) -> State:
    base = _node_completed(
        parent_backward_targets_enumerated=True,
        parent_backward_replay_passed=True,
        parent_pm_segment_decision_recorded=True,
        parent_node_completed=True,
        parent_segment_prior_context_used=True,
        route_history_context_refreshed=False,
        pm_prior_path_context_reviewed=False,
        route_history_context_stale=True,
    )
    return replace(base, **changes)


def _final_ready(**changes: object) -> State:
    base = _parent_completed(
        current_route_scan_done=True,
        pm_evidence_quality_package_card_delivered=True,
        evidence_quality_package_written=True,
        evidence_quality_prior_context_used=True,
        evidence_quality_review_card_delivered=True,
        evidence_quality_reviewer_passed=True,
        route_history_context_refreshed=True,
        pm_prior_path_context_reviewed=True,
        route_history_context_stale=False,
        unresolved_count_zero=True,
        pm_final_ledger_card_delivered=True,
        final_ledger_source_of_truth_generated=True,
        final_ledger_built=True,
        final_ledger_clean=True,
        final_ledger_prior_context_used=True,
        terminal_replay_map_generated_from_final_ledger=True,
        terminal_replay_root_segment_passed=True,
        terminal_replay_parent_segment_passed=True,
        terminal_replay_leaf_segment_passed=True,
        terminal_replay_pm_segment_decisions_recorded=True,
    )
    return replace(base, **changes)


def hazard_states() -> dict[str, State]:
    hazards = {
        "packet_registered_before_route_activation": State(
            status="running",
            controller_boundary_confirmed=True,
            current_node_packet_registered=True,
        ),
        "officer_packet_card_before_route_activation": State(
            status="running",
            controller_boundary_confirmed=True,
            officer_packet_card_delivered=True,
        ),
        "officer_packet_card_before_lifecycle_flags": State(
            status="running",
            controller_boundary_confirmed=True,
            route_version=1,
            route_activated=True,
            officer_packet_card_delivered=True,
            officer_lifecycle_flags_current=False,
        ),
        "officer_packet_relayed_without_officer_card": State(
            status="running",
            controller_boundary_confirmed=True,
            route_version=1,
            route_activated=True,
            officer_packet_relayed=True,
        ),
        "officer_result_routed_without_ledger_check": State(
            status="running",
            controller_boundary_confirmed=True,
            route_version=1,
            route_activated=True,
            officer_packet_card_delivered=True,
            officer_packet_relayed=True,
            officer_result_returned=True,
            officer_result_routed_to_pm=True,
            officer_result_ledger_checked=False,
        ),
        "worker_dispatched_before_reviewer_dispatch": State(
            status="running",
            controller_boundary_confirmed=True,
            route_version=1,
            route_activated=True,
            node_acceptance_plan_written=True,
            reviewer_node_acceptance_plan_reviewed=True,
            current_node_packet_registered=True,
            worker_dispatched=True,
        ),
        "reviewer_acceptance_plan_review_without_plan": State(
            status="running",
            controller_boundary_confirmed=True,
            route_version=1,
            route_activated=True,
            reviewer_node_acceptance_plan_reviewed=True,
        ),
        "node_acceptance_plan_without_pm_high_standard_gate": State(
            status="running",
            controller_boundary_confirmed=True,
            route_version=1,
            route_activated=True,
            officer_lifecycle_flags_current=True,
            route_history_context_refreshed=True,
            pm_prior_path_context_reviewed=True,
            node_acceptance_plan_written=True,
        ),
        "node_acceptance_plan_without_prior_path_context": State(
            status="running",
            controller_boundary_confirmed=True,
            route_version=1,
            route_activated=True,
            officer_lifecycle_flags_current=True,
            pm_node_high_standard_gate_opened=True,
            pm_node_high_standard_risks_reviewed=True,
            node_acceptance_plan_written=True,
            route_history_context_refreshed=False,
            pm_prior_path_context_reviewed=False,
        ),
        "packet_registered_before_acceptance_plan_review": State(
            status="running",
            controller_boundary_confirmed=True,
            route_version=1,
            route_activated=True,
            pm_node_high_standard_gate_opened=True,
            pm_node_high_standard_risks_reviewed=True,
            current_node_packet_registered=True,
        ),
        "parent_node_current_packet_registered": State(
            status="running",
            controller_boundary_confirmed=True,
            route_version=1,
            route_activated=True,
            active_node_kind="parent",
            pm_node_high_standard_gate_opened=True,
            pm_node_high_standard_risks_reviewed=True,
            node_acceptance_plan_written=True,
            reviewer_node_acceptance_plan_reviewed=True,
            current_node_packet_registered=True,
        ),
        "control_repair_wait_event_incompatible_with_parent": State(
            status="running",
            controller_boundary_confirmed=True,
            route_version=1,
            route_activated=True,
            active_node_kind="parent",
            control_repair_origin="parent_backward_replay",
            control_repair_wait_event="pm_registers_current_node_packet",
        ),
        "parent_backward_repair_targets_leaf_dispatch": State(
            status="running",
            controller_boundary_confirmed=True,
            route_version=1,
            route_activated=True,
            active_node_kind="parent",
            control_repair_origin="parent_backward_replay",
            control_repair_wait_event="pm_registers_current_node_packet",
            repair_outcome_success_event="pm_registers_current_node_packet",
            repair_outcome_blocker_event="pm_registers_current_node_packet",
            repair_outcome_protocol_blocker_event="pm_registers_current_node_packet",
        ),
        "collapsed_repair_outcomes_on_business_validated_event": State(
            status="running",
            controller_boundary_confirmed=True,
            route_version=1,
            route_activated=True,
            active_node_kind="leaf",
            control_repair_origin="current_node_result",
            control_repair_wait_event="pm_registers_current_node_packet",
            repair_outcome_success_event="pm_registers_current_node_packet",
            repair_outcome_blocker_event="pm_registers_current_node_packet",
            repair_outcome_protocol_blocker_event="pm_registers_current_node_packet",
        ),
        "write_grant_before_packet_registration": State(
            status="running",
            controller_boundary_confirmed=True,
            route_version=1,
            route_activated=True,
            write_grant_issued=True,
        ),
        "worker_dispatched_before_write_grant": _active_packet_loop(
            write_grant_issued=False,
            worker_project_write_performed=False,
            worker_result_returned=False,
            worker_result_identity_boundary_present=False,
            worker_result_ledger_checked=False,
            worker_result_routed_to_pm=False,
            pm_result_disposition_recorded=False,
            pm_formal_node_gate_package_released=False,
            worker_result_routed_to_reviewer=False,
            reviewer_worker_result_card_delivered=False,
        ),
        "worker_project_write_without_grant": _active_packet_loop(
            write_grant_issued=False,
        ),
        "active_holder_lease_before_worker_dispatch": _active_holder_leased(
            worker_dispatched=False,
            worker_packet_identity_boundary_present=False,
        ),
        "current_node_packet_relayed_without_active_holder_lease": _active_holder_leased(
            active_holder_lease_issued=False,
            worker_project_write_performed=True,
        ),
        "active_holder_contact_without_lease": _active_holder_leased(
            active_holder_lease_issued=False,
            active_holder_contact_attempted=True,
        ),
        "active_holder_contact_by_wrong_role": _active_holder_leased(
            active_holder_contact_attempted=True,
            active_holder_contact_is_current_holder=False,
        ),
        "active_holder_contact_by_stale_agent": _active_holder_leased(
            active_holder_contact_attempted=True,
            active_holder_contact_agent_matches=False,
        ),
        "active_holder_contact_by_stale_packet": _active_holder_leased(
            active_holder_contact_attempted=True,
            active_holder_contact_packet_current=False,
        ),
        "active_holder_contact_after_stale_frontier": _active_holder_leased(
            active_holder_contact_attempted=True,
            active_holder_contact_route_frontier_current=False,
        ),
        "active_holder_contact_action_not_allowed": _active_holder_leased(
            active_holder_contact_attempted=True,
            active_holder_contact_action_allowed=False,
        ),
        "material_active_holder_lease_without_packet_registration": _generalized_active_holder_leased(
            "material_scan",
            generalized_packet_registered=False,
        ),
        "research_active_holder_contact_by_wrong_role": _generalized_active_holder_leased(
            "research",
            active_holder_contact_attempted=True,
            active_holder_contact_is_current_holder=False,
        ),
        "pm_role_work_active_holder_without_live_holder": _generalized_active_holder_leased(
            "pm_role_work",
            generalized_packet_live_holder_known=False,
        ),
        "generalized_active_holder_result_not_to_pm": _generalized_active_holder_leased(
            "material_scan",
            generalized_result_target_is_pm=False,
        ),
        "active_holder_unknown_packet_family": _generalized_active_holder_leased(
            "legacy_unknown",
        ),
        "fast_lane_progress_leaks_controller_visible_content": _active_holder_leased(
            active_holder_contact_attempted=True,
            active_holder_ack_recorded=True,
            active_holder_progress_recorded=True,
            active_holder_progress_controller_safe=False,
        ),
        "fast_lane_result_before_packet_ack": _active_holder_leased(
            active_holder_contact_attempted=True,
            fast_lane_initial_result_submitted=True,
            active_holder_ack_recorded=False,
        ),
        "fast_lane_result_before_packet_open": _active_holder_leased(
            active_holder_contact_attempted=True,
            active_holder_ack_recorded=True,
            fast_lane_initial_result_submitted=True,
            worker_project_write_performed=False,
        ),
        "fast_lane_mechanical_pass_marks_node_complete": _active_holder_leased(
            active_holder_contact_attempted=True,
            active_holder_ack_recorded=True,
            fast_lane_initial_result_submitted=True,
            fast_lane_result_mechanics_passed=True,
            worker_result_returned=True,
            worker_result_identity_boundary_present=True,
            pm_node_completed=True,
        ),
        "fast_lane_closes_without_controller_notice": _active_packet_loop(
            fast_lane_controller_notice_written=False,
        ),
        "fast_lane_controller_notice_before_ledger_check": _active_holder_leased(
            active_holder_contact_attempted=True,
            active_holder_ack_recorded=True,
            fast_lane_initial_result_submitted=True,
            fast_lane_result_mechanics_passed=True,
            worker_result_returned=True,
            worker_result_identity_boundary_present=True,
            worker_result_ledger_checked=False,
            fast_lane_controller_notice_written=True,
        ),
        "legacy_worker_result_return_without_fast_lane_mechanics": _active_holder_leased(
            worker_result_returned=True,
            worker_result_identity_boundary_present=True,
            fast_lane_result_mechanics_passed=False,
        ),
        "reviewer_pass_without_routed_worker_result": _active_packet_loop(
            pm_formal_node_gate_package_released=False,
            reviewer_decision="pass",
        ),
        "reviewer_result_card_before_result_relay": _active_packet_loop(
            pm_formal_node_gate_package_released=False,
            reviewer_worker_result_card_delivered=True,
        ),
        "reviewer_decision_without_result_review_card": _active_packet_loop(
            reviewer_worker_result_card_delivered=False,
            reviewer_decision="pass",
        ),
        "worker_result_routed_without_ledger_check": _active_packet_loop(
            worker_result_ledger_checked=False,
            worker_result_routed_to_pm=True,
        ),
        "worker_result_routed_directly_to_reviewer": _active_packet_loop(
            worker_result_routed_to_reviewer=True,
        ),
        "pm_completion_without_reviewer_pass": _active_packet_loop(
            reviewer_decision="none",
            pm_node_completed=True,
        ),
        "node_completion_ledger_without_pm_completion": _reviewer_passed(
            node_completion_ledger_updated=True,
        ),
        "expected_pm_completion_wait_materializes_blocker": _reviewer_passed(
            pm_node_completion_card_delivered=True,
            pm_decision_required_blocker_written=True,
        ),
        "repair_packet_without_reviewer_block": _active_packet_loop(
            repair_packet_registered=True,
            reviewer_decision="none",
            reviewer_block_seen=False,
        ),
        "repair_worker_dispatched_before_reviewer_dispatch": _reviewer_blocked(
            repair_packet_registered=True,
            repair_worker_dispatched=True,
            repair_dispatch_allowed=False,
        ),
        "repair_result_routed_without_ledger_check": _reviewer_blocked(
            repair_packet_registered=True,
            repair_dispatch_allowed=True,
            repair_worker_dispatched=True,
            repair_result_returned=True,
            repair_result_routed_to_reviewer=True,
            repair_result_ledger_checked=False,
        ),
        "repair_recheck_without_reviewer_result": _reviewer_blocked(
            repair_packet_registered=True,
            repair_dispatch_allowed=True,
            repair_worker_dispatched=True,
            repair_result_returned=True,
            repair_result_ledger_checked=True,
            repair_recheck_passed=True,
            repair_result_routed_to_reviewer=False,
        ),
        "pm_completion_after_block_without_recheck": _active_packet_loop(
            reviewer_decision="pass",
            reviewer_block_seen=True,
            repair_recheck_passed=False,
            pm_node_completed=True,
        ),
        "route_mutation_without_reviewer_block": _mutated(reviewer_block_seen=False),
        "route_mutation_without_stale_evidence": _mutated(stale_evidence_marked=False),
        "route_mutation_without_stale_frontier": _mutated(frontier_marked_stale=False),
        "route_mutation_without_prior_path_context": _mutated(
            pm_prior_path_context_used_for_route_mutation=False
        ),
        "packet_registered_against_stale_mutation_frontier": _mutated(
            route_activated=True,
            officer_lifecycle_flags_current=True,
            pm_node_high_standard_gate_opened=True,
            pm_node_high_standard_risks_reviewed=True,
            node_acceptance_plan_written=True,
            reviewer_node_acceptance_plan_reviewed=True,
            current_node_packet_registered=True,
            frontier_rewritten_after_mutation=False,
        ),
        "final_scan_before_same_scope_replay_after_mutation": _parent_completed(
            route_mutation_count=1,
            stale_evidence_marked=True,
            frontier_marked_stale=True,
            frontier_rewritten_after_mutation=True,
            same_scope_replay_rerun_after_mutation=False,
            current_route_scan_done=True,
        ),
        "parent_completed_without_backward_replay": _node_completed(
            parent_node_completed=True,
        ),
        "parent_completed_without_pm_segment_decision": _node_completed(
            parent_backward_targets_enumerated=True,
            parent_backward_replay_passed=True,
            parent_node_completed=True,
        ),
        "parent_targets_before_node_completion_ledger": _reviewer_passed(
            pm_node_completed=True,
            node_completion_ledger_updated=False,
            parent_backward_targets_enumerated=True,
        ),
        "parent_segment_decision_without_prior_path_context": _node_completed(
            parent_backward_targets_enumerated=True,
            parent_backward_replay_passed=True,
            parent_pm_segment_decision_recorded=True,
            route_history_context_refreshed=False,
            pm_prior_path_context_reviewed=False,
            route_history_context_stale=True,
        ),
        "final_ledger_card_before_evidence_quality_package_card": _parent_completed(
            current_route_scan_done=True,
            pm_final_ledger_card_delivered=True,
        ),
        "final_ledger_card_before_reviewer_evidence_quality_pass": _parent_completed(
            current_route_scan_done=True,
            pm_evidence_quality_package_card_delivered=True,
            evidence_quality_package_written=True,
            pm_final_ledger_card_delivered=True,
        ),
        "expected_evidence_quality_package_wait_materializes_blocker": _parent_completed(
            current_route_scan_done=True,
            pm_evidence_quality_package_card_delivered=True,
            evidence_quality_package_written=False,
            evidence_quality_review_card_delivered=False,
            evidence_quality_reviewer_passed=False,
            pm_decision_required_blocker_written=True,
        ),
        "expected_evidence_quality_review_wait_materializes_blocker": _parent_completed(
            current_route_scan_done=True,
            pm_evidence_quality_package_card_delivered=True,
            evidence_quality_package_written=True,
            evidence_quality_review_card_delivered=True,
            evidence_quality_reviewer_passed=False,
            pm_decision_required_blocker_written=True,
        ),
        "final_ledger_built_before_evidence_quality_reviewer_pass": _parent_completed(
            current_route_scan_done=True,
            pm_evidence_quality_package_card_delivered=True,
            evidence_quality_package_written=True,
            unresolved_count_zero=True,
            pm_final_ledger_card_delivered=True,
            final_ledger_built=True,
            final_ledger_clean=True,
        ),
        "final_ledger_without_parent_completion": _node_completed(
            current_route_scan_done=True,
            pm_evidence_quality_package_card_delivered=True,
            evidence_quality_package_written=True,
            evidence_quality_reviewer_passed=True,
            unresolved_count_zero=True,
            pm_final_ledger_card_delivered=True,
            final_ledger_built=True,
            final_ledger_clean=True,
        ),
        "final_ledger_without_node_completion": State(
            status="running",
            controller_boundary_confirmed=True,
            route_version=1,
            route_activated=True,
            current_route_scan_done=True,
            pm_evidence_quality_package_card_delivered=True,
            evidence_quality_package_written=True,
            evidence_quality_reviewer_passed=True,
            unresolved_count_zero=True,
            pm_final_ledger_card_delivered=True,
            final_ledger_built=True,
            final_ledger_clean=True,
        ),
        "final_ledger_without_current_route_scan": _parent_completed(
            pm_evidence_quality_package_card_delivered=True,
            evidence_quality_package_written=True,
            evidence_quality_reviewer_passed=True,
            unresolved_count_zero=True,
            pm_final_ledger_card_delivered=True,
            final_ledger_built=True,
            final_ledger_clean=True,
        ),
        "final_ledger_with_unresolved_items": _parent_completed(
            current_route_scan_done=True,
            pm_evidence_quality_package_card_delivered=True,
            evidence_quality_package_written=True,
            evidence_quality_reviewer_passed=True,
            unresolved_count_zero=False,
            pm_final_ledger_card_delivered=True,
            final_ledger_built=True,
            final_ledger_clean=True,
        ),
        "final_ledger_without_source_of_truth_generation": _parent_completed(
            current_route_scan_done=True,
            pm_evidence_quality_package_card_delivered=True,
            evidence_quality_package_written=True,
            evidence_quality_reviewer_passed=True,
            route_history_context_refreshed=True,
            pm_prior_path_context_reviewed=True,
            route_history_context_stale=False,
            unresolved_count_zero=True,
            pm_final_ledger_card_delivered=True,
            final_ledger_source_of_truth_generated=False,
            final_ledger_built=True,
            final_ledger_clean=True,
        ),
        "final_ledger_card_without_prior_path_context": _parent_completed(
            current_route_scan_done=True,
            pm_evidence_quality_package_card_delivered=True,
            evidence_quality_package_written=True,
            evidence_quality_reviewer_passed=True,
            pm_final_ledger_card_delivered=True,
            route_history_context_refreshed=False,
            pm_prior_path_context_reviewed=False,
            route_history_context_stale=True,
        ),
        "expected_final_ledger_wait_materializes_blocker": _parent_completed(
            current_route_scan_done=True,
            pm_evidence_quality_package_card_delivered=True,
            evidence_quality_package_written=True,
            evidence_quality_review_card_delivered=True,
            evidence_quality_reviewer_passed=True,
            unresolved_count_zero=True,
            pm_final_ledger_card_delivered=True,
            final_ledger_source_of_truth_generated=False,
            final_ledger_built=False,
            final_ledger_clean=False,
            pm_decision_required_blocker_written=True,
        ),
        "final_ledger_without_prior_path_context": _parent_completed(
            current_route_scan_done=True,
            pm_evidence_quality_package_card_delivered=True,
            evidence_quality_package_written=True,
            evidence_quality_reviewer_passed=True,
            unresolved_count_zero=True,
            pm_final_ledger_card_delivered=True,
            final_ledger_source_of_truth_generated=True,
            final_ledger_built=True,
            final_ledger_clean=True,
            route_history_context_refreshed=False,
            pm_prior_path_context_reviewed=False,
            route_history_context_stale=True,
        ),
        "final_ledger_with_stale_or_unresolved_evidence": _parent_completed(
            current_route_scan_done=True,
            pm_evidence_quality_package_card_delivered=True,
            evidence_quality_package_written=True,
            evidence_quality_reviewer_passed=True,
            stale_or_unresolved_evidence_present=True,
            unresolved_count_zero=True,
            pm_final_ledger_card_delivered=True,
            final_ledger_built=True,
            final_ledger_clean=True,
        ),
        "final_ledger_with_pending_generated_resources": _parent_completed(
            current_route_scan_done=True,
            pm_evidence_quality_package_card_delivered=True,
            evidence_quality_package_written=True,
            evidence_quality_reviewer_passed=True,
            pending_generated_resources=True,
            unresolved_count_zero=True,
            pm_final_ledger_card_delivered=True,
            final_ledger_built=True,
            final_ledger_clean=True,
        ),
        "final_ledger_missing_ui_visual_screenshots": _parent_completed(
            current_route_scan_done=True,
            pm_evidence_quality_package_card_delivered=True,
            evidence_quality_package_written=True,
            evidence_quality_reviewer_passed=True,
            ui_visual_required=True,
            ui_visual_screenshots_present=False,
            unresolved_count_zero=True,
            pm_final_ledger_card_delivered=True,
            final_ledger_built=True,
            final_ledger_clean=True,
        ),
        "final_ledger_reuses_old_assets_as_current_evidence": _parent_completed(
            current_route_scan_done=True,
            pm_evidence_quality_package_card_delivered=True,
            evidence_quality_package_written=True,
            evidence_quality_reviewer_passed=True,
            old_assets_reused_as_current_evidence=True,
            unresolved_count_zero=True,
            pm_final_ledger_card_delivered=True,
            final_ledger_built=True,
            final_ledger_clean=True,
        ),
        "final_backward_replay_without_clean_ledger": _parent_completed(
            current_route_scan_done=True,
            pm_evidence_quality_package_card_delivered=True,
            evidence_quality_package_written=True,
            evidence_quality_reviewer_passed=True,
            unresolved_count_zero=True,
            pm_final_ledger_card_delivered=True,
            final_ledger_source_of_truth_generated=True,
            final_ledger_built=True,
            final_ledger_clean=False,
            terminal_replay_map_generated_from_final_ledger=True,
            terminal_replay_root_segment_passed=True,
            terminal_replay_parent_segment_passed=True,
            terminal_replay_leaf_segment_passed=True,
            terminal_replay_pm_segment_decisions_recorded=True,
            final_backward_replay_passed=True,
        ),
        "terminal_replay_map_without_source_ledger": _parent_completed(
            current_route_scan_done=True,
            pm_evidence_quality_package_card_delivered=True,
            evidence_quality_package_written=True,
            evidence_quality_reviewer_passed=True,
            unresolved_count_zero=True,
            pm_final_ledger_card_delivered=True,
            final_ledger_source_of_truth_generated=False,
            final_ledger_built=True,
            final_ledger_clean=True,
            terminal_replay_map_generated_from_final_ledger=True,
        ),
        "terminal_parent_segment_before_root": _final_ready(
            terminal_replay_map_generated_from_final_ledger=True,
            terminal_replay_root_segment_passed=False,
            terminal_replay_parent_segment_passed=True,
        ),
        "terminal_leaf_segment_before_parent": _final_ready(
            terminal_replay_map_generated_from_final_ledger=True,
            terminal_replay_root_segment_passed=True,
            terminal_replay_parent_segment_passed=False,
            terminal_replay_leaf_segment_passed=True,
        ),
        "terminal_pm_decisions_before_segments": _final_ready(
            terminal_replay_map_generated_from_final_ledger=True,
            terminal_replay_root_segment_passed=True,
            terminal_replay_parent_segment_passed=False,
            terminal_replay_leaf_segment_passed=True,
            terminal_replay_pm_segment_decisions_recorded=True,
        ),
        "final_backward_replay_without_segments": _final_ready(
            terminal_replay_map_generated_from_final_ledger=True,
            terminal_replay_root_segment_passed=True,
            terminal_replay_parent_segment_passed=True,
            terminal_replay_leaf_segment_passed=True,
            terminal_replay_pm_segment_decisions_recorded=False,
            final_backward_replay_passed=True,
        ),
        "expected_final_backward_replay_wait_materializes_blocker": _final_ready(
            final_backward_replay_card_delivered=True,
            final_backward_replay_passed=False,
            pm_decision_required_blocker_written=True,
        ),
        "controller_reads_sealed_body": State(
            status="running",
            controller_boundary_confirmed=True,
            controller_read_sealed_body=True,
        ),
        "controller_originates_project_evidence": State(
            status="running",
            controller_boundary_confirmed=True,
            controller_originated_project_evidence=True,
        ),
        "no_next_action_without_pm_blocker": State(
            status="running",
            holder="controller",
            controller_boundary_confirmed=True,
            controller_only_mode_active=True,
            no_next_action_detected=True,
            pm_decision_required_blocker_written=False,
        ),
        "true_no_next_action_without_blocker": State(
            status="running",
            holder="controller",
            controller_boundary_confirmed=True,
            controller_only_mode_active=True,
            no_next_action_detected=True,
            pm_decision_required_blocker_written=False,
        ),
        "controller_does_project_work_after_no_next_action": State(
            status="running",
            holder="controller",
            controller_boundary_confirmed=True,
            controller_only_mode_active=True,
            no_next_action_detected=True,
            pm_decision_required_blocker_written=True,
            controller_originated_project_evidence=True,
        ),
        "controller_relays_body_content": State(
            status="running",
            controller_boundary_confirmed=True,
            controller_relayed_body_content=True,
        ),
        "task_completion_projection_without_completion_ledger": _final_ready(
            node_completion_ledger_updated=False,
            final_backward_replay_passed=True,
            task_completion_projection_published=True,
        ),
        "expected_pm_terminal_closure_wait_materializes_blocker": _final_ready(
            final_backward_replay_card_delivered=True,
            final_backward_replay_passed=True,
            task_completion_projection_published=True,
            pm_terminal_closure_card_delivered=True,
            pm_decision_required_blocker_written=True,
        ),
        "completion_before_final_backward_replay": _final_ready(status="complete"),
        "completion_without_task_completion_projection": _final_ready(
            status="complete",
            final_backward_replay_passed=True,
            task_completion_projection_published=False,
        ),
    }
    hazards.update(expected_wait_hazard_states())
    return hazards
