"""Router TestMesh catalog for FlowPilot maintenance."""

from __future__ import annotations

from flowguard import (
    EVIDENCE_CONFORMANCE_GREEN,
    TEST_STATUS_FAILED,
    TEST_STATUS_PASSED,
    TEST_STATUS_TIMEOUT,
    TestPartitionItem,
    TestSuiteEvidence,
)

ROUTER_TEST_PARTITIONS = (
    TestPartitionItem("startup_bootstrap", owner_suite_id="router_startup_runtime"),
    TestPartitionItem("foreground_controller", owner_suite_id="router_foreground_controller"),
    TestPartitionItem("packet_prompt_assets", owner_suite_id="router_prompt_store"),
    TestPartitionItem("packet_runtime", owner_suite_id="router_packet_runtime"),
    TestPartitionItem("packet_runtime_progress", owner_suite_id="router_packet_runtime"),
    TestPartitionItem("packet_runtime_creation", owner_suite_id="router_packet_runtime"),
    TestPartitionItem("packet_runtime_results", owner_suite_id="router_packet_runtime"),
    TestPartitionItem("packet_runtime_audit", owner_suite_id="router_packet_runtime"),
    TestPartitionItem("packet_runtime_cli", owner_suite_id="router_packet_runtime"),
    TestPartitionItem("packets", owner_suite_id="router_packets"),
    TestPartitionItem("cards", owner_suite_id="router_cards"),
    TestPartitionItem("card_runtime_io", owner_suite_id="router_card_runtime"),
    TestPartitionItem("card_runtime_ledgers", owner_suite_id="router_card_runtime"),
    TestPartitionItem("card_runtime_envelopes", owner_suite_id="router_card_runtime"),
    TestPartitionItem("card_runtime_ack", owner_suite_id="router_card_runtime"),
    TestPartitionItem("card_runtime_bundle", owner_suite_id="router_card_runtime"),
    TestPartitionItem("ack_return", owner_suite_id="router_ack_return"),
    TestPartitionItem("route_boundaries", owner_suite_id="router_boundaries"),
    TestPartitionItem("route_mutation_draft_activation", owner_suite_id="router_route_mutation_draft_activation"),
    TestPartitionItem("route_mutation_model_miss_triage", owner_suite_id="router_route_mutation_model_miss_triage"),
    TestPartitionItem("route_mutation_acceptance_repair", owner_suite_id="router_route_mutation_acceptance_repair"),
    TestPartitionItem("route_mutation_preconditions", owner_suite_id="router_route_mutation_preconditions"),
    TestPartitionItem("route_mutation_transactions", owner_suite_id="router_route_mutation_transactions"),
    TestPartitionItem("route_mutation_topology", owner_suite_id="router_route_mutation_topology"),
    TestPartitionItem("route_mutation_sibling_replacement", owner_suite_id="router_route_mutation_sibling_replacement"),
    TestPartitionItem("route_mutation_parent_backward", owner_suite_id="router_route_mutation_parent_backward"),
    TestPartitionItem("route_mutation_contracts", owner_suite_id="router_route_mutation_contracts"),
    TestPartitionItem("user_flow_diagram", owner_suite_id="router_user_flow_diagram"),
    TestPartitionItem("user_flow_source", owner_suite_id="router_user_flow_diagram"),
    TestPartitionItem("user_flow_tree", owner_suite_id="router_user_flow_diagram"),
    TestPartitionItem("user_flow_stage", owner_suite_id="router_user_flow_diagram"),
    TestPartitionItem("user_flow_mermaid", owner_suite_id="router_user_flow_diagram"),
    TestPartitionItem("user_flow_markdown", owner_suite_id="router_user_flow_diagram"),
    TestPartitionItem("action_factory_dispatch", owner_suite_id="router_packets"),
    TestPartitionItem("action_factory_envelope", owner_suite_id="router_packets"),
    TestPartitionItem("action_factory_reconciliation", owner_suite_id="router_packets"),
    TestPartitionItem("terminal_final_ledger", owner_suite_id="router_terminal_final_ledger"),
    TestPartitionItem("terminal_replay_summary", owner_suite_id="router_terminal_replay_summary"),
    TestPartitionItem("terminal_node_stop", owner_suite_id="router_terminal_node_stop"),
    TestPartitionItem("closure_dirty_ledgers", owner_suite_id="router_closure_dirty_ledgers"),
    TestPartitionItem("closure_pm_role_work", owner_suite_id="router_closure_pm_role_work"),
    TestPartitionItem("resume_reentry", owner_suite_id="router_resume_reentry"),
    TestPartitionItem("resume_rehydration", owner_suite_id="router_resume_rehydration"),
    TestPartitionItem("resume_role_recovery", owner_suite_id="router_resume_role_recovery"),
    TestPartitionItem("resume_liveness_faults", owner_suite_id="router_resume_liveness_faults"),
    TestPartitionItem("control_blockers_recorded_events", owner_suite_id="router_control_blockers_recorded_events"),
    TestPartitionItem("control_blockers_reissue_retry", owner_suite_id="router_control_blockers_reissue_retry"),
    TestPartitionItem("control_blockers_pm_repair_decisions", owner_suite_id="router_control_blockers_pm_repair_decisions"),
    TestPartitionItem("control_blockers_protocol_transactions", owner_suite_id="router_control_blockers_protocol_transactions"),
    TestPartitionItem("control_blockers_followup_fatal", owner_suite_id="router_control_blockers_followup_fatal"),
    TestPartitionItem("pm_role_work_requests", owner_suite_id="router_pm_role_work_requests"),
    TestPartitionItem("pm_role_work_gates", owner_suite_id="router_pm_role_work_results"),
    TestPartitionItem("pm_role_work_writes", owner_suite_id="router_pm_role_work_results"),
    TestPartitionItem("pm_role_work_lifecycle", owner_suite_id="router_pm_role_work_waits"),
    TestPartitionItem("pm_role_work_actions", owner_suite_id="router_pm_role_work_waits"),
    TestPartitionItem("controller_receipt_writes", owner_suite_id="router_foreground_controller"),
    TestPartitionItem("controller_receipt_effects", owner_suite_id="router_foreground_controller"),
    TestPartitionItem("controller_receipt_pending", owner_suite_id="router_foreground_controller"),
    TestPartitionItem("controller_receipt_scheduled", owner_suite_id="router_foreground_controller"),
    TestPartitionItem("quality_gates_background_manifest", owner_suite_id="router_quality_gates_background_manifest"),
    TestPartitionItem("quality_gates_decisions", owner_suite_id="router_quality_gates_decisions"),
    TestPartitionItem("quality_gates_evidence_artifacts", owner_suite_id="router_quality_gates_evidence_artifacts"),
    TestPartitionItem("quality_gates_route_model", owner_suite_id="router_quality_gates_route_model"),
    TestPartitionItem("quality_gates_node_contracts", owner_suite_id="router_quality_gates_node_contracts"),
    TestPartitionItem("material_modeling_intake", owner_suite_id="router_material_modeling_intake"),
    TestPartitionItem("material_modeling_scan_relay", owner_suite_id="router_material_modeling_scan_relay"),
    TestPartitionItem("material_modeling_modelability", owner_suite_id="router_material_modeling_modelability"),
    TestPartitionItem("bounded_background_fanout", owner_suite_id="router_background_supervisor"),
)

ROUTER_TEST_SUITES = (
    TestSuiteEvidence(
        "router_background_supervisor",
        command="python scripts/run_test_tier.py --tier router --background --background-max-parallel 4 --background-dir tmp/flowguard_background",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=1,
        selected_count=1,
        exit_code=0,
        result_path="tmp/flowguard_background/router_background_supervisor.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("bounded_background_fanout",),
        owns_side_effects=("background_child_launch",),
    ),
    TestSuiteEvidence(
        "router_startup_runtime",
        command="python -m unittest -v tests.test_flowpilot_router_startup_runtime tests.router_runtime.bootstrap_cli tests.router_runtime.startup_bootstrap tests.router_runtime.startup_daemon",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=80,
        selected_count=80,
        exit_code=0,
        result_path="tmp/flowguard_background/router_startup_runtime.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("startup_bootstrap",),
    ),
    TestSuiteEvidence(
        "router_foreground_controller",
        command="python -m unittest -v tests.router_runtime.foreground tests.router_runtime.controller tests.router_runtime.foreground_controller tests.router_runtime.dispatch_gate",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=66,
        selected_count=66,
        exit_code=0,
        result_path="tmp/flowguard_background/router_foreground_controller.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("foreground_controller",),
    ),
    TestSuiteEvidence(
        "router_prompt_store",
        command="python -m unittest -v tests.test_flowpilot_prompt_store",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=7,
        selected_count=7,
        exit_code=0,
        result_path="tmp/flowguard_background/router_prompt_store.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("packet_prompt_assets",),
    ),
    TestSuiteEvidence(
        "router_packet_runtime",
        command="python -m unittest -v tests.test_flowpilot_packet_runtime",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=23,
        selected_count=23,
        exit_code=0,
        result_path="tmp/flowguard_background/router_packet_runtime.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=(
            "packet_runtime",
            "packet_runtime_progress",
            "packet_runtime_creation",
            "packet_runtime_results",
            "packet_runtime_audit",
            "packet_runtime_cli",
        ),
    ),
    TestSuiteEvidence(
        "router_card_runtime",
        command="python -m unittest -v tests.test_flowpilot_card_runtime tests.test_flowpilot_router_runtime_cards",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=10,
        selected_count=10,
        exit_code=0,
        result_path="tmp/flowguard_background/router_card_runtime.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=(
            "card_runtime_io",
            "card_runtime_ledgers",
            "card_runtime_envelopes",
            "card_runtime_ack",
            "card_runtime_bundle",
        ),
    ),
    TestSuiteEvidence(
        "router_packets",
        command="python -m unittest -v tests.router_runtime.packets",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=22,
        selected_count=22,
        exit_code=0,
        result_path="tmp/flowguard_background/router_packets.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("packets",),
    ),
    TestSuiteEvidence(
        "router_cards",
        command="python -m unittest -v tests.router_runtime.cards",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=8,
        selected_count=8,
        exit_code=0,
        result_path="tmp/flowguard_background/router_cards.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("cards",),
    ),
    TestSuiteEvidence(
        "router_ack_return",
        command="python -m unittest -v tests.router_runtime.ack_return",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=15,
        selected_count=15,
        exit_code=0,
        result_path="tmp/flowguard_background/router_ack_return.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("ack_return",),
    ),
    TestSuiteEvidence(
        "router_boundaries",
        command="python -m unittest -v tests.test_flowpilot_router_boundaries",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=18,
        selected_count=18,
        exit_code=0,
        result_path="tmp/flowguard_background/router_boundaries.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("route_boundaries",),
    ),
    TestSuiteEvidence(
        "router_route_mutation_draft_activation",
        command="python -m unittest -v tests.router_runtime.route_mutation_draft_activation",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=3,
        selected_count=3,
        exit_code=0,
        result_path="tmp/flowguard_background/router_route_mutation_draft_activation.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("route_mutation_draft_activation",),
    ),
    TestSuiteEvidence(
        "router_route_mutation_model_miss_triage",
        command="python -m unittest -v tests.router_runtime.route_mutation_model_miss_triage",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=8,
        selected_count=8,
        exit_code=0,
        result_path="tmp/flowguard_background/router_route_mutation_model_miss_triage.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("route_mutation_model_miss_triage",),
    ),
    TestSuiteEvidence(
        "router_route_mutation_acceptance_repair",
        command="python -m unittest -v tests.router_runtime.route_mutation_acceptance_repair",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=2,
        selected_count=2,
        exit_code=0,
        result_path="tmp/flowguard_background/router_route_mutation_acceptance_repair.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("route_mutation_acceptance_repair",),
    ),
    TestSuiteEvidence(
        "router_route_mutation_preconditions",
        command="python -m unittest -v tests.router_runtime.route_mutation_preconditions",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=3,
        selected_count=3,
        exit_code=0,
        result_path="tmp/flowguard_background/router_route_mutation_preconditions.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("route_mutation_preconditions",),
    ),
    TestSuiteEvidence(
        "router_route_mutation_transactions",
        command="python -m unittest -v tests.router_runtime.route_mutation_transactions",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=1,
        selected_count=1,
        exit_code=0,
        result_path="tmp/flowguard_background/router_route_mutation_transactions.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("route_mutation_transactions",),
    ),
    TestSuiteEvidence(
        "router_route_mutation_topology",
        command="python -m unittest -v tests.router_runtime.route_mutation_topology",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=1,
        selected_count=1,
        exit_code=0,
        result_path="tmp/flowguard_background/router_route_mutation_topology.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("route_mutation_topology",),
    ),
    TestSuiteEvidence(
        "router_route_mutation_sibling_replacement",
        command="python -m unittest -v tests.router_runtime.route_mutation_sibling_replacement",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=1,
        selected_count=1,
        exit_code=0,
        result_path="tmp/flowguard_background/router_route_mutation_sibling_replacement.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("route_mutation_sibling_replacement",),
    ),
    TestSuiteEvidence(
        "router_route_mutation_parent_backward",
        command="python -m unittest -v tests.router_runtime.route_mutation_parent_backward",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=3,
        selected_count=3,
        exit_code=0,
        result_path="tmp/flowguard_background/router_route_mutation_parent_backward.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("route_mutation_parent_backward",),
    ),
    TestSuiteEvidence(
        "router_route_mutation_contracts",
        command="python -m unittest -v tests.test_flowpilot_router_runtime_route_mutation",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=6,
        selected_count=6,
        exit_code=0,
        result_path="tmp/flowguard_background/router_route_mutation_contracts.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("route_mutation_contracts",),
    ),
    TestSuiteEvidence(
        "router_user_flow_diagram",
        command="python -m unittest -v tests.test_flowpilot_user_flow_diagram",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=19,
        selected_count=19,
        exit_code=0,
        result_path="tmp/flowguard_background/router_user_flow_diagram.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=(
            "user_flow_diagram",
            "user_flow_source",
            "user_flow_tree",
            "user_flow_stage",
            "user_flow_mermaid",
            "user_flow_markdown",
        ),
    ),
    TestSuiteEvidence(
        "router_terminal_final_ledger",
        command="python -m unittest -v -k test_final_ledger_records_frozen_contract_replay_source_paths -k test_final_ledger_rejects_dirty_pm_suggestion_ledger -k test_final_ledger_rejects_dirty_self_interrogation_index -k test_final_ledger_rejects_missing_source_of_truth_entries_and_contract_replay tests.router_runtime.terminal",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=4,
        selected_count=4,
        exit_code=0,
        result_path="tmp/flowguard_background/router_terminal_final_ledger.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("terminal_final_ledger",),
    ),
    TestSuiteEvidence(
        "router_terminal_replay_summary",
        command="python -m unittest -v -k test_reconcile_recovers_unsupported_historical_terminal_closure_state -k test_reconcile_run_recovers_terminal_status_from_current_pointer -k test_terminal_replay_requires_reviewed_segments_and_pm_segment_decisions -k test_terminal_summary_payload_requires_attribution_display_and_run_root_sources tests.router_runtime.terminal",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=4,
        selected_count=4,
        exit_code=0,
        result_path="tmp/flowguard_background/router_terminal_replay_summary.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("terminal_replay_summary",),
    ),
    TestSuiteEvidence(
        "router_terminal_node_stop",
        command="python -m unittest -v -k test_nonterminal_node_completion_does_not_show_completed_node_as_in_progress -k test_user_stop_or_cancel_makes_run_terminal_and_blocks_next_work tests.router_runtime.terminal",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=2,
        selected_count=2,
        exit_code=0,
        result_path="tmp/flowguard_background/router_terminal_node_stop.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("terminal_node_stop",),
    ),
    TestSuiteEvidence(
        "router_closure_dirty_ledgers",
        command="python -m unittest -v -k test_closure_lifecycle_blocks_when_ledgers_are_dirty_after_terminal_replay -k test_dirty_pm_suggestion_ledger_invalidates_terminal_closure_card -k test_terminal_closure_blocks_dirty_defect_ledger_after_terminal_replay tests.router_runtime.closure",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=3,
        selected_count=3,
        exit_code=0,
        result_path="tmp/flowguard_background/router_closure_dirty_ledgers.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("closure_dirty_ledgers",),
    ),
    TestSuiteEvidence(
        "router_closure_pm_role_work",
        command="python -m unittest -v -k test_flowguard_operator_role_work_writes_authorized_lifecycle_index -k test_pm_terminal_closure_uses_file_backed_contract_and_prior_context tests.router_runtime.closure",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=2,
        selected_count=2,
        exit_code=0,
        result_path="tmp/flowguard_background/router_closure_pm_role_work.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("closure_pm_role_work",),
    ),
    TestSuiteEvidence(
        "router_resume_reentry",
        command="python -m unittest -v -k test_heartbeat_alive_status_still_enters_router_resume_path -k test_resume_reentry_attaches_to_live_owner_after_delayed_heartbeat -k test_resume_reentry_attaches_to_live_router_daemon_and_ledger -k test_resume_reentry_loads_state_before_resume_cards -k test_resume_reentry_marks_dead_daemon_for_restart_after_liveness_check -k test_resume_reentry_preempts_active_control_blocker_until_replay_or_pm_decision tests.router_runtime.resume",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=6,
        selected_count=6,
        exit_code=0,
        result_path="tmp/flowguard_background/router_resume_reentry.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("resume_reentry",),
    ),
    TestSuiteEvidence(
        "router_resume_rehydration",
        command="python -m unittest -v -k test_incomplete_stateful_rehydrate_receipt_becomes_control_blocker -k test_resume_ambiguous_state_blocks_continue_without_recovery_evidence -k test_resume_rehydration_reissues_missing_obligations_before_pm -k test_resume_rehydration_settles_existing_output_without_pm tests.router_runtime.resume",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=4,
        selected_count=4,
        exit_code=0,
        result_path="tmp/flowguard_background/router_resume_rehydration.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("resume_rehydration",),
    ),
    TestSuiteEvidence(
        "router_resume_role_recovery",
        command="python -m unittest -v -k test_load_resume_state_does_not_downgrade_existing_role_recovery_report -k test_role_recovery_reissues_missing_obligations_in_original_order -k test_role_recovery_settles_existing_ack_without_replay_or_pm -k test_role_recovery_settles_existing_output_without_replay_or_pm tests.router_runtime.resume",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=4,
        selected_count=4,
        exit_code=0,
        result_path="tmp/flowguard_background/router_resume_role_recovery.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("resume_role_recovery",),
    ),
    TestSuiteEvidence(
        "router_resume_liveness_faults",
        command="python -m unittest -v -k test_blocked_role_recovery_receipt_reclaims_existing_report -k test_unsupported_historical_liveness_fault_no_output_redirects_to_reissue_not_recovery -k test_mid_run_role_liveness_fault_uses_unified_recovery_before_normal_work -k test_role_no_output_escalates_to_pm_after_two_reissues -k test_role_no_output_report_reissues_same_work_before_role_recovery tests.router_runtime.resume",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=5,
        selected_count=5,
        exit_code=0,
        result_path="tmp/flowguard_background/router_resume_liveness_faults.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("resume_liveness_faults",),
    ),
    TestSuiteEvidence(
        "router_control_blockers_recorded_events",
        command="python -m unittest -v -k test_already_recorded_event_can_resolve_delivered_control_blocker -k test_already_recorded_event_does_not_resolve_pm_required_control_blocker -k test_already_recorded_event_resolves_fatal_control_blocker_after_pm_repair_decision tests.router_runtime.control_blockers",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=3,
        selected_count=3,
        exit_code=0,
        result_path="tmp/flowguard_background/router_control_blockers_recorded_events.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("control_blockers_recorded_events",),
    ),
    TestSuiteEvidence(
        "router_control_blockers_reissue_retry",
        command="python -m unittest -v -k test_control_plane_reissue_retry_budget_escalates_to_pm -k test_missing_open_receipt_control_blocker_routes_to_same_reviewer_reissue -k test_pm_semantic_control_blocker_zero_retry_budget_is_exhausted tests.router_runtime.control_blockers",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=3,
        selected_count=3,
        exit_code=0,
        result_path="tmp/flowguard_background/router_control_blockers_reissue_retry.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("control_blockers_reissue_retry",),
    ),
    TestSuiteEvidence(
        "router_control_blockers_pm_repair_decisions",
        command="python -m unittest -v -k test_pm_repair_decision_accepts_registered_rerun_target_and_waits_for_it -k test_pm_repair_decision_can_repeat_for_new_control_blocker -k test_pm_repair_decision_rejects_unsupported_event_replay_plan_kind -k test_pm_repair_decision_rejects_registered_but_not_receivable_rerun_target -k test_pm_repair_decision_rejects_unregistered_rerun_target_before_wait_write tests.router_runtime.control_blockers",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=5,
        selected_count=5,
        exit_code=0,
        result_path="tmp/flowguard_background/router_control_blockers_pm_repair_decisions.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("control_blockers_pm_repair_decisions",),
    ),
    TestSuiteEvidence(
        "router_control_blockers_protocol_transactions",
        command="python -m unittest -v -k test_operation_replay_repair_transaction_queues_replay_action -k test_repair_transaction_protocol_blocker_registers_followup_blocker -k test_repair_transaction_recheck_blocker_registers_followup_blocker tests.router_runtime.control_blockers",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=3,
        selected_count=3,
        exit_code=0,
        result_path="tmp/flowguard_background/router_control_blockers_protocol_transactions.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("control_blockers_protocol_transactions",),
    ),
    TestSuiteEvidence(
        "router_control_blockers_followup_fatal",
        command="python -m unittest -v -k test_control_blocker_reviewer_followup_rejects_pm_origin -k test_delivered_control_blocker_with_unsupported_historical_invalid_wait_falls_back_to_pm_repair_decision -k test_fatal_control_blocker_rejects_pm_ordinary_waiver tests.router_runtime.control_blockers",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=3,
        selected_count=3,
        exit_code=0,
        result_path="tmp/flowguard_background/router_control_blockers_followup_fatal.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("control_blockers_followup_fatal",),
    ),
    TestSuiteEvidence(
        "router_pm_role_work_requests",
        command="python -m unittest -v -k test_pm_role_work_request_requires_valid_recipient_and_contract -k test_pm_role_work_request_rejects_current_node_contract_family -k test_advisory_pm_role_work_wait_is_marked_nonblocking tests.router_runtime.pm_role_work",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=3,
        selected_count=3,
        exit_code=0,
        result_path="tmp/flowguard_background/router_pm_role_work_requests.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("pm_role_work_requests",),
    ),
    TestSuiteEvidence(
        "router_pm_role_work_results",
        command="python -m unittest -v -k test_gate_targeted_pm_role_work_result_requires_mapped_gate_event -k test_strict_pm_role_work_result_rejects_wrong_next_recipient -k test_pm_role_work_existing_result_reconciles_before_wait tests.router_runtime.pm_role_work",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=3,
        selected_count=3,
        exit_code=0,
        result_path="tmp/flowguard_background/router_pm_role_work_results.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("pm_role_work_gates", "pm_role_work_writes"),
    ),
    TestSuiteEvidence(
        "router_pm_role_work_waits",
        command="python -m unittest -v -k test_pm_role_work_batch_waits_for_all_flowguard_operator_results_before_pm_relay -k test_wait_event_producer_binding_rejects_wrong_target_role tests.router_runtime.pm_role_work",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=2,
        selected_count=2,
        exit_code=0,
        result_path="tmp/flowguard_background/router_pm_role_work_waits.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("pm_role_work_lifecycle", "pm_role_work_actions"),
    ),
    TestSuiteEvidence(
        "router_quality_gates_background_manifest",
        command="python -m unittest -v -k test_runtime_role_assistances_allow_requires_six_current_role_binding_records -k test_child_skill_gate_manifest_block_records_repair_without_approval -k test_child_skill_gate_manifest_repair_pass_clears_active_gate_block -k test_manifest_references_existing_system_cards tests.router_runtime.quality_gates",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=4,
        selected_count=4,
        exit_code=0,
        result_path="tmp/flowguard_background/router_quality_gates_background_manifest.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("quality_gates_background_manifest",),
    ),
    TestSuiteEvidence(
        "router_quality_gates_decisions",
        command="python -m unittest -v -k test_gate_decision_event_records_ledger_and_state -k test_gate_decision_rejects_mechanical_contradictions -k test_gate_decision_same_identity_replay_is_already_recorded -k test_gate_outcome_block_specs_are_registered_and_reset_stale_passes -k test_reviewer_and_flowguard_operator_gate_event_groups_have_non_pass_outcomes -k test_reviewer_block_events_are_registered_in_external_taxonomy tests.router_runtime.quality_gates",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=6,
        selected_count=6,
        exit_code=0,
        result_path="tmp/flowguard_background/router_quality_gates_decisions.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("quality_gates_decisions",),
    ),
    TestSuiteEvidence(
        "router_quality_gates_evidence_artifacts",
        command="python -m unittest -v -k test_evidence_quality_package_blocks_stale_and_missing_visual_evidence -k test_route_check_reports_require_hard_gate_verdict_fields -k test_route_check_results_require_router_delivered_check_cards -k test_router_owned_check_proof_rejects_self_attested_and_stale_audit -k test_validate_artifact_reports_gate_decision_issues_together -k test_validate_artifact_reports_node_acceptance_missing_fields_together tests.router_runtime.quality_gates",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=6,
        selected_count=6,
        exit_code=0,
        result_path="tmp/flowguard_background/router_quality_gates_evidence_artifacts.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("quality_gates_evidence_artifacts",),
    ),
    TestSuiteEvidence(
        "router_quality_gates_route_model",
        command="python -m unittest -v -k test_model_miss_review_block_flags_stay_in_sync -k test_node_acceptance_plan_requires_pm_high_standard_recheck -k test_process_route_repair_required_blocks_activation_and_reopens_pm_route_draft -k test_root_contract_freeze_requires_clean_self_interrogation_records -k test_route_draft_requires_product_behavior_model_report tests.router_runtime.quality_gates",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=5,
        selected_count=5,
        exit_code=0,
        result_path="tmp/flowguard_background/router_quality_gates_route_model.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("quality_gates_route_model",),
    ),
    TestSuiteEvidence(
        "router_quality_gates_node_contracts",
        command="python -m unittest -v -k test_next_effective_node_returns_parent_before_sibling_module_after_last_child -k test_node_completion_idempotency_is_scoped_to_active_node -k test_role_output_envelope_hash_survives_same_path_envelope_rewrite -k test_single_agent_answer_records_authorized_role_continuity_without_live_agents tests.router_runtime.quality_gates",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=4,
        selected_count=4,
        exit_code=0,
        result_path="tmp/flowguard_background/router_quality_gates_node_contracts.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("quality_gates_node_contracts",),
    ),
    TestSuiteEvidence(
        "router_material_modeling_intake",
        command="python -m unittest -v -k test_pm_material_understanding_accepts_file_backed_memo_payload -k test_material_acceptance_requires_reviewer_sufficiency_and_pm_absorb_card -k test_material_insufficient_event_records_insufficient_state -k test_material_scan_results_event_requires_result_ledger_absorption tests.router_runtime.material_modeling",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=4,
        selected_count=4,
        exit_code=0,
        result_path="tmp/flowguard_background/router_material_modeling_intake.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("material_modeling_intake",),
    ),
    TestSuiteEvidence(
        "router_material_modeling_scan_relay",
        command="python -m unittest -v -k test_material_scan_direct_relay_blocks_body_hash_mismatch -k test_material_scan_direct_relay_blocks_missing_output_contract -k test_material_scan_mechanical_agent_id_gap_reissues_to_worker tests.router_runtime.material_modeling",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=3,
        selected_count=3,
        exit_code=0,
        result_path="tmp/flowguard_background/router_material_modeling_scan_relay.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("material_modeling_scan_relay",),
    ),
    TestSuiteEvidence(
        "router_material_modeling_modelability",
        command="python -m unittest -v -k test_research_required_blocks_product_architecture_until_absorbed -k test_product_architecture_and_root_contract_gate_route_skeleton -k test_process_route_model_canonical_event_writes_unsupported_historical_alias -k test_unsupported_historical_flowguard_operator_product_scope_model_report_does_not_close_modelability_gate -k test_pm_repair_transaction_commits_material_reissue_generation tests.router_runtime.material_modeling",
        result_status=TEST_STATUS_PASSED,
        evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        test_count=5,
        selected_count=5,
        exit_code=0,
        result_path="tmp/flowguard_background/router_material_modeling_modelability.exit.txt",
        log_root="tmp/flowguard_background",
        background=True,
        owns_state=("material_modeling_modelability",),
    ),
)
