"""Router facade StructureMesh catalog for FlowPilot."""

from __future__ import annotations

from flowguard import (
    EVIDENCE_CONFORMANCE_GREEN,
    ModuleStructureEvidence,
    PublicEntrypointEvidence,
    StructurePartitionItem,
)

ROUTER_FACADE_ENTRYPOINTS = (
    PublicEntrypointEvidence(
        "flowpilot_router_public_api",
        old_path="skills/flowpilot/assets/flowpilot_router.py",
        new_path="skills/flowpilot/assets/flowpilot_router.py",
        parity_evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        evidence_path="simulations/flowpilot_router_facade_split_results.json",
        release_required=True,
    ),
    PublicEntrypointEvidence(
        "flowpilot_router_cli",
        entrypoint_type="cli",
        old_path="python skills/flowpilot/assets/flowpilot_router.py",
        new_path="python skills/flowpilot/assets/flowpilot_router.py",
        parity_evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        evidence_path="simulations/flowpilot_router_facade_split_results.json",
        release_required=True,
    ),
)

ROUTER_FACADE_PARTITIONS = (
    StructurePartitionItem(
        "public_router_facade",
        item_type="public_entrypoint",
        owner_module_id="router_facade",
        ownership="parent",
        public_surface=True,
    ),
    StructurePartitionItem(
        "public_api_allowlist",
        item_type="public_entrypoint",
        owner_module_id="router_facade",
        ownership="parent",
        public_surface=True,
    ),
    StructurePartitionItem(
        "owner_export_registry",
        item_type="config",
        owner_module_id="facade_export_manifest",
        old_path="flowpilot_router hand-written private compatibility wrappers",
        new_path="flowpilot_router_facade_export_manifest",
    ),
    StructurePartitionItem(
        "owner_export_installer",
        item_type="function_cluster",
        owner_module_id="facade_exports",
        old_path="flowpilot_router hand-written private compatibility wrappers",
        new_path="flowpilot_router_facade_exports",
    ),
    StructurePartitionItem(
        "route_state_root",
        item_type="state",
        owner_module_id="router_facade",
        ownership="parent",
    ),
    StructurePartitionItem(
        "prompt_manifest_loading",
        item_type="function_cluster",
        owner_module_id="prompt_store",
        old_path="flowpilot_router inline prompt literals",
        new_path="flowpilot_prompt_store",
    ),
    StructurePartitionItem(
        "prompt_assets",
        item_type="config",
        owner_module_id="prompt_assets",
        old_path="flowpilot_router inline strings",
        new_path="runtime_kit/prompts",
    ),
    StructurePartitionItem(
        "card_post_ack_policy",
        item_type="prompt",
        owner_module_id="prompt_delivery",
        new_path="runtime_kit/prompts/cards",
    ),
    StructurePartitionItem(
        "controller_table_prompt",
        item_type="prompt",
        owner_module_id="prompt_delivery",
        new_path="runtime_kit/prompts/controller",
    ),
    StructurePartitionItem(
        "startup_heartbeat_prompt",
        item_type="prompt",
        owner_module_id="prompt_delivery",
        new_path="runtime_kit/prompts/startup",
    ),
    StructurePartitionItem(
        "packet_identity_prompt",
        item_type="prompt",
        owner_module_id="prompt_assets",
        old_path="packet_runtime_contracts inline packet identity text",
        new_path="runtime_kit/prompts/packets",
    ),
    StructurePartitionItem(
        "packet_result_identity_prompt",
        item_type="prompt",
        owner_module_id="prompt_assets",
        old_path="packet_runtime_contracts inline result identity text",
        new_path="runtime_kit/prompts/packets",
    ),
    StructurePartitionItem(
        "packet_output_contract_prompt",
        item_type="prompt",
        owner_module_id="prompt_assets",
        old_path="packet_runtime_contracts inline output contract text",
        new_path="runtime_kit/prompts/packets",
    ),
    StructurePartitionItem(
        "controller_ledger_paths",
        item_type="function_cluster",
        owner_module_id="controller_ledger",
        old_path="flowpilot_router controller ledger path helpers",
        new_path="flowpilot_router_controller_ledger",
    ),
    StructurePartitionItem(
        "router_scheduler_projection",
        item_type="function_cluster",
        owner_module_id="controller_ledger",
        old_path="flowpilot_router scheduler progress/barrier helpers",
        new_path="flowpilot_router_controller_ledger",
    ),
    StructurePartitionItem(
        "card_delivery_ledgers",
        item_type="function_cluster",
        owner_module_id="card_delivery",
        old_path="flowpilot_router card/return ledger helpers",
        new_path="flowpilot_router_card_delivery",
    ),
    StructurePartitionItem(
        "card_return_settlement",
        item_type="function_cluster",
        owner_module_id="card_returns",
        old_path="flowpilot_router ACK return settlement helpers",
        new_path="flowpilot_router_card_returns",
    ),
    StructurePartitionItem(
        "role_io_protocol",
        item_type="function_cluster",
        owner_module_id="role_io_protocol",
        old_path="flowpilot_router role I/O protocol helpers",
        new_path="flowpilot_router_role_io_protocol",
    ),
    StructurePartitionItem(
        "event_identity",
        item_type="function_cluster",
        owner_module_id="event_identity",
        old_path="flowpilot_router event payload/idempotency helpers",
        new_path="flowpilot_router_event_identity",
    ),
    StructurePartitionItem(
        "daemon_runtime",
        item_type="function_cluster",
        owner_module_id="daemon_runtime",
        old_path="flowpilot_router daemon lock/status/tick helpers",
        new_path="flowpilot_router_daemon_runtime",
    ),
    StructurePartitionItem(
        "process_liveness_probe",
        item_type="function_cluster",
        owner_module_id="process_liveness",
        old_path="duplicated process liveness helpers in router IO and startup daemon",
        new_path="flowpilot_process_liveness",
    ),
    StructurePartitionItem(
        "runtime_state",
        item_type="function_cluster",
        owner_module_id="runtime_state",
        old_path="flowpilot_router run/bootstrap state helpers",
        new_path="flowpilot_router_runtime_state",
    ),
    StructurePartitionItem(
        "router_protocol_catalog",
        item_type="config",
        owner_module_id="protocol_catalog",
        old_path="flowpilot_router top-level schema/action/event/gate catalogs",
        new_path="flowpilot_router_protocol_catalog",
    ),
    StructurePartitionItem(
        "startup_flow",
        item_type="function_cluster",
        owner_module_id="startup_flow",
        old_path="flowpilot_router startup/bootloader/resume phase bodies",
        new_path="flowpilot_router_startup_flow",
    ),
    StructurePartitionItem(
        "startup_bootloader",
        item_type="function_cluster",
        owner_module_id="startup_bootloader",
        old_path="flowpilot_router_startup_flow bootloader action bodies",
        new_path="flowpilot_router_startup_bootloader",
    ),
    StructurePartitionItem(
        "startup_intake",
        item_type="function_cluster",
        owner_module_id="startup_intake",
        old_path="flowpilot_router_startup_flow intake and answer bodies",
        new_path="flowpilot_router_startup_intake",
    ),
    StructurePartitionItem(
        "startup_display",
        item_type="function_cluster",
        owner_module_id="startup_display",
        old_path="flowpilot_router_startup_flow display and route-sign bodies",
        new_path="flowpilot_router_startup_display",
    ),
    StructurePartitionItem(
        "startup_role_recovery",
        item_type="function_cluster",
        owner_module_id="startup_role_recovery",
        old_path="flowpilot_router_startup_flow resume and role-recovery bodies",
        new_path="flowpilot_router_startup_role_recovery",
    ),
    StructurePartitionItem(
        "startup_closure",
        item_type="function_cluster",
        owner_module_id="startup_closure",
        old_path="flowpilot_router_startup_flow startup closure reconciliation bodies",
        new_path="flowpilot_router_startup_closure",
    ),
    StructurePartitionItem(
        "startup_fact_boundary",
        item_type="function_cluster",
        owner_module_id="startup_fact_boundary",
        old_path="flowpilot_router_startup_flow startup fact and boundary audit bodies",
        new_path="flowpilot_router_startup_fact_boundary",
    ),
    StructurePartitionItem(
        "self_interrogation",
        item_type="function_cluster",
        owner_module_id="self_interrogation",
        old_path="flowpilot_router self-interrogation status helpers",
        new_path="flowpilot_router_self_interrogation",
    ),
    StructurePartitionItem(
        "payload_contracts",
        item_type="function_cluster",
        owner_module_id="payload_contracts",
        old_path="flowpilot_router payload contract builders",
        new_path="flowpilot_router_payload_contracts",
    ),
    StructurePartitionItem(
        "controller_scheduler",
        item_type="function_cluster",
        owner_module_id="controller_scheduler",
        old_path="flowpilot_router controller scheduler/receipt/standby bodies",
        new_path="flowpilot_router_controller_scheduler",
    ),
    StructurePartitionItem(
        "controller_repair",
        item_type="function_cluster",
        owner_module_id="controller_repair",
        old_path="flowpilot_router controller repair and postcondition reconciliation helpers",
        new_path="flowpilot_router_controller_repair",
    ),
    StructurePartitionItem(
        "action_factory",
        item_type="function_cluster",
        owner_module_id="action_factory",
        old_path="flowpilot_router action factory and dispatch-recipient gate helpers",
        new_path="flowpilot_router_action_factory",
    ),
    StructurePartitionItem(
        "work_packets",
        item_type="function_cluster",
        owner_module_id="work_packets",
        old_path="flowpilot_router material/research/current-node/PM packet bodies",
        new_path="flowpilot_router_work_packets",
    ),
    StructurePartitionItem(
        "route_artifacts",
        item_type="function_cluster",
        owner_module_id="route_artifacts",
        old_path="flowpilot_router PM-authored route/product/node artifact writers",
        new_path="flowpilot_router_route_artifacts",
    ),
    StructurePartitionItem(
        "events_repair",
        item_type="function_cluster",
        owner_module_id="events_repair",
        old_path="flowpilot_router control blocker and repair transaction bodies",
        new_path="flowpilot_router_events_repair",
    ),
    StructurePartitionItem(
        "lifecycle_requests",
        item_type="function_cluster",
        owner_module_id="lifecycle_requests",
        old_path="flowpilot_router run lifecycle request and protocol-dead-end helpers",
        new_path="flowpilot_router_lifecycle_requests",
    ),
    StructurePartitionItem(
        "event_dispatcher",
        item_type="function_cluster",
        owner_module_id="event_dispatcher",
        old_path="flowpilot_router external event dispatcher body",
        new_path="flowpilot_router_event_dispatcher",
    ),
    StructurePartitionItem(
        "system_cards",
        item_type="function_cluster",
        owner_module_id="system_cards",
        old_path="flowpilot_router system-card action selection and delivery commit helpers",
        new_path="flowpilot_router_system_cards",
    ),
    StructurePartitionItem(
        "expected_waits",
        item_type="function_cluster",
        owner_module_id="expected_waits",
        old_path="flowpilot_router expected role wait and pending event reconciliation helpers",
        new_path="flowpilot_router_expected_waits",
    ),
    StructurePartitionItem(
        "route_frontier",
        item_type="function_cluster",
        owner_module_id="route_frontier",
        old_path="flowpilot_router route/frontier/node completion bodies",
        new_path="flowpilot_router_route_frontier",
    ),
    StructurePartitionItem(
        "terminal_ledger",
        item_type="function_cluster",
        owner_module_id="terminal_ledger",
        old_path="flowpilot_router terminal ledger/replay/closure bodies",
        new_path="flowpilot_router_terminal_ledger",
    ),
)

ROUTER_FACADE_MODULES = (
    ModuleStructureEvidence(
        "router_facade",
        path="skills/flowpilot/assets/flowpilot_router.py",
        layer="parent",
        owns_functions=(),
        owns_state=("route_state_root",),
        behavior_contracts=("public API allowlist", "CLI skeleton", "owner-export registry installation"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "facade_exports",
        path="skills/flowpilot/assets/flowpilot_router_facade_exports.py",
        owns_functions=("install_facade_exports", "resolve_facade_export"),
        dependencies=("facade_export_manifest", "router_facade"),
        behavior_contracts=("owner export installation", "no hand-written wrapper bodies in router skeleton"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "facade_export_manifest",
        path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest.py",
        owns_config=("owner_export_registry",),
        behavior_contracts=("transitional owner export registry", "public export allowlist authority"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "facade_export_manifest_actions",
        path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_actions.py",
        owns_config=("owner_export_manifest_actions",),
        behavior_contracts=("action-domain owner export registry shard",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "facade_export_manifest_controller",
        path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_controller.py",
        owns_config=("owner_export_manifest_controller",),
        behavior_contracts=("controller-domain owner export registry shard",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "facade_export_manifest_route",
        path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_route.py",
        owns_config=("owner_export_manifest_route",),
        behavior_contracts=("route-domain owner export registry shard",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "facade_export_manifest_startup",
        path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_startup.py",
        owns_config=("owner_export_manifest_startup",),
        behavior_contracts=("startup-domain owner export registry shard",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "facade_export_manifest_terminal_work",
        path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_terminal_work.py",
        owns_config=("owner_export_manifest_terminal_work",),
        behavior_contracts=("terminal/work-packet owner export registry shard",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "cli",
        path="skills/flowpilot/assets/flowpilot_router_cli.py",
        owns_functions=("parse_args", "main"),
        dependencies=("router_facade", "controller_runtime"),
        behavior_contracts=("CLI command surface", "JSON error envelope", "runtime writer settlement"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "controller_runtime",
        path="skills/flowpilot/assets/flowpilot_router_controller_runtime.py",
        owns_functions=("next_action", "compute_controller_action", "apply_action", "apply_controller_action", "run_until_wait", "record_external_event"),
        owns_state=("controller_runtime_loop",),
        dependencies=("action_factory", "action_handlers", "action_providers", "event_dispatcher", "router_facade"),
        behavior_contracts=("next action loop", "controller apply loop", "external event entrypoint", "safe run-until-wait folding"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "artifact_validation",
        path="skills/flowpilot/assets/flowpilot_router_artifact_validation.py",
        owns_functions=("validate_artifact", "_validate_hash_if_present", "_validate_role_output_hash_if_present"),
        dependencies=("packet_runtime", "role_output_bridge", "router_facade"),
        behavior_contracts=("artifact validation CLI/API", "hash validation", "role output envelope validation"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "control_transactions",
        path="skills/flowpilot/assets/flowpilot_router_control_transactions.py",
        owns_functions=("_control_transaction_registry_issues", "_validate_control_transaction_requirements"),
        owns_config=("control_transaction_registry",),
        behavior_contracts=("control transaction registry validation", "output contract coverage"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "internal_actions",
        path="skills/flowpilot/assets/flowpilot_router_internal_actions.py",
        owns_functions=("_consume_router_internal_mechanical_action", "_action_is_router_internal_mechanical"),
        owns_state=("router_internal_mechanical_events",),
        dependencies=("startup_flow", "router_facade"),
        behavior_contracts=("internal mechanical action guard", "manifest/ledger check folding", "mechanical audit write"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "role_output_bridge",
        path="skills/flowpilot/assets/flowpilot_router_role_output_bridge.py",
        owns_functions=("write_role_output_envelope", "_try_reconcile_startup_fact_role_output_ledger"),
        owns_state=("role_output_bridge_records",),
        dependencies=("role_output_runtime", "system_cards", "router_facade"),
        behavior_contracts=("role output envelope bridge", "startup fact role-output reconciliation", "prompt delivery context repair"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "startup_support",
        path="skills/flowpilot/assets/flowpilot_router_startup_support.py",
        owns_functions=("_ensure_startup_run_state", "load_manifest_from_run", "manifest_card"),
        owns_state=("startup_run_state_creation",),
        dependencies=("runtime_state", "prompt_store", "router_facade"),
        behavior_contracts=("startup run state creation", "prompt manifest lookup", "startup event digest helpers"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "lifecycle_support",
        path="skills/flowpilot/assets/flowpilot_router_lifecycle_support.py",
        owns_functions=("_write_host_heartbeat_binding", "_reset_resume_cycle_for_wakeup"),
        owns_state=("lifecycle_support_records",),
        dependencies=("lifecycle_requests", "router_facade"),
        behavior_contracts=("heartbeat binding write", "resume cycle reset", "lifecycle record paths"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "child_skill_capability",
        path="skills/flowpilot/assets/flowpilot_router_child_skill_capability.py",
        owns_functions=("_approve_child_skill_manifest_for_route", "_sync_capability_evidence"),
        owns_state=("child_skill_capability_evidence",),
        dependencies=("route_artifacts", "router_facade"),
        behavior_contracts=("child-skill manifest approval", "capability evidence sync"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "route_completion_support",
        path="skills/flowpilot/assets/flowpilot_router_route_completion_support.py",
        owns_functions=("_active_node_completion_write_missing", "_node_completion_event_advanced_to_next_node"),
        owns_state=("route_completion_support",),
        dependencies=("route_frontier", "router_facade"),
        behavior_contracts=("active node completion helper paths", "resume completion predicates"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "model_gate_state",
        path="skills/flowpilot/assets/flowpilot_router_model_gate_state.py",
        owns_functions=("_sync_model_gate_alias_flags", "_require_single_active_model_miss_review_block"),
        owns_state=("model_gate_alias_flags",),
        behavior_contracts=("model gate alias flag sync", "model-miss block uniqueness"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "pm_role_followup",
        path="skills/flowpilot/assets/flowpilot_router_pm_role_followup.py",
        owns_functions=("_validate_pm_role_work_request_against_followup", "_pm_role_work_channel_open"),
        dependencies=("work_packets", "events_repair", "router_facade"),
        behavior_contracts=("PM role-work follow-up validation", "model-miss follow-up channel check"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "proof_validation",
        path="skills/flowpilot/assets/flowpilot_router_proof_validation.py",
        owns_functions=("_validate_router_owned_check_proof",),
        dependencies=("self_interrogation", "packet_runtime", "router_facade"),
        behavior_contracts=("router-owned proof validation", "non-self-attested evidence requirement"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "prompt_store",
        path="skills/flowpilot/assets/flowpilot_prompt_store.py",
        owns_functions=("load_prompt_manifest", "load_prompt_text", "render_prompt_text"),
        owns_config=("prompt_manifest",),
        behavior_contracts=("strict prompt rendering", "hash validation", "no inline fallback"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "prompt_delivery",
        path="skills/flowpilot/assets/flowpilot_router_prompt_delivery.py",
        owns_functions=("card_checkin_instruction", "controller_table_prompt", "startup_heartbeat_prompt"),
        behavior_contracts=("card ACK instruction", "controller table prompt", "heartbeat prompt rendering"),
        dependencies=("prompt_store",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "prompt_assets",
        path="skills/flowpilot/assets/runtime_kit/prompts",
        owns_config=("prompt_assets",),
        behavior_contracts=("runtime-kit copy", "install-check inclusion", "content hash authority"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "controller_ledger",
        path="skills/flowpilot/assets/flowpilot_router_controller_ledger.py",
        owns_functions=("controller_action_ledger_path", "router_scheduler_progress_class", "prepare_router_scheduled_action"),
        owns_config=("controller_ledger_schemas",),
        behavior_contracts=("ledger path compatibility", "scheduler progress projection", "facade wrappers"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "card_delivery",
        path="skills/flowpilot/assets/flowpilot_router_card_delivery.py",
        owns_functions=("read_card_ledger", "read_return_event_ledger", "card_return_event_for_card"),
        owns_state=("card_delivery_ledgers",),
        behavior_contracts=("card ledger schema", "return event mapping", "delivery attempt identity"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "card_returns",
        path="skills/flowpilot/assets/flowpilot_router_card_returns.py",
        owns_functions=(
            "_pending_return_records",
            "_next_pending_card_return_action",
            "_apply_card_return_event_check",
            "_run_router_return_settlement_finalizers",
        ),
        owns_state=("card_return_settlement",),
        dependencies=("card_delivery", "router_facade"),
        behavior_contracts=(
            "ACK wait settlement",
            "ACK does not complete output-bearing work",
            "startup user-intake release remains mail-delivery gated",
        ),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "role_io_protocol",
        path="skills/flowpilot/assets/flowpilot_router_role_io_protocol.py",
        owns_functions=("role_io_protocol_payload", "append_role_io_protocol_injections", "role_io_protocol_receipt_for_agent"),
        owns_state=("role_io_protocol",),
        behavior_contracts=("role lifecycle protocol hash", "injection receipts", "role output envelope authority"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "event_identity",
        path="skills/flowpilot/assets/flowpilot_router_event_identity.py",
        owns_functions=(
            "_normalize_record_event_payload",
            "_scoped_event_identity",
            "_check_scoped_event_retry_budget",
            "_already_recorded_external_event_result",
        ),
        owns_state=("event_identity",),
        dependencies=("router_facade",),
        behavior_contracts=(
            "event envelope validation",
            "external event idempotency",
            "retry budget enforcement",
            "already-recorded event replay",
        ),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "daemon_runtime",
        path="skills/flowpilot/assets/flowpilot_router_daemon_runtime.py",
        owns_functions=(
            "_acquire_router_daemon_lock",
            "_write_router_daemon_status",
            "_router_daemon_tick",
            "run_router_daemon",
            "stop_router_daemon",
        ),
        owns_state=("daemon_runtime",),
        dependencies=("controller_ledger", "router_facade"),
        behavior_contracts=(
            "daemon lock ownership",
            "daemon status lifecycle",
            "bounded queue fill",
            "foreground console hidden by tier runner",
        ),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "process_liveness",
        path="skills/flowpilot/assets/flowpilot_process_liveness.py",
        owns_functions=("process_is_live",),
        behavior_contracts=("shared pid liveness probe", "no lock-domain state ownership"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "runtime_state",
        path="skills/flowpilot/assets/flowpilot_router_runtime_state.py",
        owns_functions=("new_bootstrap_state", "new_run_state", "load_run_state", "save_run_state"),
        owns_state=("bootstrap_state", "run_state", "continuation_quarantine"),
        dependencies=("router_facade",),
        behavior_contracts=("run state shape", "bootstrap state persistence", "runtime state compatibility wrappers"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "protocol_catalog",
        path="skills/flowpilot/assets/flowpilot_router_protocol_catalog.py",
        owns_functions=(
            "_public_gate_contract",
            "_gate_contract_for_id",
            "_gate_contract_for_card",
            "_gate_contract_for_event",
            "_gate_completion_wait_group",
        ),
        owns_config=("router_protocol_catalog",),
        behavior_contracts=(
            "schema constants",
            "boot and system-card catalogs",
            "external event metadata",
            "gate contract tables",
            "model gate alias tables",
        ),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "startup_flow",
        path="skills/flowpilot/assets/flowpilot_router_startup_flow.py",
        owns_functions=(),
        owns_state=(),
        dependencies=("startup_bootloader", "startup_intake", "startup_display", "startup_role_recovery", "startup_closure", "startup_fact_boundary"),
        behavior_contracts=("startup owner-module binding", "startup group ownership boundary"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "startup_bootloader",
        path="skills/flowpilot/assets/flowpilot_router_startup_bootloader.py",
        owns_functions=("compute_bootloader_action", "apply_bootloader_action", "_next_bootloader_open_action"),
        owns_state=("startup_bootloader",),
        dependencies=("runtime_state", "payload_contracts", "router_facade"),
        behavior_contracts=("bootloader action ordering", "daemon-control bootstrap", "startup question stop boundary"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "startup_intake",
        path="skills/flowpilot/assets/flowpilot_router_startup_intake.py",
        owns_functions=("_validate_startup_answer_payload", "_materialize_startup_intake_answers", "_ensure_startup_intake_ui"),
        owns_state=("startup_answers", "startup_intake_ui"),
        dependencies=("startup_support", "router_facade"),
        behavior_contracts=("startup answer validation", "intake UI materialization", "deterministic bootstrap seed"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "startup_display",
        path="skills/flowpilot/assets/flowpilot_router_startup_display.py",
        owns_functions=("_next_startup_display_action", "_write_startup_display_plan", "_ensure_route_sign_display_sync"),
        owns_state=("startup_display", "route_sign_display"),
        dependencies=("startup_support", "payload_contracts", "router_facade"),
        behavior_contracts=("startup display plan", "user dialogue projection", "route sign synchronization"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "startup_role_recovery",
        path="skills/flowpilot/assets/flowpilot_router_startup_role_recovery.py",
        owns_functions=("_next_resume_action", "_next_role_recovery_action", "_record_role_spawn_intent"),
        owns_state=("resume_role_recovery", "role_spawn_intents", "continuation_bindings"),
        dependencies=("controller_scheduler", "runtime_state", "router_facade"),
        behavior_contracts=("resume action selection", "role recovery persistence", "continuation binding rehydration"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "startup_closure",
        path="skills/flowpilot/assets/flowpilot_router_startup_closure.py",
        owns_functions=("_startup_closure_reconciliation_status", "_next_startup_closure_action"),
        owns_state=("startup_closure_reconciliation", "heartbeat_host_binding"),
        dependencies=("lifecycle_support", "terminal_ledger", "router_facade"),
        behavior_contracts=("startup closure reconciliation", "heartbeat binding readiness", "dirty closure invalidation"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "startup_fact_boundary",
        path="skills/flowpilot/assets/flowpilot_router_startup_fact_boundary.py",
        owns_functions=("_next_startup_fact_boundary_action", "_next_startup_mechanical_audit_action", "_write_startup_fact_report"),
        owns_state=("startup_fact_boundary", "startup_mechanical_audit", "controller_boundary_confirmation"),
        dependencies=("controller_boundary", "role_output_bridge", "router_facade"),
        behavior_contracts=("startup fact audit", "controller boundary confirmation", "mechanical audit repair actions"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "controller_scheduler",
        path="skills/flowpilot/assets/flowpilot_router_controller_scheduler.py",
        owns_functions=("_write_controller_action_entry", "_reconcile_controller_receipts", "foreground_controller_standby", "controller_patrol_timer"),
        owns_state=("router_scheduler_ledger", "controller_action_rows", "controller_receipts", "foreground_standby"),
        dependencies=("controller_ledger", "router_facade"),
        behavior_contracts=("controller receipt reconciliation", "scheduler row lifecycle", "standby/patrol status compatibility"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "controller_scheduler_receipt_writes",
        path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_writes.py",
        owns_functions=("_write_controller_action_entry", "_write_controller_receipt"),
        owns_side_effects=("controller_action_receipt_write",),
        dependencies=("controller_scheduler", "router_facade"),
        behavior_contracts=("controller action and receipt write helpers",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "controller_scheduler_receipt_effects",
        path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_effects.py",
        owns_functions=("_apply_stateful_receipt_postcondition", "_apply_done_controller_receipt_effects"),
        dependencies=("controller_scheduler_receipt_writes", "router_facade"),
        behavior_contracts=("Controller receipt postcondition effects",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "controller_scheduler_receipt_pending",
        path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_pending.py",
        owns_functions=("_reconcile_pending_controller_action_receipt", "_clear_pending_after_reconciled_controller_receipt"),
        dependencies=("controller_scheduler_receipt_effects", "router_facade"),
        behavior_contracts=("pending Controller action receipt reconciliation",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "controller_scheduler_receipt_scheduled",
        path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_scheduled.py",
        owns_functions=("_reconcile_scheduled_controller_action_receipts", "_backfill_scheduler_row_from_reconciled_controller_action"),
        dependencies=("controller_scheduler_receipt_pending", "router_facade"),
        behavior_contracts=("scheduled Controller action reconciliation and scheduler backfill",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "controller_repair",
        path="skills/flowpilot/assets/flowpilot_router_controller_repair.py",
        owns_functions=(
            "_close_waiting_controller_actions_for_external_event",
            "_fold_mail_delivery_postcondition",
            "_schedule_controller_deliverable_repair",
            "_reclaim_router_owned_postcondition_from_artifact",
        ),
        owns_state=("controller_postcondition_repairs",),
        dependencies=("controller_scheduler", "events_repair", "router_facade"),
        behavior_contracts=(
            "controller receipt repair",
            "mail delivery postcondition folding",
            "router-owned postcondition reclaim",
        ),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "action_factory",
        path="skills/flowpilot/assets/flowpilot_router_action_factory.py",
        owns_functions=("make_action", "_dispatch_gate_wait_action", "_apply_dispatch_recipient_gate"),
        owns_state=("controller_action_envelope", "dispatch_recipient_gate"),
        dependencies=("system_cards", "work_packets", "router_facade"),
        behavior_contracts=("action envelope construction", "dispatch-recipient gating", "formal work ACK preflight"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "action_factory_reconciliation",
        path="skills/flowpilot/assets/flowpilot_router_action_factory_reconciliation.py",
        owns_functions=("_current_scope_pre_review_reconciliation_action", "_apply_formal_work_packet_ack_preflight"),
        dependencies=("action_factory", "router_facade"),
        behavior_contracts=("scope reconciliation waits and formal work packet ACK preflight",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "action_factory_dispatch",
        path="skills/flowpilot/assets/flowpilot_router_action_factory_dispatch.py",
        owns_functions=("_apply_dispatch_recipient_gate", "_dispatch_gate_wait_action"),
        dependencies=("action_factory_reconciliation", "router_facade"),
        behavior_contracts=("dispatch recipient gate and blocker helpers",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "action_factory_envelope",
        path="skills/flowpilot/assets/flowpilot_router_action_factory_envelope.py",
        owns_functions=("make_action", "append_history", "_controller_user_reporting_policy"),
        dependencies=("action_factory_dispatch", "router_facade"),
        behavior_contracts=("action envelope and Controller user-reporting policy",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "work_packets",
        path="skills/flowpilot/assets/flowpilot_router_work_packets.py",
        owns_functions=("_next_material_packet_action", "_next_research_packet_action", "_next_current_node_packet_action", "_next_pm_role_work_request_action"),
        owns_state=("packet_ledger", "parallel_packet_batches", "pm_role_work_index", "current_node_packet_records"),
        dependencies=("route_frontier", "router_facade"),
        behavior_contracts=("packet relay lifecycle", "PM role-work lifecycle", "current-node packet absorption"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "pm_role_work_gates",
        path="skills/flowpilot/assets/flowpilot_router_work_packets_pm_role_gates.py",
        owns_functions=("_pm_role_work_gate_mappings_for_decision", "_apply_pm_role_work_gate_mappings"),
        dependencies=("work_packets", "router_facade"),
        behavior_contracts=("PM role-work gate mapping and targeted result contracts",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "pm_role_work_writes",
        path="skills/flowpilot/assets/flowpilot_router_work_packets_pm_role_writes.py",
        owns_functions=("_write_pm_role_work_request", "_write_role_work_result_returned", "_write_pm_role_work_result_decision"),
        owns_side_effects=("pm_role_work_request_result_write",),
        dependencies=("pm_role_work_gates", "router_facade"),
        behavior_contracts=("PM role-work request/result/disposition writes",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "pm_role_work_lifecycle",
        path="skills/flowpilot/assets/flowpilot_router_work_packets_pm_role_lifecycle.py",
        owns_functions=("_load_pm_role_work_request_index", "_record_officer_lifecycle_status"),
        owns_state=("pm_role_work_request_index", "officer_request_lifecycle"),
        dependencies=("router_facade",),
        behavior_contracts=("PM role-work request indexes and officer lifecycle records",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "pm_role_work_actions",
        path="skills/flowpilot/assets/flowpilot_router_work_packets_pm_role_actions.py",
        owns_functions=("_next_pm_role_work_request_action", "_try_reconcile_pm_role_work_results"),
        dependencies=("pm_role_work_lifecycle", "pm_role_work_writes", "router_facade"),
        behavior_contracts=("PM role-work next-action selection and result reconciliation",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "route_artifacts",
        path="skills/flowpilot/assets/flowpilot_router_route_artifacts.py",
        owns_functions=(
            "_write_product_function_architecture",
            "_write_root_acceptance_contract",
            "_write_node_acceptance_plan",
            "_write_evidence_quality_package",
        ),
        owns_state=("route_artifact_records", "acceptance_contracts", "node_acceptance_plans"),
        dependencies=("route_frontier", "work_packets", "router_facade"),
        behavior_contracts=("PM route artifact writes", "node acceptance plan validation", "evidence package persistence"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "events_repair",
        path="skills/flowpilot/assets/flowpilot_router_events_repair.py",
        owns_functions=("_write_control_blocker", "_next_control_blocker_action", "_write_control_blocker_repair_decision", "_finalize_repair_transaction_outcome"),
        owns_state=("active_control_blocker", "repair_transactions", "gate_decisions"),
        dependencies=("event_identity", "work_packets", "router_facade"),
        behavior_contracts=("control blocker materialization", "repair transaction finalization", "gate decision validation"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "lifecycle_requests",
        path="skills/flowpilot/assets/flowpilot_router_lifecycle_requests.py",
        owns_functions=("_write_run_lifecycle_request", "_write_protocol_dead_end_lifecycle", "_try_write_control_blocker_for_exception"),
        owns_state=("run_lifecycle_requests", "protocol_dead_end_records"),
        dependencies=("events_repair", "terminal_ledger", "router_facade"),
        behavior_contracts=("lifecycle request persistence", "protocol dead-end blocking", "exception-to-blocker routing"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "event_dispatcher",
        path="skills/flowpilot/assets/flowpilot_router_event_dispatcher.py",
        owns_functions=("_record_external_event_unchecked",),
        owns_state=("external_event_dispatch",),
        dependencies=("events_repair", "route_frontier", "terminal_ledger", "work_packets", "router_facade"),
        behavior_contracts=("external event dispatch compatibility", "wait-action settlement", "event finalizer delegation"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "system_cards",
        path="skills/flowpilot/assets/flowpilot_router_system_cards.py",
        owns_functions=(
            "_next_system_card_action",
            "_next_system_card_bundle_action",
            "_commit_system_card_delivery_artifact",
            "_commit_system_card_bundle_delivery_artifact",
        ),
        owns_state=("system_card_delivery_actions", "system_card_bundle_delivery_actions"),
        dependencies=("card_delivery", "card_returns", "router_facade"),
        behavior_contracts=("system-card action ordering", "bundle delivery commit", "direct ACK token construction"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "expected_waits",
        path="skills/flowpilot/assets/flowpilot_router_expected_waits.py",
        owns_functions=(
            "_expected_role_decision_wait_action",
            "_pending_expected_external_event_groups",
            "_reconcile_pending_role_wait_from_packet_status",
            "_record_router_reconciled_external_event",
        ),
        owns_state=("expected_role_waits", "pending_event_groups"),
        dependencies=("event_dispatcher", "work_packets", "router_facade"),
        behavior_contracts=("role decision wait construction", "pending event grouping", "packet-status wait reconciliation"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "route_frontier",
        path="skills/flowpilot/assets/flowpilot_router_route_frontier.py",
        owns_functions=("_active_frontier", "_legal_next_action_context", "_mark_frontier_node_completed", "_write_node_completion_ledger"),
        owns_state=("execution_frontier", "route_state_snapshots", "node_completion_ledger"),
        dependencies=("router_facade",),
        behavior_contracts=("route/frontier projection", "legal next-action context", "node completion lifecycle"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "payload_contracts",
        path="skills/flowpilot/assets/flowpilot_router_payload_contracts.py",
        owns_functions=("_payload_contract", "_startup_answers_payload_contract", "_pm_terminal_closure_payload_contract"),
        owns_config=("payload_contract_builders",),
        dependencies=("protocol_catalog", "router_facade"),
        behavior_contracts=("role payload contract builders", "display payload contract builders", "PM decision payload contracts"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "self_interrogation",
        path="skills/flowpilot/assets/flowpilot_router_self_interrogation.py",
        owns_functions=("_self_interrogation_status", "_self_interrogation_record_issues", "_require_clean_self_interrogation"),
        owns_state=("self_interrogation_index", "pm_suggestion_ledger"),
        dependencies=("router_facade",),
        behavior_contracts=("self-interrogation issue status", "PM suggestion ledger cleanliness", "startup self-check gating"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "terminal_ledger",
        path="skills/flowpilot/assets/flowpilot_router_terminal_ledger.py",
        owns_functions=("_write_final_route_wide_ledger", "_write_terminal_backward_replay", "_write_terminal_closure_suite", "reconcile_current_run"),
        owns_state=("final_route_wide_ledger", "terminal_backward_replay", "terminal_closure_suite"),
        dependencies=("route_frontier", "runtime_state", "router_facade"),
        behavior_contracts=("terminal ledger traceability", "closure suite persistence", "terminal status reconciliation"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "terminal_ledger_summary",
        path="skills/flowpilot/assets/flowpilot_router_terminal_ledger_summary.py",
        owns_functions=("_terminal_summary_action", "_write_terminal_summary"),
        owns_side_effects=("terminal_summary_write",),
        dependencies=("terminal_ledger", "router_facade"),
        behavior_contracts=("terminal summary validation and write",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "terminal_ledger_traceability",
        path="skills/flowpilot/assets/flowpilot_router_terminal_ledger_traceability.py",
        owns_functions=("_final_ledger_traceability_issues", "_write_final_route_wide_ledger"),
        owns_side_effects=("final_route_wide_ledger_write",),
        dependencies=("terminal_ledger", "router_facade"),
        behavior_contracts=("final ledger traceability and source-of-truth entries",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "terminal_ledger_closure",
        path="skills/flowpilot/assets/flowpilot_router_terminal_ledger_closure.py",
        owns_functions=("_write_terminal_backward_replay", "_write_terminal_closure_suite"),
        owns_side_effects=("terminal_backward_replay_write", "terminal_closure_suite_write"),
        dependencies=("terminal_ledger_traceability", "router_facade"),
        behavior_contracts=("terminal backward replay and closure suite writes",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "terminal_ledger_recovery",
        path="skills/flowpilot/assets/flowpilot_router_terminal_ledger_recovery.py",
        owns_functions=("reconcile_current_run", "_repair_legacy_material_packet_contracts"),
        owns_side_effects=("terminal_reconciliation_write",),
        dependencies=("terminal_ledger", "router_facade"),
        behavior_contracts=("terminal status recovery and legacy material packet repair",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
)
