"""Source-audited code contracts for FlowPilot model-test alignment."""

from __future__ import annotations

from flowpilot_model_test_alignment_common import *


def source_code_contracts() -> tuple[CodeContract, ...]:
    """Return source-audited code contract rows."""

    return (
        _contract(
            "router.run_until_wait",
            path="skills/flowpilot/assets/flowpilot_router_controller_runtime.py",
            symbol="run_until_wait",
            implements=("startup.questions.pause_before_work",),
            external_inputs=("project_root",),
        ),
        _contract(
            "router.apply_action",
            path="skills/flowpilot/assets/flowpilot_router_controller_runtime.py",
            symbol="apply_action",
            implements=("startup.questions.pause_before_work", "resume.current_run_reentry"),
            external_inputs=("project_root", "action_type", "payload"),
        ),
        _contract(
            "router.record_external_event",
            path="skills/flowpilot/assets/flowpilot_router_controller_runtime.py",
            symbol="record_external_event",
            implements=(
                "startup.run_isolation_and_activation",
                "ack.return_wait_preconsumption",
                "route_mutation.topology_and_recheck",
                "route_mutation.sibling_replacement_stales_old_evidence",
                "terminal.final_ledger_and_backward_replay",
                "resume.current_run_reentry",
                "router_loop.packet_result_review_loop",
            ),
            external_inputs=("project_root", "event", "payload"),
        ),
        _contract(
            "router.next_action",
            path="skills/flowpilot/assets/flowpilot_router_controller_runtime.py",
            symbol="next_action",
            implements=("startup.questions.pause_before_work", "resume.current_run_reentry"),
            external_inputs=("project_root",),
        ),
        _contract(
            "packet.create_packet",
            path="skills/flowpilot/assets/packet_runtime_creation_core.py",
            symbol="create_packet",
            implements=(
                "route_mutation.topology_and_recheck",
                "route_mutation.sibling_replacement_stales_old_evidence",
                "output_contract.packet_binding",
            ),
            external_inputs=("project_root", "from_role", "to_role", "packet_id"),
            side_effects=("write_controller_status_packet", "write_json_atomic", "write_text_atomic"),
        ),
        _contract(
            "packet.build_controller_handoff",
            path="skills/flowpilot/assets/packet_runtime_creation_handoff.py",
            symbol="build_controller_handoff",
            implements=("packet.physical_body_boundary",),
            external_inputs=("envelope", "envelope_path"),
        ),
        _contract(
            "packet.controller_handoff_text",
            path="skills/flowpilot/assets/packet_runtime_creation_handoff.py",
            symbol="controller_handoff_text",
            implements=("packet.physical_body_boundary",),
            external_inputs=("handoff",),
        ),
        _contract(
            "packet.controller_relay_envelope",
            path="skills/flowpilot/assets/packet_runtime_relay.py",
            symbol="controller_relay_envelope",
            implements=("output_contract.packet_binding",),
            external_inputs=("project_root", "envelope", "envelope_path"),
            side_effects=("update", "write_json_atomic"),
        ),
        _contract(
            "packet.write_result",
            path="skills/flowpilot/assets/packet_runtime_results.py",
            symbol="write_result",
            implements=("output_contract.packet_binding",),
            external_inputs=("project_root", "packet_envelope", "result_body_text"),
            side_effects=("write_controller_status_packet", "write_json_atomic", "write_text_atomic"),
        ),
        _contract(
            "card.open_card",
            path="skills/flowpilot/assets/card_runtime_ack.py",
            symbol="open_card",
            implements=("card.ack_identity_and_bundle", "ack.return_wait_preconsumption"),
            external_inputs=("project_root", "envelope_path", "role", "agent_id"),
            side_effects=("write_json",),
        ),
        _contract(
            "card.submit_card_ack",
            path="skills/flowpilot/assets/card_runtime_ack.py",
            symbol="submit_card_ack",
            implements=("card.ack_identity_and_bundle", "ack.return_wait_preconsumption"),
            external_inputs=("project_root", "envelope_path", "role", "agent_id"),
            side_effects=("write_json",),
        ),
        _contract(
            "card.validate_card_ack",
            path="skills/flowpilot/assets/card_runtime_ack.py",
            symbol="validate_card_ack",
            implements=("card.ack_identity_and_bundle",),
            external_inputs=("project_root", "envelope_path", "ack_path"),
        ),
        _contract(
            "route_sign.generate",
            path="skills/flowpilot/assets/flowpilot_user_flow_diagram_generate.py",
            symbol="generate",
            implements=("route_mutation.sibling_replacement_stales_old_evidence",),
            external_inputs=("root",),
            side_effects=("write_text",),
        ),
        _contract(
            "role_output.prepare_output_session",
            path="skills/flowpilot/assets/role_output_runtime_progress.py",
            symbol="prepare_output_session",
            implements=("role_output.registry_authority",),
            external_inputs=("project_root", "role", "agent_id", "output_type"),
            side_effects=("write_output_progress_status",),
        ),
        _contract(
            "runtime_closure.validate_officer_request_record",
            path="skills/flowpilot/assets/flowpilot_runtime_closure.py",
            symbol="validate_officer_request_record",
            implements=("runtime_closure.officer_lifecycle_contract",),
            external_inputs=("record",),
        ),
        _contract(
            "runtime_closure.validate_officer_result_record",
            path="skills/flowpilot/assets/flowpilot_runtime_closure.py",
            symbol="validate_officer_result_record",
            implements=("runtime_closure.officer_lifecycle_contract",),
            external_inputs=("record", "result"),
        ),
        _contract(
            "runtime_closure.officer_lifecycle_entry_from_request",
            path="skills/flowpilot/assets/flowpilot_runtime_closure.py",
            symbol="officer_lifecycle_entry_from_request",
            implements=("runtime_closure.officer_lifecycle_contract",),
            external_inputs=("record", "now"),
        ),
        _contract(
            "runtime_closure.continuation_quarantine_record",
            path="skills/flowpilot/assets/flowpilot_runtime_closure.py",
            symbol="continuation_quarantine_record",
            implements=("runtime_closure.continuation_and_final_report_contract",),
            external_inputs=("run_id", "run_root", "current_pointer", "run_index", "created_at"),
        ),
        _contract(
            "runtime_closure.validate_continuation_quarantine_record",
            path="skills/flowpilot/assets/flowpilot_runtime_closure.py",
            symbol="validate_continuation_quarantine_record",
            implements=("runtime_closure.continuation_and_final_report_contract",),
            external_inputs=("record",),
        ),
        _contract(
            "runtime_closure.final_user_report_record",
            path="skills/flowpilot/assets/flowpilot_runtime_closure.py",
            symbol="final_user_report_record",
            implements=("runtime_closure.continuation_and_final_report_contract",),
            external_inputs=("run_id", "lifecycle_status", "summary_path", "summary_json_path", "summary_sha256", "displayed_to_user", "written_at"),
        ),
        _contract(
            "runtime_closure.validate_final_user_report_record",
            path="skills/flowpilot/assets/flowpilot_runtime_closure.py",
            symbol="validate_final_user_report_record",
            implements=("runtime_closure.continuation_and_final_report_contract",),
            external_inputs=("record",),
        ),
        _contract(
            "runtime_closure.route_display_refresh_record",
            path="skills/flowpilot/assets/flowpilot_runtime_closure.py",
            symbol="route_display_refresh_record",
            implements=("runtime_closure.continuation_and_final_report_contract",),
            external_inputs=("run_id", "display_plan_path", "route_state_snapshot_path", "projection_hash", "refreshed_at"),
        ),
        _contract(
            "runtime_closure.validate_route_display_refresh_record",
            path="skills/flowpilot/assets/flowpilot_runtime_closure.py",
            symbol="validate_route_display_refresh_record",
            implements=("runtime_closure.continuation_and_final_report_contract",),
            external_inputs=("record",),
        ),
        _contract(
            "daemon.run_router_daemon",
            path="skills/flowpilot/assets/flowpilot_router_daemon_runtime.py",
            symbol="run_router_daemon",
            implements=("daemon.lock_status_queue_contract",),
            external_inputs=("router", "project_root"),
            side_effects=("save_run_state",),
        ),
        _contract(
            "daemon.stop_router_daemon",
            path="skills/flowpilot/assets/flowpilot_router_daemon_runtime.py",
            symbol="stop_router_daemon",
            implements=("daemon.lock_status_queue_contract",),
            external_inputs=("router", "project_root", "reason"),
            side_effects=("save_run_state",),
        ),
        _contract(
            "daemon.acquire_lock",
            path="skills/flowpilot/assets/flowpilot_router_daemon_runtime.py",
            symbol="_acquire_router_daemon_lock",
            implements=("daemon.lock_status_queue_contract",),
            external_inputs=("router", "project_root", "run_root", "run_state"),
            side_effects=("write", "write_json"),
        ),
        _contract(
            "daemon.refresh_lock",
            path="skills/flowpilot/assets/flowpilot_router_daemon_runtime.py",
            symbol="_refresh_router_daemon_lock",
            implements=("daemon.lock_status_queue_contract",),
            external_inputs=("router", "project_root", "run_root"),
            side_effects=("write_json",),
        ),
        _contract(
            "daemon.release_lock",
            path="skills/flowpilot/assets/flowpilot_router_daemon_runtime.py",
            symbol="_release_router_daemon_lock",
            implements=("daemon.lock_status_queue_contract",),
            external_inputs=("router", "project_root", "run_root", "reason"),
            side_effects=("write_json",),
        ),
        _contract(
            "daemon.write_status",
            path="skills/flowpilot/assets/flowpilot_router_daemon_runtime.py",
            symbol="_write_router_daemon_status",
            implements=("daemon.lock_status_queue_contract",),
            external_inputs=("router", "project_root", "run_root", "run_state", "lifecycle_status"),
            side_effects=("write_json",),
        ),
        _contract(
            "daemon.tick",
            path="skills/flowpilot/assets/flowpilot_router_daemon_runtime.py",
            symbol="_router_daemon_tick",
            implements=("daemon.lock_status_queue_contract",),
            external_inputs=("router", "project_root", "run_root", "run_state", "observe_only"),
            side_effects=("save_run_state", "update"),
        ),
        _contract(
            "startup_daemon.lock_liveness",
            path="skills/flowpilot/assets/flowpilot_router_startup_daemon.py",
            symbol="_router_daemon_lock_liveness",
            implements=("startup_daemon.lock_liveness_contract",),
            external_inputs=("lock",),
        ),
        _contract(
            "startup_daemon.heartbeat_monitor",
            path="skills/flowpilot/assets/flowpilot_router_startup_daemon.py",
            symbol="_router_daemon_heartbeat_monitor",
            implements=("startup_daemon.lock_liveness_contract",),
            external_inputs=("lock", "liveness", "status_exists", "status_ok"),
        ),
        _contract(
            "startup_daemon.lock_is_live",
            path="skills/flowpilot/assets/flowpilot_router_startup_daemon.py",
            symbol="_router_daemon_lock_is_live",
            implements=("startup_daemon.lock_liveness_contract",),
            external_inputs=("lock",),
        ),
        _contract(
            "barrier_bundle.validate_barrier_bundle",
            path="skills/flowpilot/assets/barrier_bundle.py",
            symbol="validate_barrier_bundle",
            implements=("runtime_owner.high_priority_owner_contracts",),
            external_inputs=("bundle", "cumulative_obligations"),
            side_effects=("update",),
        ),
        _contract(
            "break_glass.open_incident",
            path="skills/flowpilot/assets/flowpilot_controller_break_glass.py",
            symbol="open_incident",
            implements=("runtime_owner.high_priority_owner_contracts",),
            external_inputs=("project_root", "run_root", "incident_id"),
            side_effects=("write_json", "save_index"),
        ),
        _contract(
            "break_glass.record_patch",
            path="skills/flowpilot/assets/flowpilot_controller_break_glass.py",
            symbol="record_patch",
            implements=("runtime_owner.high_priority_owner_contracts",),
            external_inputs=("project_root", "run_root", "incident_id", "patch_id"),
            side_effects=("write_json", "save_index"),
        ),
        _contract(
            "break_glass.close_incident",
            path="skills/flowpilot/assets/flowpilot_controller_break_glass.py",
            symbol="close_incident",
            implements=("runtime_owner.high_priority_owner_contracts",),
            external_inputs=("project_root", "run_root", "incident_id"),
            side_effects=("write_json", "save_index"),
        ),
        _contract(
            "flowpilot_paths.resolve_flowpilot_paths",
            path="skills/flowpilot/assets/flowpilot_paths.py",
            symbol="resolve_flowpilot_paths",
            implements=("runtime_owner.high_priority_owner_contracts",),
            external_inputs=("project_root",),
        ),
        _contract(
            "prompt_store.load_prompt_text",
            path="skills/flowpilot/assets/flowpilot_prompt_store.py",
            symbol="load_prompt_text",
            implements=("runtime_owner.high_priority_owner_contracts",),
            external_inputs=("prompt_id", "runtime_kit_root"),
        ),
        _contract(
            "action_providers.lifecycle_provider",
            path="skills/flowpilot/assets/flowpilot_router_action_providers_lifecycle.py",
            symbol="lifecycle_provider",
            implements=("runtime_owner.high_priority_owner_contracts",),
            external_inputs=("router", "project_root", "run_state", "run_root"),
            side_effects=("append_history", "save_run_state"),
        ),
        _contract(
            "card_returns.pending_return_card_ids",
            path="skills/flowpilot/assets/flowpilot_router_card_returns_records.py",
            symbol="_pending_return_card_ids",
            implements=("runtime_owner.high_priority_owner_contracts",),
            external_inputs=("router", "pending_return"),
            side_effects=("update",),
        ),
        _contract(
            "router_errors.router_error_record",
            path="skills/flowpilot/assets/flowpilot_router_errors.py",
            symbol="router_error_record",
            implements=("runtime_owner.high_priority_owner_contracts",),
            external_inputs=("error",),
        ),
        _contract(
            "card_settlement.card_ack_clearance_scope",
            path="skills/flowpilot/assets/flowpilot_router_card_settlement.py",
            symbol="_card_ack_clearance_scope",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("delivery_context", "card_id", "target_role"),
        ),
        _contract(
            "controller_boundary.patrol_timer_command",
            path="skills/flowpilot/assets/flowpilot_router_controller_boundary.py",
            symbol="_controller_patrol_timer_command",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("seconds",),
        ),
        _contract(
            "controller_reconciliation.action_projection_kind",
            path="skills/flowpilot/assets/flowpilot_router_controller_reconciliation.py",
            symbol="_controller_action_projection_kind",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("action",),
        ),
        _contract(
            "controller_repair.bind_router",
            path="skills/flowpilot/assets/flowpilot_router_controller_repair.py",
            symbol="_bind_router",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("router",),
            external_outputs=(),
        ),
        _contract(
            "dispatch_gate.target_roles",
            path="skills/flowpilot/assets/flowpilot_router_dispatch_gate.py",
            symbol="_dispatch_gate_target_roles",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("action",),
        ),
        _contract(
            "action_factory_dispatch.apply_dispatch_recipient_gate",
            path="skills/flowpilot/assets/flowpilot_router_action_factory_dispatch_apply.py",
            symbol="_apply_dispatch_recipient_gate",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_state", "run_root", "action"),
            side_effects=("_run_router_return_settlement_finalizers",),
        ),
        _contract(
            "action_factory_envelope.make_action",
            path="skills/flowpilot/assets/flowpilot_router_action_factory_envelope.py",
            symbol="make_action",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("action_type", "actor", "label", "summary"),
            side_effects=("update",),
        ),
        _contract(
            "action_handlers_basic.check_packet_ledger",
            path="skills/flowpilot/assets/flowpilot_router_action_handlers_basic.py",
            symbol="_apply_check_packet_ledger",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_root", "run_state", "pending", "payload"),
        ),
        _contract(
            "action_handlers_basic.relay_only_system_card",
            path="skills/flowpilot/assets/flowpilot_router_action_handlers_basic.py",
            symbol="_apply_relay_only_system_card",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_root", "run_state", "pending", "payload"),
            external_outputs=(),
        ),
        _contract(
            "action_handlers_roles.controller_repair_work_packet",
            path="skills/flowpilot/assets/flowpilot_router_action_handlers_roles.py",
            symbol="_apply_controller_repair_work_packet",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_root", "run_state", "pending", "payload"),
            side_effects=("write_json",),
        ),
        _contract(
            "artifact_validation.validate_artifact",
            path="skills/flowpilot/assets/flowpilot_router_artifact_validation.py",
            symbol="validate_artifact",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "artifact_type", "artifact_path"),
        ),
        _contract(
            "card_delivery.next_card_delivery_attempt",
            path="skills/flowpilot/assets/flowpilot_router_card_delivery.py",
            symbol="next_card_delivery_attempt",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_root", "run_id", "card_id"),
        ),
        _contract(
            "child_skill_capability.approve_manifest",
            path="skills/flowpilot/assets/flowpilot_router_child_skill_capability.py",
            symbol="_approve_child_skill_manifest_for_route",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_root", "run_state", "payload"),
            external_outputs=(),
            side_effects=("write_json", "update"),
        ),
        _contract(
            "child_skill_capability.sync_capability_evidence",
            path="skills/flowpilot/assets/flowpilot_router_child_skill_capability.py",
            symbol="_sync_capability_evidence",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_root", "run_state", "payload"),
            external_outputs=(),
            side_effects=("write_json",),
        ),
        _contract(
            "controller_ledger.prepare_router_scheduled_action",
            path="skills/flowpilot/assets/flowpilot_router_controller_ledger.py",
            symbol="prepare_router_scheduled_action",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_root", "run_state", "action"),
        ),
        _contract(
            "router_cli.parse_args",
            path="skills/flowpilot/assets/flowpilot_router_cli.py",
            symbol="parse_args",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("argv",),
        ),
        _contract(
            "control_transactions.registry_issues",
            path="skills/flowpilot/assets/flowpilot_router_control_transactions.py",
            symbol="_control_transaction_registry_issues",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_root",),
        ),
        _contract(
            "controller_repair_schedule.schedule_deliverable_repair",
            path="skills/flowpilot/assets/flowpilot_router_controller_repair_schedule.py",
            symbol="_schedule_controller_deliverable_repair",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_root", "run_state", "pending_action", "receipt", "apply_result", "source"),
        ),
        _contract(
            "receipts_pending.router_scheduler_row",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_pending.py",
            symbol="_router_scheduler_row_for_controller_entry",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "run_root", "entry"),
        ),
        _contract(
            "receipts_scheduled.scheduler_row_reconciliation",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_scheduled.py",
            symbol="_scheduler_row_reconciliation_for_entry",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "run_root", "entry"),
        ),
        _contract(
            "receipts_writes.maybe_write_controller_receipt",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_writes.py",
            symbol="_maybe_write_controller_receipt_for_pending",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_root", "run_state", "pending", "status", "payload"),
        ),
        _contract(
            "event_identity.stable_identity_hash",
            path="skills/flowpilot/assets/flowpilot_router_event_identity_scopes.py",
            symbol="_stable_identity_hash",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "value"),
        ),
        _contract(
            "event_intake.role_list",
            path="skills/flowpilot/assets/flowpilot_router_event_intake.py",
            symbol="role_list",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("value",),
        ),
        _contract(
            "events_repair.owner_child_module_names",
            path="skills/flowpilot/assets/flowpilot_router_events_repair.py",
            symbol="owner_child_module_names",
            implements=("runtime_owner.router_owner_external_contracts",),
        ),
        _contract(
            "expected_waits.run_state_has_event",
            path="skills/flowpilot/assets/flowpilot_router_expected_waits_events.py",
            symbol="_run_state_has_event",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_state", "event"),
        ),
        _contract(
            "model_gate_state.sync_model_gate_alias_flags",
            path="skills/flowpilot/assets/flowpilot_router_model_gate_state.py",
            symbol="_sync_model_gate_alias_flags",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_state", "event"),
            external_outputs=(),
        ),
        _contract(
            "protocol_external_events.external_event_contract",
            path="skills/flowpilot/assets/flowpilot_router_protocol_external_events.py",
            symbol="external_event_contract",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("event",),
        ),
        _contract(
            "manifest_actions.owner_exports_actions",
            path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_actions.py",
            symbol="owner_exports_actions",
            implements=("runtime_owner.router_owner_external_contracts",),
        ),
        _contract(
            "manifest_controller.owner_exports_controller",
            path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_controller.py",
            symbol="owner_exports_controller",
            implements=("runtime_owner.router_owner_external_contracts",),
        ),
        _contract(
            "manifest_route.owner_exports_route",
            path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_route.py",
            symbol="owner_exports_route",
            implements=("runtime_owner.router_owner_external_contracts",),
        ),
        _contract(
            "manifest_startup.owner_exports_startup",
            path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_startup.py",
            symbol="owner_exports_startup",
            implements=("runtime_owner.router_owner_external_contracts",),
        ),
        _contract(
            "manifest_terminal_work.owner_exports_terminal_work",
            path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_terminal_work.py",
            symbol="owner_exports_terminal_work",
            implements=("runtime_owner.router_owner_external_contracts",),
        ),
        _contract(
            "facade_exports.resolve_facade_export",
            path="skills/flowpilot/assets/flowpilot_router_facade_exports.py",
            symbol="resolve_facade_export",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("name", "router_module"),
        ),
        _contract(
            "lifecycle_requests.clear_terminal_blocker",
            path="skills/flowpilot/assets/flowpilot_router_lifecycle_requests.py",
            symbol="_clear_active_control_blocker_for_terminal_lifecycle",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_root", "run_state", "mode", "event", "cleared_at"),
            side_effects=("write_json",),
        ),
        _contract(
            "lifecycle_support.lifecycle_record_path",
            path="skills/flowpilot/assets/flowpilot_router_lifecycle_support.py",
            symbol="_lifecycle_record_path",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_root",),
        ),
        _contract(
            "startup_bootloader.depends_on_role_slots",
            path="skills/flowpilot/assets/flowpilot_router_startup_bootloader_progress.py",
            symbol="_startup_bootloader_action_depends_on_role_slots",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "action_type"),
        ),
        _contract(
            "startup_closure.host_heartbeat_binding_ready",
            path="skills/flowpilot/assets/flowpilot_router_startup_closure.py",
            symbol="_host_heartbeat_binding_ready",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "run_root", "run_state"),
        ),
        _contract(
            "startup_display.display_text_hash",
            path="skills/flowpilot/assets/flowpilot_router_startup_display.py",
            symbol="_display_text_hash",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "display_text"),
        ),
        _contract(
            "startup_fact_boundary.controller_boundary_constraints",
            path="skills/flowpilot/assets/flowpilot_router_startup_fact_boundary_controller.py",
            symbol="_controller_boundary_constraints",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router",),
        ),
        _contract(
            "startup_flow.owner_module_name",
            path="skills/flowpilot/assets/flowpilot_router_startup_flow.py",
            symbol="owner_module_name",
            implements=("runtime_owner.router_owner_external_contracts",),
        ),
        _contract(
            "startup_intake.normalize_stop_boundary",
            path="skills/flowpilot/assets/flowpilot_router_startup_intake_ui.py",
            symbol="_normalize_startup_question_stop_boundary",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "state"),
        ),
        _contract(
            "startup_role_recovery.owner_child_module_names",
            path="skills/flowpilot/assets/flowpilot_router_startup_role_recovery.py",
            symbol="owner_child_module_names",
            implements=("runtime_owner.router_owner_external_contracts",),
        ),
        _contract(
            "startup_support.ensure_startup_run_state",
            path="skills/flowpilot/assets/flowpilot_router_startup_support.py",
            symbol="_ensure_startup_run_state",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "bootstrap_state"),
            side_effects=("write_json", "save_run_state"),
        ),
        _contract(
            "system_cards_delivery.commit_system_card_delivery",
            path="skills/flowpilot/assets/flowpilot_router_system_cards_delivery_single.py",
            symbol="_commit_system_card_delivery_artifact",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_state", "run_root", "pending"),
            side_effects=("update", "write_json"),
        ),
        _contract(
            "internal_actions.action_is_router_internal_mechanical",
            path="skills/flowpilot/assets/flowpilot_router_internal_actions.py",
            symbol="_action_is_router_internal_mechanical",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("action",),
        ),
        _contract(
            "payload_contracts.payload_contract",
            path="skills/flowpilot/assets/flowpilot_router_payload_contracts_core.py",
            symbol="_payload_contract",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("name", "required_object", "required_fields", "description"),
        ),
        _contract(
            "pm_role_followup.pm_role_work_channel_open",
            path="skills/flowpilot/assets/flowpilot_router_pm_role_followup.py",
            symbol="_pm_role_work_channel_open",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_state",),
        ),
        _contract(
            "prompt_delivery.card_checkin_instruction",
            path="skills/flowpilot/assets/flowpilot_router_prompt_delivery.py",
            symbol="card_checkin_instruction",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "envelope_path", "role", "agent_id", "card_return_event", "bundle"),
        ),
        _contract(
            "proof_validation.validate_router_owned_check_proof",
            path="skills/flowpilot/assets/flowpilot_router_proof_validation.py",
            symbol="_validate_router_owned_check_proof",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_root", "check_name", "audit_path"),
        ),
        _contract(
            "role_io_protocol.empty_role_io_protocol_ledger",
            path="skills/flowpilot/assets/flowpilot_router_role_io_protocol.py",
            symbol="empty_role_io_protocol_ledger",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_id",),
        ),
        _contract(
            "role_output_bridge.role_output_snapshot_name",
            path="skills/flowpilot/assets/flowpilot_router_role_output_bridge.py",
            symbol="_role_output_snapshot_name",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_root", "output_path"),
        ),
        _contract(
            "route_artifacts_evidence.write_pm_review_block_repair",
            path="skills/flowpilot/assets/flowpilot_router_route_artifacts_evidence.py",
            symbol="_write_pm_review_block_repair",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_root", "run_state", "payload"),
            external_outputs=(),
        ),
        _contract(
            "route_completion_support.resume_waits_for_pm_decision",
            path="skills/flowpilot/assets/flowpilot_router_route_completion_support.py",
            symbol="_resume_waits_for_pm_decision",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_state",),
        ),
        _contract(
            "self_interrogation.self_interrogation_issue",
            path="skills/flowpilot/assets/flowpilot_router_self_interrogation_records.py",
            symbol="_self_interrogation_issue",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("message", "record_id", "record_path", "scope"),
        ),
        _contract(
            "terminal_closure.terminal_closure_suite_is_closed",
            path="skills/flowpilot/assets/flowpilot_router_terminal_ledger_closure.py",
            symbol="_terminal_closure_suite_is_closed",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "run_root"),
        ),
        _contract(
            "terminal_recovery.recover_terminal_status",
            path="skills/flowpilot/assets/flowpilot_router_terminal_ledger_recovery.py",
            symbol="_recover_terminal_status_from_run_authorities",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_root", "run_state"),
        ),
        _contract(
            "terminal_summary.terminal_summary_action",
            path="skills/flowpilot/assets/flowpilot_router_terminal_ledger_summary.py",
            symbol="_terminal_summary_action",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_state", "run_root", "mode"),
        ),
        _contract(
            "work_packets_next_actions.try_reconcile_material_scan",
            path="skills/flowpilot/assets/flowpilot_router_work_packets_next_actions.py",
            symbol="_try_reconcile_material_scan_body_delivery",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_root", "run_state"),
        ),
        _contract(
            "work_packets_pm_role_actions.try_reconcile_pm_role_work",
            path="skills/flowpilot/assets/flowpilot_router_work_packets_pm_role_actions.py",
            symbol="_try_reconcile_pm_role_work_results",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_root", "run_state"),
        ),
        _contract(
            "user_flow_source.route_source_summary",
            path="skills/flowpilot/assets/flowpilot_user_flow_source.py",
            symbol="_route_source_summary",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("route",),
        ),
        _contract(
            "user_flow_stage.classify_current_stage",
            path="skills/flowpilot/assets/flowpilot_user_flow_stage.py",
            symbol="classify_current_stage",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("frontier", "route"),
        ),
        _contract(
            "user_flow_tree.active_node",
            path="skills/flowpilot/assets/flowpilot_user_flow_tree.py",
            symbol="_active_node",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("frontier", "state", "route"),
        ),
        _contract(
            "user_flow_mermaid.build_mermaid",
            path="skills/flowpilot/assets/flowpilot_user_flow_mermaid.py",
            symbol="build_mermaid",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("frontier", "route", "current_stage", "trigger"),
        ),
        _contract(
            "user_flow_markdown.build_chat_markdown",
            path="skills/flowpilot/assets/flowpilot_user_flow_markdown.py",
            symbol="build_chat_markdown",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=(
                "source",
                "generated_at",
                "current_stage",
                "active_route",
                "active_node",
                "trigger",
                "cockpit_open",
                "chat_display_required",
                "return_path",
                "source_status",
                "source_findings",
            ),
        ),
        _contract(
            "packet_invariants.controller_handoff_body_leak_never_advances",
            path="skills/flowpilot/assets/packet_control_plane_model_invariants_handoff.py",
            symbol="controller_handoff_body_leak_never_advances",
            implements=("packet_control_plane.model_state_contract",),
            external_inputs=("state", "trace"),
        ),
        _contract(
            "packet_issue_resume.pm_issue_apply",
            path="skills/flowpilot/assets/packet_control_plane_model_transitions_issue_resume.py",
            symbol="PMIssuePacket.apply",
            implements=("packet_control_plane.model_state_contract",),
            external_inputs=("input_obj", "state"),
            external_outputs=(),
        ),
        _contract(
            "packet_relay.runtime_write_apply",
            path="skills/flowpilot/assets/packet_control_plane_model_transitions_packet_relay.py",
            symbol="PacketRuntimeWrite.apply",
            implements=("packet_control_plane.model_state_contract",),
            external_inputs=("input_obj", "state"),
            external_outputs=(),
        ),
        _contract(
            "packet_dispatch.router_direct_dispatch_apply",
            path="skills/flowpilot/assets/packet_control_plane_model_transitions_dispatch_results.py",
            symbol="RouterDirectDispatch.apply",
            implements=("packet_control_plane.model_state_contract",),
            external_inputs=("input_obj", "state"),
            external_outputs=(),
        ),
        _contract(
            "packet_review.reviewer_result_apply",
            path="skills/flowpilot/assets/packet_control_plane_model_transitions_review_pm.py",
            symbol="ReviewerResultEnvelopeCheck.apply",
            implements=("packet_control_plane.model_state_contract",),
            external_inputs=("input_obj", "state"),
            external_outputs=(),
        ),
        _contract(
            "packet_runtime_reviewer.validate_for_reviewer",
            path="skills/flowpilot/assets/packet_runtime_reviewer.py",
            symbol="validate_for_reviewer",
            implements=("packet_runtime.runtime_owner_contracts",),
            external_inputs=("project_root", "packet_envelope", "result_envelope", "agent_role_map"),
        ),
        _contract(
            "event_dispatcher.record_external_event_unchecked",
            path="skills/flowpilot/assets/flowpilot_router_event_dispatcher.py",
            symbol="_record_external_event_unchecked",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("router", "project_root", "event", "payload"),
            side_effects=("save_run_state",),
        ),
        _contract(
            "router_events.handle_precheck_event",
            path="skills/flowpilot/assets/flowpilot_router_events.py",
            symbol="handle_precheck_event",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("router", "project_root", "run_root", "run_state", "event", "meta", "payload"),
        ),
        _contract(
            "router_events.apply_migrated_event_side_effect",
            path="skills/flowpilot/assets/flowpilot_router_events.py",
            symbol="apply_migrated_event_side_effect",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("router", "project_root", "run_root", "run_state", "event", "payload"),
        ),
        _contract(
            "router_io.write_json",
            path="skills/flowpilot/assets/flowpilot_router_io.py",
            symbol="write_json",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("path", "payload"),
            external_outputs=(),
            side_effects=("write_json_atomic",),
        ),
        _contract(
            "runtime_state.bind_router",
            path="skills/flowpilot/assets/flowpilot_router_runtime_state.py",
            symbol="_bind_router",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("router",),
            external_outputs=(),
        ),
        _contract(
            "router_resume.reset_resume_cycle_for_wakeup",
            path="skills/flowpilot/assets/flowpilot_router_resume.py",
            symbol="reset_resume_cycle_for_wakeup",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("router", "run_state"),
            external_outputs=(),
        ),
        _contract(
            "router_route.route_payload_from_reviewed_draft",
            path="skills/flowpilot/assets/flowpilot_router_route.py",
            symbol="route_payload_from_reviewed_draft",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("router", "project_root", "run_root", "payload"),
        ),
        _contract(
            "router_terminal.terminal_lifecycle_mode",
            path="skills/flowpilot/assets/flowpilot_router_terminal.py",
            symbol="_terminal_lifecycle_mode",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("run_state",),
        ),
        _contract(
            "protocol_tables.terminal_statuses",
            path="skills/flowpilot/assets/flowpilot_router_protocol_tables.py",
            symbol="terminal_statuses",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=(),
        ),
        _contract(
            "protocol_tables.mail_sequence_entry",
            path="skills/flowpilot/assets/flowpilot_router_protocol_tables.py",
            symbol="mail_sequence_entry",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("mail_id",),
        ),
        _contract(
            "startup_catalog.startup_boot_catalog",
            path="skills/flowpilot/assets/flowpilot_router_protocol_startup_catalog.py",
            symbol="startup_boot_catalog",
            implements=("runtime_owner.router_boundary_helpers",),
            external_outputs=("return",),
        ),
        _contract(
            "planning_cards.planning_system_card_catalog",
            path="skills/flowpilot/assets/flowpilot_router_protocol_planning_cards.py",
            symbol="planning_system_card_catalog",
            implements=("runtime_owner.router_boundary_helpers",),
            external_outputs=("return",),
        ),
        _contract(
            "runtime_cards.runtime_system_card_catalog",
            path="skills/flowpilot/assets/flowpilot_router_protocol_runtime_cards.py",
            symbol="runtime_system_card_catalog",
            implements=("runtime_owner.router_boundary_helpers",),
            external_outputs=("return",),
        ),
        _contract(
            "card_metadata.system_card_metadata_catalog",
            path="skills/flowpilot/assets/flowpilot_router_protocol_card_metadata.py",
            symbol="system_card_metadata_catalog",
            implements=("runtime_owner.router_boundary_helpers",),
            external_outputs=("return",),
        ),
        _contract(
            "boot_cards.system_card_catalog",
            path="skills/flowpilot/assets/flowpilot_router_protocol_boot_cards.py",
            symbol="system_card_catalog",
            implements=("runtime_owner.router_boundary_helpers",),
            external_outputs=("return",),
        ),
        _contract(
            "packet_audit.audit_barrier_bundles",
            path="skills/flowpilot/assets/packet_runtime_audit.py",
            symbol="audit_barrier_bundles",
            implements=("packet_runtime.owner_helper_contracts",),
            external_inputs=("project_root", "run_id", "node_id", "bundle_id"),
            side_effects=("write_json_atomic",),
        ),
        _contract(
            "packet_contracts.normalize_output_contract",
            path="skills/flowpilot/assets/packet_runtime_contracts.py",
            symbol="normalize_output_contract",
            implements=("packet_runtime.owner_helper_contracts",),
            external_inputs=("output_contract", "packet_type", "from_role", "to_role", "node_id"),
        ),
        _contract(
            "packet_paths.load_envelope",
            path="skills/flowpilot/assets/packet_runtime_paths.py",
            symbol="load_envelope",
            implements=("packet_runtime.owner_helper_contracts",),
            external_inputs=("project_root", "envelope_path"),
        ),
        _contract(
            "packet_schema.sha256_file",
            path="skills/flowpilot/assets/packet_runtime_schema.py",
            symbol="sha256_file",
            implements=("packet_runtime.owner_helper_contracts",),
            external_inputs=("path",),
        ),
        _contract(
            "packet_control_plane.main",
            path="skills/flowpilot/assets/run_packet_control_plane_checks.py",
            symbol="main",
            implements=("packet_control_plane.runner_contract",),
            external_inputs=(),
        ),
        _contract(
            "card_bundle.validate_card_bundle_ack",
            path="skills/flowpilot/assets/card_runtime_bundle.py",
            symbol="validate_card_bundle_ack",
            implements=("card_runtime.owner_helper_contracts",),
            external_inputs=("project_root", "ack_path", "envelope_path"),
        ),
        _contract(
            "card_envelopes.validate_direct_router_ack_token",
            path="skills/flowpilot/assets/card_runtime_envelopes.py",
            symbol="_validate_direct_router_ack_token",
            implements=("card_runtime.owner_helper_contracts",),
            external_inputs=("envelope", "role", "agent_id", "bundle"),
        ),
        _contract(
            "card_io.project_relative",
            path="skills/flowpilot/assets/card_runtime_io.py",
            symbol="project_relative",
            implements=("card_runtime.owner_helper_contracts",),
            external_inputs=("project_root", "path"),
        ),
        _contract(
            "card_ledgers.load_card_ledger",
            path="skills/flowpilot/assets/card_runtime_ledgers.py",
            symbol="_load_card_ledger",
            implements=("card_runtime.owner_helper_contracts",),
            external_inputs=("project_root", "envelope"),
        ),
        _contract(
            "packet_startup.create_user_intake_packet",
            path="skills/flowpilot/assets/packet_runtime_creation_startup.py",
            symbol="create_user_intake_packet",
            implements=("packet_runtime.runtime_owner_contracts",),
            external_inputs=("project_root", "packet_id", "node_id", "body_text"),
            side_effects=("create_packet", "update"),
        ),
        _contract(
            "packet_ledger.packet_ledger_record_for_envelope",
            path="skills/flowpilot/assets/packet_runtime_ledger.py",
            symbol="packet_ledger_record_for_envelope",
            implements=("packet_runtime.runtime_owner_contracts",),
            external_inputs=("project_root", "envelope"),
        ),
        _contract(
            "packet_active_holder.require_concrete_agent_id",
            path="skills/flowpilot/assets/packet_runtime_active_holder_core.py",
            symbol="_require_concrete_agent_id",
            implements=("packet_runtime.runtime_owner_contracts",),
            external_inputs=("agent_id", "role"),
        ),
        _contract(
            "packet_progress.validate_progress_message",
            path="skills/flowpilot/assets/packet_runtime_progress.py",
            symbol="_validate_progress_message",
            implements=("packet_runtime.runtime_owner_contracts",),
            external_inputs=("message",),
        ),
        _contract(
            "packet_cli.parse_args",
            path="skills/flowpilot/assets/packet_runtime_cli_args.py",
            symbol="parse_args",
            implements=("packet_runtime.runtime_owner_contracts",),
            external_inputs=("argv",),
        ),
        _contract(
            "packet_sessions.runtime_sessions_dir",
            path="skills/flowpilot/assets/packet_runtime_sessions.py",
            symbol="_runtime_sessions_dir",
            implements=("packet_runtime.runtime_owner_contracts",),
            external_inputs=("project_root", "envelope_path"),
        ),
        _contract(
            "packet_relay_checks.verify_router_startup_release",
            path="skills/flowpilot/assets/packet_runtime_relay_checks.py",
            symbol="verify_router_startup_release",
            implements=("packet_runtime.runtime_owner_contracts",),
            external_inputs=("envelope", "recipient_role"),
        ),
        _contract(
            "packet_control_plane_state.packet_from_id",
            path="skills/flowpilot/assets/packet_control_plane_model_state.py",
            symbol="_packet_from_id",
            implements=("packet_control_plane.model_state_contract",),
            external_inputs=("packet_id",),
        ),
        _contract(
            "role_output_contracts.build_output_skeleton",
            path="skills/flowpilot/assets/role_output_runtime_contracts.py",
            symbol="build_output_skeleton",
            implements=("role_output_runtime.owner_helper_contracts",),
            external_inputs=("project_root", "output_type", "role"),
        ),
        _contract(
            "role_output_cli.parse_args",
            path="skills/flowpilot/assets/role_output_runtime_cli.py",
            symbol="parse_args",
            implements=("role_output_runtime.owner_helper_contracts",),
            external_inputs=("argv",),
        ),
        _contract(
            "role_output_schema.controller_boundary_constraints",
            path="skills/flowpilot/assets/role_output_runtime_schema_io.py",
            symbol="controller_boundary_constraints",
            implements=("role_output_runtime.owner_helper_contracts",),
            external_inputs=(),
        ),
        _contract(
            "role_output_envelopes.runtime_envelope_for_body",
            path="skills/flowpilot/assets/role_output_runtime_envelopes.py",
            symbol="runtime_envelope_for_body",
            implements=("role_output_runtime.owner_helper_contracts",),
            external_inputs=("project_root", "output_type", "body_path", "body_hash"),
        ),
        _contract(
            "test_tier.commands_for_tier",
            path="scripts/test_tier/definitions.py",
            symbol="commands_for_tier",
            implements=("test_tiering.foreground_fast_scope",),
            external_inputs=("tier",),
        ),
        _contract(
            "meta_runner.main",
            path="simulations/run_meta_checks.py",
            symbol="main",
            implements=("meta_parent.thin_default_and_layered_full_boundary",),
            external_inputs=("argv",),
        ),
        _contract(
            "smoke.main",
            path="scripts/smoke_autopilot.py",
            symbol="main",
            implements=("capability_parent.proof_reuse_and_fast_boundary",),
            external_inputs=("argv",),
        ),
    )
