"""Router StructureMesh catalog for FlowPilot maintenance."""

from __future__ import annotations

from flowguard import (
    EVIDENCE_CONFORMANCE_GREEN,
    ModuleStructureEvidence,
    PublicEntrypointEvidence,
    StructurePartitionItem,
)

ROUTER_PUBLIC_ENTRYPOINTS = (
    PublicEntrypointEvidence(
        "flowpilot_router_public_api",
        old_path="skills/flowpilot/assets/flowpilot_router.py",
        new_path="skills/flowpilot/assets/flowpilot_router.py",
        parity_evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        evidence_path="simulations/flowpilot_structure_maintenance_results.json",
        release_required=True,
    ),
    PublicEntrypointEvidence(
        "flowpilot_router_cli",
        entrypoint_type="cli",
        old_path="python skills/flowpilot/assets/flowpilot_router.py",
        new_path="python skills/flowpilot/assets/flowpilot_router.py",
        parity_evidence_tier=EVIDENCE_CONFORMANCE_GREEN,
        evidence_path="simulations/flowpilot_structure_maintenance_results.json",
        release_required=True,
    ),
)

ROUTER_STRUCTURE_PARTITIONS = (
    StructurePartitionItem(
        "route_state_root",
        item_type="state",
        owner_module_id="router_facade",
        ownership="parent",
        description="Root run-state coordination remains visible through the router skeleton.",
    ),
    StructurePartitionItem(
        "router_public_api_allowlist",
        item_type="public_entrypoint",
        owner_module_id="router_facade",
        ownership="parent",
        public_surface=True,
        description="The router skeleton exposes only the supported CLI/runtime allowlist.",
    ),
    StructurePartitionItem(
        "router_owner_export_registry",
        item_type="config",
        owner_module_id="facade_export_registry",
        old_path="flowpilot_router hand-written compatibility wrappers",
        new_path="flowpilot_router_facade_export_registry",
    ),
    StructurePartitionItem(
        "router_owner_export_manifest_shards",
        item_type="config",
        owner_module_id="facade_export_manifest",
        old_path="flowpilot_router_facade_export_manifest_* row shards",
        new_path="flowpilot_router_facade_export_manifest_* compatibility views",
    ),
    StructurePartitionItem(
        "router_owner_export_installer",
        item_type="function_cluster",
        owner_module_id="facade_exports",
        old_path="flowpilot_router hand-written compatibility wrappers",
        new_path="flowpilot_router_facade_exports",
    ),
    StructurePartitionItem(
        "external_event_intake",
        item_type="function_cluster",
        owner_module_id="external_events",
        public_surface=True,
        old_path="flowpilot_router._record_external_event_unchecked",
        new_path="flowpilot_router_event_dispatcher",
    ),
    StructurePartitionItem(
        "daemon_tick_and_status",
        item_type="function_cluster",
        owner_module_id="daemon_loop",
        old_path="flowpilot_router._router_daemon_tick/run_router_daemon",
        new_path="flowpilot_router_daemon_runtime",
    ),
    StructurePartitionItem(
        "process_liveness_probe",
        item_type="function_cluster",
        owner_module_id="process_liveness",
        old_path="duplicated process liveness helpers in router IO and startup daemon",
        new_path="flowpilot_process_liveness",
        description="Shared pid-liveness probe used by lock owners without owning lock-domain decisions.",
    ),
    StructurePartitionItem(
        "router_io_facade",
        item_type="function_cluster",
        owner_module_id="router_io",
        ownership="parent",
        public_surface=True,
        old_path="flowpilot_router_io mixed low-level helper owner",
        new_path="flowpilot_router_io compatibility facade",
        description="The legacy IO module stays import-compatible while behavior moves to focused child owners.",
    ),
    StructurePartitionItem(
        "router_io_paths",
        item_type="function_cluster",
        owner_module_id="router_io_paths",
        old_path="flowpilot_router_io path/time/bootstrap helpers",
        new_path="flowpilot_router_io_paths",
    ),
    StructurePartitionItem(
        "runtime_json_write_locks",
        item_type="function_cluster",
        owner_module_id="router_io_locks",
        old_path="flowpilot_router_io runtime JSON write-lock helpers",
        new_path="flowpilot_router_io_locks",
    ),
    StructurePartitionItem(
        "runtime_json_reads_writes",
        item_type="function_cluster",
        owner_module_id="router_io_json",
        old_path="flowpilot_router_io JSON read/write helpers",
        new_path="flowpilot_router_io_json",
    ),
    StructurePartitionItem(
        "role_output_hashing",
        item_type="function_cluster",
        owner_module_id="router_io_hashes",
        old_path="flowpilot_router_io JSON and role-output hash helpers",
        new_path="flowpilot_router_io_hashes",
    ),
    StructurePartitionItem(
        "startup_bootloader_actions",
        item_type="function_cluster",
        owner_module_id="bootloader",
        old_path="flowpilot_router.apply_bootloader_action",
        new_path="flowpilot_router_startup_bootloader",
    ),
    StructurePartitionItem(
        "startup_intake_and_display",
        item_type="function_cluster",
        owner_module_id="startup_intake_display",
        old_path="flowpilot_router_startup_flow intake/display helpers",
        new_path="flowpilot_router_startup_intake + flowpilot_router_startup_display",
    ),
    StructurePartitionItem(
        "startup_resume_and_recovery",
        item_type="function_cluster",
        owner_module_id="startup_role_recovery",
        old_path="flowpilot_router_startup_flow resume and role-recovery helpers",
        new_path="flowpilot_router_startup_role_recovery",
    ),
    StructurePartitionItem(
        "startup_closure_and_fact_boundary",
        item_type="function_cluster",
        owner_module_id="startup_closure_fact_boundary",
        old_path="flowpilot_router_startup_flow closure and fact-boundary helpers",
        new_path="flowpilot_router_startup_closure + flowpilot_router_startup_fact_boundary",
    ),
    StructurePartitionItem(
        "router_protocol_catalog",
        item_type="config",
        owner_module_id="protocol_catalog",
        old_path="flowpilot_router schema/action/event/gate catalogs",
        new_path="flowpilot_router_protocol_catalog",
    ),
    StructurePartitionItem(
        "pm_role_work_next_actions",
        item_type="function_cluster",
        owner_module_id="pm_role_work",
        old_path="flowpilot_router._next_pm_role_work_request_action",
        new_path="flowpilot_router_work_packets",
    ),
    StructurePartitionItem(
        "pm_role_work_polish_children",
        item_type="function_cluster",
        owner_module_id="pm_role_work",
        old_path="flowpilot_router_work_packets_pm_role mixed PM role-work helpers",
        new_path="flowpilot_router_work_packets_pm_role_*",
    ),
    StructurePartitionItem(
        "terminal_ledger_writers",
        item_type="function_cluster",
        owner_module_id="terminal_ledger",
        old_path="flowpilot_router._write_final_route_wide_ledger",
        new_path="flowpilot_router_terminal_ledger",
    ),
    StructurePartitionItem(
        "terminal_ledger_polish_children",
        item_type="function_cluster",
        owner_module_id="terminal_ledger",
        old_path="flowpilot_router_terminal_ledger mixed terminal helpers",
        new_path="flowpilot_router_terminal_ledger_*",
    ),
    StructurePartitionItem(
        "controller_receipt_polish_children",
        item_type="function_cluster",
        owner_module_id="controller_scheduler",
        old_path="flowpilot_router_controller_scheduler_receipts mixed receipt helpers",
        new_path="flowpilot_router_controller_scheduler_receipts_*",
    ),
    StructurePartitionItem(
        "action_factory_polish_children",
        item_type="function_cluster",
        owner_module_id="action_factory",
        old_path="flowpilot_router_action_factory mixed action/gate helpers",
        new_path="flowpilot_router_action_factory_*",
    ),
    StructurePartitionItem(
        "control_blocker_repair",
        item_type="function_cluster",
        owner_module_id="control_blockers",
        old_path="flowpilot_router._write_control_blocker_repair_decision",
        new_path="flowpilot_router_events_repair",
    ),
    StructurePartitionItem(
        "lifecycle_request_facade",
        item_type="function_cluster",
        owner_module_id="lifecycle_requests",
        ownership="parent",
        old_path="flowpilot_router_lifecycle_requests mixed lifecycle helpers",
        new_path="flowpilot_router_lifecycle_requests",
    ),
    StructurePartitionItem(
        "terminal_controller_work_fence",
        item_type="function_cluster",
        owner_module_id="lifecycle_requests_fence",
        old_path="flowpilot_router_lifecycle_requests terminal fence helpers",
        new_path="flowpilot_router_lifecycle_requests_fence",
    ),
    StructurePartitionItem(
        "terminal_lifecycle_reconciliation",
        item_type="function_cluster",
        owner_module_id="lifecycle_requests_reconciliation",
        old_path="flowpilot_router_lifecycle_requests terminal reconciliation helpers",
        new_path="flowpilot_router_lifecycle_requests_reconciliation",
    ),
    StructurePartitionItem(
        "run_lifecycle_records",
        item_type="function_cluster",
        owner_module_id="lifecycle_requests_records",
        old_path="flowpilot_router_lifecycle_requests lifecycle record helpers",
        new_path="flowpilot_router_lifecycle_requests_records",
    ),
    StructurePartitionItem(
        "exception_blocker_fallback",
        item_type="function_cluster",
        owner_module_id="lifecycle_requests_blockers",
        old_path="flowpilot_router_lifecycle_requests exception blocker fallback",
        new_path="flowpilot_router_lifecycle_requests_blockers",
    ),
    StructurePartitionItem(
        "packet_prompt_assets",
        item_type="prompt",
        owner_module_id="packet_runtime_contracts",
        old_path="packet_runtime_contracts inline packet/result/output-contract text",
        new_path="runtime_kit/prompts/packets",
    ),
    StructurePartitionItem(
        "packet_runtime_progress",
        item_type="function_cluster",
        owner_module_id="packet_runtime_progress",
        old_path="packet_runtime progress/status helpers",
        new_path="packet_runtime_progress",
    ),
    StructurePartitionItem(
        "packet_runtime_creation",
        item_type="function_cluster",
        owner_module_id="packet_runtime_creation",
        old_path="packet_runtime packet creation and handoff helpers",
        new_path="packet_runtime_creation",
    ),
    StructurePartitionItem(
        "packet_runtime_results",
        item_type="function_cluster",
        owner_module_id="packet_runtime_results",
        old_path="packet_runtime result write/read helpers",
        new_path="packet_runtime_results",
    ),
    StructurePartitionItem(
        "packet_runtime_audit",
        item_type="function_cluster",
        owner_module_id="packet_runtime_audit",
        old_path="packet_runtime ledger/audit helpers",
        new_path="packet_runtime_audit",
    ),
    StructurePartitionItem(
        "packet_runtime_cli",
        item_type="function_cluster",
        owner_module_id="packet_runtime_cli",
        old_path="packet_runtime command parsing and CLI",
        new_path="packet_runtime_cli",
    ),
    StructurePartitionItem(
        "card_runtime_io",
        item_type="function_cluster",
        owner_module_id="card_runtime_io",
        old_path="card_runtime path/hash/json helpers",
        new_path="card_runtime_io",
    ),
    StructurePartitionItem(
        "card_runtime_ledgers",
        item_type="function_cluster",
        owner_module_id="card_runtime_ledgers",
        old_path="card_runtime ledger helpers",
        new_path="card_runtime_ledgers",
    ),
    StructurePartitionItem(
        "card_runtime_envelopes",
        item_type="function_cluster",
        owner_module_id="card_runtime_envelopes",
        old_path="card_runtime envelope validation helpers",
        new_path="card_runtime_envelopes",
    ),
    StructurePartitionItem(
        "card_runtime_ack",
        item_type="function_cluster",
        owner_module_id="card_runtime_ack",
        old_path="card_runtime single-card ACK helpers",
        new_path="card_runtime_ack",
    ),
    StructurePartitionItem(
        "card_runtime_bundle",
        item_type="function_cluster",
        owner_module_id="card_runtime_bundle",
        old_path="card_runtime bundle ACK helpers",
        new_path="card_runtime_bundle",
    ),
    StructurePartitionItem(
        "user_flow_source",
        item_type="function_cluster",
        owner_module_id="user_flow_source",
        old_path="flowpilot_user_flow_diagram source loading helpers",
        new_path="flowpilot_user_flow_source",
    ),
    StructurePartitionItem(
        "user_flow_tree",
        item_type="function_cluster",
        owner_module_id="user_flow_tree",
        old_path="flowpilot_user_flow_diagram tree/topology helpers",
        new_path="flowpilot_user_flow_tree",
    ),
    StructurePartitionItem(
        "user_flow_stage",
        item_type="function_cluster",
        owner_module_id="user_flow_stage",
        old_path="flowpilot_user_flow_diagram stage classification helpers",
        new_path="flowpilot_user_flow_stage",
    ),
    StructurePartitionItem(
        "user_flow_mermaid",
        item_type="function_cluster",
        owner_module_id="user_flow_mermaid",
        old_path="flowpilot_user_flow_diagram Mermaid rendering helpers",
        new_path="flowpilot_user_flow_mermaid",
    ),
    StructurePartitionItem(
        "user_flow_markdown",
        item_type="function_cluster",
        owner_module_id="user_flow_markdown",
        old_path="flowpilot_user_flow_diagram chat Markdown helpers",
        new_path="flowpilot_user_flow_markdown",
    ),
)

ROUTER_STRUCTURE_MODULES = (
    ModuleStructureEvidence(
        "router_facade",
        path="skills/flowpilot/assets/flowpilot_router.py",
        layer="parent",
        owns_functions=(),
        owns_state=("route_state_root",),
        behavior_contracts=("public API allowlist", "CLI skeleton", "owner-export registry installation"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "facade_exports",
        path="skills/flowpilot/assets/flowpilot_router_facade_exports.py",
        owns_functions=("install_facade_exports", "resolve_facade_export"),
        dependencies=("facade_export_manifest", "facade_export_registry", "router_facade"),
        behavior_contracts=("owner lookup resolver", "obsolete hand-written wrapper removal"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "facade_export_registry",
        path="skills/flowpilot/assets/flowpilot_router_facade_export_registry.py",
        owns_config=(
            "router_owner_export_registry",
            "router_owner_export_manifest_actions",
            "router_owner_export_manifest_controller",
            "router_owner_export_manifest_route",
            "router_owner_export_manifest_startup",
            "router_owner_export_manifest_terminal_work",
        ),
        behavior_contracts=("canonical owner lookup registry", "public export allowlist authority"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "facade_export_manifest",
        path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest.py",
        owns_config=("router_owner_export_manifest_shards",),
        dependencies=("facade_export_registry",),
        behavior_contracts=("legacy owner lookup registry import compatibility",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "facade_export_manifest_actions",
        path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_actions.py",
        dependencies=("facade_export_registry",),
        behavior_contracts=("action export manifest compatibility view",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "facade_export_manifest_controller",
        path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_controller.py",
        dependencies=("facade_export_registry",),
        behavior_contracts=("controller export manifest compatibility view",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "facade_export_manifest_route",
        path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_route.py",
        dependencies=("facade_export_registry",),
        behavior_contracts=("route export manifest compatibility view",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "facade_export_manifest_startup",
        path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_startup.py",
        dependencies=("facade_export_registry",),
        behavior_contracts=("startup export manifest compatibility view",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "facade_export_manifest_terminal_work",
        path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_terminal_work.py",
        dependencies=("facade_export_registry",),
        behavior_contracts=("terminal/work-packet export manifest compatibility view",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "router_cli",
        path="skills/flowpilot/assets/flowpilot_router_cli.py",
        owns_functions=("main", "parse_args"),
        dependencies=("router_facade",),
        behavior_contracts=("CLI command surface", "JSON error envelope"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "controller_runtime",
        path="skills/flowpilot/assets/flowpilot_router_controller_runtime.py",
        owns_functions=("next_action", "apply_action", "record_external_event", "run_until_wait"),
        dependencies=("router_facade", "external_events"),
        behavior_contracts=("high-level runtime API allowlist", "controller action loop"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "artifact_validation",
        path="skills/flowpilot/assets/flowpilot_router_artifact_validation.py",
        owns_functions=("validate_artifact",),
        dependencies=("router_facade",),
        behavior_contracts=("artifact validation public API", "hash validation"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "external_events",
        path="skills/flowpilot/assets/flowpilot_router_event_dispatcher.py",
        owns_functions=("record_external_event_family", "settle_external_event_family"),
        owns_state=("event_log", "wait_action_status"),
        owns_side_effects=("event_ledger_write", "wait_action_close_write"),
        behavior_contracts=("event names", "wait/idempotency facade spine"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "daemon_loop",
        path="skills/flowpilot/assets/flowpilot_router_daemon_runtime.py",
        owns_functions=("router_daemon_tick", "run_router_daemon_loop"),
        owns_state=("daemon_status_record", "standby_snapshot"),
        owns_side_effects=("daemon_status_write",),
        behavior_contracts=("daemon startup", "standby status"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "process_liveness",
        path="skills/flowpilot/assets/flowpilot_process_liveness.py",
        owns_functions=("process_is_live",),
        behavior_contracts=("shared pid liveness probe", "no lock-domain state ownership"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "router_io",
        path="skills/flowpilot/assets/flowpilot_router_io.py",
        layer="parent",
        owns_functions=(),
        dependencies=("router_io_paths", "router_io_locks", "router_io_json", "router_io_hashes", "process_liveness"),
        behavior_contracts=("low-level IO compatibility facade", "legacy import surface"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "router_io_paths",
        path="skills/flowpilot/assets/flowpilot_router_io_paths.py",
        owns_functions=(
            "utc_now",
            "_parse_utc_timestamp",
            "skill_root",
            "runtime_kit_source",
            "_copy_runtime_kit_into_run_root",
            "bootstrap_state_path",
            "project_relative",
            "_project_root_from_run_root",
            "_flowpilot_runtime_entrypoint_ref",
        ),
        behavior_contracts=("path resolution", "runtime-kit copy safety", "bootstrap state discovery"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "router_io_locks",
        path="skills/flowpilot/assets/flowpilot_router_io_locks.py",
        owns_functions=(
            "_json_write_lock_liveness",
            "_acquire_json_write_lock",
            "_cleanup_runtime_json_write_lock",
            "_run_foreground_with_runtime_writer_settlement",
        ),
        owns_state=("runtime_json_write_lock",),
        owns_side_effects=("runtime_json_write_lock_takeover_log", "runtime_json_write_lock_cleanup_log"),
        dependencies=("process_liveness", "router_io_paths"),
        behavior_contracts=("runtime JSON write-lock liveness", "safe stale lock takeover", "writer settlement"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "router_io_json",
        path="skills/flowpilot/assets/flowpilot_router_io_json.py",
        owns_functions=(
            "write_json_atomic",
            "write_json",
            "read_json",
            "read_json_if_exists",
            "read_daemon_critical_json_if_exists",
            "read_json_if_valid",
            "_read_json_for_runtime_scan",
        ),
        owns_side_effects=("runtime_json_atomic_write",),
        dependencies=("router_io_locks",),
        behavior_contracts=("atomic JSON write", "daemon-critical JSON corruption boundary", "runtime scan reads"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "router_io_hashes",
        path="skills/flowpilot/assets/flowpilot_router_io_hashes.py",
        owns_functions=(
            "_json_sha256",
            "_without_role_output_envelope",
            "_role_output_semantic_hash",
            "_role_output_semantic_hashes",
            "_role_output_hashes",
        ),
        behavior_contracts=("JSON content hash", "role-output semantic hash"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "bootloader",
        path="skills/flowpilot/assets/flowpilot_router_startup_bootloader.py",
        owns_functions=("apply_bootloader_action", "compute_bootloader_action"),
        owns_state=("bootloader_rows", "startup_review_projection"),
        owns_side_effects=("bootloader_row_write",),
        behavior_contracts=("startup ordering", "question stop boundary"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "startup_intake_display",
        path="skills/flowpilot/assets/flowpilot_router_startup_intake.py",
        owns_functions=("validate_startup_answer_payload", "write_startup_display_plan"),
        owns_state=("startup_answers", "startup_display"),
        owns_side_effects=("startup_answer_write", "startup_display_write"),
        behavior_contracts=("startup answer validation", "display projection"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "startup_role_recovery",
        path="skills/flowpilot/assets/flowpilot_router_startup_role_recovery.py",
        owns_functions=("next_resume_action", "next_role_recovery_action"),
        owns_state=("resume_role_recovery", "continuation_bindings"),
        owns_side_effects=("role_recovery_write",),
        behavior_contracts=("resume re-entry", "role recovery persistence"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "startup_closure_fact_boundary",
        path="skills/flowpilot/assets/flowpilot_router_startup_closure.py",
        owns_functions=("startup_closure_reconciliation_status", "write_startup_fact_report"),
        owns_state=("startup_closure_reconciliation", "startup_fact_boundary"),
        owns_side_effects=("startup_fact_write", "closure_reconciliation_write"),
        behavior_contracts=("startup closure reconciliation", "fact-boundary audit"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "protocol_catalog",
        path="skills/flowpilot/assets/flowpilot_router_protocol_catalog.py",
        owns_functions=(
            "_gate_contract_for_id",
            "_gate_contract_for_card",
            "_gate_contract_for_event",
        ),
        owns_config=("router_protocol_catalog",),
        behavior_contracts=(
            "schema/action/event catalogs",
            "gate contract lookup",
            "model gate alias tables",
        ),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "controller_scheduler",
        path="skills/flowpilot/assets/flowpilot_router_controller_scheduler.py",
        owns_functions=(),
        owns_state=("controller_action_rows", "controller_receipts"),
        owns_side_effects=(),
        dependencies=("router_facade",),
        behavior_contracts=("controller action and receipt reconciliation compatibility",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "controller_receipt_writes",
        path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_writes.py",
        owns_functions=("_write_controller_action_entry", "_write_controller_receipt"),
        owns_side_effects=("controller_action_write", "controller_receipt_write"),
        dependencies=("controller_scheduler", "router_facade"),
        behavior_contracts=("controller action and receipt writes",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "controller_receipt_effects",
        path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_effects.py",
        owns_functions=("_apply_stateful_receipt_postcondition", "_apply_done_controller_receipt_effects"),
        dependencies=("controller_scheduler", "router_facade"),
        behavior_contracts=("controller receipt postcondition effects",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "controller_receipt_pending",
        path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_pending.py",
        owns_functions=("_reconcile_pending_controller_action_receipt", "_clear_pending_after_reconciled_controller_receipt"),
        dependencies=("controller_receipt_effects", "router_facade"),
        behavior_contracts=("pending Controller action receipt reconciliation",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "controller_receipt_scheduled",
        path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_scheduled.py",
        owns_functions=("_reconcile_scheduled_controller_action_receipts", "_backfill_scheduler_row_from_reconciled_controller_action"),
        dependencies=("controller_receipt_pending", "router_facade"),
        behavior_contracts=("scheduled Controller action reconciliation and scheduler backfill",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "action_factory",
        path="skills/flowpilot/assets/flowpilot_router_action_factory.py",
        owns_functions=("make_action", "_apply_dispatch_recipient_gate"),
        owns_state=("controller_action_envelope", "dispatch_recipient_gate"),
        dependencies=("router_facade",),
        behavior_contracts=("action envelope construction and dispatch-recipient gating",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "action_factory_reconciliation",
        path="skills/flowpilot/assets/flowpilot_router_action_factory_reconciliation.py",
        owns_functions=("_current_scope_pre_review_reconciliation_action", "_apply_formal_work_packet_ack_preflight"),
        dependencies=("action_factory", "router_facade"),
        behavior_contracts=("scope reconciliation and formal packet ACK preflight",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "action_factory_dispatch",
        path="skills/flowpilot/assets/flowpilot_router_action_factory_dispatch.py",
        owns_functions=("_apply_dispatch_recipient_gate", "_dispatch_gate_wait_action"),
        dependencies=("action_factory_reconciliation", "router_facade"),
        behavior_contracts=("dispatch recipient gate and blocker construction",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "action_factory_envelope",
        path="skills/flowpilot/assets/flowpilot_router_action_factory_envelope.py",
        owns_functions=("make_action", "append_history"),
        dependencies=("action_factory_dispatch", "router_facade"),
        behavior_contracts=("action envelope and Controller user-reporting policy",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "pm_role_work",
        path="skills/flowpilot/assets/flowpilot_router_work_packets.py",
        owns_functions=("next_pm_role_work_request_action", "write_pm_role_work_request"),
        owns_state=("pm_role_work_requests", "pm_role_work_results"),
        owns_side_effects=("packet_or_action_write",),
        behavior_contracts=("role authority", "packet contracts"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "pm_role_work_gates",
        path="skills/flowpilot/assets/flowpilot_router_work_packets_pm_role_gates.py",
        owns_functions=("_pm_role_work_gate_mappings_for_decision", "_apply_pm_role_work_gate_mappings"),
        dependencies=("pm_role_work", "router_facade"),
        behavior_contracts=("PM role-work gate mapping and targeted result contracts",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "pm_role_work_writes",
        path="skills/flowpilot/assets/flowpilot_router_work_packets_pm_role_writes.py",
        owns_functions=("_write_pm_role_work_request", "_write_role_work_result_returned", "_write_pm_role_work_result_decision"),
        owns_side_effects=("pm_role_work_request_result_write",),
        dependencies=("pm_role_work_gates", "router_facade"),
        behavior_contracts=("PM role-work request/result/disposition writes",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "pm_role_work_lifecycle",
        path="skills/flowpilot/assets/flowpilot_router_work_packets_pm_role_lifecycle.py",
        owns_functions=("_load_pm_role_work_request_index", "_record_officer_lifecycle_status"),
        owns_state=("pm_role_work_index", "officer_request_lifecycle"),
        dependencies=("router_facade",),
        behavior_contracts=("PM role-work request indexes and officer lifecycle records",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "pm_role_work_actions",
        path="skills/flowpilot/assets/flowpilot_router_work_packets_pm_role_actions.py",
        owns_functions=("_next_pm_role_work_request_action", "_try_reconcile_pm_role_work_results"),
        dependencies=("pm_role_work_lifecycle", "pm_role_work_writes", "router_facade"),
        behavior_contracts=("PM role-work next-action selection and result reconciliation",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "terminal_ledger",
        path="skills/flowpilot/assets/flowpilot_router_terminal_ledger.py",
        owns_functions=("write_final_route_wide_ledger", "write_terminal_backward_replay"),
        owns_state=("final_route_wide_gate_ledger", "terminal_closure_suite"),
        owns_side_effects=("terminal_ledger_write",),
        behavior_contracts=("terminal replay", "closure blocking"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "control_blockers",
        path="skills/flowpilot/assets/flowpilot_router_events_repair.py",
        owns_functions=("write_control_blocker", "write_control_blocker_repair_decision"),
        owns_state=("control_blocker_records", "repair_transactions"),
        owns_side_effects=("control_blocker_write",),
        behavior_contracts=("repair transaction idempotency",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
    ),
    ModuleStructureEvidence(
        "lifecycle_requests",
        path="skills/flowpilot/assets/flowpilot_router_lifecycle_requests.py",
        layer="parent",
        owns_functions=(
            "_write_run_lifecycle_request",
            "_write_protocol_dead_end_lifecycle",
            "_reconcile_terminal_lifecycle_authorities",
            "_clear_active_control_blocker_for_terminal_lifecycle",
            "_run_lifecycle_terminal_action",
            "_try_write_control_blocker_for_exception",
        ),
        dependencies=(
            "lifecycle_requests_fence",
            "lifecycle_requests_reconciliation",
            "lifecycle_requests_records",
            "lifecycle_requests_blockers",
            "router_facade",
        ),
        behavior_contracts=("lifecycle request compatibility facade", "child router binding"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "lifecycle_requests_fence",
        path="skills/flowpilot/assets/flowpilot_router_lifecycle_requests_fence.py",
        owns_functions=(
            "_controller_action_is_terminal_cleanup",
            "_supersede_nonterminal_controller_work_for_terminal",
            "_write_terminal_lifecycle_fence",
        ),
        owns_state=("terminal_controller_work_fence",),
        owns_side_effects=("terminal_fence_write", "controller_work_supersede_write"),
        dependencies=("controller_scheduler", "daemon_loop", "router_facade"),
        behavior_contracts=("terminal controller-work fencing", "terminal daemon fence persistence"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "lifecycle_requests_reconciliation",
        path="skills/flowpilot/assets/flowpilot_router_lifecycle_requests_reconciliation.py",
        owns_functions=(
            "_clear_active_control_blocker_for_terminal_lifecycle",
            "_reconcile_terminal_lifecycle_authorities",
        ),
        owns_state=("terminal_lifecycle_reconciliation",),
        owns_side_effects=("terminal_lifecycle_reconciliation_write", "control_blocker_resolution_write"),
        dependencies=("control_blockers", "router_facade"),
        behavior_contracts=("terminal authority reconciliation", "terminal control-blocker clearance"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "lifecycle_requests_records",
        path="skills/flowpilot/assets/flowpilot_router_lifecycle_requests_records.py",
        owns_functions=(
            "_write_run_lifecycle_request",
            "_write_protocol_dead_end_lifecycle",
            "_run_lifecycle_terminal_action",
        ),
        owns_state=("run_lifecycle_requests", "protocol_dead_end_records"),
        owns_side_effects=("run_lifecycle_write", "flowpilot_current_index_write"),
        dependencies=("lifecycle_requests_fence", "lifecycle_requests_reconciliation", "terminal_ledger", "router_facade"),
        behavior_contracts=("lifecycle request persistence", "protocol dead-end blocking", "terminal action construction"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "lifecycle_requests_blockers",
        path="skills/flowpilot/assets/flowpilot_router_lifecycle_requests_blockers.py",
        owns_functions=("_try_write_control_blocker_for_exception",),
        owns_state=("exception_control_blocker_fallback",),
        owns_side_effects=("control_blocker_materialization_failure_write",),
        dependencies=("control_blockers", "runtime_state", "router_facade"),
        behavior_contracts=("exception-to-blocker routing", "control blocker fallback diagnostics"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "packet_runtime_contracts",
        path="skills/flowpilot/assets/packet_runtime_contracts.py",
        owns_functions=("packet_identity_boundary", "result_identity_boundary", "output_contract_section"),
        owns_config=("packet_prompt_assets",),
        dependencies=("prompt_store",),
        behavior_contracts=("packet prompt rendering", "output contract text authority"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "terminal_ledger_summary",
        path="skills/flowpilot/assets/flowpilot_router_terminal_ledger_summary.py",
        owns_functions=("_terminal_summary_action", "_write_terminal_summary"),
        owns_side_effects=("terminal_summary_write",),
        dependencies=("terminal_ledger", "router_facade"),
        behavior_contracts=("terminal summary validation and write",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "terminal_ledger_traceability",
        path="skills/flowpilot/assets/flowpilot_router_terminal_ledger_traceability.py",
        owns_functions=("_final_ledger_traceability_issues", "_write_final_route_wide_ledger"),
        owns_side_effects=("final_route_wide_ledger_write",),
        dependencies=("terminal_ledger", "router_facade"),
        behavior_contracts=("final ledger traceability and source-of-truth entries",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "terminal_ledger_closure",
        path="skills/flowpilot/assets/flowpilot_router_terminal_ledger_closure.py",
        owns_functions=("_write_terminal_backward_replay", "_write_terminal_closure_suite"),
        owns_side_effects=("terminal_backward_replay_write", "terminal_closure_suite_write"),
        dependencies=("terminal_ledger_traceability", "router_facade"),
        behavior_contracts=("terminal backward replay and closure suite writes",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "terminal_ledger_recovery",
        path="skills/flowpilot/assets/flowpilot_router_terminal_ledger_recovery.py",
        owns_functions=("reconcile_current_run", "_repair_legacy_material_packet_contracts"),
        owns_side_effects=("terminal_reconciliation_write",),
        dependencies=("terminal_ledger", "router_facade"),
        behavior_contracts=("terminal status recovery and legacy material packet repair",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "packet_runtime_progress",
        path="skills/flowpilot/assets/packet_runtime_progress.py",
        owns_functions=("write_controller_status_packet", "update_controller_progress"),
        owns_state=("packet_runtime_progress",),
        dependencies=("packet_runtime_paths", "packet_runtime_schema"),
        behavior_contracts=("controller status packet writes", "progress validation"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "packet_runtime_creation",
        path="skills/flowpilot/assets/packet_runtime_creation.py",
        owns_functions=("create_packet", "create_user_intake_packet", "build_controller_handoff", "controller_handoff_text"),
        owns_state=("packet_runtime_creation",),
        owns_side_effects=("packet_envelope_body_write",),
        dependencies=("packet_runtime_contracts", "packet_runtime_paths", "packet_runtime_relay"),
        behavior_contracts=("packet envelope/body creation", "controller handoff envelope-only boundary"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "packet_runtime_results",
        path="skills/flowpilot/assets/packet_runtime_results.py",
        owns_functions=("write_result", "read_result_body_for_role"),
        owns_state=("packet_runtime_results",),
        owns_side_effects=("packet_result_write",),
        dependencies=("packet_runtime_contracts", "packet_runtime_paths", "packet_runtime_relay"),
        behavior_contracts=("result envelope/body write", "role-scoped result reads"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "packet_runtime_audit",
        path="skills/flowpilot/assets/packet_runtime_audit.py",
        owns_functions=("audit_barrier_bundles", "audit_packet_chain"),
        owns_state=("packet_runtime_audit",),
        dependencies=("packet_runtime_paths", "packet_runtime_ledger"),
        behavior_contracts=("packet chain audit", "replacement-chain audit"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "packet_runtime_cli",
        path="skills/flowpilot/assets/packet_runtime_cli.py",
        owns_functions=("parse_args", "main"),
        dependencies=("packet_runtime_creation", "packet_runtime_results", "packet_runtime_audit"),
        behavior_contracts=("packet runtime CLI compatibility", "subcommand dispatch"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "card_runtime_io",
        path="skills/flowpilot/assets/card_runtime_io.py",
        owns_functions=("read_json", "write_json", "project_relative", "resolve_project_path"),
        behavior_contracts=("card runtime path and JSON helpers", "stable hash helpers"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "card_runtime_ledgers",
        path="skills/flowpilot/assets/card_runtime_ledgers.py",
        owns_functions=("_load_card_ledger", "_load_return_ledger", "_merge_pending_return_ack"),
        owns_state=("card_runtime_ledgers",),
        dependencies=("card_runtime_io",),
        behavior_contracts=("card ledger reads", "return ledger merge identity"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "card_runtime_envelopes",
        path="skills/flowpilot/assets/card_runtime_envelopes.py",
        owns_functions=("_load_envelope", "_load_bundle_envelope", "_validate_target_identity"),
        dependencies=("card_runtime_io",),
        behavior_contracts=("card envelope validation", "direct router ACK token checks"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "card_runtime_ack",
        path="skills/flowpilot/assets/card_runtime_ack.py",
        owns_functions=("open_card", "submit_card_ack", "validate_card_ack"),
        owns_state=("card_runtime_ack",),
        owns_side_effects=("card_ack_write",),
        dependencies=("card_runtime_envelopes", "card_runtime_ledgers"),
        behavior_contracts=("single-card open and ACK lifecycle", "role/token/receipt validation"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "card_runtime_bundle",
        path="skills/flowpilot/assets/card_runtime_bundle.py",
        owns_functions=("open_card_bundle", "submit_card_bundle_ack", "validate_card_bundle_ack"),
        owns_state=("card_runtime_bundle",),
        owns_side_effects=("card_bundle_ack_write",),
        dependencies=("card_runtime_envelopes", "card_runtime_ledgers"),
        behavior_contracts=("bundle open and ACK lifecycle", "incomplete bundle inspection"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "user_flow_source",
        path="skills/flowpilot/assets/flowpilot_user_flow_source.py",
        owns_functions=("_load_route_source", "_review_display"),
        owns_state=("user_flow_source",),
        behavior_contracts=("route source discovery", "review display loading"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "user_flow_tree",
        path="skills/flowpilot/assets/flowpilot_user_flow_tree.py",
        owns_functions=("_all_route_nodes", "_node_status", "_node_topology"),
        owns_state=("user_flow_tree",),
        behavior_contracts=("route tree flattening", "route topology classification"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "user_flow_stage",
        path="skills/flowpilot/assets/flowpilot_user_flow_stage.py",
        owns_functions=("classify_current_stage",),
        dependencies=("user_flow_tree",),
        behavior_contracts=("current stage classification", "route mutation pending detection"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "user_flow_mermaid",
        path="skills/flowpilot/assets/flowpilot_user_flow_mermaid.py",
        owns_functions=("detect_return_path", "build_mermaid"),
        dependencies=("user_flow_tree", "user_flow_stage"),
        behavior_contracts=("Mermaid route rendering", "return-path display"),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
    ModuleStructureEvidence(
        "user_flow_markdown",
        path="skills/flowpilot/assets/flowpilot_user_flow_markdown.py",
        owns_functions=("build_chat_markdown",),
        dependencies=("user_flow_mermaid", "user_flow_stage"),
        behavior_contracts=("chat Markdown route summary",),
        behavior_parity_tier=EVIDENCE_CONFORMANCE_GREEN,
        release_required=True,
    ),
)
