"""Source-audited test evidence for FlowPilot model-test alignment."""

from __future__ import annotations

from flowpilot_model_test_alignment_common import *


def source_test_evidence() -> tuple[TestEvidence, ...]:
    """Return source-audited test evidence rows."""

    return (
        _evidence(
            "source.startup.waits",
            test_name="test_startup_waits_for_answers_before_banner_or_controller",
            path="tests/router_runtime/startup_bootstrap.py",
            command="python -m unittest tests.test_flowpilot_router_runtime_startup_daemon",
            test_kind=NEGATIVE,
            covers=("startup.questions.pause_before_work",),
            code_contracts=("router.run_until_wait", "router.apply_action"),
        ),
        _evidence(
            "source.startup.native_intake",
            test_name="test_startup_daemon_defers_banner_and_queues_next_boot_row",
            path="tests/router_runtime/startup_bootstrap.py",
            command="python -m unittest tests.test_flowpilot_router_runtime_startup_daemon",
            test_kind=HAPPY,
            covers=("startup.questions.pause_before_work",),
            code_contracts=("router.apply_action", "router.next_action"),
        ),
        _evidence(
            "source.startup.activation",
            test_name="test_startup_activation_requires_reviewer_facts_before_work",
            path="tests/router_runtime/startup_bootstrap.py",
            command="python -m unittest tests.test_flowpilot_router_runtime_startup_daemon",
            test_kind=FAILURE,
            covers=("startup.run_isolation_and_activation",),
            code_contracts=("router.record_external_event",),
        ),
        _evidence(
            "source.new_entrypoint.start",
            test_name="test_start_rehearsal_reuses_old_startup_ui_and_enters_new_ledger",
            path="tests/test_flowpilot_new_entrypoint.py",
            command="python -m unittest tests.test_flowpilot_new_entrypoint.FlowPilotNewEntrypointTests.test_start_rehearsal_reuses_old_startup_ui_and_enters_new_ledger",
            test_kind=HAPPY,
            covers=("new_entrypoint.startup_ui_to_new_ledger",),
            code_contracts=("flowpilot_new.start_run",),
        ),
        _evidence(
            "source.new_entrypoint.headless_reject",
            test_name="test_formal_mode_rejects_headless_startup_result_as_formal_evidence",
            path="tests/test_flowpilot_new_entrypoint.py",
            command="python -m unittest tests.test_flowpilot_new_entrypoint.FlowPilotNewEntrypointTests.test_formal_mode_rejects_headless_startup_result_as_formal_evidence",
            test_kind=NEGATIVE,
            covers=("new_entrypoint.formal_headless_rejection",),
            code_contracts=(
                "flowpilot_new.start_run",
                "flowpilot_new.assert_formal_interactive_result",
            ),
        ),
        _evidence(
            "source.new_entrypoint.e2e",
            test_name="test_fake_end_to_end_rehearsal_reaches_final_closure",
            path="tests/test_flowpilot_new_entrypoint.py",
            command="python -m unittest tests.test_flowpilot_new_entrypoint.FlowPilotNewEntrypointTests.test_fake_end_to_end_rehearsal_reaches_final_closure",
            test_kind=HAPPY,
            covers=("new_entrypoint.rehearsal_closure",),
            code_contracts=("flowpilot_new.run_fake_e2e",),
        ),
        _evidence(
            "source.packet.handoff",
            test_name="test_controller_handoff_contains_envelope_only_not_body_content",
            path="tests/test_flowpilot_packet_runtime.py",
            command="python -m unittest tests.test_flowpilot_packet_runtime",
            test_kind=NEGATIVE,
            covers=("packet.physical_body_boundary",),
            code_contracts=("packet.build_controller_handoff", "packet.controller_handoff_text"),
        ),
        _evidence(
            "source.card.happy",
            test_name="test_card_runtime_opens_card_and_submits_ack",
            path="tests/test_flowpilot_card_runtime.py",
            command="python -m pytest tests/test_flowpilot_card_runtime.py",
            test_kind=HAPPY,
            covers=("card.ack_identity_and_bundle",),
            code_contracts=("card.open_card", "card.submit_card_ack", "card.validate_card_ack"),
        ),
        _evidence(
            "source.ack.edge",
            test_name="test_record_external_event_preconsumes_valid_card_ack_before_blocking",
            path="tests/router_runtime/ack_return.py",
            command="python -m unittest tests.test_flowpilot_router_runtime_ack_return",
            test_kind=EDGE,
            covers=("ack.return_wait_preconsumption",),
            code_contracts=("router.record_external_event", "card.open_card", "card.submit_card_ack"),
        ),
        _evidence(
            "source.route.preconditions",
            test_name="test_route_mutation_and_final_ledger_have_required_preconditions",
            path="tests/router_runtime/route_mutation_preconditions.py",
            command="python -m unittest tests.router_runtime.route_mutation_preconditions.RouteMutationPreconditionRuntimeTests.test_route_mutation_and_final_ledger_have_required_preconditions",
            test_kind=NEGATIVE,
            covers=("route_mutation.topology_and_recheck",),
            code_contracts=("router.record_external_event", "packet.create_packet"),
        ),
        _evidence(
            "source.route.sibling",
            test_name="test_route_mutation_sibling_branch_replacement_blocks_old_sibling_proof",
            path="tests/router_runtime/route_mutation_sibling_replacement.py",
            command="python -m unittest tests.router_runtime.route_mutation_sibling_replacement.RouteMutationSiblingReplacementRuntimeTests.test_route_mutation_sibling_branch_replacement_blocks_old_sibling_proof",
            test_kind=NEGATIVE,
            covers=("route_mutation.sibling_replacement_stales_old_evidence",),
            code_contracts=("router.record_external_event", "packet.create_packet"),
        ),
        _evidence(
            "source.route.display",
            test_name="test_sibling_branch_replacement_draws_replacement_and_replay_scope",
            path="tests/test_flowpilot_user_flow_diagram.py",
            command="python -m unittest tests.test_flowpilot_user_flow_diagram.FlowPilotUserFlowDiagramTests.test_sibling_branch_replacement_draws_replacement_and_replay_scope",
            test_kind=EDGE,
            covers=("route_mutation.sibling_replacement_stales_old_evidence",),
            code_contracts=("route_sign.generate",),
        ),
        _evidence(
            "source.terminal.replay",
            test_name="test_terminal_replay_requires_reviewed_segments_and_pm_segment_decisions",
            path="tests/router_runtime/terminal.py",
            command="python -m unittest tests.test_flowpilot_router_runtime_terminal",
            test_kind=HAPPY,
            covers=("terminal.final_ledger_and_backward_replay",),
            code_contracts=("router.record_external_event",),
        ),
        _evidence(
            "source.terminal.final",
            test_name="test_final_ledger_rejects_missing_source_of_truth_entries_and_contract_replay",
            path="tests/router_runtime/terminal.py",
            command="python -m unittest tests.test_flowpilot_router_runtime_terminal",
            test_kind=EDGE,
            covers=("terminal.final_ledger_and_backward_replay",),
            code_contracts=("router.record_external_event",),
        ),
        _evidence(
            "source.terminal.source_entries_child_build",
            test_name="test_terminal_source_entry_child_builds_expected_gate_families",
            path="tests/test_flowpilot_terminal_ledger_source_entries.py",
            command="python -m unittest tests.test_flowpilot_terminal_ledger_source_entries.TerminalLedgerSourceEntryTests.test_terminal_source_entry_child_builds_expected_gate_families",
            test_kind=EDGE,
            covers=("terminal.final_ledger_source_entries",),
            code_contracts=(
                "terminal_ledger_source_entries.build_source_entries",
            ),
        ),
        _evidence(
            "source.terminal.source_entries_trace_projection",
            test_name="test_terminal_source_entry_child_projects_requirement_trace_defaults",
            path="tests/test_flowpilot_terminal_ledger_source_entries.py",
            command="python -m unittest tests.test_flowpilot_terminal_ledger_source_entries.TerminalLedgerSourceEntryTests.test_terminal_source_entry_child_projects_requirement_trace_defaults",
            test_kind=EDGE,
            covers=("terminal.requirement_trace_projection",),
            code_contracts=(
                "terminal_ledger_source_entries.route_nodes_with_requirement_trace",
                "terminal_ledger_source_entries.requirement_trace_closure",
            ),
        ),
        _evidence(
            "source.resume.loads",
            test_name="test_resume_reentry_loads_state_before_resume_cards",
            path="tests/router_runtime/resume.py",
            command="python -m unittest tests.test_flowpilot_router_runtime_resume",
            test_kind=HAPPY,
            covers=("resume.current_run_reentry",),
            code_contracts=("router.record_external_event", "router.next_action", "router.apply_action"),
        ),
        _evidence(
            "source.resume.ambiguous",
            test_name="test_resume_ambiguous_state_blocks_continue_without_recovery_evidence",
            path="tests/router_runtime/resume.py",
            command="python -m unittest tests.test_flowpilot_router_runtime_resume",
            test_kind=FAILURE,
            covers=("resume.current_run_reentry",),
            code_contracts=("router.record_external_event", "router.apply_action"),
        ),
        _evidence(
            "source.role.prep",
            test_name="test_registry_backed_output_types_are_preparable",
            path="tests/test_flowpilot_role_output_runtime.py",
            command="python -m unittest tests.test_flowpilot_role_output_runtime",
            test_kind=HAPPY,
            covers=("role_output.registry_authority",),
            code_contracts=("role_output.prepare_output_session",),
        ),
        _evidence(
            "source.pm_package.packet_outcomes",
            test_name="test_pm_disposition_records_packet_outcomes_and_blocks_mixed_absorption",
            path="tests/test_flowpilot_control_plane_contracts.py",
            command="python -m unittest tests.test_flowpilot_control_plane_contracts.FlowPilotControlPlaneContractRuntimeTests.test_pm_disposition_records_packet_outcomes_and_blocks_mixed_absorption",
            test_kind=EDGE,
            covers=("pm_package_disposition.semantic_identity_and_packet_outcomes",),
            code_contracts=("pm_decisions._write_pm_package_result_disposition",),
        ),
        _evidence(
            "source.pm_package.same_generation_conflict",
            test_name="test_pm_disposition_rejects_second_body_for_same_batch_generation",
            path="tests/test_flowpilot_control_plane_contracts.py",
            command="python -m unittest tests.test_flowpilot_control_plane_contracts.FlowPilotControlPlaneContractRuntimeTests.test_pm_disposition_rejects_second_body_for_same_batch_generation",
            test_kind=NEGATIVE,
            covers=("pm_package_disposition.semantic_identity_and_packet_outcomes",),
            code_contracts=(
                "pm_decisions._write_pm_package_result_disposition",
                "role_output_runtime.submit_output",
            ),
        ),
        _evidence(
            "source.pm_package.fake_ai_trace_conflict",
            test_name="test_fake_ai_pm_package_trace_catches_same_package_conflicting_decisions",
            path="tests/test_flowpilot_synthetic_agent_trace_replay.py",
            command="python -m unittest tests.test_flowpilot_synthetic_agent_trace_replay.FlowPilotSyntheticAgentTraceReplayTests.test_fake_ai_pm_package_trace_catches_same_package_conflicting_decisions",
            test_kind=NEGATIVE,
            covers=("pm_package_disposition.semantic_identity_and_packet_outcomes",),
            code_contracts=(
                "role_output_runtime.submit_output",
                "router._scoped_event_identity",
                "router._check_scoped_event_conflict",
            ),
        ),
        _evidence(
            "source.controller_aside.boundary",
            test_name="test_controller_process_aside_is_metadata_only_and_validated",
            path="tests/test_flowpilot_boundary_contracts.py",
            command="python -m unittest tests.test_flowpilot_boundary_contracts.FlowPilotBoundaryContractTests.test_controller_process_aside_is_metadata_only_and_validated",
            test_kind=NEGATIVE,
            covers=("controller_aside.metadata_only_boundary",),
            code_contracts=(
                "controller_aside.contract",
                "controller_aside.validate_text",
                "controller_aside.build",
            ),
        ),
        _evidence(
            "source.material_artifact_map.boundary",
            test_name="test_material_artifact_map_is_index_only_and_preserves_sealed_body_boundary",
            path="tests/test_flowpilot_boundary_contracts.py",
            command="python -m unittest tests.test_flowpilot_boundary_contracts.FlowPilotBoundaryContractTests.test_material_artifact_map_is_index_only_and_preserves_sealed_body_boundary",
            test_kind=NEGATIVE,
            covers=("material_artifact_map.index_only_boundary",),
            code_contracts=(
                "material_artifact_map.refresh",
                "material_artifact_map.summary",
                "material_artifact_map.source_ref",
                "material_artifact_map.review_ids",
                "material_artifact_map.review_paths",
            ),
        ),
        _evidence(
            "source.material_artifact_map.entry_policy",
            test_name="test_material_artifact_map_entry_policy_preserves_reference_boundaries",
            path="tests/test_flowpilot_boundary_contracts.py",
            command="python -m unittest tests.test_flowpilot_boundary_contracts.FlowPilotBoundaryContractTests.test_material_artifact_map_entry_policy_preserves_reference_boundaries",
            test_kind=EDGE,
            covers=("material_artifact_map.index_only_boundary",),
            code_contracts=(
                "material_artifact_map_entries.make_entry",
                "material_artifact_map_entries.safe_source_ref",
                "material_artifact_map_entries.sealed_body_ref",
                "material_artifact_map_entries.static_artifact_entries",
            ),
        ),
        _evidence(
            "source.branch_pruning.classifier",
            test_name="test_result_case_classifier_covers_shared_cases",
            path="tests/test_flowpilot_router_reconciliation_branch_pruning_model.py",
            command="python -m unittest tests.test_flowpilot_router_reconciliation_branch_pruning_model",
            test_kind=HAPPY,
            covers=("branch_pruning.result_case_classifier",),
            code_contracts=("branch_pruning.next_states",),
        ),
        _evidence(
            "source.branch_pruning.known_bad",
            test_name="test_known_bad_contracts_are_rejected",
            path="tests/test_flowpilot_router_reconciliation_branch_pruning_model.py",
            command="python -m unittest tests.test_flowpilot_router_reconciliation_branch_pruning_model",
            test_kind=NEGATIVE,
            covers=(
                "branch_pruning.result_case_classifier",
                "branch_pruning.scheduled_receipt_effect_cases",
                "branch_pruning.role_output_authority_cases",
                "branch_pruning.runtime_state_resume_cases",
            ),
            code_contracts=("branch_pruning.next_states", "branch_pruning.failures"),
        ),
        _evidence(
            "source.branch_pruning.scheduled_replay",
            test_name="test_scheduled_receipt_effect_cases_keep_replay_gate",
            path="tests/test_flowpilot_router_reconciliation_branch_pruning_model.py",
            command="python -m unittest tests.test_flowpilot_router_reconciliation_branch_pruning_model",
            test_kind=REPLAY,
            covers=("branch_pruning.scheduled_receipt_effect_cases",),
            code_contracts=("branch_pruning.failures",),
        ),
        _evidence(
            "source.branch_pruning.role_output_authority",
            test_name="test_role_output_authority_cases_preserve_not_ready_and_unauthorized",
            path="tests/test_flowpilot_router_reconciliation_branch_pruning_model.py",
            command="python -m unittest tests.test_flowpilot_router_reconciliation_branch_pruning_model",
            test_kind=HAPPY,
            covers=("branch_pruning.role_output_authority_cases",),
            code_contracts=("branch_pruning.failures",),
        ),
        _evidence(
            "source.branch_pruning.runtime_state_resume",
            test_name="test_runtime_state_resume_cases_keep_single_owner_model_only",
            path="tests/test_flowpilot_router_reconciliation_branch_pruning_model.py",
            command="python -m unittest tests.test_flowpilot_router_reconciliation_branch_pruning_model",
            test_kind=EDGE,
            covers=("branch_pruning.runtime_state_resume_cases",),
            code_contracts=("branch_pruning.ownership_snapshot", "branch_pruning.failures"),
        ),
        _evidence(
            "source.runtime_closure.records",
            test_name="test_runtime_closure_external_record_contracts_are_self_validating",
            path="tests/test_flowpilot_router_boundaries.py",
            command="python -m unittest tests.test_flowpilot_router_boundaries.FlowPilotRouterBoundaryTests.test_runtime_closure_external_record_contracts_are_self_validating",
            test_kind=HAPPY,
            covers=(
                "runtime_closure.officer_lifecycle_contract",
                "runtime_closure.continuation_and_final_report_contract",
            ),
            code_contracts=(
                "runtime_closure.validate_officer_request_record",
                "runtime_closure.validate_officer_result_record",
                "runtime_closure.officer_lifecycle_entry_from_request",
                "runtime_closure.continuation_quarantine_record",
                "runtime_closure.validate_continuation_quarantine_record",
                "runtime_closure.final_user_report_record",
                "runtime_closure.validate_final_user_report_record",
                "runtime_closure.route_display_refresh_record",
                "runtime_closure.validate_route_display_refresh_record",
            ),
        ),
        _evidence(
            "source.daemon.run_stop",
            test_name="test_router_daemon_observation_initializes_lock_status_and_ledger",
            path="tests/router_runtime/startup_daemon.py",
            command="python -m unittest tests.test_flowpilot_router_runtime_startup_daemon",
            test_kind=HAPPY,
            covers=("daemon.lock_status_queue_contract",),
            code_contracts=("daemon.run_router_daemon", "daemon.stop_router_daemon"),
        ),
        _evidence(
            "source.daemon.tick_bound",
            test_name="test_router_daemon_tick_stays_bound_when_current_focus_changes",
            path="tests/router_runtime/startup_daemon.py",
            command="python -m unittest tests.test_flowpilot_router_runtime_startup_daemon",
            test_kind=EDGE,
            covers=("daemon.lock_status_queue_contract",),
            code_contracts=("daemon.acquire_lock", "daemon.tick"),
        ),
        _evidence(
            "source.daemon.refresh_lock",
            test_name="test_router_daemon_refresh_does_not_reactivate_released_lock",
            path="tests/router_runtime/startup_daemon.py",
            command="python -m unittest tests.test_flowpilot_router_runtime_startup_daemon",
            test_kind=NEGATIVE,
            covers=("daemon.lock_status_queue_contract",),
            code_contracts=("daemon.acquire_lock", "daemon.refresh_lock", "daemon.release_lock"),
        ),
        _evidence(
            "source.daemon.status",
            test_name="test_router_daemon_status_not_active_after_error_lock_or_missing_pid",
            path="tests/router_runtime/startup_daemon.py",
            command="python -m unittest tests.test_flowpilot_router_runtime_startup_daemon",
            test_kind=FAILURE,
            covers=("daemon.lock_status_queue_contract",),
            code_contracts=("daemon.write_status",),
        ),
        _evidence(
            "source.startup_daemon.liveness",
            test_name="test_startup_daemon_helpers_belong_to_owner_module",
            path="tests/test_flowpilot_router_boundaries.py",
            command="python -m unittest tests.test_flowpilot_router_boundaries.FlowPilotRouterBoundaryTests.test_startup_daemon_helpers_belong_to_owner_module",
            test_kind=HAPPY,
            covers=("startup_daemon.lock_liveness_contract",),
            code_contracts=(
                "process_liveness.probe",
                "startup_daemon.lock_liveness",
                "startup_daemon.heartbeat_monitor",
                "startup_daemon.lock_is_live",
            ),
        ),
        _evidence(
            "source.runtime_owner.break_glass_happy",
            test_name="test_break_glass_contract_records_controller_only_incident_patch_and_close",
            path="tests/test_flowpilot_runtime_owner_contracts.py",
            command="python -m unittest tests.test_flowpilot_runtime_owner_contracts.FlowPilotRuntimeOwnerContractTests.test_break_glass_contract_records_controller_only_incident_patch_and_close",
            test_kind=HAPPY,
            covers=("runtime_owner.high_priority_owner_contracts",),
            code_contracts=(
                "break_glass.open_incident",
                "break_glass.record_patch",
                "break_glass.close_incident",
            ),
        ),
        _evidence(
            "source.runtime_owner.path_prompt_happy",
            test_name="test_path_and_prompt_store_contracts_resolve_active_run_and_hash_checked_text",
            path="tests/test_flowpilot_runtime_owner_contracts.py",
            command="python -m unittest tests.test_flowpilot_runtime_owner_contracts.FlowPilotRuntimeOwnerContractTests.test_path_and_prompt_store_contracts_resolve_active_run_and_hash_checked_text",
            test_kind=HAPPY,
            covers=("runtime_owner.high_priority_owner_contracts",),
            code_contracts=(
                "flowpilot_paths.resolve_flowpilot_paths",
                "prompt_store.load_prompt_text",
            ),
        ),
        _evidence(
            "source.runtime_owner.runtime_gateway_negative",
            test_name="test_gateway_classifies_and_blocks_wrong_owner_for_critical_state",
            path="tests/test_flowpilot_runtime_gateway_adoption.py",
            command="python -m unittest tests.test_flowpilot_runtime_gateway_adoption.FlowPilotRuntimeGatewayAdoptionTests.test_gateway_classifies_and_blocks_wrong_owner_for_critical_state",
            test_kind=NEGATIVE,
            covers=("runtime_owner.high_priority_owner_contracts",),
            code_contracts=("runtime_gateway.assert_runtime_gateway_write",),
        ),
        _evidence(
            "source.runtime_owner.small_helpers_happy",
            test_name="test_small_runtime_owner_helpers_return_stable_external_shapes",
            path="tests/test_flowpilot_runtime_owner_contracts.py",
            command="python -m unittest tests.test_flowpilot_runtime_owner_contracts.FlowPilotRuntimeOwnerContractTests.test_small_runtime_owner_helpers_return_stable_external_shapes",
            test_kind=HAPPY,
            covers=("runtime_owner.high_priority_owner_contracts",),
            code_contracts=(
                "action_providers.lifecycle_provider",
                "card_returns.pending_return_card_ids",
                "router_errors.router_error_record",
            ),
        ),
        _evidence(
            "source.runtime_owner.card_settlement_happy",
            test_name="test_card_settlement_ack_helpers_belong_to_owner_module",
            path="tests/test_flowpilot_router_boundaries.py",
            command="python -m unittest tests.test_flowpilot_router_boundaries.FlowPilotRouterBoundaryTests.test_card_settlement_ack_helpers_belong_to_owner_module",
            test_kind=HAPPY,
            covers=("runtime_owner.router_boundary_helpers",),
            code_contracts=("card_settlement.card_ack_clearance_scope",),
        ),
        _evidence(
            "source.runtime_owner.controller_boundary_happy",
            test_name="test_controller_boundary_helpers_belong_to_owner_module",
            path="tests/test_flowpilot_router_boundaries.py",
            command="python -m unittest tests.test_flowpilot_router_boundaries.FlowPilotRouterBoundaryTests.test_controller_boundary_helpers_belong_to_owner_module",
            test_kind=HAPPY,
            covers=("runtime_owner.router_boundary_helpers",),
            code_contracts=("controller_boundary.patrol_timer_command",),
        ),
        _evidence(
            "source.runtime_owner.controller_reconciliation_happy",
            test_name="test_controller_reconciliation_helpers_belong_to_owner_module",
            path="tests/test_flowpilot_router_boundaries.py",
            command="python -m unittest tests.test_flowpilot_router_boundaries.FlowPilotRouterBoundaryTests.test_controller_reconciliation_helpers_belong_to_owner_module",
            test_kind=HAPPY,
            covers=("runtime_owner.router_boundary_helpers",),
            code_contracts=("controller_reconciliation.action_projection_kind",),
        ),
        _evidence(
            "source.runtime_owner.controller_repair_happy",
            test_name="test_protocol_tables_and_mail_lookup_belong_to_owner_modules",
            path="tests/test_flowpilot_router_boundaries.py",
            command="python -m unittest tests.test_flowpilot_router_boundaries.FlowPilotRouterBoundaryTests.test_protocol_tables_and_mail_lookup_belong_to_owner_modules",
            test_kind=HAPPY,
            covers=("runtime_owner.router_boundary_helpers",),
            code_contracts=(
                "controller_repair.bind_router",
                "protocol_tables.terminal_statuses",
                "protocol_tables.mail_sequence_entry",
            ),
        ),
        _evidence(
            "source.runtime_owner.startup_catalog_happy",
            test_name="test_startup_boot_catalog_split_preserves_protocol_owner_boundary",
            path="tests/test_flowpilot_router_boundaries.py",
            command="python -m unittest tests.test_flowpilot_router_boundaries.FlowPilotRouterBoundaryTests.test_startup_boot_catalog_split_preserves_protocol_owner_boundary",
            test_kind=HAPPY,
            covers=("runtime_owner.router_boundary_helpers",),
            code_contracts=(
                "startup_catalog.startup_boot_catalog",
                "planning_cards.planning_system_card_catalog",
                "runtime_cards.runtime_system_card_catalog",
                "card_metadata.system_card_metadata_catalog",
                "boot_cards.system_card_catalog",
            ),
        ),
        _evidence(
            "source.runtime_owner.dispatch_gate_happy",
            test_name="test_dispatch_gate_helpers_belong_to_owner_module",
            path="tests/test_flowpilot_router_boundaries.py",
            command="python -m unittest tests.test_flowpilot_router_boundaries.FlowPilotRouterBoundaryTests.test_dispatch_gate_helpers_belong_to_owner_module",
            test_kind=HAPPY,
            covers=("runtime_owner.router_boundary_helpers",),
            code_contracts=("dispatch_gate.target_roles",),
        ),
        _evidence(
            "source.router_owner.action_factory_happy",
            test_name="test_action_factory_and_dispatch_gate_external_contracts",
            path="tests/test_flowpilot_router_owner_contracts.py",
            command="python -m unittest tests.test_flowpilot_router_owner_contracts.FlowPilotRouterOwnerContractTests.test_action_factory_and_dispatch_gate_external_contracts",
            test_kind=HAPPY,
            covers=("runtime_owner.router_owner_external_contracts",),
            code_contracts=(
                "action_factory_dispatch.apply_dispatch_recipient_gate",
                "action_factory_envelope.make_action",
            ),
        ),
        _evidence(
            "source.router_owner.card_ledger_happy",
            test_name="test_card_delivery_and_controller_ledger_external_contracts",
            path="tests/test_flowpilot_router_owner_contracts.py",
            command="python -m unittest tests.test_flowpilot_router_owner_contracts.FlowPilotRouterOwnerContractTests.test_card_delivery_and_controller_ledger_external_contracts",
            test_kind=HAPPY,
            covers=("runtime_owner.router_owner_external_contracts",),
            code_contracts=(
                "card_delivery.next_card_delivery_attempt",
                "controller_ledger.prepare_router_scheduled_action",
            ),
        ),
        _evidence(
            "source.router_owner.controller_wait_audit_edge",
            test_name="test_audit_marks_formal_return_ready_when_next_notice_exists",
            path="tests/test_flowpilot_controller_wait_receipt_audit.py",
            command="python -m unittest tests.test_flowpilot_controller_wait_receipt_audit.ControllerWaitReceiptAuditUnitTests.test_audit_marks_formal_return_ready_when_next_notice_exists",
            test_kind=EDGE,
            covers=("runtime_owner.router_owner_external_contracts",),
            code_contracts=("controller_wait_audit.controller_wait_receipt_audit",),
        ),
        _evidence(
            "source.router_owner.action_handlers_negative",
            test_name="test_action_handler_modules_return_outcomes_and_reject_forbidden_authority",
            path="tests/test_flowpilot_router_owner_contracts.py",
            command="python -m unittest tests.test_flowpilot_router_owner_contracts.FlowPilotRouterOwnerContractTests.test_action_handler_modules_return_outcomes_and_reject_forbidden_authority",
            test_kind=NEGATIVE,
            covers=("runtime_owner.router_owner_external_contracts",),
            code_contracts=(
                "action_handlers_basic.check_packet_ledger",
                "action_handlers_basic.relay_only_system_card",
                "action_handlers_roles.controller_repair_work_packet",
            ),
        ),
        _evidence(
            "source.router_owner.artifact_child_skill_negative",
            test_name="test_artifact_validation_and_child_skill_capability_external_contracts",
            path="tests/test_flowpilot_router_owner_contracts.py",
            command="python -m unittest tests.test_flowpilot_router_owner_contracts.FlowPilotRouterOwnerContractTests.test_artifact_validation_and_child_skill_capability_external_contracts",
            test_kind=NEGATIVE,
            covers=("runtime_owner.router_owner_external_contracts",),
            code_contracts=(
                "artifact_validation.validate_artifact",
                "child_skill_capability.approve_manifest",
                "child_skill_capability.sync_capability_evidence",
            ),
        ),
        _evidence(
            "source.full_diagnostic.controller_control_scheduler",
            test_name="test_controller_control_scheduler_external_contracts",
            path="tests/test_flowpilot_full_diagnostic_contracts.py",
            command="python -m unittest tests.test_flowpilot_full_diagnostic_contracts.FlowPilotFullDiagnosticContractTests.test_controller_control_scheduler_external_contracts",
            test_kind=HAPPY,
            covers=("runtime_owner.router_owner_external_contracts",),
            code_contracts=(
                "router_cli.parse_args",
                "control_transactions.registry_issues",
                "controller_repair_schedule.schedule_deliverable_repair",
                "receipts_pending.router_scheduler_row",
                "receipts_scheduled.scheduler_row_reconciliation",
                "receipts_writes.maybe_write_controller_receipt",
            ),
        ),
        _evidence(
            "source.receipts_scheduled.reconcile_loop",
            test_name="test_reconciled_controller_action_backfills_receipt_done_scheduler_row",
            path="tests/router_runtime/foreground_controller.py",
            command="python -m unittest tests.router_runtime.foreground_controller.ForegroundControllerRuntimeTests.test_reconciled_controller_action_backfills_receipt_done_scheduler_row",
            test_kind=HAPPY,
            covers=("runtime_owner.router_owner_external_contracts",),
            code_contracts=("receipts_scheduled.reconcile_loop",),
        ),
        _evidence(
            "source.receipts_bootloader.boundary",
            test_name="test_receipt_bootloader_policy_child_preserves_facade_boundary",
            path="tests/test_flowpilot_boundary_contracts.py",
            command="python -m unittest tests.test_flowpilot_boundary_contracts.FlowPilotBoundaryContractTests.test_receipt_bootloader_policy_child_preserves_facade_boundary",
            test_kind=EDGE,
            covers=("runtime_owner.receipt_bootloader_policy_boundary",),
            code_contracts=(
                "receipts_bootloader.boot_action_meta",
                "receipts_bootloader.matching_pending_action",
                "receipts_bootloader.apply_startup_bootloader_receipt_effects",
            ),
        ),
        _evidence(
            "source.receipt_packet_fold.registry_child",
            test_name="test_receipt_packet_fold_registry_child_preserves_registered_actions",
            path="tests/test_flowpilot_full_diagnostic_contracts.py",
            command="python -m unittest tests.test_flowpilot_full_diagnostic_contracts.FlowPilotFullDiagnosticContractTests.test_receipt_packet_fold_registry_child_preserves_registered_actions",
            test_kind=EDGE,
            covers=("runtime_owner.receipt_packet_fold_registry_boundary",),
            code_contracts=("receipt_packet_fold_registry.registered_actions",),
        ),
        _evidence(
            "source.receipt_packet_fold.lifecycle_child",
            test_name="test_pm_role_work_receipt_lifecycle_consumes_shared_policy",
            path="tests/test_flowpilot_full_diagnostic_contracts.py",
            command="python -m unittest tests.test_flowpilot_full_diagnostic_contracts.FlowPilotFullDiagnosticContractTests.test_pm_role_work_receipt_lifecycle_consumes_shared_policy",
            test_kind=EDGE,
            covers=("runtime_owner.receipt_packet_fold_lifecycle_boundary",),
            code_contracts=(
                "receipt_packet_fold_lifecycle.policy",
                "receipt_packet_fold_lifecycle.apply_parallel_batch",
                "receipt_packet_fold_lifecycle.apply_pm_role_work",
            ),
        ),
        _evidence(
            "source.receipt_scheduled.policy_child",
            test_name="test_scheduled_receipt_policy_child_preserves_facade_boundary",
            path="tests/test_flowpilot_full_diagnostic_contracts.py",
            command="python -m unittest tests.test_flowpilot_full_diagnostic_contracts.FlowPilotFullDiagnosticContractTests.test_scheduled_receipt_policy_child_preserves_facade_boundary",
            test_kind=EDGE,
            covers=("runtime_owner.receipt_scheduled_policy_boundary",),
            code_contracts=(
                "receipt_scheduled_policy.scheduler_row_reconciliation",
                "receipt_scheduled_policy.backfill_scheduler_row",
                "receipt_scheduled_policy.clear_pending_match",
                "receipt_scheduled_policy.apply_result_case",
            ),
        ),
        _evidence(
            "source.current_work_pending.boundary",
            test_name="test_current_work_pending_policy_child_preserves_facade_boundary",
            path="tests/test_flowpilot_boundary_contracts.py",
            command="python -m unittest tests.test_flowpilot_boundary_contracts.FlowPilotBoundaryContractTests.test_current_work_pending_policy_child_preserves_facade_boundary",
            test_kind=EDGE,
            covers=("runtime_owner.current_work_pending_policy_boundary",),
            code_contracts=(
                "current_work_pending.has_controller_authority",
                "current_work_pending.scheduler_row",
                "current_work_pending.durable_resolution",
                "current_work_pending.clear_durable_wait",
                "current_work_pending.role_wait_batch_projection",
            ),
        ),
        _evidence(
            "source.standby_policy.boundary",
            test_name="test_foreground_controller_standby_state_policy_classifier",
            path="tests/test_flowpilot_full_diagnostic_contracts.py",
            command="python -m unittest tests.test_flowpilot_full_diagnostic_contracts.FlowPilotFullDiagnosticContractTests.test_foreground_controller_standby_state_policy_classifier",
            test_kind=EDGE,
            covers=("runtime_owner.standby_state_policy_boundary",),
            code_contracts=(
                "standby_policy.foreground_standby_state",
                "standby_policy.foreground_standby_policy",
            ),
        ),
        _evidence(
            "source.full_diagnostic.event_wait_repair",
            test_name="test_event_wait_repair_external_contracts",
            path="tests/test_flowpilot_full_diagnostic_contracts.py",
            command="python -m unittest tests.test_flowpilot_full_diagnostic_contracts.FlowPilotFullDiagnosticContractTests.test_event_wait_repair_external_contracts",
            test_kind=HAPPY,
            covers=("runtime_owner.router_owner_external_contracts",),
            code_contracts=(
                "event_identity.stable_identity_hash",
                "event_intake.role_list",
                "events_repair.owner_child_module_names",
                "expected_waits.run_state_has_event",
                "model_gate_state.sync_model_gate_flags",
                "protocol_external_events.external_event_contract",
            ),
        ),
        _evidence(
            "source.full_diagnostic.facade_export_manifest",
            test_name="test_facade_export_manifest_external_contracts",
            path="tests/test_flowpilot_full_diagnostic_contracts.py",
            command="python -m unittest tests.test_flowpilot_full_diagnostic_contracts.FlowPilotFullDiagnosticContractTests.test_facade_export_manifest_external_contracts",
            test_kind=HAPPY,
            covers=("runtime_owner.router_owner_external_contracts",),
            code_contracts=(
                "manifest_registry.owner_exports_for_domain",
                "manifest_actions.owner_exports_actions",
                "manifest_controller.owner_exports_controller",
                "manifest_route.owner_exports_route",
                "manifest_startup.owner_exports_startup",
                "manifest_terminal_work.owner_exports_terminal_work",
                "facade_exports.resolve_facade_export",
            ),
        ),
        _evidence(
            "source.full_diagnostic.lifecycle_startup_system_card",
            test_name="test_lifecycle_startup_system_card_external_contracts",
            path="tests/test_flowpilot_full_diagnostic_contracts.py",
            command="python -m unittest tests.test_flowpilot_full_diagnostic_contracts.FlowPilotFullDiagnosticContractTests.test_lifecycle_startup_system_card_external_contracts",
            test_kind=NEGATIVE,
            covers=("runtime_owner.router_owner_external_contracts",),
            code_contracts=(
                "lifecycle_requests.write_terminal_fence",
                "lifecycle_requests.clear_terminal_blocker",
                "lifecycle_terminal_quarantine.clear_repair_transaction",
                "lifecycle_terminal_quarantine.material_progress_flags",
                "lifecycle_terminal_quarantine.duplicate_role_events",
                "lifecycle_terminal_quarantine.packet_result_authority",
                "lifecycle_requests.write_run_lifecycle",
                "lifecycle_requests.write_protocol_dead_end",
                "lifecycle_requests.exception_blocker_fallback",
                "lifecycle_support.lifecycle_record_path",
                "startup_bootloader.depends_on_role_slots",
                "startup_closure.host_heartbeat_binding_ready",
                "startup_display.display_text_hash",
                "startup_fact_boundary.controller_boundary_constraints",
                "startup_flow.owner_module_name",
                "startup_intake.result_payload_contract",
                "startup_role_recovery.owner_child_module_names",
                "startup_support.ensure_startup_run_state",
                "system_cards_delivery.commit_system_card_delivery",
            ),
        ),
        _evidence(
            "source.terminal.terminal_lifecycle_quarantine",
            test_name="test_user_stop_quarantines_active_repair_and_historical_control_plane_artifacts",
            path="tests/router_runtime/terminal.py",
            command="python -m unittest tests.router_runtime.terminal.TerminalRuntimeTests.test_user_stop_quarantines_active_repair_and_historical_control_plane_artifacts",
            test_kind=NEGATIVE,
            covers=("terminal.final_ledger_and_backward_replay",),
            code_contracts=(
                "router.record_external_event",
            ),
        ),
        _evidence(
            "source.startup_intake.flowguard_capability_child",
            test_name="test_startup_intake_flowguard_capability_child_preserves_boundary",
            path="tests/test_flowpilot_full_diagnostic_contracts.py",
            command="python -m unittest tests.test_flowpilot_full_diagnostic_contracts.FlowPilotFullDiagnosticContractTests.test_startup_intake_flowguard_capability_child_preserves_boundary",
            test_kind=EDGE,
            covers=("runtime_owner.startup_intake_flowguard_capability_boundary",),
            code_contracts=(
                "startup_intake_flowguard_capability.route_classification",
                "startup_intake_flowguard_capability.import_snapshot",
                "startup_intake_flowguard_capability.write_snapshot",
            ),
        ),
        _evidence(
            "source.full_diagnostic.role_prompt_proof_terminal_work_packet",
            test_name="test_role_prompt_proof_terminal_work_packet_external_contracts",
            path="tests/test_flowpilot_full_diagnostic_contracts.py",
            command="python -m unittest tests.test_flowpilot_full_diagnostic_contracts.FlowPilotFullDiagnosticContractTests.test_role_prompt_proof_terminal_work_packet_external_contracts",
            test_kind=NEGATIVE,
            covers=("runtime_owner.router_owner_external_contracts",),
            code_contracts=(
                "internal_actions.action_is_router_internal_mechanical",
                "payload_contracts.payload_contract",
                "pm_role_followup.pm_role_work_channel_open",
                "prompt_delivery.card_checkin_instruction",
                "proof_validation.validate_router_owned_check_proof",
                "role_io_protocol.empty_role_io_protocol_ledger",
                "role_output_bridge.role_output_snapshot_name",
                "route_artifacts_evidence.write_pm_review_block_repair",
                "route_completion_support.resume_waits_for_pm_decision",
                "self_interrogation.self_interrogation_issue",
                "terminal_closure.terminal_closure_suite_is_closed",
                "terminal_recovery.recover_terminal_status",
                "terminal_summary.terminal_summary_action",
                "work_packets_next_actions.try_reconcile_material_scan",
                "work_packets_pm_role_actions.try_reconcile_pm_role_work",
            ),
        ),
        _evidence(
            "source.full_diagnostic.user_flow",
            test_name="test_user_flow_external_contracts",
            path="tests/test_flowpilot_full_diagnostic_contracts.py",
            command="python -m unittest tests.test_flowpilot_full_diagnostic_contracts.FlowPilotFullDiagnosticContractTests.test_user_flow_external_contracts",
            test_kind=HAPPY,
            covers=("runtime_owner.router_owner_external_contracts",),
            code_contracts=(
                "user_flow_source.route_source_summary",
                "user_flow_stage.classify_current_stage",
                "user_flow_tree.active_node",
                "user_flow_mermaid.build_mermaid",
                "user_flow_markdown.build_chat_markdown",
            ),
        ),
        _evidence(
            "source.runtime_owner.role_output_bridge_events",
            test_name="test_role_output_bridge_event_child_reads_body_and_checks_pending_authority",
            path="tests/test_flowpilot_role_output_bridge_events.py",
            command="python -m unittest tests.test_flowpilot_role_output_bridge_events.RoleOutputBridgeEventChildTests.test_role_output_bridge_event_child_reads_body_and_checks_pending_authority",
            test_kind=EDGE,
            covers=("runtime_owner.role_output_bridge_event_policy_boundary",),
            code_contracts=(
                "role_output_bridge_events.body_payload_from_record",
                "role_output_bridge_events.event_has_durable_authority",
            ),
        ),
        _evidence(
            "source.runtime_owner.role_output_package_replay_repair",
            test_name="test_replay_child_contract_reconciles_package_authority_split",
            path="tests/test_flowpilot_role_output_reconciliation.py",
            command="python -m unittest tests.test_flowpilot_role_output_reconciliation.RoleOutputReconciliationTests.test_replay_child_contract_reconciles_package_authority_split",
            test_kind=REPLAY,
            covers=("runtime_owner.role_output_bridge_event_policy_boundary",),
            code_contracts=("role_output_bridge_events_replay.try_reconcile_direct_role_output_event_ledger",),
        ),
        _evidence(
            "source.runtime_owner.expected_waits_pm_package_repair",
            test_name="test_expected_waits_pm_package_contract_repairs_domain_commit",
            path="tests/test_flowpilot_role_output_reconciliation.py",
            command="python -m unittest tests.test_flowpilot_role_output_reconciliation.RoleOutputReconciliationTests.test_expected_waits_pm_package_contract_repairs_domain_commit",
            test_kind=REPLAY,
            covers=("runtime_owner.router_owner_external_contracts",),
            code_contracts=("expected_waits_pm_package.record_router_reconciled_external_event",),
        ),
        _evidence(
            "source.full_diagnostic.packet_control_plane_reviewer",
            test_name="test_packet_control_plane_and_reviewer_external_contracts",
            path="tests/test_flowpilot_full_diagnostic_contracts.py",
            command="python -m unittest tests.test_flowpilot_full_diagnostic_contracts.FlowPilotFullDiagnosticContractTests.test_packet_control_plane_and_reviewer_external_contracts",
            test_kind=HAPPY,
            covers=("packet_runtime.runtime_owner_contracts", "packet_control_plane.model_state_contract"),
            code_contracts=(
                "packet_invariants.controller_handoff_body_leak_never_advances",
                "packet_issue_resume.pm_issue_apply",
                "packet_relay.runtime_write_apply",
                "packet_dispatch.router_direct_dispatch_apply",
                "packet_review.reviewer_result_apply",
                "packet_runtime_reviewer.validate_for_reviewer",
            ),
        ),
        _evidence(
            "source.runtime_owner.router_events_happy",
            test_name="test_event_boundary_registry_covers_first_migrated_events",
            path="tests/test_flowpilot_router_boundaries.py",
            command="python -m unittest tests.test_flowpilot_router_boundaries.FlowPilotRouterBoundaryTests.test_event_boundary_registry_covers_first_migrated_events",
            test_kind=HAPPY,
            covers=("runtime_owner.router_boundary_helpers",),
            code_contracts=(
                "router_events.handle_precheck_event",
                "router_events.apply_migrated_event_side_effect",
            ),
        ),
        _evidence(
            "source.runtime_owner.event_dispatcher_happy",
            test_name="test_event_dispatcher_passes_router_facade_to_event_helpers",
            path="tests/test_flowpilot_router_boundaries.py",
            command="python -m unittest tests.test_flowpilot_router_boundaries.FlowPilotRouterBoundaryTests.test_event_dispatcher_passes_router_facade_to_event_helpers",
            test_kind=HAPPY,
            covers=("runtime_owner.router_boundary_helpers",),
            code_contracts=("event_dispatcher.record_external_event_unchecked",),
        ),
        _evidence(
            "source.runtime_owner.event_dispatcher_package_authority_repair",
            test_name="test_event_dispatcher_direct_package_authority_contract_repairs_domain_commit",
            path="tests/test_flowpilot_role_output_reconciliation.py",
            command="python -m unittest tests.test_flowpilot_role_output_reconciliation.RoleOutputReconciliationTests.test_event_dispatcher_direct_package_authority_contract_repairs_domain_commit",
            test_kind=REPLAY,
            covers=("runtime_owner.router_boundary_helpers",),
            code_contracts=("event_dispatcher.repair_direct_package_disposition_authority_split",),
        ),
        _evidence(
            "source.runtime_owner.router_io_happy",
            test_name="test_runtime_json_helpers_round_trip_through_io_owner",
            path="tests/test_flowpilot_router_boundaries.py",
            command="python -m unittest tests.test_flowpilot_router_boundaries.FlowPilotRouterBoundaryTests.test_runtime_json_helpers_round_trip_through_io_owner",
            test_kind=HAPPY,
            covers=("runtime_owner.router_boundary_helpers",),
            code_contracts=(
                "router_io.write_json",
                "router_io_locks.json_write_lock_liveness",
                "router_io_paths.project_relative",
                "router_io_hashes.json_sha256",
            ),
        ),
        _evidence(
            "source.runtime_owner.runtime_state_happy",
            test_name="test_coarse_owner_bind_router_refreshes_facade_globals_without_overwriting_owner_locals",
            path="tests/test_flowpilot_router_boundaries.py",
            command="python -m unittest tests.test_flowpilot_router_boundaries.FlowPilotRouterBoundaryTests.test_coarse_owner_bind_router_refreshes_facade_globals_without_overwriting_owner_locals",
            test_kind=HAPPY,
            covers=("runtime_owner.router_boundary_helpers",),
            code_contracts=("runtime_state.bind_router",),
        ),
        _evidence(
            "source.runtime_state.stale_save_merge_child",
            test_name="test_child_merge_preserves_foreground_clear_without_metadata_leak",
            path="tests/test_flowpilot_runtime_state_persistence.py",
            command="python -m unittest tests.test_flowpilot_runtime_state_persistence.RuntimeStatePersistenceTests.test_child_merge_preserves_foreground_clear_without_metadata_leak",
            test_kind=EDGE,
            covers=("runtime_state.stale_save_merge_boundary",),
            code_contracts=(
                "runtime_state_persistence.merge_stale_run_state_save",
            ),
        ),
        _evidence(
            "source.runtime_state.load_save_persistence_child",
            test_name="test_parent_facade_delegates_load_and_stale_save_to_child",
            path="tests/test_flowpilot_runtime_state_persistence.py",
            command="python -m unittest tests.test_flowpilot_runtime_state_persistence.RuntimeStatePersistenceTests.test_parent_facade_delegates_load_and_stale_save_to_child",
            test_kind=EDGE,
            covers=("runtime_state.load_save_persistence_boundary",),
            code_contracts=(
                "runtime_state_persistence.load_run_state_from_run_root",
                "runtime_state_persistence.save_run_state",
            ),
        ),
        _evidence(
            "source.runtime_owner.route_resume_happy",
            test_name="test_route_domain_helpers_are_available_in_route_owner",
            path="tests/test_flowpilot_router_boundaries.py",
            command="python -m unittest tests.test_flowpilot_router_boundaries.FlowPilotRouterBoundaryTests.test_route_domain_helpers_are_available_in_route_owner",
            test_kind=HAPPY,
            covers=("runtime_owner.router_boundary_helpers",),
            code_contracts=("router_route.route_payload_from_reviewed_draft",),
        ),
        _evidence(
            "source.runtime_owner.resume_happy",
            test_name="test_resume_domain_helpers_are_available_in_resume_owner",
            path="tests/test_flowpilot_router_boundaries.py",
            command="python -m unittest tests.test_flowpilot_router_boundaries.FlowPilotRouterBoundaryTests.test_resume_domain_helpers_are_available_in_resume_owner",
            test_kind=HAPPY,
            covers=("runtime_owner.router_boundary_helpers",),
            code_contracts=("router_resume.reset_resume_cycle_for_wakeup",),
        ),
        _evidence(
            "source.runtime_owner.terminal_happy",
            test_name="test_terminal_helpers_belong_to_owner_module",
            path="tests/test_flowpilot_router_boundaries.py",
            command="python -m unittest tests.test_flowpilot_router_boundaries.FlowPilotRouterBoundaryTests.test_terminal_helpers_belong_to_owner_module",
            test_kind=HAPPY,
            covers=("runtime_owner.router_boundary_helpers",),
            code_contracts=("router_terminal.terminal_lifecycle_mode",),
        ),
        _evidence(
            "source.packet_runtime.owner_helpers_happy",
            test_name="test_packet_runtime_contracts_paths_schema_and_audit_boundaries",
            path="tests/test_flowpilot_runtime_owner_contracts.py",
            command="python -m unittest tests.test_flowpilot_runtime_owner_contracts.FlowPilotRuntimeOwnerContractTests.test_packet_runtime_contracts_paths_schema_and_audit_boundaries",
            test_kind=HAPPY,
            covers=("packet_runtime.owner_helper_contracts",),
            code_contracts=(
                "packet_contracts.normalize_output_contract",
                "packet_paths.load_envelope",
                "packet_schema.sha256_file",
            ),
        ),
        _evidence(
            "source.packet_control_plane.runner_happy",
            test_name="test_packet_control_plane_runner_main_uses_flowguard_report_exit_contract",
            path="tests/test_flowpilot_runtime_owner_contracts.py",
            command="python -m unittest tests.test_flowpilot_runtime_owner_contracts.FlowPilotRuntimeOwnerContractTests.test_packet_control_plane_runner_main_uses_flowguard_report_exit_contract",
            test_kind=HAPPY,
            covers=("packet_control_plane.runner_contract",),
            code_contracts=("packet_control_plane.main",),
        ),
        _evidence(
            "source.card.owner_modules",
            test_name="test_card_runtime_owner_modules_expose_direct_external_contracts",
            path="tests/test_flowpilot_card_runtime.py",
            command="python -m pytest tests/test_flowpilot_card_runtime.py::test_card_runtime_owner_modules_expose_direct_external_contracts",
            test_kind=HAPPY,
            covers=("card_runtime.owner_helper_contracts",),
            code_contracts=(
                "card_bundle.validate_card_bundle_ack",
                "card_envelopes.validate_direct_router_ack_token",
                "card_io.project_relative",
                "card_ledgers.load_card_ledger",
            ),
        ),
        _evidence(
            "source.packet.runtime_owner_modules",
            test_name="test_packet_runtime_owner_modules_expose_direct_external_contracts",
            path="tests/test_flowpilot_packet_runtime.py",
            command="python -m unittest tests.test_flowpilot_packet_runtime.FlowPilotPacketRuntimeTests.test_packet_runtime_owner_modules_expose_direct_external_contracts",
            test_kind=HAPPY,
            covers=("packet_runtime.runtime_owner_contracts", "packet_control_plane.model_state_contract"),
            code_contracts=(
                "packet_startup.create_user_intake_packet",
                "packet_ledger.packet_ledger_record_for_envelope",
                "packet_active_holder.require_concrete_agent_id",
                "packet_progress.validate_progress_message",
                "packet_cli.parse_args",
                "packet_sessions.runtime_sessions_dir",
                "packet_relay_checks.verify_router_startup_release",
                "packet_audit.audit_packet_chain",
                "packet_control_plane_state.packet_from_id",
            ),
        ),
        _evidence(
            "source.role_output.owner_modules",
            test_name="test_role_output_owner_modules_expose_direct_external_contracts",
            path="tests/test_flowpilot_role_output_runtime.py",
            command="python -m unittest tests.test_flowpilot_role_output_runtime.FlowPilotRoleOutputRuntimeTests.test_role_output_owner_modules_expose_direct_external_contracts",
            test_kind=HAPPY,
            covers=("role_output_runtime.owner_helper_contracts",),
            code_contracts=(
                "role_output_contracts.build_output_skeleton",
                "role_output_cli.parse_args",
                "role_output_schema.controller_boundary_constraints",
                "role_output_envelopes.runtime_envelope_for_body",
            ),
        ),
        _evidence(
            "source.role_output.controller_boundary_child",
            test_name="test_controller_boundary_helper_writes_runtime_body_receipt_and_ledger",
            path="tests/test_flowpilot_role_output_runtime.py",
            command="python -m unittest tests.test_flowpilot_role_output_runtime.FlowPilotRoleOutputRuntimeTests.test_controller_boundary_helper_writes_runtime_body_receipt_and_ledger",
            test_kind=EDGE,
            covers=("role_output_runtime.owner_helper_contracts",),
            code_contracts=(
                "role_output_controller_boundary.build_confirmation_body",
                "role_output_controller_boundary.submit_confirmation",
            ),
        ),
        _evidence(
            "source.runtime_path_evidence.helper_binding",
            test_name="test_flowpilot_runtime_path_evidence_helper_binds_model_nodes",
            path="tests/test_flowpilot_model_test_alignment.py",
            command="python -m unittest tests.test_flowpilot_model_test_alignment.FlowPilotModelTestAlignmentTests.test_flowpilot_runtime_path_evidence_helper_binds_model_nodes",
            test_kind=HAPPY,
            covers=("runtime_path_contracts.runtime_evidence_binding",),
            code_contracts=(
                "flowpilot_runtime_path_evidence.attach_runtime_path_evidence_to_plan",
            ),
        ),
        _evidence(
            "source.workflow_step.controller_receipt",
            test_name="test_controller_receipt_projection_blocks_apply_path_confusion",
            path="tests/test_flowpilot_workflow_step_contracts.py",
            command="python -m unittest tests.test_flowpilot_workflow_step_contracts",
            test_kind=HAPPY,
            covers=("workflow_step_contracts.next_step_projection",),
            code_contracts=("workflow_step_contracts.project_action",),
        ),
        _evidence(
            "source.workflow_step.known_bad",
            test_name="test_missing_prerequisite_and_forbidden_skip_are_rejected",
            path="tests/test_flowpilot_workflow_step_contracts.py",
            command="python -m unittest tests.test_flowpilot_workflow_step_contracts",
            test_kind=NEGATIVE,
            covers=("workflow_step_contracts.next_step_projection",),
            code_contracts=("workflow_step_contracts.project_action", "workflow_step_contracts.review_trace"),
        ),
        _evidence(
            "source.workflow_step.ack_separation",
            test_name="test_ack_read_receipt_does_not_complete_target_work",
            path="tests/test_flowpilot_workflow_step_contracts.py",
            command="python -m unittest tests.test_flowpilot_workflow_step_contracts",
            test_kind=EDGE,
            covers=("workflow_step_contracts.next_step_projection",),
            code_contracts=("workflow_step_contracts.project_action", "workflow_step_contracts.review_trace"),
        ),
        _evidence(
            "source.workflow_step.runner",
            test_name="test_flowguard_workflow_step_runner_passes_known_good_and_known_bad",
            path="tests/test_flowpilot_workflow_step_contracts.py",
            command="python -m unittest tests.test_flowpilot_workflow_step_contracts",
            test_kind=HAPPY,
            covers=("workflow_step_contracts.next_step_projection",),
            code_contracts=("workflow_step_contracts.runner",),
        ),
        _evidence(
            "source.output.packet",
            test_name="test_pm_packet_repeats_output_contract_in_envelope_body_ledger_and_result",
            path="tests/test_flowpilot_output_contracts.py",
            command="python -m unittest tests.test_flowpilot_output_contracts",
            test_kind=HAPPY,
            covers=("output_contract.packet_binding",),
            code_contracts=("packet.create_packet", "packet.controller_relay_envelope", "packet.write_result"),
        ),
        _evidence(
            "source.router.direct",
            test_name="test_current_node_packet_relay_uses_router_direct_dispatch",
            path="tests/router_runtime/packets.py",
            command="python -m unittest tests.test_flowpilot_router_runtime_packets",
            test_kind=HAPPY,
            covers=("router_loop.packet_result_review_loop",),
            code_contracts=("router.record_external_event",),
        ),
        _evidence(
            "source.router.audit",
            test_name="test_current_node_completion_requires_reviewer_passed_packet_audit",
            path="tests/router_runtime/packets.py",
            command="python -m unittest tests.test_flowpilot_router_runtime_packets",
            test_kind=FAILURE,
            covers=("router_loop.packet_result_review_loop",),
            code_contracts=("router.record_external_event",),
        ),
        _evidence(
            "source.tier.release",
            test_name="test_fast_and_router_tiers_do_not_contain_release_only_commands",
            path="tests/test_flowpilot_test_tiers.py",
            command="python -m unittest tests.test_flowpilot_test_tiers",
            test_kind=NEGATIVE,
            covers=("test_tiering.foreground_fast_scope",),
            code_contracts=("test_tier.commands_for_tier",),
        ),
        _evidence(
            "source.meta.thin",
            test_name="test_default_meta_runner_uses_thin_parent_without_full_graph",
            path="tests/test_flowpilot_thin_parent_checks.py",
            command="python -m unittest tests.test_flowpilot_thin_parent_checks",
            test_kind=HAPPY,
            covers=("meta_parent.thin_default_and_layered_full_boundary",),
            code_contracts=("meta_runner.main",),
        ),
        _evidence(
            "source.smoke.fast",
            test_name="test_smoke_fast_only_marks_slow_model_checks_fast",
            path="tests/test_flowguard_result_proof.py",
            command="python -m unittest tests.test_flowguard_result_proof",
            test_kind=NEGATIVE,
            covers=("capability_parent.proof_reuse_and_fast_boundary",),
            code_contracts=("smoke.main",),
        ),
    )
