"""Source-audited code contracts for FlowPilot model-test alignment."""

from __future__ import annotations

from flowpilot_model_test_alignment_common import *


def source_code_contracts() -> tuple[CodeContract, ...]:
    """Return source-audited code contract rows."""

    return (
        _contract(
            "router.run_until_wait",
            path="skills/flowpilot/assets/flowpilot_router_controller_runtime.py",
            symbol="run_until_wait",
            implements=("startup.questions.pause_before_work",),
            external_inputs=("project_root",),
        ),
        _contract(
            "router.apply_action",
            path="skills/flowpilot/assets/flowpilot_router_controller_runtime.py",
            symbol="apply_action",
            implements=("startup.questions.pause_before_work", "resume.current_run_reentry"),
            external_inputs=("project_root", "action_type", "payload"),
        ),
        _contract(
            "router.record_external_event",
            path="skills/flowpilot/assets/flowpilot_router_controller_runtime.py",
            symbol="record_external_event",
            implements=(
                "startup.run_isolation_and_activation",
                "ack.return_wait_preconsumption",
                "route_mutation.topology_and_recheck",
                "route_mutation.sibling_replacement_stales_old_evidence",
                "terminal.final_ledger_and_backward_replay",
                "resume.current_run_reentry",
                "router_loop.packet_result_review_loop",
            ),
            external_inputs=("project_root", "event", "payload"),
        ),
        _contract(
            "router.next_action",
            path="skills/flowpilot/assets/flowpilot_router_controller_runtime.py",
            symbol="next_action",
            implements=("startup.questions.pause_before_work", "resume.current_run_reentry"),
            external_inputs=("project_root",),
        ),
        _contract(
            "flowpilot_new.start_run",
            path="skills/flowpilot/assets/flowpilot_new.py",
            symbol="start_run",
            implements=(
                "new_entrypoint.startup_ui_to_new_ledger",
                "new_entrypoint.formal_headless_rejection",
            ),
            external_inputs=("root", "run_id", "headless_startup_text", "require_formal_ui"),
            external_outputs=("return",),
            side_effects=("create_run_shell",),
        ),
        _contract(
            "flowpilot_new.assert_formal_interactive_result",
            path="skills/flowpilot/assets/flowpilot_new.py",
            symbol="_assert_formal_interactive_result",
            implements=("new_entrypoint.formal_headless_rejection",),
            external_inputs=("result_path",),
            external_outputs=(),
        ),
        _contract(
            "flowpilot_new.run_fake_e2e",
            path="skills/flowpilot/assets/flowpilot_new.py",
            symbol="run_fake_e2e",
            implements=(
                "new_entrypoint.rehearsal_closure",
                "new_entrypoint.symmetric_role_packet_lifecycle",
            ),
            external_inputs=("root", "run_id", "startup_text"),
            external_outputs=("return",),
        ),
        _contract(
            "fake_e2e.run_fake_e2e",
            path="skills/flowpilot/assets/flowpilot_core_runtime/fake_e2e.py",
            symbol="run_fake_e2e",
            implements=(
                "new_entrypoint.rehearsal_closure",
                "new_entrypoint.symmetric_role_packet_lifecycle",
            ),
            external_inputs=("root", "run_id", "startup_text"),
            external_outputs=("return",),
            side_effects=("save_run_ledger",),
        ),
        _contract(
            "flowpilot_new.lease_agent",
            path="skills/flowpilot/assets/flowpilot_new.py",
            symbol="lease_agent",
            implements=(
                "new_entrypoint.symmetric_role_packet_lifecycle",
                "new_entrypoint.role_lease_requires_matching_packet",
            ),
            external_inputs=("root", "packet_id", "responsibility", "agent_id", "host_kind"),
            external_outputs=("return",),
            side_effects=("lease_responsibility", "assign_packet", "save_run_ledger"),
        ),
        _contract(
            "flowpilot_new.ack",
            path="skills/flowpilot/assets/flowpilot_new.py",
            symbol="ack",
            implements=("new_entrypoint.symmetric_role_packet_lifecycle",),
            external_inputs=("root", "lease_id", "packet_id"),
            external_outputs=("return",),
            side_effects=("ack_lease", "save_run_ledger"),
        ),
        _contract(
            "flowpilot_new.submit_result",
            path="skills/flowpilot/assets/flowpilot_new.py",
            symbol="submit_result",
            implements=(
                "new_entrypoint.symmetric_role_packet_lifecycle",
                "new_entrypoint.flowguard_run_local_evidence",
                "new_entrypoint.lifecycle_guard_stale_result_quarantine",
            ),
            external_inputs=("root", "lease_id", "packet_id", "body"),
            external_outputs=("return",),
            side_effects=("submit_host_result", "_run_until_wait_and_save"),
        ),
        _contract(
            "flowpilot_new.status",
            path="skills/flowpilot/assets/flowpilot_new.py",
            symbol="status",
            implements=(
                "new_entrypoint.symmetric_role_packet_lifecycle",
                "new_entrypoint.lifecycle_guard_stop_authority",
            ),
            external_inputs=("root",),
            external_outputs=("return",),
        ),
        _contract(
            "flowpilot_new.patrol",
            path="skills/flowpilot/assets/flowpilot_new.py",
            symbol="patrol",
            implements=(
                "new_entrypoint.lifecycle_guard_stop_authority",
                "new_entrypoint.lifecycle_guard_resume_patrol",
            ),
            external_inputs=("root",),
            external_outputs=("return",),
            side_effects=("_run_until_wait_and_save",),
        ),
        _contract(
            "flowpilot_new.resume",
            path="skills/flowpilot/assets/flowpilot_new.py",
            symbol="resume",
            implements=("new_entrypoint.lifecycle_guard_resume_patrol",),
            external_inputs=("root", "reason"),
            external_outputs=("return",),
            side_effects=("record_resume_request", "reconcile_resume_request", "_run_until_wait_and_save"),
        ),
        _contract(
            "host.submit_host_result",
            path="skills/flowpilot/assets/flowpilot_core_runtime/host.py",
            symbol="submit_host_result",
            implements=("new_entrypoint.lifecycle_guard_stale_result_quarantine",),
            external_inputs=("ledger", "lease_id", "packet_id", "body"),
            external_outputs=("return",),
            side_effects=("submit_result",),
        ),
        _contract(
            "runtime.refresh_lifecycle_guard",
            path="skills/flowpilot/assets/flowpilot_core_runtime/runtime.py",
            symbol="refresh_lifecycle_guard",
            implements=(
                "new_entrypoint.lifecycle_guard_stop_authority",
                "new_entrypoint.lifecycle_guard_resume_patrol",
            ),
            external_inputs=("ledger", "trigger", "resume_source", "record_history", "record_event"),
            external_outputs=("return",),
            state_writes=("lifecycle_guard", "lifecycle_guard_history"),
        ),
        _contract(
            "flowpilot_new.main",
            path="skills/flowpilot/assets/flowpilot_new.py",
            symbol="main",
            implements=(
                "new_entrypoint.side_command_surface_unsupported",
                "new_entrypoint.host_kind_value_menu",
            ),
            external_inputs=("argv",),
            external_outputs=("exit_code",),
        ),
        _contract(
            "meta_checks_runner.run_local_json_out",
            path="simulations/run_meta_checks.py",
            symbol="main",
            implements=("new_entrypoint.flowguard_run_local_evidence",),
            external_inputs=("argv",),
            external_outputs=("exit_code",),
        ),
        _contract(
            "capability_checks_runner.run_local_json_out",
            path="simulations/run_capability_checks.py",
            symbol="main",
            implements=("new_entrypoint.flowguard_run_local_evidence",),
            external_inputs=("argv",),
            external_outputs=("exit_code",),
        ),
        _contract(
            "flowpilot_fake_project_rehearsal.run_checks",
            path="simulations/run_flowpilot_fake_project_rehearsal_checks.py",
            symbol="run_checks",
            implements=("new_entrypoint.blackbox_fake_project_rehearsal",),
            external_inputs=("work_root",),
            external_outputs=("return",),
        ),
        _contract(
            "terminal_ledger_source_entries.route_nodes_with_requirement_trace",
            path="skills/flowpilot/assets/flowpilot_router_terminal_ledger_source_entries.py",
            symbol="_route_nodes_with_requirement_trace",
            implements=("terminal.requirement_trace_projection",),
            external_inputs=("router", "nodes", "root_requirement_ids"),
        ),
        _contract(
            "terminal_ledger_source_entries.requirement_trace_closure",
            path="skills/flowpilot/assets/flowpilot_router_terminal_ledger_source_entries.py",
            symbol="_requirement_trace_closure_from_root_replay",
            implements=("terminal.requirement_trace_projection",),
            external_inputs=("router", "contract", "root_replay"),
        ),
        _contract(
            "terminal_ledger_source_entries.build_source_entries",
            path="skills/flowpilot/assets/flowpilot_router_terminal_ledger_source_entries.py",
            symbol="_build_source_of_truth_final_entries",
            implements=("terminal.final_ledger_source_entries",),
            external_inputs=(
                "router",
                "project_root",
                "run_root",
                "frontier",
                "route",
                "mutations",
                "contract",
                "root_replay",
                "child_manifest",
                "evidence_ledger",
                "generated_ledger",
            ),
        ),
        _contract(
            "packet.create_packet",
            path="skills/flowpilot/assets/packet_runtime_creation_core.py",
            symbol="create_packet",
            implements=(
                "route_mutation.topology_and_recheck",
                "route_mutation.sibling_replacement_stales_old_evidence",
                "output_contract.packet_binding",
            ),
            external_inputs=("project_root", "from_role", "to_role", "packet_id"),
            side_effects=("write_controller_status_packet", "write_json_atomic", "write_text_atomic"),
        ),
        _contract(
            "packet.build_controller_handoff",
            path="skills/flowpilot/assets/packet_runtime_creation_handoff.py",
            symbol="build_controller_handoff",
            implements=("packet.physical_body_boundary",),
            external_inputs=("envelope", "envelope_path"),
        ),
        _contract(
            "packet.controller_handoff_text",
            path="skills/flowpilot/assets/packet_runtime_creation_handoff.py",
            symbol="controller_handoff_text",
            implements=("packet.physical_body_boundary",),
            external_inputs=("handoff",),
        ),
        _contract(
            "packet.controller_relay_envelope",
            path="skills/flowpilot/assets/packet_runtime_relay.py",
            symbol="controller_relay_envelope",
            implements=("output_contract.packet_binding",),
            external_inputs=("project_root", "envelope", "envelope_path"),
            side_effects=("write_json_atomic",),
        ),
        _contract(
            "packet.write_result",
            path="skills/flowpilot/assets/packet_runtime_results.py",
            symbol="write_result",
            implements=("output_contract.packet_binding",),
            external_inputs=("project_root", "packet_envelope", "result_body_text"),
            side_effects=("write_controller_status_packet", "write_json_atomic", "write_text_atomic"),
        ),
        _contract(
            "card.open_card",
            path="skills/flowpilot/assets/card_runtime_ack.py",
            symbol="open_card",
            implements=("card.ack_identity_and_bundle", "ack.return_wait_preconsumption"),
            external_inputs=("project_root", "envelope_path", "role", "agent_id"),
            side_effects=("write_json",),
        ),
        _contract(
            "card.submit_card_ack",
            path="skills/flowpilot/assets/card_runtime_ack.py",
            symbol="submit_card_ack",
            implements=("card.ack_identity_and_bundle", "ack.return_wait_preconsumption"),
            external_inputs=("project_root", "envelope_path", "role", "agent_id"),
            side_effects=("write_json",),
        ),
        _contract(
            "card.validate_card_ack",
            path="skills/flowpilot/assets/card_runtime_ack.py",
            symbol="validate_card_ack",
            implements=("card.ack_identity_and_bundle",),
            external_inputs=("project_root", "envelope_path", "ack_path"),
        ),
        _contract(
            "route_sign.generate",
            path="skills/flowpilot/assets/flowpilot_user_flow_diagram_generate.py",
            symbol="generate",
            implements=("route_mutation.sibling_replacement_stales_old_evidence",),
            external_inputs=("root",),
            side_effects=("write_text",),
        ),
        _contract(
            "role_output.prepare_output_session",
            path="skills/flowpilot/assets/role_output_runtime_progress.py",
            symbol="prepare_output_session",
            implements=("role_output.registry_authority",),
            external_inputs=("project_root", "role", "agent_id", "output_type"),
            side_effects=("write_output_progress_status",),
        ),
        _contract(
            "role_output_runtime.submit_output",
            path="skills/flowpilot/assets/role_output_runtime_envelopes.py",
            symbol="submit_output",
            implements=("pm_package_disposition.semantic_identity_and_packet_outcomes",),
            external_inputs=("project_root", "output_type", "role", "event_name", "body"),
            side_effects=("write_output_progress_status",),
        ),
        _contract(
            "pm_decisions._write_pm_package_result_disposition",
            path="skills/flowpilot/assets/flowpilot_router_work_packets_pm_role_writes_decisions_package_disposition.py",
            symbol="_write_pm_package_result_disposition",
            implements=("pm_package_disposition.semantic_identity_and_packet_outcomes",),
            external_inputs=("project_root", "run_root", "run_state", "payload", "batch_kind"),
            external_outputs=(),
            side_effects=("write_json",),
        ),
        _contract(
            "router._scoped_event_identity",
            path="skills/flowpilot/assets/flowpilot_router_event_identity_scopes.py",
            symbol="_scoped_event_identity",
            implements=("pm_package_disposition.semantic_identity_and_packet_outcomes",),
            external_inputs=("project_root", "run_root", "run_state", "event", "payload"),
        ),
        _contract(
            "router._check_scoped_event_conflict",
            path="skills/flowpilot/assets/flowpilot_router_event_identity_replay.py",
            symbol="_check_scoped_event_conflict",
            implements=("pm_package_disposition.semantic_identity_and_packet_outcomes",),
            external_inputs=("run_state", "identity"),
            external_outputs=(),
        ),
        _contract(
            "controller_aside.contract",
            path="skills/flowpilot/assets/controller_process_aside.py",
            symbol="controller_process_aside_contract",
            implements=("controller_aside.metadata_only_boundary",),
        ),
        _contract(
            "controller_aside.validate_text",
            path="skills/flowpilot/assets/controller_process_aside.py",
            symbol="validate_controller_aside_text",
            implements=("controller_aside.metadata_only_boundary",),
            external_inputs=("text",),
        ),
        _contract(
            "controller_aside.build",
            path="skills/flowpilot/assets/controller_process_aside.py",
            symbol="build_controller_aside",
            implements=("controller_aside.metadata_only_boundary",),
            external_inputs=("text", "from_role", "source", "to_role"),
        ),
        _contract(
            "material_artifact_map.refresh",
            path="skills/flowpilot/assets/flowpilot_material_artifact_map.py",
            symbol="refresh_material_artifact_map",
            implements=("material_artifact_map.index_only_boundary",),
            external_inputs=("project_root", "run_root", "run_state"),
            side_effects=("write_json_atomic",),
        ),
        _contract(
            "material_artifact_map.summary",
            path="skills/flowpilot/assets/flowpilot_material_artifact_map.py",
            symbol="material_artifact_map_summary",
            implements=("material_artifact_map.index_only_boundary",),
            external_inputs=("doc",),
        ),
        _contract(
            "material_artifact_map.source_ref",
            path="skills/flowpilot/assets/flowpilot_material_artifact_map.py",
            symbol="material_artifact_map_source_ref",
            implements=("material_artifact_map.index_only_boundary",),
            external_inputs=("project_root", "run_root"),
        ),
        _contract(
            "material_artifact_map.review_ids",
            path="skills/flowpilot/assets/flowpilot_material_artifact_map.py",
            symbol="review_source_entry_ids",
            implements=("material_artifact_map.index_only_boundary",),
            external_inputs=("doc", "batch_kind"),
        ),
        _contract(
            "material_artifact_map.review_paths",
            path="skills/flowpilot/assets/flowpilot_material_artifact_map.py",
            symbol="reviewable_source_paths",
            implements=("material_artifact_map.index_only_boundary",),
            external_inputs=("doc", "entry_ids"),
        ),
        _contract(
            "material_artifact_map_entries.make_entry",
            path="skills/flowpilot/assets/flowpilot_material_artifact_map_entries.py",
            symbol="make_entry",
            implements=("material_artifact_map.index_only_boundary",),
            external_inputs=("entry_id", "kind", "source_refs", "envelope_refs", "body_refs"),
        ),
        _contract(
            "material_artifact_map_entries.safe_source_ref",
            path="skills/flowpilot/assets/flowpilot_material_artifact_map_entries.py",
            symbol="safe_source_ref",
            implements=("material_artifact_map.index_only_boundary",),
            external_inputs=("project_root", "path"),
        ),
        _contract(
            "material_artifact_map_entries.sealed_body_ref",
            path="skills/flowpilot/assets/flowpilot_material_artifact_map_entries.py",
            symbol="sealed_body_ref",
            implements=("material_artifact_map.index_only_boundary",),
            external_inputs=("path", "body_hash", "visibility"),
        ),
        _contract(
            "material_artifact_map_entries.static_artifact_entries",
            path="skills/flowpilot/assets/flowpilot_material_artifact_map_entries.py",
            symbol="static_artifact_entries",
            implements=("material_artifact_map.index_only_boundary",),
            external_inputs=("project_root", "run_root"),
        ),
        _contract(
            "branch_pruning.next_states",
            path="simulations/flowpilot_router_reconciliation_branch_pruning_model.py",
            symbol="next_states",
            implements=(
                "branch_pruning.result_case_classifier",
                "branch_pruning.scheduled_receipt_effect_cases",
                "branch_pruning.role_output_authority_cases",
                "branch_pruning.runtime_state_resume_cases",
            ),
            external_inputs=("state",),
        ),
        _contract(
            "branch_pruning.failures",
            path="simulations/flowpilot_router_reconciliation_branch_pruning_model.py",
            symbol="branch_pruning_failures",
            implements=(
                "branch_pruning.result_case_classifier",
                "branch_pruning.scheduled_receipt_effect_cases",
                "branch_pruning.role_output_authority_cases",
                "branch_pruning.runtime_state_resume_cases",
            ),
            external_inputs=("state",),
        ),
        _contract(
            "branch_pruning.ownership_snapshot",
            path="simulations/flowpilot_router_reconciliation_branch_pruning_model.py",
            symbol="ownership_snapshot",
            implements=("branch_pruning.runtime_state_resume_cases",),
        ),
        _contract(
            "runtime_closure.validate_flowguard_operator_request_record",
            path="skills/flowpilot/assets/flowpilot_runtime_closure.py",
            symbol="validate_flowguard_operator_request_record",
            implements=("runtime_closure.flowguard_operator_lifecycle_contract",),
            external_inputs=("record",),
        ),
        _contract(
            "runtime_closure.validate_flowguard_operator_result_record",
            path="skills/flowpilot/assets/flowpilot_runtime_closure.py",
            symbol="validate_flowguard_operator_result_record",
            implements=("runtime_closure.flowguard_operator_lifecycle_contract",),
            external_inputs=("record", "result"),
        ),
        _contract(
            "runtime_closure.flowguard_operator_lifecycle_entry_from_request",
            path="skills/flowpilot/assets/flowpilot_runtime_closure.py",
            symbol="flowguard_operator_lifecycle_entry_from_request",
            implements=("runtime_closure.flowguard_operator_lifecycle_contract",),
            external_inputs=("record", "now"),
        ),
        _contract(
            "runtime_closure.continuation_quarantine_record",
            path="skills/flowpilot/assets/flowpilot_runtime_closure.py",
            symbol="continuation_quarantine_record",
            implements=("runtime_closure.continuation_and_final_report_contract",),
            external_inputs=("run_id", "run_root", "current_pointer", "run_index", "created_at"),
        ),
        _contract(
            "runtime_closure.validate_continuation_quarantine_record",
            path="skills/flowpilot/assets/flowpilot_runtime_closure.py",
            symbol="validate_continuation_quarantine_record",
            implements=("runtime_closure.continuation_and_final_report_contract",),
            external_inputs=("record",),
        ),
        _contract(
            "runtime_closure.final_user_report_record",
            path="skills/flowpilot/assets/flowpilot_runtime_closure.py",
            symbol="final_user_report_record",
            implements=("runtime_closure.continuation_and_final_report_contract",),
            external_inputs=("run_id", "lifecycle_status", "summary_path", "summary_json_path", "summary_sha256", "displayed_to_user", "written_at"),
        ),
        _contract(
            "runtime_closure.validate_final_user_report_record",
            path="skills/flowpilot/assets/flowpilot_runtime_closure.py",
            symbol="validate_final_user_report_record",
            implements=("runtime_closure.continuation_and_final_report_contract",),
            external_inputs=("record",),
        ),
        _contract(
            "runtime_closure.route_display_refresh_record",
            path="skills/flowpilot/assets/flowpilot_runtime_closure.py",
            symbol="route_display_refresh_record",
            implements=("runtime_closure.continuation_and_final_report_contract",),
            external_inputs=("run_id", "display_plan_path", "route_state_snapshot_path", "projection_hash", "refreshed_at"),
        ),
        _contract(
            "runtime_closure.validate_route_display_refresh_record",
            path="skills/flowpilot/assets/flowpilot_runtime_closure.py",
            symbol="validate_route_display_refresh_record",
            implements=("runtime_closure.continuation_and_final_report_contract",),
            external_inputs=("record",),
        ),
        _contract(
            "daemon.run_router_daemon",
            path="skills/flowpilot/assets/flowpilot_router_daemon_runtime.py",
            symbol="run_router_daemon",
            implements=("daemon.lock_status_queue_contract",),
            external_inputs=("router", "project_root"),
            side_effects=("save_run_state", "update"),
        ),
        _contract(
            "daemon.stop_router_daemon",
            path="skills/flowpilot/assets/flowpilot_router_daemon_runtime.py",
            symbol="stop_router_daemon",
            implements=("daemon.lock_status_queue_contract",),
            external_inputs=("router", "project_root", "reason"),
            side_effects=("save_run_state",),
        ),
        _contract(
            "daemon.acquire_lock",
            path="skills/flowpilot/assets/flowpilot_router_daemon_runtime_lock.py",
            symbol="_acquire_router_daemon_lock",
            implements=("daemon.lock_status_queue_contract",),
            external_inputs=("router", "project_root", "run_root", "run_state"),
            side_effects=("write", "write_json"),
        ),
        _contract(
            "daemon.refresh_lock",
            path="skills/flowpilot/assets/flowpilot_router_daemon_runtime_lock.py",
            symbol="_refresh_router_daemon_lock",
            implements=("daemon.lock_status_queue_contract",),
            external_inputs=("router", "project_root", "run_root"),
            side_effects=("write_json",),
        ),
        _contract(
            "daemon.release_lock",
            path="skills/flowpilot/assets/flowpilot_router_daemon_runtime_lock.py",
            symbol="_release_router_daemon_lock",
            implements=("daemon.lock_status_queue_contract",),
            external_inputs=("router", "project_root", "run_root", "reason"),
            side_effects=("write_json",),
        ),
        _contract(
            "daemon.write_status",
            path="skills/flowpilot/assets/flowpilot_router_daemon_runtime.py",
            symbol="_write_router_daemon_status",
            implements=("daemon.lock_status_queue_contract",),
            external_inputs=("router", "project_root", "run_root", "run_state", "lifecycle_status"),
            side_effects=("write_json",),
        ),
        _contract(
            "daemon.tick",
            path="skills/flowpilot/assets/flowpilot_router_daemon_runtime.py",
            symbol="_router_daemon_tick",
            implements=("daemon.lock_status_queue_contract",),
            external_inputs=("router", "project_root", "run_root", "run_state", "observe_only"),
            side_effects=("save_run_state", "update"),
        ),
        _contract(
            "process_liveness.probe",
            path="skills/flowpilot/assets/flowpilot_process_liveness.py",
            symbol="process_is_live",
            implements=("startup_daemon.lock_liveness_contract", "runtime_owner.router_boundary_helpers"),
            external_inputs=("pid",),
        ),
        _contract(
            "startup_daemon.lock_liveness",
            path="skills/flowpilot/assets/flowpilot_router_startup_daemon.py",
            symbol="_router_daemon_lock_liveness",
            implements=("startup_daemon.lock_liveness_contract",),
            external_inputs=("lock",),
        ),
        _contract(
            "startup_daemon.heartbeat_monitor",
            path="skills/flowpilot/assets/flowpilot_router_startup_daemon.py",
            symbol="_router_daemon_heartbeat_monitor",
            implements=("startup_daemon.lock_liveness_contract",),
            external_inputs=("lock", "liveness", "status_exists", "status_ok"),
        ),
        _contract(
            "startup_daemon.lock_is_live",
            path="skills/flowpilot/assets/flowpilot_router_startup_daemon.py",
            symbol="_router_daemon_lock_is_live",
            implements=("startup_daemon.lock_liveness_contract",),
            external_inputs=("lock",),
        ),
        _contract(
            "break_glass.open_incident",
            path="skills/flowpilot/assets/flowpilot_controller_break_glass.py",
            symbol="open_incident",
            implements=("runtime_owner.high_priority_owner_contracts",),
            external_inputs=("project_root", "run_root", "incident_id"),
            side_effects=("write_json", "save_index"),
        ),
        _contract(
            "break_glass.record_patch",
            path="skills/flowpilot/assets/flowpilot_controller_break_glass.py",
            symbol="record_patch",
            implements=("runtime_owner.high_priority_owner_contracts",),
            external_inputs=("project_root", "run_root", "incident_id", "patch_id"),
            side_effects=("write_json", "save_index"),
        ),
        _contract(
            "break_glass.close_incident",
            path="skills/flowpilot/assets/flowpilot_controller_break_glass.py",
            symbol="close_incident",
            implements=("runtime_owner.high_priority_owner_contracts",),
            external_inputs=("project_root", "run_root", "incident_id"),
            side_effects=("write_json", "save_index"),
        ),
        _contract(
            "flowpilot_paths.resolve_flowpilot_paths",
            path="skills/flowpilot/assets/flowpilot_paths.py",
            symbol="resolve_flowpilot_paths",
            implements=("runtime_owner.high_priority_owner_contracts",),
            external_inputs=("project_root",),
        ),
        _contract(
            "runtime_gateway.assert_runtime_gateway_write",
            path="skills/flowpilot/assets/flowpilot_runtime_gateway.py",
            symbol="assert_runtime_gateway_write",
            implements=("runtime_owner.high_priority_owner_contracts",),
            external_inputs=("path", "gateway_id", "operation"),
        ),
        _contract(
            "prompt_store.load_prompt_text",
            path="skills/flowpilot/assets/flowpilot_prompt_store.py",
            symbol="load_prompt_text",
            implements=("runtime_owner.high_priority_owner_contracts",),
            external_inputs=("prompt_id", "runtime_kit_root"),
        ),
        _contract(
            "action_providers.lifecycle_provider",
            path="skills/flowpilot/assets/flowpilot_router_action_providers_lifecycle.py",
            symbol="lifecycle_provider",
            implements=("runtime_owner.high_priority_owner_contracts",),
            external_inputs=("router", "project_root", "run_state", "run_root"),
            side_effects=("append_history", "save_run_state"),
        ),
        _contract(
            "card_returns.pending_return_card_ids",
            path="skills/flowpilot/assets/flowpilot_router_card_returns_records.py",
            symbol="_pending_return_card_ids",
            implements=("runtime_owner.high_priority_owner_contracts",),
            external_inputs=("router", "pending_return"),
            side_effects=("update",),
        ),
        _contract(
            "router_errors.router_error_record",
            path="skills/flowpilot/assets/flowpilot_router_errors.py",
            symbol="router_error_record",
            implements=("runtime_owner.high_priority_owner_contracts",),
            external_inputs=("error",),
        ),
        _contract(
            "card_settlement.card_ack_clearance_scope",
            path="skills/flowpilot/assets/flowpilot_router_card_settlement.py",
            symbol="_card_ack_clearance_scope",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("delivery_context", "card_id", "target_role"),
        ),
        _contract(
            "controller_boundary.patrol_timer_command",
            path="skills/flowpilot/assets/flowpilot_router_controller_boundary.py",
            symbol="_controller_patrol_timer_command",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("seconds",),
        ),
        _contract(
            "controller_reconciliation.action_projection_kind",
            path="skills/flowpilot/assets/flowpilot_router_controller_reconciliation.py",
            symbol="_controller_action_projection_kind",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("action",),
        ),
        _contract(
            "controller_repair.bind_router",
            path="skills/flowpilot/assets/flowpilot_router_controller_repair.py",
            symbol="_bind_router",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("router",),
            external_outputs=(),
        ),
        _contract(
            "dispatch_gate.target_roles",
            path="skills/flowpilot/assets/flowpilot_router_dispatch_gate.py",
            symbol="_dispatch_gate_target_roles",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("action",),
        ),
        _contract(
            "action_factory_dispatch.apply_dispatch_recipient_gate",
            path="skills/flowpilot/assets/flowpilot_router_action_factory_dispatch_apply.py",
            symbol="_apply_dispatch_recipient_gate",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_state", "run_root", "action"),
            side_effects=("_run_router_return_settlement_finalizers",),
        ),
        _contract(
            "action_factory_envelope.make_action",
            path="skills/flowpilot/assets/flowpilot_router_action_factory_envelope.py",
            symbol="make_action",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("action_type", "actor", "label", "summary"),
            side_effects=("update",),
        ),
        _contract(
            "action_handlers_basic.check_packet_ledger",
            path="skills/flowpilot/assets/flowpilot_router_action_handlers_basic.py",
            symbol="_apply_check_packet_ledger",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_root", "run_state", "pending", "payload"),
        ),
        _contract(
            "action_handlers_basic.relay_only_system_card",
            path="skills/flowpilot/assets/flowpilot_router_action_handlers_basic.py",
            symbol="_apply_relay_only_system_card",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_root", "run_state", "pending", "payload"),
            external_outputs=(),
        ),
        _contract(
            "action_handlers_roles.controller_repair_work_packet",
            path="skills/flowpilot/assets/flowpilot_router_action_handlers_roles.py",
            symbol="_apply_controller_repair_work_packet",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_root", "run_state", "pending", "payload"),
            side_effects=("write_json",),
        ),
        _contract(
            "artifact_validation.validate_artifact",
            path="skills/flowpilot/assets/flowpilot_router_artifact_validation.py",
            symbol="validate_artifact",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "artifact_type", "artifact_path"),
        ),
        _contract(
            "card_delivery.next_card_delivery_attempt",
            path="skills/flowpilot/assets/flowpilot_router_card_delivery.py",
            symbol="next_card_delivery_attempt",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_root", "run_id", "card_id"),
        ),
        _contract(
            "child_skill_capability.approve_manifest",
            path="skills/flowpilot/assets/flowpilot_router_child_skill_capability.py",
            symbol="_approve_child_skill_manifest_for_route",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_root", "run_state", "payload"),
            external_outputs=(),
            side_effects=("write_json", "update"),
        ),
        _contract(
            "child_skill_capability.sync_capability_evidence",
            path="skills/flowpilot/assets/flowpilot_router_child_skill_capability.py",
            symbol="_sync_capability_evidence",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_root", "run_state", "payload"),
            external_outputs=(),
            side_effects=("write_json",),
        ),
        _contract(
            "controller_ledger.prepare_router_scheduled_action",
            path="skills/flowpilot/assets/flowpilot_router_controller_ledger.py",
            symbol="prepare_router_scheduled_action",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_root", "run_state", "action"),
        ),
        _contract(
            "controller_wait_audit.controller_wait_receipt_audit",
            path="skills/flowpilot/assets/flowpilot_router_controller_wait_audit.py",
            symbol="controller_wait_receipt_audit",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_root", "current_wait"),
            side_effects=("update",),
        ),
        _contract(
            "router_cli.parse_args",
            path="skills/flowpilot/assets/flowpilot_router_cli.py",
            symbol="parse_args",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("argv",),
        ),
        _contract(
            "control_transactions.registry_issues",
            path="skills/flowpilot/assets/flowpilot_router_control_transactions.py",
            symbol="_control_transaction_registry_issues",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_root",),
        ),
        _contract(
            "controller_repair_schedule.schedule_deliverable_repair",
            path="skills/flowpilot/assets/flowpilot_router_controller_repair_schedule.py",
            symbol="_schedule_controller_deliverable_repair",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_root", "run_state", "pending_action", "receipt", "apply_result", "source"),
        ),
        _contract(
            "receipts_pending.router_scheduler_row",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_pending.py",
            symbol="_router_scheduler_row_for_controller_entry",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "run_root", "entry"),
        ),
        _contract(
            "receipts_scheduled.scheduler_row_reconciliation",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_scheduled_policy.py",
            symbol="_scheduler_row_reconciliation_for_entry",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "run_root", "entry"),
        ),
        _contract(
            "receipts_scheduled.reconcile_loop",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_scheduled.py",
            symbol="_reconcile_scheduled_controller_action_receipts",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_root", "run_state"),
            side_effects=(
                "_commit_controller_action_reconciliation",
                "_clear_pending_controller_action_if_matches",
                "append_history",
                "_apply_done_controller_receipt_effects",
                "_clear_matching_controller_pending_and_save",
                "_defer_controller_postcondition_reconciliation_retry",
                "write_json",
                "_write_control_blocker",
                "_backfill_scheduler_row_from_reconciled_controller_action",
                "_resolve_control_blockers_for_reconciled_controller_action",
                "_reclaim_role_recovery_postcondition_from_report",
                "_rebuild_controller_action_ledger",
                "_refresh_route_memory",
                "_sync_derived_run_views",
                "save_run_state",
                "update",
            ),
        ),
        _contract(
            "receipts_writes.maybe_write_controller_receipt",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_writes.py",
            symbol="_maybe_write_controller_receipt_for_pending",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_root", "run_state", "pending", "status", "payload"),
        ),
        _contract(
            "current_work_pending.has_controller_authority",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_current_work_pending.py",
            symbol="_pending_action_has_controller_authority",
            implements=("runtime_owner.current_work_pending_policy_boundary",),
            external_inputs=("router", "pending", "controller_ledger"),
        ),
        _contract(
            "current_work_pending.scheduler_row",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_current_work_pending.py",
            symbol="_scheduler_row_for_pending_action",
            implements=("runtime_owner.current_work_pending_policy_boundary",),
            external_inputs=("router", "run_root", "pending"),
        ),
        _contract(
            "current_work_pending.durable_resolution",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_current_work_pending.py",
            symbol="_pending_action_durable_resolution",
            implements=("runtime_owner.current_work_pending_policy_boundary",),
            external_inputs=("router", "run_root", "pending", "controller_ledger"),
        ),
        _contract(
            "current_work_pending.clear_durable_wait",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_current_work_pending.py",
            symbol="_clear_pending_action_if_durable_wait_resolved",
            implements=("runtime_owner.current_work_pending_policy_boundary",),
            external_inputs=("router", "project_root", "run_root", "run_state", "source"),
            side_effects=("append_history",),
        ),
        _contract(
            "current_work_pending.role_wait_batch_projection",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_current_work_pending.py",
            symbol="_pending_role_wait_should_use_batch_projection",
            implements=("runtime_owner.current_work_pending_policy_boundary",),
            external_inputs=("router", "pending"),
        ),
        _contract(
            "standby_policy.foreground_standby_state",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_standby_policy.py",
            symbol="_foreground_standby_state",
            implements=("runtime_owner.standby_state_policy_boundary",),
            external_inputs=(
                "terminal",
                "user_required",
                "daemon_liveness_check_required",
                "pending_action_ids",
                "current_wait",
            ),
        ),
        _contract(
            "standby_policy.foreground_standby_policy",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_standby_policy.py",
            symbol="_foreground_standby_policy",
            implements=("runtime_owner.standby_state_policy_boundary",),
            external_inputs=("standby_state",),
        ),
        _contract(
            "receipts_bootloader.boot_action_meta",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_bootloader.py",
            symbol="_boot_action_meta",
            implements=("runtime_owner.receipt_bootloader_policy_boundary",),
            external_inputs=("router", "action_type"),
        ),
        _contract(
            "receipts_bootloader.matching_pending_action",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_bootloader.py",
            symbol="_matching_bootstrap_pending_action",
            implements=("runtime_owner.receipt_bootloader_policy_boundary",),
            external_inputs=("router", "bootstrap_state", "action"),
        ),
        _contract(
            "receipts_bootloader.apply_startup_bootloader_receipt_effects",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_bootloader.py",
            symbol="_apply_startup_bootloader_receipt_effects",
            implements=("runtime_owner.receipt_bootloader_policy_boundary",),
            external_inputs=("router", "project_root", "run_root", "run_state", "action", "receipt_payload"),
            side_effects=("save_bootstrap_state", "save_run_state", "update", "write_json"),
        ),
        _contract(
            "receipt_packet_fold_registry.registered_actions",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_packet_fold_registry.py",
            symbol="_registered_controller_receipt_evidence_fold_actions",
            implements=("runtime_owner.receipt_packet_fold_registry_boundary",),
            external_inputs=(),
        ),
        _contract(
            "receipt_packet_fold_lifecycle.policy",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_packet_fold_lifecycle.py",
            symbol="_receipt_lifecycle_policy",
            implements=("runtime_owner.receipt_packet_fold_lifecycle_boundary",),
            external_inputs=("spec",),
        ),
        _contract(
            "receipt_packet_fold_lifecycle.apply_parallel_batch",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_packet_fold_lifecycle.py",
            symbol="_apply_parallel_batch_receipt_lifecycle",
            implements=("runtime_owner.receipt_packet_fold_lifecycle_boundary",),
            external_inputs=("router", "run_root", "spec", "records"),
        ),
        _contract(
            "receipt_packet_fold_lifecycle.apply_pm_role_work",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_packet_fold_lifecycle.py",
            symbol="_apply_pm_role_work_receipt_lifecycle",
            implements=("runtime_owner.receipt_packet_fold_lifecycle_boundary",),
            external_inputs=("router", "project_root", "run_root", "run_state", "spec", "records"),
        ),
        _contract(
            "receipt_scheduled_policy.scheduler_row_reconciliation",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_scheduled_policy.py",
            symbol="_scheduler_row_reconciliation_for_entry",
            implements=("runtime_owner.receipt_scheduled_policy_boundary",),
            external_inputs=("router", "run_root", "entry"),
        ),
        _contract(
            "receipt_scheduled_policy.backfill_scheduler_row",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_scheduled_policy.py",
            symbol="_backfill_scheduler_row_from_reconciled_controller_action",
            implements=("runtime_owner.receipt_scheduled_policy_boundary",),
            external_inputs=("router", "project_root", "run_root", "run_state", "entry", "source"),
            side_effects=("_update_router_scheduler_row",),
        ),
        _contract(
            "receipt_scheduled_policy.clear_pending_match",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_scheduled_policy.py",
            symbol="_clear_pending_controller_action_if_matches",
            implements=("runtime_owner.receipt_scheduled_policy_boundary",),
            external_inputs=("router", "run_state", "entry", "action", "action_id", "source"),
            side_effects=("append_history",),
        ),
        _contract(
            "receipt_scheduled_policy.apply_result_case",
            path="skills/flowpilot/assets/flowpilot_router_controller_scheduler_receipts_scheduled_policy.py",
            symbol="_scheduled_controller_receipt_apply_result_case",
            implements=("runtime_owner.receipt_scheduled_policy_boundary",),
            external_inputs=("applied", "retry"),
        ),
        _contract(
            "event_identity.stable_identity_hash",
            path="skills/flowpilot/assets/flowpilot_router_event_identity_scopes.py",
            symbol="_stable_identity_hash",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "value"),
        ),
        _contract(
            "event_intake.role_list",
            path="skills/flowpilot/assets/flowpilot_router_event_intake.py",
            symbol="role_list",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("value",),
        ),
        _contract(
            "events_repair.owner_child_module_names",
            path="skills/flowpilot/assets/flowpilot_router_events_repair.py",
            symbol="owner_child_module_names",
            implements=("runtime_owner.router_owner_external_contracts",),
        ),
        _contract(
            "expected_waits.run_state_has_event",
            path="skills/flowpilot/assets/flowpilot_router_expected_waits_events.py",
            symbol="_run_state_has_event",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_state", "event"),
        ),
        _contract(
            "expected_waits_pm_package.record_router_reconciled_external_event",
            path="skills/flowpilot/assets/flowpilot_router_expected_waits_reconciliation_pm_package.py",
            symbol="_record_router_reconciled_external_event",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_root", "run_state", "event", "payload"),
            external_outputs=(),
            side_effects=("append_history",),
        ),
        _contract(
            "model_gate_state.sync_model_gate_flags",
            path="skills/flowpilot/assets/flowpilot_router_model_gate_state.py",
            symbol="_sync_model_gate_flags",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_state", "event"),
            external_outputs=(),
        ),
        _contract(
            "protocol_external_events.external_event_contract",
            path="skills/flowpilot/assets/flowpilot_router_protocol_external_events.py",
            symbol="external_event_contract",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("event",),
        ),
        _contract(
            "manifest_registry.owner_exports_for_domain",
            path="skills/flowpilot/assets/flowpilot_router_facade_export_registry.py",
            symbol="owner_exports_for_domain",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("domain",),
        ),
        _contract(
            "manifest_actions.owner_exports_actions",
            path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_actions.py",
            symbol="owner_exports_actions",
            implements=("runtime_owner.router_owner_external_contracts",),
        ),
        _contract(
            "manifest_controller.owner_exports_controller",
            path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_controller.py",
            symbol="owner_exports_controller",
            implements=("runtime_owner.router_owner_external_contracts",),
        ),
        _contract(
            "manifest_route.owner_exports_route",
            path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_route.py",
            symbol="owner_exports_route",
            implements=("runtime_owner.router_owner_external_contracts",),
        ),
        _contract(
            "manifest_startup.owner_exports_startup",
            path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_startup.py",
            symbol="owner_exports_startup",
            implements=("runtime_owner.router_owner_external_contracts",),
        ),
        _contract(
            "manifest_terminal_work.owner_exports_terminal_work",
            path="skills/flowpilot/assets/flowpilot_router_facade_export_manifest_terminal_work.py",
            symbol="owner_exports_terminal_work",
            implements=("runtime_owner.router_owner_external_contracts",),
        ),
        _contract(
            "facade_exports.resolve_facade_export",
            path="skills/flowpilot/assets/flowpilot_router_facade_exports.py",
            symbol="resolve_facade_export",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("name", "router_module"),
        ),
        _contract(
            "lifecycle_requests.write_terminal_fence",
            path="skills/flowpilot/assets/flowpilot_router_lifecycle_requests_fence.py",
            symbol="_write_terminal_lifecycle_fence",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_root", "run_state", "mode", "event"),
            side_effects=("write_json",),
        ),
        _contract(
            "lifecycle_requests.clear_terminal_blocker",
            path="skills/flowpilot/assets/flowpilot_router_lifecycle_requests_reconciliation.py",
            symbol="_clear_active_control_blocker_for_terminal_lifecycle",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_root", "run_state", "mode", "event", "cleared_at"),
            side_effects=("write_json",),
        ),
        _contract(
            "lifecycle_terminal_quarantine.clear_repair_transaction",
            path="skills/flowpilot/assets/flowpilot_router_lifecycle_requests_terminal_quarantine.py",
            symbol="clear_active_repair_transaction_for_terminal_lifecycle",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_root", "run_state", "mode", "event", "cleared_at"),
            side_effects=("write_json",),
        ),
        _contract(
            "lifecycle_terminal_quarantine.material_progress_flags",
            path="skills/flowpilot/assets/flowpilot_router_lifecycle_requests_terminal_quarantine.py",
            symbol="quarantine_material_progress_for_terminal_lifecycle",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_root", "run_state", "mode", "event", "reconciled_at"),
            side_effects=("write_json",),
        ),
        _contract(
            "lifecycle_terminal_quarantine.duplicate_role_events",
            path="skills/flowpilot/assets/flowpilot_router_lifecycle_requests_terminal_quarantine.py",
            symbol="quarantine_duplicate_role_events_for_terminal_lifecycle",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_state", "mode", "event", "reconciled_at"),
        ),
        _contract(
            "lifecycle_terminal_quarantine.packet_result_authority",
            path="skills/flowpilot/assets/flowpilot_router_lifecycle_requests_terminal_quarantine.py",
            symbol="quarantine_packet_result_authority_for_terminal_lifecycle",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_root", "mode", "event", "reconciled_at"),
            side_effects=("write_json",),
        ),
        _contract(
            "lifecycle_requests.write_run_lifecycle",
            path="skills/flowpilot/assets/flowpilot_router_lifecycle_requests_records.py",
            symbol="_write_run_lifecycle_request",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_root", "run_state", "event", "payload"),
            external_outputs=(),
            side_effects=("write_json",),
        ),
        _contract(
            "lifecycle_requests.write_protocol_dead_end",
            path="skills/flowpilot/assets/flowpilot_router_lifecycle_requests_records.py",
            symbol="_write_protocol_dead_end_lifecycle",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_root", "run_state", "dead_end_path", "reason"),
            external_outputs=(),
            side_effects=("write_json",),
        ),
        _contract(
            "lifecycle_requests.exception_blocker_fallback",
            path="skills/flowpilot/assets/flowpilot_router_lifecycle_requests_blockers.py",
            symbol="_try_write_control_blocker_for_exception",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "source", "error_message", "event", "action_type", "payload"),
            side_effects=("write",),
        ),
        _contract(
            "lifecycle_support.lifecycle_record_path",
            path="skills/flowpilot/assets/flowpilot_router_lifecycle_support.py",
            symbol="_lifecycle_record_path",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_root",),
        ),
        _contract(
            "startup_bootloader.depends_on_role_slots",
            path="skills/flowpilot/assets/flowpilot_router_startup_bootloader_progress.py",
            symbol="_startup_bootloader_action_depends_on_role_slots",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "action_type"),
        ),
        _contract(
            "startup_closure.host_heartbeat_binding_ready",
            path="skills/flowpilot/assets/flowpilot_router_startup_closure.py",
            symbol="_host_heartbeat_binding_ready",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "run_root", "run_state"),
        ),
        _contract(
            "startup_display.display_text_hash",
            path="skills/flowpilot/assets/flowpilot_router_startup_display.py",
            symbol="_display_text_hash",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "display_text"),
        ),
        _contract(
            "startup_fact_boundary.controller_boundary_constraints",
            path="skills/flowpilot/assets/flowpilot_router_startup_fact_boundary_controller.py",
            symbol="_controller_boundary_constraints",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router",),
        ),
        _contract(
            "startup_flow.owner_module_name",
            path="skills/flowpilot/assets/flowpilot_router_startup_flow.py",
            symbol="owner_module_name",
            implements=("runtime_owner.router_owner_external_contracts",),
        ),
        _contract(
            "startup_intake.result_payload_contract",
            path="skills/flowpilot/assets/flowpilot_router_startup_intake_ui.py",
            symbol="_startup_intake_result_payload_contract",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "state"),
        ),
        _contract(
            "startup_intake_flowguard_capability.route_classification",
            path="skills/flowpilot/assets/flowpilot_router_startup_intake_flowguard_capability.py",
            symbol="_flowguard_route_classification",
            implements=("runtime_owner.startup_intake_flowguard_capability_boundary",),
            external_inputs=("skill_name",),
        ),
        _contract(
            "startup_intake_flowguard_capability.import_snapshot",
            path="skills/flowpilot/assets/flowpilot_router_startup_intake_flowguard_capability.py",
            symbol="_flowguard_import_snapshot",
            implements=("runtime_owner.startup_intake_flowguard_capability_boundary",),
            external_inputs=(),
        ),
        _contract(
            "startup_intake_flowguard_capability.write_snapshot",
            path="skills/flowpilot/assets/flowpilot_router_startup_intake_flowguard_capability.py",
            symbol="_write_flowguard_capability_snapshot",
            implements=("runtime_owner.startup_intake_flowguard_capability_boundary",),
            external_inputs=("router", "project_root", "run_root", "state"),
            side_effects=("mkdir", "write_json"),
        ),
        _contract(
            "startup_role_recovery.owner_child_module_names",
            path="skills/flowpilot/assets/flowpilot_router_startup_role_recovery.py",
            symbol="owner_child_module_names",
            implements=("runtime_owner.router_owner_external_contracts",),
        ),
        _contract(
            "startup_support.ensure_startup_run_state",
            path="skills/flowpilot/assets/flowpilot_router_startup_support.py",
            symbol="_ensure_startup_run_state",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "bootstrap_state"),
            side_effects=("write_json", "save_run_state"),
        ),
        _contract(
            "system_cards_delivery.commit_system_card_delivery",
            path="skills/flowpilot/assets/flowpilot_router_system_cards_delivery_single.py",
            symbol="_commit_system_card_delivery_artifact",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_state", "run_root", "pending"),
            side_effects=("update", "write_json"),
        ),
        _contract(
            "internal_actions.action_is_router_internal_mechanical",
            path="skills/flowpilot/assets/flowpilot_router_internal_actions.py",
            symbol="_action_is_router_internal_mechanical",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("action",),
        ),
        _contract(
            "payload_contracts.payload_contract",
            path="skills/flowpilot/assets/flowpilot_router_payload_contracts_core.py",
            symbol="_payload_contract",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("name", "required_object", "required_fields", "description"),
        ),
        _contract(
            "pm_role_followup.pm_role_work_channel_open",
            path="skills/flowpilot/assets/flowpilot_router_pm_role_followup.py",
            symbol="_pm_role_work_channel_open",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_state",),
        ),
        _contract(
            "prompt_delivery.card_checkin_instruction",
            path="skills/flowpilot/assets/flowpilot_router_prompt_delivery.py",
            symbol="card_checkin_instruction",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "envelope_path", "role", "agent_id", "card_return_event", "bundle"),
        ),
        _contract(
            "proof_validation.validate_router_owned_check_proof",
            path="skills/flowpilot/assets/flowpilot_router_proof_validation.py",
            symbol="_validate_router_owned_check_proof",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_root", "check_name", "audit_path"),
        ),
        _contract(
            "role_io_protocol.empty_role_io_protocol_ledger",
            path="skills/flowpilot/assets/flowpilot_router_role_io_protocol.py",
            symbol="empty_role_io_protocol_ledger",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_id",),
        ),
        _contract(
            "role_output_bridge.role_output_snapshot_name",
            path="skills/flowpilot/assets/flowpilot_router_role_output_bridge.py",
            symbol="_role_output_snapshot_name",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_root", "output_path"),
        ),
        _contract(
            "role_output_bridge_events.body_payload_from_record",
            path="skills/flowpilot/assets/flowpilot_router_role_output_bridge_events.py",
            symbol="_role_output_body_payload_from_record",
            implements=("runtime_owner.role_output_bridge_event_policy_boundary",),
            external_inputs=("router", "project_root", "record", "envelope"),
        ),
        _contract(
            "role_output_bridge_events.event_has_durable_authority",
            path="skills/flowpilot/assets/flowpilot_router_role_output_bridge_events.py",
            symbol="_role_output_event_has_durable_authority",
            implements=("runtime_owner.role_output_bridge_event_policy_boundary",),
            external_inputs=("router", "run_root", "run_state", "event"),
        ),
        _contract(
            "role_output_bridge_events_replay.try_reconcile_direct_role_output_event_ledger",
            path="skills/flowpilot/assets/flowpilot_router_role_output_bridge_events_replay.py",
            symbol="_try_reconcile_direct_role_output_event_ledger",
            implements=("runtime_owner.role_output_bridge_event_policy_boundary",),
            external_inputs=("router", "project_root", "run_root", "run_state"),
            side_effects=("append_history",),
        ),
        _contract(
            "route_artifacts_evidence.write_pm_review_block_repair",
            path="skills/flowpilot/assets/flowpilot_router_route_artifacts_evidence.py",
            symbol="_write_pm_review_block_repair",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("project_root", "run_root", "run_state", "payload"),
            external_outputs=(),
        ),
        _contract(
            "route_completion_support.resume_waits_for_pm_decision",
            path="skills/flowpilot/assets/flowpilot_router_route_completion_support.py",
            symbol="_resume_waits_for_pm_decision",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("run_state",),
        ),
        _contract(
            "self_interrogation.self_interrogation_issue",
            path="skills/flowpilot/assets/flowpilot_router_self_interrogation_records.py",
            symbol="_self_interrogation_issue",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("message", "record_id", "record_path", "scope"),
        ),
        _contract(
            "terminal_closure.terminal_closure_suite_is_closed",
            path="skills/flowpilot/assets/flowpilot_router_terminal_ledger_closure.py",
            symbol="_terminal_closure_suite_is_closed",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "run_root"),
        ),
        _contract(
            "terminal_recovery.recover_terminal_status",
            path="skills/flowpilot/assets/flowpilot_router_terminal_ledger_recovery.py",
            symbol="_recover_terminal_status_from_run_authorities",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_root", "run_state"),
        ),
        _contract(
            "terminal_summary.terminal_summary_action",
            path="skills/flowpilot/assets/flowpilot_router_terminal_ledger_summary.py",
            symbol="_terminal_summary_action",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_state", "run_root", "mode"),
        ),
        _contract(
            "work_packets_next_actions.try_reconcile_material_scan",
            path="skills/flowpilot/assets/flowpilot_router_work_packets_next_actions.py",
            symbol="_try_reconcile_material_scan_body_delivery",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_root", "run_state"),
        ),
        _contract(
            "work_packets_pm_role_actions.try_reconcile_pm_role_work",
            path="skills/flowpilot/assets/flowpilot_router_work_packets_pm_role_actions.py",
            symbol="_try_reconcile_pm_role_work_results",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("router", "project_root", "run_root", "run_state"),
        ),
        _contract(
            "user_flow_source.route_source_summary",
            path="skills/flowpilot/assets/flowpilot_user_flow_source.py",
            symbol="_route_source_summary",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("route",),
        ),
        _contract(
            "user_flow_stage.classify_current_stage",
            path="skills/flowpilot/assets/flowpilot_user_flow_stage.py",
            symbol="classify_current_stage",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("frontier", "route"),
        ),
        _contract(
            "user_flow_tree.active_node",
            path="skills/flowpilot/assets/flowpilot_user_flow_tree.py",
            symbol="_active_node",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("frontier", "state", "route"),
        ),
        _contract(
            "user_flow_mermaid.build_mermaid",
            path="skills/flowpilot/assets/flowpilot_user_flow_mermaid.py",
            symbol="build_mermaid",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=("frontier", "route", "current_stage", "trigger"),
        ),
        _contract(
            "user_flow_markdown.build_chat_markdown",
            path="skills/flowpilot/assets/flowpilot_user_flow_markdown.py",
            symbol="build_chat_markdown",
            implements=("runtime_owner.router_owner_external_contracts",),
            external_inputs=(
                "source",
                "generated_at",
                "current_stage",
                "active_route",
                "active_node",
                "trigger",
                "cockpit_open",
                "chat_display_required",
                "return_path",
                "source_status",
                "source_findings",
            ),
        ),
        _contract(
            "packet_invariants.controller_handoff_body_leak_never_advances",
            path="skills/flowpilot/assets/packet_control_plane_model_invariants_handoff.py",
            symbol="controller_handoff_body_leak_never_advances",
            implements=("packet_control_plane.model_state_contract",),
            external_inputs=("state", "trace"),
        ),
        _contract(
            "packet_issue_resume.pm_issue_apply",
            path="skills/flowpilot/assets/packet_control_plane_model_transitions_issue_resume.py",
            symbol="PMIssuePacket.apply",
            implements=("packet_control_plane.model_state_contract",),
            external_inputs=("input_obj", "state"),
            external_outputs=(),
        ),
        _contract(
            "packet_relay.runtime_write_apply",
            path="skills/flowpilot/assets/packet_control_plane_model_transitions_packet_relay.py",
            symbol="PacketRuntimeWrite.apply",
            implements=("packet_control_plane.model_state_contract",),
            external_inputs=("input_obj", "state"),
            external_outputs=(),
        ),
        _contract(
            "packet_dispatch.router_direct_dispatch_apply",
            path="skills/flowpilot/assets/packet_control_plane_model_transitions_dispatch_results.py",
            symbol="RouterDirectDispatch.apply",
            implements=("packet_control_plane.model_state_contract",),
            external_inputs=("input_obj", "state"),
            external_outputs=(),
        ),
        _contract(
            "packet_review.reviewer_result_apply",
            path="skills/flowpilot/assets/packet_control_plane_model_transitions_review_pm.py",
            symbol="ReviewerResultEnvelopeCheck.apply",
            implements=("packet_control_plane.model_state_contract",),
            external_inputs=("input_obj", "state"),
            external_outputs=(),
        ),
        _contract(
            "packet_runtime_reviewer.validate_for_reviewer",
            path="skills/flowpilot/assets/packet_runtime_reviewer.py",
            symbol="validate_for_reviewer",
            implements=("packet_runtime.runtime_owner_contracts",),
            external_inputs=("project_root", "packet_envelope", "result_envelope", "agent_role_map"),
        ),
        _contract(
            "event_dispatcher.record_external_event_unchecked",
            path="skills/flowpilot/assets/flowpilot_router_event_dispatcher_record.py",
            symbol="_record_external_event_unchecked",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("router", "project_root", "event", "payload"),
            side_effects=("save_run_state",),
        ),
        _contract(
            "event_dispatcher.repair_direct_package_disposition_authority_split",
            path="skills/flowpilot/assets/flowpilot_router_event_dispatcher.py",
            symbol="_repair_direct_package_disposition_authority_split",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("router", "project_root", "run_root", "run_state", "event", "payload"),
            side_effects=("save_run_state",),
        ),
        _contract(
            "router_events.handle_precheck_event",
            path="skills/flowpilot/assets/flowpilot_router_events.py",
            symbol="handle_precheck_event",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("router", "project_root", "run_root", "run_state", "event", "meta", "payload"),
        ),
        _contract(
            "router_events.apply_migrated_event_side_effect",
            path="skills/flowpilot/assets/flowpilot_router_events.py",
            symbol="apply_migrated_event_side_effect",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("router", "project_root", "run_root", "run_state", "event", "payload"),
        ),
        _contract(
            "router_io.write_json",
            path="skills/flowpilot/assets/flowpilot_router_io_json.py",
            symbol="write_json",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("path", "payload"),
            external_outputs=(),
            side_effects=("write_json_atomic",),
        ),
        _contract(
            "router_io_locks.json_write_lock_liveness",
            path="skills/flowpilot/assets/flowpilot_router_io_locks.py",
            symbol="_json_write_lock_liveness",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("path",),
        ),
        _contract(
            "router_io_paths.project_relative",
            path="skills/flowpilot/assets/flowpilot_router_io_paths.py",
            symbol="project_relative",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("project_root", "path"),
        ),
        _contract(
            "router_io_hashes.json_sha256",
            path="skills/flowpilot/assets/flowpilot_router_io_hashes.py",
            symbol="_json_sha256",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("payload",),
        ),
        _contract(
            "runtime_state.bind_router",
            path="skills/flowpilot/assets/flowpilot_router_runtime_state.py",
            symbol="_bind_router",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("router",),
            external_outputs=(),
        ),
        _contract(
            "runtime_state_persistence.merge_stale_run_state_save",
            path="skills/flowpilot/assets/flowpilot_router_runtime_state_persistence_save.py",
            symbol="_merge_stale_run_state_save",
            implements=("runtime_state.stale_save_merge_boundary",),
            external_inputs=("existing", "current"),
        ),
        _contract(
            "runtime_state_persistence.load_run_state_from_run_root",
            path="skills/flowpilot/assets/flowpilot_router_runtime_state_persistence_save.py",
            symbol="load_run_state_from_run_root",
            implements=("runtime_state.load_save_persistence_boundary",),
            external_inputs=("router", "project_root", "run_root"),
        ),
        _contract(
            "runtime_state_persistence.save_run_state",
            path="skills/flowpilot/assets/flowpilot_router_runtime_state_persistence_save.py",
            symbol="save_run_state",
            implements=("runtime_state.load_save_persistence_boundary",),
            external_inputs=("router", "run_root", "state"),
            external_outputs=(),
            side_effects=("write_json", "update"),
        ),
        _contract(
            "router_resume.reset_resume_cycle_for_wakeup",
            path="skills/flowpilot/assets/flowpilot_router_resume.py",
            symbol="reset_resume_cycle_for_wakeup",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("router", "run_state"),
            external_outputs=(),
        ),
        _contract(
            "router_route.route_payload_from_reviewed_draft",
            path="skills/flowpilot/assets/flowpilot_router_route.py",
            symbol="route_payload_from_reviewed_draft",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("router", "project_root", "run_root", "payload"),
        ),
        _contract(
            "router_terminal.terminal_lifecycle_mode",
            path="skills/flowpilot/assets/flowpilot_router_terminal.py",
            symbol="_terminal_lifecycle_mode",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("run_state",),
        ),
        _contract(
            "protocol_tables.terminal_statuses",
            path="skills/flowpilot/assets/flowpilot_router_protocol_tables.py",
            symbol="terminal_statuses",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=(),
        ),
        _contract(
            "protocol_tables.mail_sequence_entry",
            path="skills/flowpilot/assets/flowpilot_router_protocol_tables.py",
            symbol="mail_sequence_entry",
            implements=("runtime_owner.router_boundary_helpers",),
            external_inputs=("mail_id",),
        ),
        _contract(
            "startup_catalog.startup_boot_catalog",
            path="skills/flowpilot/assets/flowpilot_router_protocol_startup_catalog.py",
            symbol="startup_boot_catalog",
            implements=("runtime_owner.router_boundary_helpers",),
            external_outputs=("return",),
        ),
        _contract(
            "planning_cards.planning_system_card_catalog",
            path="skills/flowpilot/assets/flowpilot_router_protocol_planning_cards.py",
            symbol="planning_system_card_catalog",
            implements=("runtime_owner.router_boundary_helpers",),
            external_outputs=("return",),
        ),
        _contract(
            "runtime_cards.runtime_system_card_catalog",
            path="skills/flowpilot/assets/flowpilot_router_protocol_runtime_cards.py",
            symbol="runtime_system_card_catalog",
            implements=("runtime_owner.router_boundary_helpers",),
            external_outputs=("return",),
        ),
        _contract(
            "card_metadata.system_card_metadata_catalog",
            path="skills/flowpilot/assets/flowpilot_router_protocol_card_metadata.py",
            symbol="system_card_metadata_catalog",
            implements=("runtime_owner.router_boundary_helpers",),
            external_outputs=("return",),
        ),
        _contract(
            "boot_cards.system_card_catalog",
            path="skills/flowpilot/assets/flowpilot_router_protocol_boot_cards.py",
            symbol="system_card_catalog",
            implements=("runtime_owner.router_boundary_helpers",),
            external_outputs=("return",),
        ),
        _contract(
            "packet_contracts.normalize_output_contract",
            path="skills/flowpilot/assets/packet_runtime_contracts.py",
            symbol="normalize_output_contract",
            implements=("packet_runtime.owner_helper_contracts",),
            external_inputs=("output_contract", "packet_type", "from_role", "to_role", "node_id"),
        ),
        _contract(
            "packet_paths.load_envelope",
            path="skills/flowpilot/assets/packet_runtime_paths.py",
            symbol="load_envelope",
            implements=("packet_runtime.owner_helper_contracts",),
            external_inputs=("project_root", "envelope_path"),
        ),
        _contract(
            "packet_schema.sha256_file",
            path="skills/flowpilot/assets/packet_runtime_schema.py",
            symbol="sha256_file",
            implements=("packet_runtime.owner_helper_contracts",),
            external_inputs=("path",),
        ),
        _contract(
            "packet_control_plane.main",
            path="skills/flowpilot/assets/run_packet_control_plane_checks.py",
            symbol="main",
            implements=("packet_control_plane.runner_contract",),
            external_inputs=(),
        ),
        _contract(
            "card_bundle.validate_card_bundle_ack",
            path="skills/flowpilot/assets/card_runtime_bundle.py",
            symbol="validate_card_bundle_ack",
            implements=("card_runtime.owner_helper_contracts",),
            external_inputs=("project_root", "ack_path", "envelope_path"),
        ),
        _contract(
            "card_envelopes.validate_direct_router_ack_token",
            path="skills/flowpilot/assets/card_runtime_envelopes.py",
            symbol="_validate_direct_router_ack_token",
            implements=("card_runtime.owner_helper_contracts",),
            external_inputs=("envelope", "role", "agent_id", "bundle"),
        ),
        _contract(
            "card_io.project_relative",
            path="skills/flowpilot/assets/card_runtime_io.py",
            symbol="project_relative",
            implements=("card_runtime.owner_helper_contracts",),
            external_inputs=("project_root", "path"),
        ),
        _contract(
            "card_ledgers.load_card_ledger",
            path="skills/flowpilot/assets/card_runtime_ledgers.py",
            symbol="_load_card_ledger",
            implements=("card_runtime.owner_helper_contracts",),
            external_inputs=("project_root", "envelope"),
        ),
        _contract(
            "packet_startup.create_user_intake_packet",
            path="skills/flowpilot/assets/packet_runtime_creation_startup.py",
            symbol="create_user_intake_packet",
            implements=("packet_runtime.runtime_owner_contracts",),
            external_inputs=("project_root", "packet_id", "node_id", "body_text"),
            side_effects=("create_packet", "update"),
        ),
        _contract(
            "packet_ledger.packet_ledger_record_for_envelope",
            path="skills/flowpilot/assets/packet_runtime_ledger.py",
            symbol="packet_ledger_record_for_envelope",
            implements=("packet_runtime.runtime_owner_contracts",),
            external_inputs=("project_root", "envelope"),
        ),
        _contract(
            "packet_active_holder.require_concrete_agent_id",
            path="skills/flowpilot/assets/packet_runtime_active_holder_core.py",
            symbol="_require_concrete_agent_id",
            implements=("packet_runtime.runtime_owner_contracts",),
            external_inputs=("agent_id", "role"),
        ),
        _contract(
            "packet_progress.validate_progress_message",
            path="skills/flowpilot/assets/packet_runtime_progress.py",
            symbol="_validate_progress_message",
            implements=("packet_runtime.runtime_owner_contracts",),
            external_inputs=("message",),
        ),
        _contract(
            "packet_cli.parse_args",
            path="skills/flowpilot/assets/packet_runtime_cli_args.py",
            symbol="parse_args",
            implements=("packet_runtime.runtime_owner_contracts",),
            external_inputs=("argv",),
        ),
        _contract(
            "packet_sessions.runtime_sessions_dir",
            path="skills/flowpilot/assets/packet_runtime_sessions.py",
            symbol="_runtime_sessions_dir",
            implements=("packet_runtime.runtime_owner_contracts",),
            external_inputs=("project_root", "envelope_path"),
        ),
        _contract(
            "packet_relay_checks.verify_router_startup_release",
            path="skills/flowpilot/assets/packet_runtime_relay_checks.py",
            symbol="verify_router_startup_release",
            implements=("packet_runtime.runtime_owner_contracts",),
            external_inputs=("envelope", "recipient_role"),
        ),
        _contract(
            "packet_audit.audit_packet_chain",
            path="skills/flowpilot/assets/packet_runtime_audit.py",
            symbol="audit_packet_chain",
            implements=("packet_runtime.runtime_owner_contracts",),
            external_inputs=("project_root", "run_id", "node_id"),
            external_outputs=("return",),
            side_effects=("write_json_atomic",),
        ),
        _contract(
            "packet_control_plane_state.packet_from_id",
            path="skills/flowpilot/assets/packet_control_plane_model_state.py",
            symbol="_packet_from_id",
            implements=("packet_control_plane.model_state_contract",),
            external_inputs=("packet_id",),
        ),
        _contract(
            "role_output_contracts.build_output_skeleton",
            path="skills/flowpilot/assets/role_output_runtime_contracts.py",
            symbol="build_output_skeleton",
            implements=("role_output_runtime.owner_helper_contracts",),
            external_inputs=("project_root", "output_type", "role"),
        ),
        _contract(
            "role_output_cli.parse_args",
            path="skills/flowpilot/assets/role_output_runtime_cli.py",
            symbol="parse_args",
            implements=("role_output_runtime.owner_helper_contracts",),
            external_inputs=("argv",),
        ),
        _contract(
            "role_output_schema.controller_boundary_constraints",
            path="skills/flowpilot/assets/role_output_runtime_schema_io.py",
            symbol="controller_boundary_constraints",
            implements=("role_output_runtime.owner_helper_contracts",),
            external_inputs=(),
        ),
        _contract(
            "role_output_envelopes.runtime_envelope_for_body",
            path="skills/flowpilot/assets/role_output_runtime_envelope_receipts.py",
            symbol="runtime_envelope_for_body",
            implements=("role_output_runtime.owner_helper_contracts",),
            external_inputs=("project_root", "output_type", "body_path", "body_hash"),
        ),
        _contract(
            "role_output_controller_boundary.build_confirmation_body",
            path="skills/flowpilot/assets/role_output_runtime_controller_boundary.py",
            symbol="build_controller_boundary_confirmation_body",
            implements=("role_output_runtime.owner_helper_contracts",),
            external_inputs=("project_root", "run_id", "action_id", "source_action_id"),
        ),
        _contract(
            "role_output_controller_boundary.submit_confirmation",
            path="skills/flowpilot/assets/role_output_runtime_controller_boundary.py",
            symbol="submit_controller_boundary_confirmation",
            implements=("role_output_runtime.owner_helper_contracts",),
            external_inputs=("project_root", "agent_id", "submit_output", "run_id", "action_id", "source_action_id"),
        ),
        _contract(
            "flowpilot_runtime_path_evidence.attach_runtime_path_evidence_to_plan",
            path="skills/flowpilot/assets/flowpilot_runtime_path_evidence.py",
            symbol="attach_runtime_path_evidence_to_plan",
            implements=("runtime_path_contracts.runtime_evidence_binding",),
            external_inputs=("plan", "family", "code_contract_prefix", "model_path"),
        ),
        _contract(
            "workflow_step_contracts.project_action",
            path="simulations/flowpilot_workflow_step_contracts.py",
            symbol="workflow_step_contracts_for_action",
            implements=("workflow_step_contracts.next_step_projection",),
            external_inputs=("action",),
        ),
        _contract(
            "workflow_step_contracts.review_trace",
            path="simulations/flowpilot_workflow_step_contracts.py",
            symbol="review_trace",
            implements=("workflow_step_contracts.next_step_projection",),
            external_inputs=("steps", "contracts"),
        ),
        _contract(
            "workflow_step_contracts.runner",
            path="simulations/run_flowpilot_workflow_step_contract_checks.py",
            symbol="build_report",
            implements=("workflow_step_contracts.next_step_projection",),
            external_inputs=(),
        ),
        _contract(
            "test_tier.commands_for_tier",
            path="scripts/test_tier/definitions.py",
            symbol="commands_for_tier",
            implements=("test_tiering.foreground_fast_scope",),
            external_inputs=("tier",),
        ),
        _contract(
            "meta_runner.main",
            path="simulations/run_meta_checks.py",
            symbol="main",
            implements=("meta_parent.thin_default_and_layered_full_boundary",),
            external_inputs=("argv",),
        ),
        _contract(
            "smoke.main",
            path="scripts/smoke_flowpilot.py",
            symbol="main",
            implements=("capability_parent.proof_reuse_and_fast_boundary",),
            external_inputs=("argv",),
        ),
    )
