"""Hazard states for the FlowPilot prompt-isolation model."""

from __future__ import annotations

from dataclasses import replace

from prompt_isolation_model_state import State


def _ready(**changes: object) -> State:
    base = State(
        status="running",
        startup_state="controller_ready",
        holder="controller",
        phase="startup_intake",
        router_loaded=True,
        run_scoped_bootstrap_created=True,
        startup_intake_ui_completed=True,
        startup_intake_result_recorded=True,
        startup_intake_body_boundary_enforced=True,
        startup_answer_values_valid=True,
        startup_answer_provenance="explicit_user_reply",
        startup_answers_recorded=True,
        banner_emitted=True,
        startup_banner_user_visible=True,
        run_shell_created=True,
        current_pointer_written=True,
        run_index_updated=True,
        runtime_kit_copied=True,
        placeholders_filled=True,
        mailbox_initialized=True,
        user_request_recorded=True,
        user_request_provenance="explicit_user_request",
        user_intake_ready=True,
        roles_started=True,
        fresh_role_bindings_started=True,
        role_core_prompts_injected=True,
        controller_core_loaded=True,
        controller_boundary_confirmation_written=True,
        controller_boundary_policy_hash_recorded=True,
        pm_core_delivered=True,
        pm_phase_map_delivered=True,
        pm_startup_intake_card_delivered=True,
        reviewer_startup_fact_check_card_delivered=True,
        startup_fact_reported=True,
        pm_startup_activation_card_delivered=True,
        startup_activation_approved=True,
        user_intake_delivered_to_pm=True,
        user_intake_controller_relayed=True,
        controller_role_confirmed=True,
        prompt_deliveries=5,
        manifest_check_requests=5,
        manifest_checks=5,
        mail_deliveries=1,
        ledger_check_requests=1,
        ledger_checks=1,
        system_card_identity_boundaries_verified=True,
        packet_body_identity_boundaries_verified=True,
        result_body_identity_boundaries_verified=True,
        role_output_body_file_written=True,
        role_output_envelope_only_to_controller=True,
        role_output_path_hash_verified=True,
        bootloader_actions=14,
        router_action_requests=14,
    )
    return replace(base, **changes)


def _root_contract_ready(**changes: object) -> State:
    return _ready(
        pm_material_scan_card_delivered=True,
        pm_material_scan_packets_issued=True,
        reviewer_dispatch_allowed=True,
        worker_packets_delivered=True,
        worker_scan_results_returned=True,
        material_scan_result_ledger_checked=True,
        reviewer_material_sufficiency_card_delivered=True,
        material_review="sufficient",
        pm_material_absorb_or_research_card_delivered=True,
        material_accepted_by_pm=True,
        pm_material_understanding_card_delivered=True,
        material_understanding_written=True,
        pm_product_architecture_card_delivered=True,
        product_architecture_draft_written=True,
        product_architecture_modelability_card_delivered=True,
        product_architecture_modelability_passed=True,
        product_architecture_officer_result_ledger_checked=True,
        product_architecture_challenge_card_delivered=True,
        product_architecture_reviewer_challenged=True,
        pm_root_contract_card_delivered=True,
        root_contract_draft_written=True,
        root_contract_challenge_card_delivered=True,
        root_contract_reviewer_challenged=True,
        root_contract_frozen_by_pm=True,
        **changes,
    )


def _step5_ready(**changes: object) -> State:
    return _root_contract_ready(
        pm_dependency_policy_card_delivered=True,
        dependency_policy_recorded=True,
        capabilities_manifest_written=True,
        pm_child_skill_selection_card_delivered=True,
        pm_child_skill_selection_written=True,
        pm_child_skill_gate_manifest_card_delivered=True,
        child_skill_gate_manifest_written=True,
        reviewer_child_skill_gate_manifest_card_delivered=True,
        child_skill_manifest_reviewer_passed=True,
        child_skill_manifest_pm_approved_for_route=True,
        capability_evidence_synced=True,
        **changes,
    )


def _node_completed_ready(**changes: object) -> State:
    return _step5_ready(
        route_activated_by_pm=True,
        pm_current_node_card_delivered=True,
        pm_node_started_event_delivered=True,
        pm_node_acceptance_plan_card_delivered=True,
        node_acceptance_plan_written=True,
        reviewer_node_acceptance_plan_review_card_delivered=True,
        node_acceptance_plan_reviewed=True,
        pm_node_packet_issued=True,
        node_dispatch_allowed=True,
        node_worker_body_delivered=True,
        node_worker_result_returned=True,
        node_worker_result_ledger_checked=True,
        node_reviewer_reviewed_result=True,
        node_review_blocked=False,
        node_completed_by_pm=True,
        **changes,
    )


def hazard_states() -> dict[str, State]:
    return {
        "questions_without_router": State(startup_intake_ui_completed=True),
        "router_loaded_without_run_scoped_bootstrap": State(router_loaded=True),
        "stale_top_level_bootstrap_reused_for_answers": State(
            router_loaded=True,
            run_scoped_bootstrap_created=False,
            startup_intake_ui_completed=True,
            startup_intake_result_recorded=True,
            startup_intake_body_boundary_enforced=True,
            stale_top_level_bootstrap_reused=True,
            startup_answers_recorded=True,
            startup_answer_values_valid=True,
            startup_answer_provenance="explicit_user_reply",
        ),
        "banner_before_answers": State(router_loaded=True, startup_intake_ui_completed=True, banner_emitted=True),
        "answers_with_naked_provenance": State(
            router_loaded=True,
            run_scoped_bootstrap_created=True,
            startup_intake_ui_completed=True,
            startup_intake_result_recorded=True,
            startup_intake_body_boundary_enforced=True,
            startup_answers_recorded=True,
            startup_answer_values_valid=True,
            startup_answer_provenance="naked",
        ),
        "answers_with_inferred_provenance": State(
            router_loaded=True,
            run_scoped_bootstrap_created=True,
            startup_intake_ui_completed=True,
            startup_intake_result_recorded=True,
            startup_intake_body_boundary_enforced=True,
            startup_answers_recorded=True,
            startup_answer_values_valid=True,
            startup_answer_provenance="inferred",
        ),
        "answers_with_invalid_values": State(
            router_loaded=True,
            run_scoped_bootstrap_created=True,
            startup_intake_ui_completed=True,
            startup_intake_result_recorded=True,
            startup_intake_body_boundary_enforced=True,
            startup_answers_recorded=True,
            startup_answer_values_valid=False,
            startup_answer_provenance="explicit_user_reply",
        ),
        "run_shell_before_banner": State(router_loaded=True, startup_intake_ui_completed=True, run_shell_created=True),
        "banner_without_router_next_action": State(
            router_loaded=True,
            run_scoped_bootstrap_created=True,
            startup_intake_ui_completed=True,
            startup_intake_result_recorded=True,
            startup_intake_body_boundary_enforced=True,
            startup_answer_values_valid=True,
            startup_answer_provenance="explicit_user_reply",
            startup_answers_recorded=True,
            banner_emitted=True,
            bootloader_actions=5,
            router_action_requests=4,
        ),
        "run_shell_after_banner_without_router_next_action": State(
            router_loaded=True,
            run_scoped_bootstrap_created=True,
            startup_intake_ui_completed=True,
            startup_intake_result_recorded=True,
            startup_intake_body_boundary_enforced=True,
            startup_answer_values_valid=True,
            startup_answer_provenance="explicit_user_reply",
            startup_answers_recorded=True,
            banner_emitted=True,
            run_shell_created=True,
            bootloader_actions=6,
            router_action_requests=5,
        ),
        "bootloader_generates_prompts": _ready(bootloader_generated_prompt_body=True),
        "banner_emitted_without_user_visible_text": _ready(startup_banner_user_visible=False),
        "user_intake_without_explicit_user_request": _ready(
            user_request_recorded=False,
            user_request_provenance="none",
        ),
        "roles_started_without_current_role_bindings": _ready(fresh_role_bindings_started=False),
        "roles_before_runtime_kit": State(
            router_loaded=True,
            run_scoped_bootstrap_created=True,
            startup_intake_ui_completed=True,
            startup_answer_values_valid=True,
            startup_answer_provenance="explicit_user_reply",
            startup_answers_recorded=True,
            banner_emitted=True,
            roles_started=True,
        ),
        "user_intake_before_pm_cards": _ready(pm_phase_map_delivered=False),
        "startup_activation_without_reviewer_facts": _ready(
            startup_fact_reported=False,
            startup_activation_approved=True,
        ),
        "user_intake_before_startup_activation": _ready(startup_activation_approved=False),
        "user_intake_without_controller_relay": _ready(
            user_intake_delivered_to_pm=True,
            user_intake_controller_relayed=False,
        ),
        "material_scan_before_full_user_intake": _ready(
            user_intake_delivered_to_pm=False,
            user_intake_controller_relayed=False,
            pm_material_scan_card_delivered=True,
        ),
        "material_scan_without_card": _ready(pm_material_scan_packets_issued=True),
        "worker_body_without_dispatch": _ready(
            pm_material_scan_card_delivered=True,
            pm_material_scan_packets_issued=True,
            worker_packets_delivered=True,
            reviewer_dispatch_allowed=False,
        ),
        "material_scan_result_without_ledger_check": _ready(
            pm_material_scan_card_delivered=True,
            pm_material_scan_packets_issued=True,
            reviewer_dispatch_allowed=True,
            worker_packets_delivered=True,
            worker_scan_results_returned=True,
            material_scan_result_ledger_checked=False,
        ),
        "pm_accepts_unreviewed_worker_result": _ready(
            worker_scan_results_returned=True,
            material_accepted_by_pm=True,
            pm_used_unreviewed_evidence=True,
        ),
        "material_sufficiency_without_worker_result": _ready(
            reviewer_material_sufficiency_card_delivered=True,
            worker_scan_results_returned=False,
        ),
        "pm_absorbs_material_without_absorb_card": _ready(
            material_review="sufficient",
            material_accepted_by_pm=True,
        ),
        "research_package_without_required_branch": _ready(
            material_review="sufficient",
            pm_material_absorb_or_research_card_delivered=True,
            pm_research_package_card_delivered=True,
        ),
        "research_worker_report_without_capability_decision": _ready(
            material_review="research_required",
            pm_material_absorb_or_research_card_delivered=True,
            pm_research_package_card_delivered=True,
            pm_research_package_written=True,
            research_worker_report_card_delivered=True,
            research_worker_report_returned=True,
        ),
        "research_packet_without_reviewer_dispatch": _ready(
            material_review="research_required",
            pm_material_absorb_or_research_card_delivered=True,
            pm_research_package_card_delivered=True,
            pm_research_package_written=True,
            research_capability_decision_recorded=True,
            research_worker_report_card_delivered=True,
            research_worker_packet_delivered=True,
            research_dispatch_allowed=False,
        ),
        "research_worker_result_without_ledger_check": _ready(
            material_review="research_required",
            pm_material_absorb_or_research_card_delivered=True,
            pm_research_package_card_delivered=True,
            pm_research_package_written=True,
            research_capability_decision_recorded=True,
            research_worker_report_card_delivered=True,
            research_dispatch_allowed=True,
            research_worker_packet_delivered=True,
            research_worker_report_returned=True,
            research_worker_result_ledger_checked=False,
        ),
        "research_pass_without_direct_source_check": _ready(
            material_review="research_required",
            research_worker_report_card_delivered=True,
            research_dispatch_allowed=True,
            research_worker_packet_delivered=True,
            research_worker_report_returned=True,
            research_worker_result_ledger_checked=True,
            research_reviewer_passed=True,
        ),
        "officer_result_without_ledger_check": _ready(
            pm_material_understanding_card_delivered=True,
            material_understanding_written=True,
            pm_product_architecture_card_delivered=True,
            product_architecture_draft_written=True,
            product_architecture_modelability_card_delivered=True,
            product_architecture_modelability_passed=True,
            product_architecture_officer_result_ledger_checked=False,
        ),
        "product_architecture_before_research_absorbed": _ready(
            material_review="research_required",
            pm_material_absorb_or_research_card_delivered=True,
            pm_product_architecture_card_delivered=True,
        ),
        "root_contract_without_product_architecture_challenge": _ready(
            material_review="sufficient",
            material_accepted_by_pm=True,
            pm_material_understanding_card_delivered=True,
            material_understanding_written=True,
            pm_product_architecture_card_delivered=True,
            product_architecture_draft_written=True,
            product_architecture_modelability_card_delivered=True,
            product_architecture_modelability_passed=True,
            pm_root_contract_card_delivered=True,
            root_contract_draft_written=True,
        ),
        "contract_frozen_without_root_reviewer": _ready(
            root_contract_draft_written=True,
            root_contract_challenge_card_delivered=True,
            root_contract_frozen_by_pm=True,
        ),
        "capabilities_manifest_without_dependency_policy": _root_contract_ready(
            capabilities_manifest_written=True,
        ),
        "child_skill_selection_before_capabilities_manifest": _root_contract_ready(
            pm_child_skill_selection_card_delivered=True,
            pm_child_skill_selection_written=True,
        ),
        "child_skill_gate_manifest_without_pm_selection": _root_contract_ready(
            child_skill_gate_manifest_written=True,
        ),
        "child_skill_pm_approval_without_reviewer": _root_contract_ready(
            child_skill_manifest_pm_approved_for_route=True,
        ),
        "capability_evidence_sync_without_pm_approval": _root_contract_ready(
            capability_evidence_synced=True,
        ),
        "route_skeleton_before_capability_evidence_sync": _root_contract_ready(
            pm_route_skeleton_card_delivered=True,
            route_skeleton_written=True,
        ),
        "route_skeleton_before_contract_freeze": _ready(
            pm_route_skeleton_card_delivered=True,
            route_skeleton_written=True,
        ),
        "route_skeleton_without_prior_path_context": _step5_ready(
            pm_prior_path_context_card_delivered=True,
            pm_route_skeleton_card_delivered=True,
            route_skeleton_written=True,
            route_history_context_refreshed=False,
            pm_prior_path_context_reviewed=False,
        ),
        "route_activated_without_route_skeleton": _ready(
            route_activated_by_pm=True,
        ),
        "node_acceptance_plan_without_prior_path_context": _step5_ready(
            pm_prior_path_context_card_delivered=True,
            route_history_context_refreshed=False,
            pm_prior_path_context_reviewed=False,
            route_activated_by_pm=True,
            pm_current_node_card_delivered=True,
            pm_node_started_event_delivered=True,
            pm_node_acceptance_plan_card_delivered=True,
            node_acceptance_plan_written=True,
        ),
        "node_packet_without_node_cards": _step5_ready(
            route_activated_by_pm=True,
            pm_node_packet_issued=True,
        ),
        "node_packet_without_acceptance_plan_review": _step5_ready(
            route_activated_by_pm=True,
            pm_current_node_card_delivered=True,
            pm_node_started_event_delivered=True,
            pm_node_packet_issued=True,
        ),
        "direct_dispatch_without_reviewed_acceptance_plan": _step5_ready(
            route_activated_by_pm=True,
            pm_current_node_card_delivered=True,
            pm_node_started_event_delivered=True,
            pm_node_acceptance_plan_card_delivered=True,
            node_acceptance_plan_written=True,
            pm_node_packet_issued=True,
            node_dispatch_allowed=True,
        ),
        "direct_dispatch_without_packet": _step5_ready(
            route_activated_by_pm=True,
            pm_current_node_card_delivered=True,
            pm_node_started_event_delivered=True,
            pm_node_acceptance_plan_card_delivered=True,
            node_acceptance_plan_written=True,
            reviewer_node_acceptance_plan_review_card_delivered=True,
            node_acceptance_plan_reviewed=True,
            pm_node_packet_issued=False,
            node_dispatch_allowed=True,
        ),
        "node_worker_result_without_ledger_check": _step5_ready(
            route_activated_by_pm=True,
            pm_current_node_card_delivered=True,
            pm_node_started_event_delivered=True,
            pm_node_acceptance_plan_card_delivered=True,
            node_acceptance_plan_written=True,
            reviewer_node_acceptance_plan_review_card_delivered=True,
            node_acceptance_plan_reviewed=True,
            pm_node_packet_issued=True,
            node_dispatch_allowed=True,
            node_worker_body_delivered=True,
            node_worker_result_returned=True,
            node_worker_result_ledger_checked=False,
        ),
        "repair_issued_without_block_event_card": _ready(
            node_reviewer_reviewed_result=True,
            node_review_blocked=True,
            pm_node_repair_packet_issued=True,
        ),
        "repair_result_without_ledger_check": _ready(
            node_reviewer_reviewed_result=True,
            node_review_blocked=True,
            pm_review_repair_card_delivered=True,
            pm_reviewer_blocked_event_delivered=True,
            pm_node_repair_packet_issued=True,
            node_repair_result_returned=True,
            node_repair_result_ledger_checked=False,
        ),
        "repair_recheck_bypasses_reviewer_result": _ready(
            node_reviewer_reviewed_result=True,
            node_review_blocked=True,
            pm_review_repair_card_delivered=True,
            pm_reviewer_blocked_event_delivered=True,
            pm_node_repair_packet_issued=True,
            node_repair_review_passed=True,
            node_repair_result_returned=False,
        ),
        "route_mutation_without_prior_path_context": _step5_ready(
            pm_prior_path_context_card_delivered=True,
            route_history_context_refreshed=False,
            pm_prior_path_context_reviewed=False,
            route_activated_by_pm=True,
            pm_current_node_card_delivered=True,
            pm_node_started_event_delivered=True,
            pm_node_acceptance_plan_card_delivered=True,
            node_acceptance_plan_written=True,
            reviewer_node_acceptance_plan_review_card_delivered=True,
            node_acceptance_plan_reviewed=True,
            pm_node_packet_issued=True,
            node_dispatch_allowed=True,
            node_worker_body_delivered=True,
            node_worker_result_returned=True,
            node_worker_result_ledger_checked=True,
            node_reviewer_reviewed_result=True,
            node_review_blocked=True,
            route_mutated_by_pm=True,
        ),
        "parent_backward_replay_without_targets": _node_completed_ready(
            reviewer_parent_backward_replay_card_delivered=True,
            parent_backward_replay_passed=True,
        ),
        "parent_pm_segment_decision_without_replay": _node_completed_ready(
            pm_parent_segment_decision_card_delivered=True,
            parent_pm_segment_decision_recorded=True,
        ),
        "final_ledger_card_before_evidence_quality_package_card": _node_completed_ready(
            pm_parent_backward_targets_card_delivered=True,
            parent_backward_targets_enumerated=True,
            reviewer_parent_backward_replay_card_delivered=True,
            parent_backward_replay_passed=True,
            pm_parent_segment_decision_card_delivered=True,
            parent_pm_segment_decision_recorded=True,
            pm_final_ledger_card_delivered=True,
        ),
        "final_ledger_card_before_reviewer_evidence_quality_pass": _node_completed_ready(
            pm_parent_backward_targets_card_delivered=True,
            parent_backward_targets_enumerated=True,
            reviewer_parent_backward_replay_card_delivered=True,
            parent_backward_replay_passed=True,
            pm_parent_segment_decision_card_delivered=True,
            parent_pm_segment_decision_recorded=True,
            pm_evidence_quality_package_card_delivered=True,
            pm_evidence_quality_package_written=True,
            reviewer_evidence_quality_review_card_delivered=True,
            pm_final_ledger_card_delivered=True,
        ),
        "final_ledger_built_before_reviewer_evidence_quality_pass": _node_completed_ready(
            pm_parent_backward_targets_card_delivered=True,
            parent_backward_targets_enumerated=True,
            reviewer_parent_backward_replay_card_delivered=True,
            parent_backward_replay_passed=True,
            pm_parent_segment_decision_card_delivered=True,
            parent_pm_segment_decision_recorded=True,
            pm_evidence_quality_package_card_delivered=True,
            pm_evidence_quality_package_written=True,
            reviewer_evidence_quality_review_card_delivered=True,
            pm_final_ledger_card_delivered=True,
            final_ledger_built_by_pm=True,
        ),
        "final_ledger_before_parent_backward_decision": _node_completed_ready(
            pm_final_ledger_card_delivered=True,
            final_ledger_built_by_pm=True,
        ),
        "final_ledger_before_node_completion": _ready(
            pm_final_ledger_card_delivered=True,
            final_ledger_built_by_pm=True,
        ),
        "final_ledger_without_prior_path_context": _node_completed_ready(
            pm_parent_backward_targets_card_delivered=True,
            parent_backward_targets_enumerated=True,
            reviewer_parent_backward_replay_card_delivered=True,
            parent_backward_replay_passed=True,
            pm_parent_segment_decision_card_delivered=True,
            parent_pm_segment_decision_recorded=True,
            pm_evidence_quality_package_card_delivered=True,
            pm_evidence_quality_package_written=True,
            reviewer_evidence_quality_review_card_delivered=True,
            evidence_quality_reviewer_passed=True,
            pm_final_ledger_card_delivered=True,
            final_ledger_built_by_pm=True,
            route_history_context_refreshed=False,
            pm_prior_path_context_reviewed=False,
        ),
        "complete_before_closure_cleanup": _node_completed_ready(
            pm_parent_backward_targets_card_delivered=True,
            parent_backward_targets_enumerated=True,
            reviewer_parent_backward_replay_card_delivered=True,
            parent_backward_replay_passed=True,
            pm_parent_segment_decision_card_delivered=True,
            parent_pm_segment_decision_recorded=True,
            pm_evidence_quality_package_card_delivered=True,
            pm_evidence_quality_package_written=True,
            reviewer_evidence_quality_review_card_delivered=True,
            evidence_quality_reviewer_passed=True,
            pm_final_ledger_card_delivered=True,
            final_ledger_built_by_pm=True,
            final_backward_replay_passed=True,
            pm_completion_decision=True,
        ),
        "prompt_delivery_without_manifest_check": _ready(prompt_deliveries=4, manifest_checks=3),
        "mail_delivery_without_ledger_check": _ready(mail_deliveries=2, ledger_checks=1),
        "controller_reads_body": _ready(controller_read_forbidden_body=True),
        "controller_creates_project_evidence": _ready(controller_origin_project_evidence=True),
        "controller_relays_body_content": _ready(controller_relayed_body_content=True),
        "role_chat_response_discloses_body": _ready(role_chat_response_disclosed_body=True),
        "controller_uses_role_chat_body": _ready(controller_used_role_chat_body=True),
        "controller_direct_free_text_instruction": _ready(controller_direct_free_text_instruction_used=True),
        "controller_inspects_router_hard_checks": _ready(controller_inspected_router_internal_hard_checks=True),
        "role_output_without_file_backed_envelope": _ready(
            role_output_body_file_written=False,
            role_output_envelope_only_to_controller=False,
            role_output_path_hash_verified=False,
        ),
        "wrong_role_prompt": _ready(wrong_role_prompt_delivered=True),
        "wrong_role_body": _ready(wrong_role_body_delivered=True),
    }


__all__ = ["hazard_states"]
