"""Run checks for the FlowPilot modeling coverage model."""

from __future__ import annotations

import argparse
import json
from collections import deque
from pathlib import Path
from typing import Any

from flowguard import Explorer

import flowpilot_modeling_coverage_model as model


RESULTS_PATH = Path(__file__).resolve().with_name(
    "flowpilot_modeling_coverage_results.json"
)

REQUIRED_LABELS = tuple(
    [f"select_{scenario}" for scenario in model.SCENARIOS]
    + [f"accept_{scenario}" for scenario in model.VALID_SCENARIOS]
    + [f"reject_{scenario}" for scenario in model.NEGATIVE_SCENARIOS]
)

HAZARD_EXPECTED_FAILURES = {
    model.FLOWGUARD_OPTIONAL_CHILD_SKILL: "FlowGuard was treated as an optional ordinary child skill",
    model.MISSING_STARTUP_SNAPSHOT: "startup FlowGuard capability snapshot is missing",
    model.SNAPSHOT_NOT_ROUTER_GENERATED: "startup FlowGuard capability snapshot was not generated by Router startup script",
    model.PM_IGNORES_SNAPSHOT: "PM product modeling started without referencing the startup FlowGuard snapshot",
    model.MISSING_PRODUCT_MODELING_PLAN: "PM product modeling plan is missing before FlowGuard operator product-scope modeling",
    model.PRODUCT_SINGLE_MODEL_OVERCOLLAPSE: "distinct product risk families were collapsed into one model without merge or skip reasons",
    model.PRODUCT_REPORT_MISSING_PLANNED_FAMILY: "FlowGuard operator product-scope report omitted a planned product model family",
    model.CHILD_SKILL_BEFORE_PRODUCT_MODEL: "ordinary child skills were selected before PM accepted the product model family",
    model.MANIFEST_ONLY_MODEL_COVERAGE: "child-skill manifest was used as FlowGuard operator model-family coverage",
    model.MISSING_PROCESS_MODELING_PLAN: "PM process modeling plan is missing before FlowGuard operator route-scope modeling",
    model.PROCESS_PLAN_OMITS_PRODUCT_OR_MANIFEST: "process modeling plan does not consume accepted product family and child-skill manifest",
    model.PROCESS_REPORT_MISSING_PLANNED_FAMILY: "FlowGuard operator route-scope report omitted a planned process model family",
    model.ROUTE_ACTIVATED_BEFORE_MODEL_FAMILIES: "route activated before accepted product and process model families",
    model.FINAL_LEDGER_UNRESOLVED_MODEL_FAMILY: "terminal completion declared with unresolved model families",
}


def _state_id(state: model.State) -> str:
    return (
        f"scenario={state.scenario}|status={state.status}|fg="
        f"{state.flowguard_treated_as_foundation},{state.startup_snapshot_written},"
        f"{state.startup_snapshot_generated_by_router},{state.startup_snapshot_has_portable_resolution},"
        f"{state.pm_references_snapshot_before_product_modeling}|product="
        f"{state.product_modeling_plan_written},{state.product_model_families_declared},"
        f"{state.flowguard_operator_product_scope_covers_planned_families},{state.product_model_family_pm_accepted}|"
        f"child={state.ordinary_child_skills_selected_after_product_acceptance},"
        f"{state.child_skill_manifest_maps_to_product_family},"
        f"{state.child_skill_manifest_used_as_model_family_coverage}|process="
        f"{state.process_modeling_plan_written},{state.process_model_families_declared},"
        f"{state.flowguard_operator_route_scope_covers_planned_families},{state.process_model_family_pm_accepted}|"
        f"route={state.route_activated}|ledger={state.final_ledger_references_modeling_coverage},"
        f"{state.final_ledger_has_unresolved_model_families},{state.completion_declared}|"
        f"reason={state.terminal_reason}"
    )


def _build_graph() -> dict[str, Any]:
    initial = model.initial_state()
    queue: deque[model.State] = deque([initial])
    states: list[model.State] = [initial]
    index = {initial: 0}
    edges: list[list[tuple[str, int]]] = []
    labels: set[str] = set()
    invariant_failures: list[dict[str, object]] = []

    while queue:
        state = queue.popleft()
        source = index[state]
        while len(edges) <= source:
            edges.append([])

        failures = model.invariant_failures(state)
        if failures:
            invariant_failures.append({"state": _state_id(state), "failures": failures})

        for transition in model.next_safe_states(state):
            labels.add(transition.label)
            if transition.state not in index:
                index[transition.state] = len(states)
                states.append(transition.state)
                queue.append(transition.state)
            edges[source].append((transition.label, index[transition.state]))

    return {
        "states": states,
        "edges": edges,
        "labels": labels,
        "edge_count": sum(len(outgoing) for outgoing in edges),
        "invariant_failures": invariant_failures,
    }


def _safe_graph_report(graph: dict[str, Any]) -> dict[str, object]:
    states: list[model.State] = graph["states"]
    terminal = [state for state in states if model.is_terminal(state)]
    accepted = [state for state in terminal if state.status == "accepted"]
    rejected = [state for state in terminal if state.status == "rejected"]
    accepted_scenarios = sorted(state.scenario for state in accepted)
    rejected_scenarios = sorted(state.scenario for state in rejected)
    missing_labels = sorted(set(REQUIRED_LABELS) - set(graph["labels"]))
    return {
        "ok": not graph["invariant_failures"]
        and not missing_labels
        and set(accepted_scenarios) == set(model.VALID_SCENARIOS)
        and set(rejected_scenarios) == set(model.NEGATIVE_SCENARIOS),
        "state_count": len(states),
        "edge_count": graph["edge_count"],
        "accepted_scenarios": accepted_scenarios,
        "rejected_scenarios": rejected_scenarios,
        "missing_labels": missing_labels,
        "invariant_failures": graph["invariant_failures"][:5],
    }


def _progress_report(graph: dict[str, Any]) -> dict[str, object]:
    states: list[model.State] = graph["states"]
    edges: list[list[tuple[str, int]]] = graph["edges"]
    terminal = {idx for idx, state in enumerate(states) if model.is_terminal(state)}
    can_reach_terminal = set(terminal)
    changed = True
    while changed:
        changed = False
        for source, outgoing in enumerate(edges):
            if source not in can_reach_terminal and any(
                target in can_reach_terminal for _label, target in outgoing
            ):
                can_reach_terminal.add(source)
                changed = True
    stuck = [
        _state_id(state)
        for idx, state in enumerate(states)
        if idx not in terminal and not edges[idx]
    ]
    cannot_reach_terminal = [
        _state_id(state)
        for idx, state in enumerate(states)
        if idx not in can_reach_terminal
    ]
    return {
        "ok": not stuck and not cannot_reach_terminal,
        "stuck_state_count": len(stuck),
        "cannot_reach_terminal_count": len(cannot_reach_terminal),
        "samples": (stuck + cannot_reach_terminal)[:5],
    }


def _flowguard_report() -> dict[str, object]:
    report = Explorer(
        workflow=model.build_workflow(),
        initial_states=(model.initial_state(),),
        external_inputs=model.EXTERNAL_INPUTS,
        invariants=model.INVARIANTS,
        max_sequence_length=model.MAX_SEQUENCE_LENGTH,
        terminal_predicate=lambda _input, state, _trace: model.is_terminal(state),
        success_predicate=lambda state, _trace: model.is_success(state),
        required_labels=REQUIRED_LABELS,
    ).explore()
    return {
        "ok": report.ok,
        "summary": report.summary,
        "violation_count": len(report.violations),
        "dead_branch_count": len(report.dead_branches),
        "exception_branch_count": len(report.exception_branches),
        "reachability_failure_count": len(report.reachability_failures),
        "reachability_failures": [
            failure.message for failure in report.reachability_failures
        ],
    }


def _hazard_report() -> dict[str, object]:
    hazards: dict[str, object] = {}
    failures: list[str] = []
    for name, state in model.hazard_states().items():
        scenario_failures = model.modeling_coverage_failures(state)
        expected = HAZARD_EXPECTED_FAILURES[name]
        detected = any(expected in failure for failure in scenario_failures)
        hazards[name] = {
            "detected": detected,
            "expected_failure": expected,
            "failures": scenario_failures,
        }
        if not detected:
            failures.append(f"{name}: expected failure containing {expected!r}")
    return {"ok": not failures, "hazards": hazards, "failures": failures}


def _intended_plan_report() -> dict[str, object]:
    state = model.intended_plan_state()
    failures = model.modeling_coverage_failures(state)
    return {
        "ok": not failures,
        "scenario": state.scenario,
        "state": state.__dict__,
        "failures": failures,
    }


def run_checks() -> dict[str, object]:
    graph = _build_graph()
    safe_graph = _safe_graph_report(graph)
    progress = _progress_report(graph)
    explorer = _flowguard_report()
    hazards = _hazard_report()
    intended_plan = _intended_plan_report()
    result = {
        "safe_graph": safe_graph,
        "progress": progress,
        "flowguard_explorer": explorer,
        "hazard_checks": hazards,
        "intended_plan": intended_plan,
        "model_plan": model.model_plan(),
    }
    result["ok"] = all(
        section.get("ok", False)
        for section in (safe_graph, progress, explorer, hazards, intended_plan)
    )
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json-out", type=Path, default=RESULTS_PATH)
    args = parser.parse_args()

    result = run_checks()
    output = json.dumps(result, indent=2, sort_keys=True)
    print(output)
    if args.json_out:
        args.json_out.write_text(output + "\n", encoding="utf-8")
    return 0 if result["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
